SMOKE_TESTS = [
    "accept.gen.test",
    "accept4.gen.test",
    "access.gen.test",
    "acct.gen.test",
    "add_key.gen.test",
    "adjtimex.gen.test",
    "alarm.gen.test",
    "brk.test",
    "chdir.gen.test",
    "chmod.gen.test",
    "chown.gen.test",
    "rename.gen.test",
    "clock_adjtime.gen.test",
    "creat.gen.test",
    "fstat.gen.test",
    "lstat.gen.test",
    "mmap.test",
    "open.gen.test",
    "openat.gen.test",
    "read.gen.test",
    "stat.gen.test",
    "statfs.gen.test",
    "symlinkat.gen.test",
    "sync.gen.test",
    "write.gen.test",
]

# Curated pure-eBPF reference subset. These tests are diagnostic references,
# not the main eBPF gate, because upstream exact diff still encodes ptrace
# ordering and text contracts.
UPSTREAM_REFERENCE_TESTS = [
    "getpid.gen.test",
    "openat.gen.test",
    "read-write.gen.test",
    "recvmsg.gen.test",
    "scm_credentials.gen.test",
    "msg_control.gen.test",
    "msg_name.gen.test",
    "mmsg.gen.test",
    "recvmmsg-timeout.gen.test",
    "execveat.gen.test",
    "fork-f.gen.test",
    "readv.test",
    "preadv.gen.test",
    "pwritev.gen.test",
    "preadv-pwritev.gen.test",
    "preadv2-pwritev2.gen.test",
    "vmsplice.gen.test",
    "process_vm_readv.gen.test",
    "process_vm_writev.gen.test",
]

UPSTREAM_REFERENCE_EXPECTED_FAILURES = {
    "read-write.gen.test": "bounded eBPF snapshot does not promise ptrace-sized read/write hexdump fetches",
}

# Known non-contract differences for the growing compatibility list.
MORE_EXPECTED_FAILURES = {
    "strace-C.test": "upstream -c summary counts per-syscall CPU time; eBPF only observes wall-clock duration",
    "read-write.gen.test": "bounded eBPF snapshot does not promise ptrace-sized read/write hexdump fetches",
    "attach-p-cmd.test": "pure eBPF does not promise exact cross-task lifecycle exit ordering",
}

# Tests for the next feature we are tackling.
# Add tests here when working on a new syscall or feature.
MORE_TESTS = [
    "strace-A.test",
    "strace-p.test",
    "strace-C.test",
    "strace-e-negation.test",
    "strace-e-class.test",
    "strace-e-class2.test",
    "strace-E.test",
    "strace-x.gen.test",
    "strace-xx.gen.test",
    "aio_pgetevents.gen.test",
    "aio.gen.test",
    "arch_prctl-Xabbrev.gen.test",
    "arch_prctl-Xverbose.gen.test",
    "arch_prctl.gen.test",
    "at_fdcwd-pathmax.gen.test",
    "bpf-v.gen.test",
    "bpf.gen.test",
    "cachestat-P.gen.test",
    "cachestat.gen.test",
    "chroot.gen.test",
    "clock_xettime.gen.test",
    "dup-P.gen.test",
    "dup2-P.gen.test",
    "dup3-P.gen.test",
    "dup-yy.gen.test",
    "dup2.gen.test",
    "dup3.gen.test",
    "epoll_create.gen.test",
    "epoll_create1.gen.test",
    "epoll_ctl.gen.test",
    "epoll_pwait2-y.gen.test",
    "epoll_pwait2.gen.test",
    "epoll_wait.gen.test",
    "erestartsys.gen.test",
    "eventfd.test",
    "fchmod.gen.test",
    "fchmodat.gen.test",
    "fchown.gen.test",
    "fchownat.gen.test",
    "fcntl.gen.test",
    "filter-unavailable.test",
    "filter_seccomp-flag.gen.test",
    "fspick.gen.test",
    "fstat-Xabbrev.gen.test",
    "fstatfs.gen.test",
    "ftruncate.gen.test",
    "getcwd.gen.test",
    "getegid.gen.test",
    "geteuid.gen.test",
    "getgid.gen.test",
    "getpgrp.gen.test",
    "getpid.gen.test",
    "getppid.gen.test",
    "getrlimit.gen.test",
    "getsid.gen.test",
    "getsockname.gen.test",
    "gettid.gen.test",
    "getuid.test",
    "inotify_init.gen.test",
    "ioctl.test",
    "ioctl_fiemap-Xabbrev.gen.test",
    "ioctl_fiemap-Xraw.gen.test",
    "ioctl_fiemap-Xverbose.gen.test",
    "ioctl_fiemap.gen.test",
    "ioctl_fs_0x15-Xabbrev.gen.test",
    "ioctl_fs_0x15.gen.test",
    "arch_prctl-Xraw.gen.test",
    "status-successful.gen.test",
    "status-failed.gen.test",
    "status-all.gen.test",
    "status-none.gen.test",
    "fork-f.gen.test",
    "vfork-f.gen.test",
    "strace-E.test",
    "strace-E-override.test",
    "strace-E-unset.test",
    "attach-p-cmd.test",
    "attach-f-p.test",
    "strace-r.test",
    "strace-t.test",
    "strace-tt.test",
    "strace-ttt.test",
    "strace-T_upper.test",
    "strace-x.gen.test",
    "strace-xx.gen.test",
    "read-write.gen.test",
    "pread64-pwrite64.gen.test",
    "opipe.test",
]
