package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const defaultVersionOutputPath = "cmd/strace-go/version_generated.go"

var (
	validVersion = regexp.MustCompile(`^[0-9][0-9A-Za-z.+-]*$`)
	validYear    = regexp.MustCompile(`^[0-9]{4}$`)
)

type versionMetadata struct {
	version string
	year    string
}

func main() {
	if err := runVersionGenerator(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func runVersionGenerator(args []string) error {
	flags := flag.NewFlagSet("generate-version", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	outputPath := flags.String("output", defaultVersionOutputPath, "generated Go source path")
	check := flags.Bool("check", false, "check generated file without writing it")
	if err := flags.Parse(args); err != nil {
		return err
	}
	root, err := findVersionRepoRoot()
	if err != nil {
		return err
	}
	metadata, err := loadVersionMetadata(root)
	if err != nil {
		return err
	}
	source, err := renderVersionMetadata(metadata)
	if err != nil {
		return err
	}
	output := resolveVersionPath(root, *outputPath)
	if *check {
		return checkVersionFile(output, source)
	}
	return writeVersionFile(output, source)
}

func loadVersionMetadata(root string) (versionMetadata, error) {
	version, err := runVersionSource(root, "git-version-gen", ".tarball-version")
	if err != nil {
		return versionMetadata{}, err
	}
	year, err := runVersionSource(root, "copyright-year-gen", ".year")
	if err != nil {
		return versionMetadata{}, err
	}
	metadata := versionMetadata{version: version, year: year}
	if err := validateVersionMetadata(metadata); err != nil {
		return versionMetadata{}, err
	}
	return metadata, nil
}

func runVersionSource(root, script, argument string) (string, error) {
	upstream := filepath.Join(root, "strace-upstream")
	command := exec.Command(filepath.Join(upstream, "build-aux", script), argument)
	command.Dir = upstream
	output, err := command.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("run upstream %s: %w: %s", script, err, strings.TrimSpace(string(output)))
	}
	return strings.TrimSpace(string(output)), nil
}

func validateVersionMetadata(metadata versionMetadata) error {
	if !validVersion.MatchString(metadata.version) {
		return fmt.Errorf("invalid upstream version %q", metadata.version)
	}
	if !validYear.MatchString(metadata.year) {
		return fmt.Errorf("invalid upstream copyright year %q", metadata.year)
	}
	return nil
}

func renderVersionMetadata(metadata versionMetadata) (string, error) {
	if err := validateVersionMetadata(metadata); err != nil {
		return "", err
	}
	source := "// Code generated by generate-version; DO NOT EDIT.\n\n" +
		"package main\n\n" +
		"const (\n" +
		"\tstraceVersion = " + strconv.Quote(metadata.version) + "\n" +
		"\tstraceCopyrightYear = " + strconv.Quote(metadata.year) + "\n" +
		")\n"
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", fmt.Errorf("format generated version source: %w", err)
	}
	return string(formatted), nil
}

func findVersionRepoRoot() (string, error) {
	directory, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	for {
		if isVersionFile(filepath.Join(directory, "go.mod")) &&
			isVersionFile(filepath.Join(directory, "strace-upstream", "build-aux", "git-version-gen")) {
			return directory, nil
		}
		parent := filepath.Dir(directory)
		if parent == directory {
			return "", fmt.Errorf("repository root not found from %s", directory)
		}
		directory = parent
	}
}

func resolveVersionPath(root, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(root, path)
}

func writeVersionFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func checkVersionFile(path, want string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated file %s: %w", path, err)
	}
	if string(data) != want {
		return fmt.Errorf("generated file is stale: %s", path)
	}
	return nil
}

func isVersionFile(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
