// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBpfStats struct {
	_                      structs.HostLayout
	RingbufReserveFail     uint64
	RingbufCopyFail        uint64
	PayloadTruncatedEvents uint64
	PendingUpdateFail      uint64
	OrphanExit             uint64
	PendingMismatch        uint64
	LifecycleMapUpdateFail uint64
}

type bpfFdPathScratch struct {
	_          structs.HostLayout
	Name       [256]int8
	Components [8]uint64
	Args       [6]uint64
}

type bpfPendingSyscall struct {
	_         structs.HostLayout
	EnterTime uint64
	Args      [6]uint64
	Pid       uint32
	SysId     uint32
	Tid       uint32
	StackId   int32
	Aux0      uint32
	Aux1      uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	EnterAio                      *ebpf.ProgramSpec `ebpf:"enter_aio"`
	EnterAioBuf                   *ebpf.ProgramSpec `ebpf:"enter_aio_buf"`
	EnterAioIovec                 *ebpf.ProgramSpec `ebpf:"enter_aio_iovec"`
	EnterBpf                      *ebpf.ProgramSpec `ebpf:"enter_bpf"`
	EnterCachestat                *ebpf.ProgramSpec `ebpf:"enter_cachestat"`
	EnterCapability               *ebpf.ProgramSpec `ebpf:"enter_capability"`
	EnterClone3                   *ebpf.ProgramSpec `ebpf:"enter_clone3"`
	EnterDualPath                 *ebpf.ProgramSpec `ebpf:"enter_dual_path"`
	EnterEpoll                    *ebpf.ProgramSpec `ebpf:"enter_epoll"`
	EnterExec                     *ebpf.ProgramSpec `ebpf:"enter_exec"`
	EnterFcntl                    *ebpf.ProgramSpec `ebpf:"enter_fcntl"`
	EnterFileTime                 *ebpf.ProgramSpec `ebpf:"enter_file_time"`
	EnterFs                       *ebpf.ProgramSpec `ebpf:"enter_fs"`
	EnterFutex                    *ebpf.ProgramSpec `ebpf:"enter_futex"`
	EnterIoctl                    *ebpf.ProgramSpec `ebpf:"enter_ioctl"`
	EnterIovec                    *ebpf.ProgramSpec `ebpf:"enter_iovec"`
	EnterIovecBase                *ebpf.ProgramSpec `ebpf:"enter_iovec_base"`
	EnterItimer                   *ebpf.ProgramSpec `ebpf:"enter_itimer"`
	EnterKey                      *ebpf.ProgramSpec `ebpf:"enter_key"`
	EnterMemfd                    *ebpf.ProgramSpec `ebpf:"enter_memfd"`
	EnterMiscStruct               *ebpf.ProgramSpec `ebpf:"enter_misc_struct"`
	EnterMmsg                     *ebpf.ProgramSpec `ebpf:"enter_mmsg"`
	EnterMmsgBase0                *ebpf.ProgramSpec `ebpf:"enter_mmsg_base0"`
	EnterMmsgBase1                *ebpf.ProgramSpec `ebpf:"enter_mmsg_base1"`
	EnterMmsgBase2                *ebpf.ProgramSpec `ebpf:"enter_mmsg_base2"`
	EnterMmsgBase3                *ebpf.ProgramSpec `ebpf:"enter_mmsg_base3"`
	EnterMmsgBytes0               *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes0"`
	EnterMmsgBytes1               *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes1"`
	EnterMmsgBytes2               *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes2"`
	EnterMmsgBytes3               *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes3"`
	EnterMountPath                *ebpf.ProgramSpec `ebpf:"enter_mount_path"`
	EnterMsg                      *ebpf.ProgramSpec `ebpf:"enter_msg"`
	EnterNetwork                  *ebpf.ProgramSpec `ebpf:"enter_network"`
	EnterNoPayloadDirect          *ebpf.ProgramSpec `ebpf:"enter_no_payload_direct"`
	EnterOpenat2                  *ebpf.ProgramSpec `ebpf:"enter_openat2"`
	EnterPathOnly                 *ebpf.ProgramSpec `ebpf:"enter_path_only"`
	EnterPathStat                 *ebpf.ProgramSpec `ebpf:"enter_path_stat"`
	EnterPayloadDirect            *ebpf.ProgramSpec `ebpf:"enter_payload_direct"`
	EnterPoll                     *ebpf.ProgramSpec `ebpf:"enter_poll"`
	EnterPrctl                    *ebpf.ProgramSpec `ebpf:"enter_prctl"`
	EnterQuota                    *ebpf.ProgramSpec `ebpf:"enter_quota"`
	EnterReadlink                 *ebpf.ProgramSpec `ebpf:"enter_readlink"`
	EnterSelect                   *ebpf.ProgramSpec `ebpf:"enter_select"`
	EnterSendmsgBase              *ebpf.ProgramSpec `ebpf:"enter_sendmsg_base"`
	EnterSignal                   *ebpf.ProgramSpec `ebpf:"enter_signal"`
	EnterSleep                    *ebpf.ProgramSpec `ebpf:"enter_sleep"`
	EnterSmallStruct              *ebpf.ProgramSpec `ebpf:"enter_small_struct"`
	EnterTerminating              *ebpf.ProgramSpec `ebpf:"enter_terminating"`
	EnterTimeStruct               *ebpf.ProgramSpec `ebpf:"enter_time_struct"`
	EnterXattr                    *ebpf.ProgramSpec `ebpf:"enter_xattr"`
	ExitGeneric                   *ebpf.ProgramSpec `ebpf:"exit_generic"`
	ExitIovecBase                 *ebpf.ProgramSpec `ebpf:"exit_iovec_base"`
	ExitMmsgFinal                 *ebpf.ProgramSpec `ebpf:"exit_mmsg_final"`
	ExitMountQuery                *ebpf.ProgramSpec `ebpf:"exit_mount_query"`
	ExitMsg                       *ebpf.ProgramSpec `ebpf:"exit_msg"`
	ExitPath                      *ebpf.ProgramSpec `ebpf:"exit_path"`
	ExitQuota                     *ebpf.ProgramSpec `ebpf:"exit_quota"`
	ExitRecvmmsgBase01            *ebpf.ProgramSpec `ebpf:"exit_recvmmsg_base01"`
	ExitRecvmmsgBase2             *ebpf.ProgramSpec `ebpf:"exit_recvmmsg_base2"`
	ExitRecvmmsgBase3             *ebpf.ProgramSpec `ebpf:"exit_recvmmsg_base3"`
	TraceKretprobeRecvmsgControl  *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgDispatch *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_dispatch"`
	TraceKretprobeRecvmsgFinal    *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_final"`
	TraceKretprobeRecvmsgName     *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_name"`
	TraceSchedProcessExec         *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit         *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork         *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree         *ebpf.ProgramSpec `ebpf:"trace_sched_process_free"`
	TraceSysEnter                 *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceSysExit                  *ebpf.ProgramSpec `ebpf:"trace_sys_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ArmForkMap       *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap  *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap   *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs       *ebpf.MapSpec `ebpf:"enter_progs"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	ExitProgs        *ebpf.MapSpec `ebpf:"exit_progs"`
	FdPathScratchMap *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap    *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs   *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap   *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.MapSpec `ebpf:"pending_syscalls"`
	PreExecMap       *ebpf.MapSpec `ebpf:"pre_exec_map"`
	RecvmsgProgs     *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	StackTraces      *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ArmForkMap       *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap  *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap   *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	EnterProgs       *ebpf.Map `ebpf:"enter_progs"`
	Events           *ebpf.Map `ebpf:"events"`
	ExitProgs        *ebpf.Map `ebpf:"exit_progs"`
	FdPathScratchMap *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap    *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs   *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap   *ebpf.Map `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.Map `ebpf:"pending_syscalls"`
	PreExecMap       *ebpf.Map `ebpf:"pre_exec_map"`
	RecvmsgProgs     *ebpf.Map `ebpf:"recvmsg_progs"`
	StackTraces      *ebpf.Map `ebpf:"stack_traces"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.Events,
		m.ExitProgs,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingSyscalls,
		m.PreExecMap,
		m.RecvmsgProgs,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	EnterAio                      *ebpf.Program `ebpf:"enter_aio"`
	EnterAioBuf                   *ebpf.Program `ebpf:"enter_aio_buf"`
	EnterAioIovec                 *ebpf.Program `ebpf:"enter_aio_iovec"`
	EnterBpf                      *ebpf.Program `ebpf:"enter_bpf"`
	EnterCachestat                *ebpf.Program `ebpf:"enter_cachestat"`
	EnterCapability               *ebpf.Program `ebpf:"enter_capability"`
	EnterClone3                   *ebpf.Program `ebpf:"enter_clone3"`
	EnterDualPath                 *ebpf.Program `ebpf:"enter_dual_path"`
	EnterEpoll                    *ebpf.Program `ebpf:"enter_epoll"`
	EnterExec                     *ebpf.Program `ebpf:"enter_exec"`
	EnterFcntl                    *ebpf.Program `ebpf:"enter_fcntl"`
	EnterFileTime                 *ebpf.Program `ebpf:"enter_file_time"`
	EnterFs                       *ebpf.Program `ebpf:"enter_fs"`
	EnterFutex                    *ebpf.Program `ebpf:"enter_futex"`
	EnterIoctl                    *ebpf.Program `ebpf:"enter_ioctl"`
	EnterIovec                    *ebpf.Program `ebpf:"enter_iovec"`
	EnterIovecBase                *ebpf.Program `ebpf:"enter_iovec_base"`
	EnterItimer                   *ebpf.Program `ebpf:"enter_itimer"`
	EnterKey                      *ebpf.Program `ebpf:"enter_key"`
	EnterMemfd                    *ebpf.Program `ebpf:"enter_memfd"`
	EnterMiscStruct               *ebpf.Program `ebpf:"enter_misc_struct"`
	EnterMmsg                     *ebpf.Program `ebpf:"enter_mmsg"`
	EnterMmsgBase0                *ebpf.Program `ebpf:"enter_mmsg_base0"`
	EnterMmsgBase1                *ebpf.Program `ebpf:"enter_mmsg_base1"`
	EnterMmsgBase2                *ebpf.Program `ebpf:"enter_mmsg_base2"`
	EnterMmsgBase3                *ebpf.Program `ebpf:"enter_mmsg_base3"`
	EnterMmsgBytes0               *ebpf.Program `ebpf:"enter_mmsg_bytes0"`
	EnterMmsgBytes1               *ebpf.Program `ebpf:"enter_mmsg_bytes1"`
	EnterMmsgBytes2               *ebpf.Program `ebpf:"enter_mmsg_bytes2"`
	EnterMmsgBytes3               *ebpf.Program `ebpf:"enter_mmsg_bytes3"`
	EnterMountPath                *ebpf.Program `ebpf:"enter_mount_path"`
	EnterMsg                      *ebpf.Program `ebpf:"enter_msg"`
	EnterNetwork                  *ebpf.Program `ebpf:"enter_network"`
	EnterNoPayloadDirect          *ebpf.Program `ebpf:"enter_no_payload_direct"`
	EnterOpenat2                  *ebpf.Program `ebpf:"enter_openat2"`
	EnterPathOnly                 *ebpf.Program `ebpf:"enter_path_only"`
	EnterPathStat                 *ebpf.Program `ebpf:"enter_path_stat"`
	EnterPayloadDirect            *ebpf.Program `ebpf:"enter_payload_direct"`
	EnterPoll                     *ebpf.Program `ebpf:"enter_poll"`
	EnterPrctl                    *ebpf.Program `ebpf:"enter_prctl"`
	EnterQuota                    *ebpf.Program `ebpf:"enter_quota"`
	EnterReadlink                 *ebpf.Program `ebpf:"enter_readlink"`
	EnterSelect                   *ebpf.Program `ebpf:"enter_select"`
	EnterSendmsgBase              *ebpf.Program `ebpf:"enter_sendmsg_base"`
	EnterSignal                   *ebpf.Program `ebpf:"enter_signal"`
	EnterSleep                    *ebpf.Program `ebpf:"enter_sleep"`
	EnterSmallStruct              *ebpf.Program `ebpf:"enter_small_struct"`
	EnterTerminating              *ebpf.Program `ebpf:"enter_terminating"`
	EnterTimeStruct               *ebpf.Program `ebpf:"enter_time_struct"`
	EnterXattr                    *ebpf.Program `ebpf:"enter_xattr"`
	ExitGeneric                   *ebpf.Program `ebpf:"exit_generic"`
	ExitIovecBase                 *ebpf.Program `ebpf:"exit_iovec_base"`
	ExitMmsgFinal                 *ebpf.Program `ebpf:"exit_mmsg_final"`
	ExitMountQuery                *ebpf.Program `ebpf:"exit_mount_query"`
	ExitMsg                       *ebpf.Program `ebpf:"exit_msg"`
	ExitPath                      *ebpf.Program `ebpf:"exit_path"`
	ExitQuota                     *ebpf.Program `ebpf:"exit_quota"`
	ExitRecvmmsgBase01            *ebpf.Program `ebpf:"exit_recvmmsg_base01"`
	ExitRecvmmsgBase2             *ebpf.Program `ebpf:"exit_recvmmsg_base2"`
	ExitRecvmmsgBase3             *ebpf.Program `ebpf:"exit_recvmmsg_base3"`
	TraceKretprobeRecvmsgControl  *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgDispatch *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_dispatch"`
	TraceKretprobeRecvmsgFinal    *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_final"`
	TraceKretprobeRecvmsgName     *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_name"`
	TraceSchedProcessExec         *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit         *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork         *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree         *ebpf.Program `ebpf:"trace_sched_process_free"`
	TraceSysEnter                 *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit                  *ebpf.Program `ebpf:"trace_sys_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.EnterAio,
		p.EnterAioBuf,
		p.EnterAioIovec,
		p.EnterBpf,
		p.EnterCachestat,
		p.EnterCapability,
		p.EnterClone3,
		p.EnterDualPath,
		p.EnterEpoll,
		p.EnterExec,
		p.EnterFcntl,
		p.EnterFileTime,
		p.EnterFs,
		p.EnterFutex,
		p.EnterIoctl,
		p.EnterIovec,
		p.EnterIovecBase,
		p.EnterItimer,
		p.EnterKey,
		p.EnterMemfd,
		p.EnterMiscStruct,
		p.EnterMmsg,
		p.EnterMmsgBase0,
		p.EnterMmsgBase1,
		p.EnterMmsgBase2,
		p.EnterMmsgBase3,
		p.EnterMmsgBytes0,
		p.EnterMmsgBytes1,
		p.EnterMmsgBytes2,
		p.EnterMmsgBytes3,
		p.EnterMountPath,
		p.EnterMsg,
		p.EnterNetwork,
		p.EnterNoPayloadDirect,
		p.EnterOpenat2,
		p.EnterPathOnly,
		p.EnterPathStat,
		p.EnterPayloadDirect,
		p.EnterPoll,
		p.EnterPrctl,
		p.EnterQuota,
		p.EnterReadlink,
		p.EnterSelect,
		p.EnterSendmsgBase,
		p.EnterSignal,
		p.EnterSleep,
		p.EnterSmallStruct,
		p.EnterTerminating,
		p.EnterTimeStruct,
		p.EnterXattr,
		p.ExitGeneric,
		p.ExitIovecBase,
		p.ExitMmsgFinal,
		p.ExitMountQuery,
		p.ExitMsg,
		p.ExitPath,
		p.ExitQuota,
		p.ExitRecvmmsgBase01,
		p.ExitRecvmmsgBase2,
		p.ExitRecvmmsgBase3,
		p.TraceKretprobeRecvmsgControl,
		p.TraceKretprobeRecvmsgDispatch,
		p.TraceKretprobeRecvmsgFinal,
		p.TraceKretprobeRecvmsgName,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSchedProcessFree,
		p.TraceSysEnter,
		p.TraceSysExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
