// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBpfStats struct {
	_                      structs.HostLayout
	RingbufReserveFail     uint64
	RingbufCopyFail        uint64
	PayloadTruncatedEvents uint64
}

type bpfPendingSyscall struct {
	_         structs.HostLayout
	EnterTime uint64
	Args      [6]uint64
	Pid       uint32
	SysId     uint32
	Tid       uint32
	StackId   int32
	Aux0      uint32
	Aux1      uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceKretprobeRecvmsgControl *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgName    *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_name"`
	TraceSchedProcessExec        *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit        *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork        *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree        *ebpf.ProgramSpec `ebpf:"trace_sched_process_free"`
	TraceSysEnter                *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceSysEnterBpf             *ebpf.ProgramSpec `ebpf:"trace_sys_enter_bpf"`
	TraceSysEnterIovecBase       *ebpf.ProgramSpec `ebpf:"trace_sys_enter_iovec_base"`
	TraceSysEnterMmsg            *ebpf.ProgramSpec `ebpf:"trace_sys_enter_mmsg"`
	TraceSysEnterMsg             *ebpf.ProgramSpec `ebpf:"trace_sys_enter_msg"`
	TraceSysEnterSendmmsgBase0   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendmmsg_base0"`
	TraceSysEnterSendmmsgBase1   *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendmmsg_base1"`
	TraceSysEnterSendmsgBase     *ebpf.ProgramSpec `ebpf:"trace_sys_enter_sendmsg_base"`
	TraceSysExit                 *ebpf.ProgramSpec `ebpf:"trace_sys_exit"`
	TraceSysExitIovecBase        *ebpf.ProgramSpec `ebpf:"trace_sys_exit_iovec_base"`
	TraceSysExitMmsg             *ebpf.ProgramSpec `ebpf:"trace_sys_exit_mmsg"`
	TraceSysExitMsg              *ebpf.ProgramSpec `ebpf:"trace_sys_exit_msg"`
	TraceSysExitRecvmmsgBase0    *ebpf.ProgramSpec `ebpf:"trace_sys_exit_recvmmsg_base0"`
	TraceSysExitRecvmmsgBase1    *ebpf.ProgramSpec `ebpf:"trace_sys_exit_recvmmsg_base1"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap    *ebpf.MapSpec `ebpf:"main_exited_map"`
	PendingExecMap   *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.MapSpec `ebpf:"pending_syscalls"`
	StackTraces      *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	Events           *ebpf.Map `ebpf:"events"`
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap    *ebpf.Map `ebpf:"main_exited_map"`
	PendingExecMap   *ebpf.Map `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.Map `ebpf:"pending_syscalls"`
	StackTraces      *ebpf.Map `ebpf:"stack_traces"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.Events,
		m.FilterMap,
		m.MainExitedMap,
		m.PendingExecMap,
		m.PendingSyscalls,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceKretprobeRecvmsgControl *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgName    *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_name"`
	TraceSchedProcessExec        *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit        *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork        *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree        *ebpf.Program `ebpf:"trace_sched_process_free"`
	TraceSysEnter                *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysEnterBpf             *ebpf.Program `ebpf:"trace_sys_enter_bpf"`
	TraceSysEnterIovecBase       *ebpf.Program `ebpf:"trace_sys_enter_iovec_base"`
	TraceSysEnterMmsg            *ebpf.Program `ebpf:"trace_sys_enter_mmsg"`
	TraceSysEnterMsg             *ebpf.Program `ebpf:"trace_sys_enter_msg"`
	TraceSysEnterSendmmsgBase0   *ebpf.Program `ebpf:"trace_sys_enter_sendmmsg_base0"`
	TraceSysEnterSendmmsgBase1   *ebpf.Program `ebpf:"trace_sys_enter_sendmmsg_base1"`
	TraceSysEnterSendmsgBase     *ebpf.Program `ebpf:"trace_sys_enter_sendmsg_base"`
	TraceSysExit                 *ebpf.Program `ebpf:"trace_sys_exit"`
	TraceSysExitIovecBase        *ebpf.Program `ebpf:"trace_sys_exit_iovec_base"`
	TraceSysExitMmsg             *ebpf.Program `ebpf:"trace_sys_exit_mmsg"`
	TraceSysExitMsg              *ebpf.Program `ebpf:"trace_sys_exit_msg"`
	TraceSysExitRecvmmsgBase0    *ebpf.Program `ebpf:"trace_sys_exit_recvmmsg_base0"`
	TraceSysExitRecvmmsgBase1    *ebpf.Program `ebpf:"trace_sys_exit_recvmmsg_base1"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceKretprobeRecvmsgControl,
		p.TraceKretprobeRecvmsgName,
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSchedProcessFree,
		p.TraceSysEnter,
		p.TraceSysEnterBpf,
		p.TraceSysEnterIovecBase,
		p.TraceSysEnterMmsg,
		p.TraceSysEnterMsg,
		p.TraceSysEnterSendmmsgBase0,
		p.TraceSysEnterSendmmsgBase1,
		p.TraceSysEnterSendmsgBase,
		p.TraceSysExit,
		p.TraceSysExitIovecBase,
		p.TraceSysExitMmsg,
		p.TraceSysExitMsg,
		p.TraceSysExitRecvmmsgBase0,
		p.TraceSysExitRecvmmsgBase1,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
