package main

// Generated by generate-capture-manifest. DO NOT EDIT.

const (
	bpfRouteMapMaxEntries           = 512
	bpfEnterProgArrayMaxEntries     = 54
	bpfExitProgArrayMaxEntries      = 18
	bpfRecvmsgProgArrayMaxEntries   = 3
	bpfMmsgBytesProgArrayMaxEntries = 4
)

const (
	enterProgTerminating      = 1
	enterProgExec             = 2
	enterProgPathStat         = 3
	enterProgPathOnly         = 4
	enterProgDualPath         = 5
	enterProgOpenat2          = 6
	enterProgReadlink         = 7
	enterProgMiscStruct       = 8
	enterProgSmallStruct      = 9
	enterProgItimer           = 10
	enterProgTimeStruct       = 11
	enterProgSignal           = 12
	enterProgFileTime         = 13
	enterProgSleep            = 14
	enterProgFutex            = 15
	enterProgCachestat        = 16
	enterProgCapability       = 17
	enterProgMemfd            = 18
	enterProgPrctl            = 19
	enterProgClone3           = 20
	enterProgBpf              = 21
	enterProgIovec            = 22
	enterProgMsg              = 23
	enterProgMmsg             = 24
	enterProgFcntl            = 25
	enterProgIoctl            = 26
	enterProgNetwork          = 27
	enterProgKey              = 28
	enterProgXattr            = 29
	enterProgFs               = 30
	enterProgAio              = 31
	enterProgPoll             = 32
	enterProgSelect           = 33
	enterProgEpoll            = 34
	enterProgNoPayload        = 35
	enterProgPayload          = 36
	enterProgIovecBase        = 37
	enterProgSendmsgBase      = 38
	enterProgMmsgB01          = 39
	enterProgMmsgB2           = 40
	enterProgMmsgB3           = 41
	enterProgAioIovec         = 42
	enterProgAioBuf           = 43
	enterProgQuota            = 44
	enterProgMountPath        = 45
	enterProgNoPayloadGeneric = 46
	enterProgNestedFDPath0    = 47
	enterProgNestedFDPath1    = 48
	enterProgNestedFDPath2    = 49
	enterProgNestedFDPath3    = 50
	enterProgBpfUprobeMulti   = 51
	enterProgBpfProgLoad      = 52
	enterProgBpfProgLoadDebug = 53
)

const (
	exitProgGeneric        = 0
	exitProgIovecBase      = 1
	exitProgMsg            = 2
	exitProgMmsgFinal      = 3
	exitProgRecvmmsgBase01 = 4
	exitProgRecvmmsgBase23 = 5
	exitProgQuota          = 6
	exitProgMountQuery     = 7
	exitProgPath           = 8
	exitProgFDTime         = 9
	exitProgStruct         = 10
	exitProgAsync          = 11
	exitProgIO             = 12
	exitProgControl        = 13
	exitProgNestedFDPath0  = 14
	exitProgNestedFDPath1  = 15
	exitProgNestedFDPath2  = 16
	exitProgNestedFDPath3  = 17
)

const (
	recvmsgProgName    = 0
	recvmsgProgControl = 1
	recvmsgProgFinal   = 2
)

const (
	mmsgBytesProgBase0 = 0
	mmsgBytesProgBase1 = 1
	mmsgBytesProgBase2 = 2
	mmsgBytesProgBase3 = 3
)

var bpfEnterProgramCatalog = []bpfTailCallProgramSpec{
	{slot: enterProgTerminating, name: "enter_terminating", family: bpfHandlerEnterGenericFamily},
	{slot: enterProgExec, name: "enter_exec", family: bpfHandlerEnterPayloadFamily},
	{slot: enterProgPathStat, name: "enter_path_stat", family: bpfHandlerEnterPathFamily},
	{slot: enterProgPathOnly, name: "enter_path_only", family: bpfHandlerEnterPathFamily},
	{slot: enterProgDualPath, name: "enter_dual_path", family: bpfHandlerEnterPathFamily},
	{slot: enterProgOpenat2, name: "enter_openat2", family: bpfHandlerEnterPathFamily},
	{slot: enterProgReadlink, name: "enter_readlink", family: bpfHandlerEnterPathFamily},
	{slot: enterProgMiscStruct, name: "enter_misc_struct", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgSmallStruct, name: "enter_small_struct", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgItimer, name: "enter_itimer", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgTimeStruct, name: "enter_time_struct", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgSignal, name: "enter_signal", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgFileTime, name: "enter_file_time", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgSleep, name: "enter_sleep", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgFutex, name: "enter_futex", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgCachestat, name: "enter_cachestat", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgCapability, name: "enter_capability", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgMemfd, name: "enter_memfd", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgPrctl, name: "enter_prctl", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgClone3, name: "enter_clone3", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgBpf, name: "enter_bpf", family: bpfHandlerEnterStructuredFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgBpfUprobeMulti}, {array: bpfProgramArrayEnter, slot: enterProgBpfProgLoad}, {array: bpfProgramArrayEnter, slot: enterProgBpfProgLoadDebug}}},
	{slot: enterProgIovec, name: "enter_iovec", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgIovecBase}}},
	{slot: enterProgMsg, name: "enter_msg", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgSendmsgBase}}},
	{slot: enterProgMmsg, name: "enter_mmsg", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgMmsgB01}, {array: bpfProgramArrayEnter, slot: enterProgMmsgB2}, {array: bpfProgramArrayEnter, slot: enterProgMmsgB3}}},
	{slot: enterProgFcntl, name: "enter_fcntl", family: bpfHandlerEnterControlFamily},
	{slot: enterProgIoctl, name: "enter_ioctl", family: bpfHandlerEnterControlFamily},
	{slot: enterProgNetwork, name: "enter_network", family: bpfHandlerEnterControlFamily},
	{slot: enterProgKey, name: "enter_key", family: bpfHandlerEnterControlFamily},
	{slot: enterProgXattr, name: "enter_xattr", family: bpfHandlerEnterControlFamily},
	{slot: enterProgFs, name: "enter_fs", family: bpfHandlerEnterControlFamily},
	{slot: enterProgAio, name: "enter_aio", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgAioIovec}}},
	{slot: enterProgPoll, name: "enter_poll", family: bpfHandlerEnterControlFamily},
	{slot: enterProgSelect, name: "enter_select", family: bpfHandlerEnterControlFamily},
	{slot: enterProgEpoll, name: "enter_epoll", family: bpfHandlerEnterControlFamily},
	{slot: enterProgNoPayload, name: "enter_no_payload_direct", family: bpfHandlerEnterPathFamily},
	{slot: enterProgPayload, name: "enter_payload_direct", family: bpfHandlerEnterPayloadFamily},
	{slot: enterProgIovecBase, name: "enter_iovec_base", family: bpfHandlerEnterMemoryFamily},
	{slot: enterProgSendmsgBase, name: "enter_sendmsg_base", family: bpfHandlerEnterMemoryFamily},
	{slot: enterProgMmsgB01, name: "enter_mmsg_base01", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgMmsgB2}}},
	{slot: enterProgMmsgB2, name: "enter_mmsg_base2", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgMmsgB3}}},
	{slot: enterProgMmsgB3, name: "enter_mmsg_base3", family: bpfHandlerEnterMemoryFamily},
	{slot: enterProgAioIovec, name: "enter_aio_iovec", family: bpfHandlerEnterMemoryFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayEnter, slot: enterProgAioBuf}}},
	{slot: enterProgAioBuf, name: "enter_aio_buf", family: bpfHandlerEnterMemoryFamily},
	{slot: enterProgQuota, name: "enter_quota", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgMountPath, name: "enter_mount_path", family: bpfHandlerEnterPathFamily},
	{slot: enterProgNoPayloadGeneric, name: "enter_no_payload_generic", family: bpfHandlerEnterGenericFamily},
	{slot: enterProgNestedFDPath0, name: "enter_nested_fd_path0", family: bpfHandlerEnterControlFamily},
	{slot: enterProgNestedFDPath1, name: "enter_nested_fd_path1", family: bpfHandlerEnterControlFamily},
	{slot: enterProgNestedFDPath2, name: "enter_nested_fd_path2", family: bpfHandlerEnterControlFamily},
	{slot: enterProgNestedFDPath3, name: "enter_nested_fd_path3", family: bpfHandlerEnterControlFamily},
	{slot: enterProgBpfUprobeMulti, name: "enter_bpf_uprobe_multi", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgBpfProgLoad, name: "enter_bpf_prog_load", family: bpfHandlerEnterStructuredFamily},
	{slot: enterProgBpfProgLoadDebug, name: "enter_bpf_prog_load_debug", family: bpfHandlerEnterStructuredFamily},
}

var bpfExitProgramCatalog = []bpfTailCallProgramSpec{
	{slot: exitProgGeneric, name: "exit_generic", family: bpfHandlerExitFamily},
	{slot: exitProgIovecBase, name: "exit_iovec_base", family: bpfHandlerExitFamily},
	{slot: exitProgMsg, name: "exit_msg", family: bpfHandlerExitFamily},
	{slot: exitProgMmsgFinal, name: "exit_mmsg_final", family: bpfHandlerExitFamily},
	{slot: exitProgRecvmmsgBase01, name: "exit_recvmmsg_base01", family: bpfHandlerExitFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayExit, slot: exitProgRecvmmsgBase23}}},
	{slot: exitProgRecvmmsgBase23, name: "exit_recvmmsg_base23", family: bpfHandlerExitFamily, dependencies: []bpfProgramRef{{array: bpfProgramArrayExit, slot: exitProgMmsgFinal}}},
	{slot: exitProgQuota, name: "exit_quota", family: bpfHandlerExitFamily},
	{slot: exitProgMountQuery, name: "exit_mount_query", family: bpfHandlerExitFamily},
	{slot: exitProgPath, name: "exit_path", family: bpfHandlerExitFamily},
	{slot: exitProgFDTime, name: "exit_fd_time", family: bpfHandlerExitFamily},
	{slot: exitProgStruct, name: "exit_struct", family: bpfHandlerExitFamily},
	{slot: exitProgAsync, name: "exit_async", family: bpfHandlerExitFamily},
	{slot: exitProgIO, name: "exit_io", family: bpfHandlerExitFamily},
	{slot: exitProgControl, name: "exit_control", family: bpfHandlerExitFamily},
	{slot: exitProgNestedFDPath0, name: "exit_nested_fd_path0", family: bpfHandlerExitFamily},
	{slot: exitProgNestedFDPath1, name: "exit_nested_fd_path1", family: bpfHandlerExitFamily},
	{slot: exitProgNestedFDPath2, name: "exit_nested_fd_path2", family: bpfHandlerExitFamily},
	{slot: exitProgNestedFDPath3, name: "exit_nested_fd_path3", family: bpfHandlerExitFamily},
}

var bpfRecvmsgProgramCatalog = []bpfTailCallProgramSpec{
	{slot: recvmsgProgName, name: "trace_kretprobe_recvmsg_name", family: bpfHandlerRecvmsgFamily},
	{slot: recvmsgProgControl, name: "trace_kretprobe_recvmsg_control", family: bpfHandlerRecvmsgFamily},
	{slot: recvmsgProgFinal, name: "trace_kretprobe_recvmsg_final", family: bpfHandlerRecvmsgFamily},
}

var bpfMmsgByteProgramCatalog = []bpfTailCallProgramSpec{
	{slot: mmsgBytesProgBase0, name: "enter_mmsg_bytes0", family: bpfHandlerEnterMemoryFamily},
	{slot: mmsgBytesProgBase1, name: "enter_mmsg_bytes1", family: bpfHandlerEnterMemoryFamily},
	{slot: mmsgBytesProgBase2, name: "enter_mmsg_bytes2", family: bpfHandlerEnterMemoryFamily},
	{slot: mmsgBytesProgBase3, name: "enter_mmsg_bytes3", family: bpfHandlerEnterMemoryFamily},
}

const bpfRecvmsgDispatchProgramName = "trace_kretprobe_recvmsg_dispatch"

var bpfStandaloneProgramCatalog = []bpfStandaloneProgramSpec{
	{name: bpfRecvmsgDispatchProgramName, family: bpfHandlerRecvmsgFamily},
}

var bpfRouteCapabilities = map[string]bpfRouteCapability{
	"accept":            {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"accept4":           {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"access":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"acct":              {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"add_key":           {enterSlot: enterProgKey, exitSlot: 0, standaloneExitElision: false},
	"adjtimex":          {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"arch_prctl":        {enterSlot: 0, exitSlot: exitProgAsync, standaloneExitElision: true},
	"bind":              {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"bpf":               {enterSlot: enterProgBpf, exitSlot: exitProgIO, standaloneExitElision: false},
	"cachestat":         {enterSlot: enterProgCachestat, exitSlot: exitProgAsync, standaloneExitElision: false},
	"capget":            {enterSlot: enterProgCapability, exitSlot: exitProgAsync, standaloneExitElision: false},
	"capset":            {enterSlot: enterProgCapability, exitSlot: exitProgAsync, standaloneExitElision: false},
	"chdir":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"chmod":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"chown":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"chroot":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"clock_adjtime":     {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"clock_getres":      {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: true},
	"clock_gettime":     {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: true},
	"clock_nanosleep":   {enterSlot: enterProgSleep, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"clock_settime":     {enterSlot: enterProgTimeStruct, exitSlot: 0, standaloneExitElision: false},
	"clone3":            {enterSlot: enterProgClone3, exitSlot: 0, standaloneExitElision: false},
	"connect":           {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"copy_file_range":   {enterSlot: enterProgSmallStruct, exitSlot: 0, standaloneExitElision: false},
	"creat":             {enterSlot: enterProgPayload, exitSlot: exitProgPath, standaloneExitElision: false},
	"dup":               {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"dup2":              {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"dup3":              {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"epoll_create":      {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"epoll_create1":     {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"epoll_ctl":         {enterSlot: enterProgEpoll, exitSlot: 0, standaloneExitElision: false},
	"epoll_pwait":       {enterSlot: 0, exitSlot: exitProgIO, standaloneExitElision: false},
	"epoll_pwait2":      {enterSlot: enterProgEpoll, exitSlot: exitProgIO, standaloneExitElision: false},
	"epoll_wait":        {enterSlot: 0, exitSlot: exitProgIO, standaloneExitElision: false},
	"eventfd":           {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"eventfd2":          {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"execve":            {enterSlot: enterProgExec, exitSlot: exitProgIO, standaloneExitElision: false},
	"execveat":          {enterSlot: enterProgExec, exitSlot: exitProgIO, standaloneExitElision: false},
	"exit":              {enterSlot: enterProgTerminating, exitSlot: 0, standaloneExitElision: false},
	"exit_group":        {enterSlot: enterProgTerminating, exitSlot: 0, standaloneExitElision: false},
	"faccessat":         {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"faccessat2":        {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"fchmodat":          {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"fchownat":          {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"fcntl":             {enterSlot: enterProgFcntl, exitSlot: exitProgControl, standaloneExitElision: false},
	"fgetxattr":         {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"flistxattr":        {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"fremovexattr":      {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"fsconfig":          {enterSlot: enterProgFs, exitSlot: 0, standaloneExitElision: false},
	"fsetxattr":         {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"fsopen":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"fspick":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"fstat":             {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"fstatfs":           {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"futex":             {enterSlot: enterProgFutex, exitSlot: 0, standaloneExitElision: false},
	"futex_requeue":     {enterSlot: enterProgFutex, exitSlot: 0, standaloneExitElision: false},
	"futex_wait":        {enterSlot: enterProgFutex, exitSlot: 0, standaloneExitElision: false},
	"futex_waitv":       {enterSlot: enterProgFutex, exitSlot: 0, standaloneExitElision: false},
	"futimesat":         {enterSlot: enterProgFileTime, exitSlot: 0, standaloneExitElision: false},
	"get_robust_list":   {enterSlot: 0, exitSlot: exitProgAsync, standaloneExitElision: true},
	"getcwd":            {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"getdents":          {enterSlot: 0, exitSlot: exitProgIO, standaloneExitElision: false},
	"getdents64":        {enterSlot: 0, exitSlot: exitProgIO, standaloneExitElision: false},
	"getitimer":         {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"getpeername":       {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"getrlimit":         {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"getsockname":       {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"getsockopt":        {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"gettimeofday":      {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: true},
	"getxattr":          {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"inotify_init":      {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"inotify_init1":     {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"io_cancel":         {enterSlot: enterProgAio, exitSlot: 0, standaloneExitElision: false},
	"io_getevents":      {enterSlot: enterProgAio, exitSlot: exitProgAsync, standaloneExitElision: false},
	"io_pgetevents":     {enterSlot: enterProgAio, exitSlot: exitProgAsync, standaloneExitElision: false},
	"io_setup":          {enterSlot: enterProgAio, exitSlot: exitProgAsync, standaloneExitElision: false},
	"io_submit":         {enterSlot: enterProgAio, exitSlot: 0, standaloneExitElision: false},
	"ioctl":             {enterSlot: enterProgIoctl, exitSlot: exitProgControl, standaloneExitElision: false},
	"keyctl":            {enterSlot: enterProgKey, exitSlot: exitProgIO, standaloneExitElision: false},
	"lchown":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"lgetxattr":         {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"link":              {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"linkat":            {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"listmount":         {enterSlot: enterProgFs, exitSlot: exitProgMountQuery, standaloneExitElision: false},
	"listxattr":         {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"llistxattr":        {enterSlot: enterProgXattr, exitSlot: exitProgIO, standaloneExitElision: false},
	"lremovexattr":      {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"lsetxattr":         {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"lstat":             {enterSlot: enterProgPathStat, exitSlot: exitProgStruct, standaloneExitElision: false},
	"memfd_create":      {enterSlot: enterProgMemfd, exitSlot: 0, standaloneExitElision: false},
	"mkdir":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"mkdirat":           {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"mknod":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"mknodat":           {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"mount":             {enterSlot: enterProgFs, exitSlot: 0, standaloneExitElision: false},
	"mount_setattr":     {enterSlot: enterProgFs, exitSlot: 0, standaloneExitElision: false},
	"move_mount":        {enterSlot: enterProgMountPath, exitSlot: 0, standaloneExitElision: false},
	"nanosleep":         {enterSlot: enterProgSleep, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"newfstatat":        {enterSlot: enterProgPathStat, exitSlot: exitProgStruct, standaloneExitElision: false},
	"open":              {enterSlot: enterProgPayload, exitSlot: exitProgPath, standaloneExitElision: false},
	"open_tree":         {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"openat":            {enterSlot: enterProgPayload, exitSlot: exitProgPath, standaloneExitElision: false},
	"openat2":           {enterSlot: enterProgOpenat2, exitSlot: exitProgPath, standaloneExitElision: false},
	"pidfd_open":        {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"pipe":              {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"pipe2":             {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"poll":              {enterSlot: enterProgPoll, exitSlot: exitProgAsync, standaloneExitElision: false},
	"ppoll":             {enterSlot: enterProgPoll, exitSlot: exitProgAsync, standaloneExitElision: false},
	"prctl":             {enterSlot: enterProgPrctl, exitSlot: exitProgAsync, standaloneExitElision: false},
	"pread64":           {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"preadv":            {enterSlot: enterProgIovec, exitSlot: exitProgIovecBase, standaloneExitElision: false},
	"preadv2":           {enterSlot: enterProgIovec, exitSlot: exitProgIovecBase, standaloneExitElision: false},
	"prlimit64":         {enterSlot: enterProgMiscStruct, exitSlot: exitProgStruct, standaloneExitElision: false},
	"process_madvise":   {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
	"process_vm_readv":  {enterSlot: enterProgIovec, exitSlot: exitProgIovecBase, standaloneExitElision: false},
	"process_vm_writev": {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
	"pselect6":          {enterSlot: enterProgSelect, exitSlot: exitProgIO, standaloneExitElision: false},
	"pwrite64":          {enterSlot: enterProgPayload, exitSlot: 0, standaloneExitElision: false},
	"pwritev":           {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
	"pwritev2":          {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
	"quotactl":          {enterSlot: enterProgQuota, exitSlot: exitProgQuota, standaloneExitElision: false},
	"quotactl_fd":       {enterSlot: enterProgQuota, exitSlot: exitProgQuota, standaloneExitElision: false},
	"read":              {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"readlink":          {enterSlot: enterProgReadlink, exitSlot: exitProgStruct, standaloneExitElision: false},
	"readlinkat":        {enterSlot: enterProgReadlink, exitSlot: exitProgStruct, standaloneExitElision: false},
	"readv":             {enterSlot: enterProgIovec, exitSlot: exitProgIovecBase, standaloneExitElision: false},
	"recvfrom":          {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"recvmmsg":          {enterSlot: enterProgMmsg, exitSlot: exitProgRecvmmsgBase01, standaloneExitElision: false},
	"recvmsg":           {enterSlot: enterProgMsg, exitSlot: exitProgMsg, standaloneExitElision: false},
	"removexattr":       {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"rename":            {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"renameat":          {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"renameat2":         {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"request_key":       {enterSlot: enterProgKey, exitSlot: 0, standaloneExitElision: false},
	"rmdir":             {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"rt_sigaction":      {enterSlot: enterProgSignal, exitSlot: exitProgStruct, standaloneExitElision: false},
	"rt_sigprocmask":    {enterSlot: enterProgSignal, exitSlot: exitProgStruct, standaloneExitElision: false},
	"rt_sigsuspend":     {enterSlot: enterProgSignal, exitSlot: exitProgStruct, standaloneExitElision: false},
	"select":            {enterSlot: enterProgSelect, exitSlot: exitProgIO, standaloneExitElision: false},
	"sendfile":          {enterSlot: enterProgSmallStruct, exitSlot: exitProgAsync, standaloneExitElision: false},
	"sendmmsg":          {enterSlot: enterProgMmsg, exitSlot: exitProgMmsgFinal, standaloneExitElision: false},
	"sendmsg":           {enterSlot: enterProgMsg, exitSlot: exitProgMsg, standaloneExitElision: false},
	"sendto":            {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"setitimer":         {enterSlot: enterProgItimer, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"setrlimit":         {enterSlot: enterProgMiscStruct, exitSlot: exitProgStruct, standaloneExitElision: false},
	"setsockopt":        {enterSlot: enterProgNetwork, exitSlot: exitProgControl, standaloneExitElision: false},
	"settimeofday":      {enterSlot: enterProgTimeStruct, exitSlot: 0, standaloneExitElision: false},
	"setxattr":          {enterSlot: enterProgXattr, exitSlot: 0, standaloneExitElision: false},
	"signalfd":          {enterSlot: enterProgSignal, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"signalfd4":         {enterSlot: enterProgSignal, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"socket":            {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"socketpair":        {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"stat":              {enterSlot: enterProgPathStat, exitSlot: exitProgStruct, standaloneExitElision: false},
	"statfs":            {enterSlot: enterProgPathStat, exitSlot: exitProgStruct, standaloneExitElision: false},
	"statmount":         {enterSlot: enterProgFs, exitSlot: exitProgMountQuery, standaloneExitElision: false},
	"statx":             {enterSlot: enterProgPathStat, exitSlot: exitProgStruct, standaloneExitElision: false},
	"swapoff":           {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"swapon":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"symlink":           {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"symlinkat":         {enterSlot: enterProgDualPath, exitSlot: exitProgPath, standaloneExitElision: false},
	"sysinfo":           {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"time":              {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"timerfd_create":    {enterSlot: 0, exitSlot: exitProgFDTime, standaloneExitElision: false},
	"truncate":          {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"umount2":           {enterSlot: enterProgFs, exitSlot: 0, standaloneExitElision: false},
	"uname":             {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"unlink":            {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"unlinkat":          {enterSlot: enterProgPathOnly, exitSlot: exitProgPath, standaloneExitElision: false},
	"utime":             {enterSlot: enterProgFileTime, exitSlot: 0, standaloneExitElision: false},
	"utimensat":         {enterSlot: enterProgFileTime, exitSlot: 0, standaloneExitElision: false},
	"utimes":            {enterSlot: enterProgFileTime, exitSlot: 0, standaloneExitElision: false},
	"vmsplice":          {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
	"waitid":            {enterSlot: 0, exitSlot: exitProgStruct, standaloneExitElision: false},
	"write":             {enterSlot: enterProgPayload, exitSlot: 0, standaloneExitElision: false},
	"writev":            {enterSlot: enterProgIovec, exitSlot: 0, standaloneExitElision: false},
}

var bpfSyscallProgramRoots = map[string]bpfProgramRootSpec{
	"recvmsg":  {programs: []string{"trace_kretprobe_recvmsg_dispatch"}, refs: []bpfProgramRef{{array: bpfProgramArrayRecvmsg, slot: recvmsgProgName}, {array: bpfProgramArrayRecvmsg, slot: recvmsgProgControl}, {array: bpfProgramArrayRecvmsg, slot: recvmsgProgFinal}}, recvmsgKretprobe: true},
	"sendmmsg": {refs: []bpfProgramRef{{array: bpfProgramArrayMmsgBytes, slot: mmsgBytesProgBase0}, {array: bpfProgramArrayMmsgBytes, slot: mmsgBytesProgBase1}, {array: bpfProgramArrayMmsgBytes, slot: mmsgBytesProgBase2}, {array: bpfProgramArrayMmsgBytes, slot: mmsgBytesProgBase3}}},
}
