// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBpfEvent struct {
	_             structs.HostLayout
	Pid           uint32
	SysId         uint32
	Tid           uint32
	EventVersion  uint16
	EventType     uint16
	EventFlags    uint32
	ProbeRetEnter int32
	ProbeRetExit  int32
	_             [4]byte
	EnterTime     uint64
	Duration      uint64
	Args          [6]uint64
	Ret           int64
	Ptr           uint64
	DataLen       uint32
	StackId       int32
	StrArg        [10400]uint8
}

type bpfPendingSyscall struct {
	_         structs.HostLayout
	EnterTime uint64
	Args      [6]uint64
	Pid       uint32
	SysId     uint32
	Tid       uint32
	StackId   int32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceSchedProcessExec *ebpf.ProgramSpec `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.ProgramSpec `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.ProgramSpec `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree *ebpf.ProgramSpec `ebpf:"trace_sched_process_free"`
	TraceSysEnter         *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceSysExit          *ebpf.ProgramSpec `ebpf:"trace_sys_exit"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	Heap             *ebpf.MapSpec `ebpf:"heap"`
	MainExitedMap    *ebpf.MapSpec `ebpf:"main_exited_map"`
	PendingExecMap   *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.MapSpec `ebpf:"pending_syscalls"`
	StackTraces      *ebpf.MapSpec `ebpf:"stack_traces"`
	SyscallFilterMap *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	Events           *ebpf.Map `ebpf:"events"`
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	Heap             *ebpf.Map `ebpf:"heap"`
	MainExitedMap    *ebpf.Map `ebpf:"main_exited_map"`
	PendingExecMap   *ebpf.Map `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.Map `ebpf:"pending_syscalls"`
	StackTraces      *ebpf.Map `ebpf:"stack_traces"`
	SyscallFilterMap *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.Events,
		m.FilterMap,
		m.Heap,
		m.MainExitedMap,
		m.PendingExecMap,
		m.PendingSyscalls,
		m.StackTraces,
		m.SyscallFilterMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceSchedProcessExec *ebpf.Program `ebpf:"trace_sched_process_exec"`
	TraceSchedProcessExit *ebpf.Program `ebpf:"trace_sched_process_exit"`
	TraceSchedProcessFork *ebpf.Program `ebpf:"trace_sched_process_fork"`
	TraceSchedProcessFree *ebpf.Program `ebpf:"trace_sched_process_free"`
	TraceSysEnter         *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit          *ebpf.Program `ebpf:"trace_sys_exit"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceSchedProcessExec,
		p.TraceSchedProcessExit,
		p.TraceSchedProcessFork,
		p.TraceSchedProcessFree,
		p.TraceSysEnter,
		p.TraceSysExit,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
