// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEnterPathBpfStats struct {
	_                      structs.HostLayout
	RingbufReserveFail     uint64
	RingbufCopyFail        uint64
	PayloadTruncatedEvents uint64
	PendingUpdateFail      uint64
	OrphanExit             uint64
	PendingMismatch        uint64
	LifecycleMapUpdateFail uint64
}

type bpfEnterPathFdPathScratch struct {
	_             structs.HostLayout
	Name          [256]int8
	Components    [8]uint64
	Args          [6]uint64
	NestedFdset   [128]uint8
	NestedFd0     int32
	NestedFd1     int32
	NestedFd2     int32
	NestedFd3     int32
	NestedFdCount uint32
	_             [4]byte
}

type bpfEnterPathPendingSyscall struct {
	_         structs.HostLayout
	EnterTime uint64
	Args      [6]uint64
	Pid       uint32
	SysId     uint32
	Tid       uint32
	StackId   int32
}

type bpfEnterPathPendingSyscallAux struct {
	_    structs.HostLayout
	Aux0 uint32
}

// loadBpfEnterPath returns the embedded CollectionSpec for bpfEnterPath.
func loadBpfEnterPath() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfEnterPathBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfEnterPath: %w", err)
	}

	return spec, err
}

// loadBpfEnterPathObjects loads bpfEnterPath and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfEnterPathObjects
//	*bpfEnterPathPrograms
//	*bpfEnterPathMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfEnterPathObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfEnterPath()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfEnterPathSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPathSpecs struct {
	bpfEnterPathProgramSpecs
	bpfEnterPathMapSpecs
	bpfEnterPathVariableSpecs
}

// bpfEnterPathProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPathProgramSpecs struct {
	EnterDualPath        *ebpf.ProgramSpec `ebpf:"enter_dual_path"`
	EnterMountPath       *ebpf.ProgramSpec `ebpf:"enter_mount_path"`
	EnterNoPayloadDirect *ebpf.ProgramSpec `ebpf:"enter_no_payload_direct"`
	EnterOpenat2         *ebpf.ProgramSpec `ebpf:"enter_openat2"`
	EnterPathOnly        *ebpf.ProgramSpec `ebpf:"enter_path_only"`
	EnterPathStat        *ebpf.ProgramSpec `ebpf:"enter_path_stat"`
	EnterReadlink        *ebpf.ProgramSpec `ebpf:"enter_readlink"`
}

// bpfEnterPathMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPathMapSpecs struct {
	ArmForkMap           *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap      *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap       *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap            *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs           *ebpf.MapSpec `ebpf:"enter_progs"`
	EnterRoutes          *ebpf.MapSpec `ebpf:"enter_routes"`
	Events               *ebpf.MapSpec `ebpf:"events"`
	ExitProgs            *ebpf.MapSpec `ebpf:"exit_progs"`
	ExitRoutes           *ebpf.MapSpec `ebpf:"exit_routes"`
	FdPathScratchMap     *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap            *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap        *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs       *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap       *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingSyscallAuxMap *ebpf.MapSpec `ebpf:"pending_syscall_aux_map"`
	PendingSyscalls      *ebpf.MapSpec `ebpf:"pending_syscalls"`
	PreExecMap           *ebpf.MapSpec `ebpf:"pre_exec_map"`
	RecvmsgProgs         *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	StackTraces          *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap             *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap     *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfEnterPathVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPathVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterPathObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPathObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPathObjects struct {
	bpfEnterPathPrograms
	bpfEnterPathMaps
	bpfEnterPathVariables
}

func (o *bpfEnterPathObjects) Close() error {
	return _BpfEnterPathClose(
		&o.bpfEnterPathPrograms,
		&o.bpfEnterPathMaps,
	)
}

// bpfEnterPathMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPathObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPathMaps struct {
	ArmForkMap           *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap      *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap       *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap            *ebpf.Map `ebpf:"config_map"`
	EnterProgs           *ebpf.Map `ebpf:"enter_progs"`
	EnterRoutes          *ebpf.Map `ebpf:"enter_routes"`
	Events               *ebpf.Map `ebpf:"events"`
	ExitProgs            *ebpf.Map `ebpf:"exit_progs"`
	ExitRoutes           *ebpf.Map `ebpf:"exit_routes"`
	FdPathScratchMap     *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap            *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap        *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs       *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap       *ebpf.Map `ebpf:"pending_exec_map"`
	PendingSyscallAuxMap *ebpf.Map `ebpf:"pending_syscall_aux_map"`
	PendingSyscalls      *ebpf.Map `ebpf:"pending_syscalls"`
	PreExecMap           *ebpf.Map `ebpf:"pre_exec_map"`
	RecvmsgProgs         *ebpf.Map `ebpf:"recvmsg_progs"`
	StackTraces          *ebpf.Map `ebpf:"stack_traces"`
	StatsMap             *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap     *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfEnterPathMaps) Close() error {
	return _BpfEnterPathClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.EnterRoutes,
		m.Events,
		m.ExitProgs,
		m.ExitRoutes,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingSyscallAuxMap,
		m.PendingSyscalls,
		m.PreExecMap,
		m.RecvmsgProgs,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfEnterPathVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPathObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPathVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterPathPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPathObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPathPrograms struct {
	EnterDualPath        *ebpf.Program `ebpf:"enter_dual_path"`
	EnterMountPath       *ebpf.Program `ebpf:"enter_mount_path"`
	EnterNoPayloadDirect *ebpf.Program `ebpf:"enter_no_payload_direct"`
	EnterOpenat2         *ebpf.Program `ebpf:"enter_openat2"`
	EnterPathOnly        *ebpf.Program `ebpf:"enter_path_only"`
	EnterPathStat        *ebpf.Program `ebpf:"enter_path_stat"`
	EnterReadlink        *ebpf.Program `ebpf:"enter_readlink"`
}

func (p *bpfEnterPathPrograms) Close() error {
	return _BpfEnterPathClose(
		p.EnterDualPath,
		p.EnterMountPath,
		p.EnterNoPayloadDirect,
		p.EnterOpenat2,
		p.EnterPathOnly,
		p.EnterPathStat,
		p.EnterReadlink,
	)
}

func _BpfEnterPathClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfenterpath_bpfeb.o
var _BpfEnterPathBytes []byte
