// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEnterStructuredBpfStats struct {
	_                                 structs.HostLayout
	RingbufReserveFail                uint64
	RingbufCopyFail                   uint64
	PayloadTruncatedEvents            uint64
	PendingUpdateFail                 uint64
	OrphanExit                        uint64
	PendingMismatch                   uint64
	LifecycleMapUpdateFail            uint64
	LifecycleForkSeen                 uint64
	LifecycleForkParentTracked        uint64
	LifecycleForkParentUntracked      uint64
	LifecycleForkChildFilterInstalled uint64
	LifecycleForkChildFilterFailed    uint64
	LifecycleExecSeen                 uint64
	LifecycleExecUntracked            uint64
	LifecycleExitSeen                 uint64
	LifecycleExitUntracked            uint64
}

type bpfEnterStructuredFdPathScratch struct {
	_             structs.HostLayout
	Name          [256]int8
	Components    [8]uint64
	Args          [6]uint64
	NestedFdset   [128]uint8
	NestedFd0     int32
	NestedFd1     int32
	NestedFd2     int32
	NestedFd3     int32
	NestedFdCount uint32
	_             [4]byte
}

type bpfEnterStructuredPendingTaskState struct {
	_       structs.HostLayout
	Syscall struct {
		_         structs.HostLayout
		EnterTime uint64
		Args      [6]uint64
		Pid       uint32
		SysId     uint32
		Tid       uint32
		StackId   int32
	}
	NamespaceSnapshot struct {
		_      structs.HostLayout
		Flags  uint64
		Cgroup uint32
		Ipc    uint32
		Mnt    uint32
		Net    uint32
		Pid    uint32
		Time   uint32
		Uts    uint32
		User   uint32
	}
	Aux0  uint32
	Valid uint32
}

// loadBpfEnterStructured returns the embedded CollectionSpec for bpfEnterStructured.
func loadBpfEnterStructured() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfEnterStructuredBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfEnterStructured: %w", err)
	}

	return spec, err
}

// loadBpfEnterStructuredObjects loads bpfEnterStructured and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfEnterStructuredObjects
//	*bpfEnterStructuredPrograms
//	*bpfEnterStructuredMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfEnterStructuredObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfEnterStructured()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfEnterStructuredSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterStructuredSpecs struct {
	bpfEnterStructuredProgramSpecs
	bpfEnterStructuredMapSpecs
	bpfEnterStructuredVariableSpecs
}

// bpfEnterStructuredProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterStructuredProgramSpecs struct {
	EnterBpf              *ebpf.ProgramSpec `ebpf:"enter_bpf"`
	EnterBpfProgLoad      *ebpf.ProgramSpec `ebpf:"enter_bpf_prog_load"`
	EnterBpfProgLoadDebug *ebpf.ProgramSpec `ebpf:"enter_bpf_prog_load_debug"`
	EnterBpfUprobeMulti   *ebpf.ProgramSpec `ebpf:"enter_bpf_uprobe_multi"`
	EnterCachestat        *ebpf.ProgramSpec `ebpf:"enter_cachestat"`
	EnterCapability       *ebpf.ProgramSpec `ebpf:"enter_capability"`
	EnterClone3           *ebpf.ProgramSpec `ebpf:"enter_clone3"`
	EnterFileTime         *ebpf.ProgramSpec `ebpf:"enter_file_time"`
	EnterFutex            *ebpf.ProgramSpec `ebpf:"enter_futex"`
	EnterItimer           *ebpf.ProgramSpec `ebpf:"enter_itimer"`
	EnterMemfd            *ebpf.ProgramSpec `ebpf:"enter_memfd"`
	EnterMiscStruct       *ebpf.ProgramSpec `ebpf:"enter_misc_struct"`
	EnterPrctl            *ebpf.ProgramSpec `ebpf:"enter_prctl"`
	EnterQuota            *ebpf.ProgramSpec `ebpf:"enter_quota"`
	EnterSignal           *ebpf.ProgramSpec `ebpf:"enter_signal"`
	EnterSleep            *ebpf.ProgramSpec `ebpf:"enter_sleep"`
	EnterSmallStruct      *ebpf.ProgramSpec `ebpf:"enter_small_struct"`
	EnterTimeStruct       *ebpf.ProgramSpec `ebpf:"enter_time_struct"`
}

// bpfEnterStructuredMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterStructuredMapSpecs struct {
	ArmForkMap         *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap    *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap     *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap          *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs         *ebpf.MapSpec `ebpf:"enter_progs"`
	EnterRoutes        *ebpf.MapSpec `ebpf:"enter_routes"`
	Events             *ebpf.MapSpec `ebpf:"events"`
	ExitProgs          *ebpf.MapSpec `ebpf:"exit_progs"`
	ExitRoutes         *ebpf.MapSpec `ebpf:"exit_routes"`
	FdPathScratchMap   *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap          *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap      *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs     *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap     *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingStackMap    *ebpf.MapSpec `ebpf:"pending_stack_map"`
	PendingTaskStorage *ebpf.MapSpec `ebpf:"pending_task_storage"`
	PlainEnterElideMap *ebpf.MapSpec `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs       *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	RuntimeMetaMap     *ebpf.MapSpec `ebpf:"runtime_meta_map"`
	StackTraces        *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap           *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap   *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfEnterStructuredVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterStructuredVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterStructuredObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterStructuredObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterStructuredObjects struct {
	bpfEnterStructuredPrograms
	bpfEnterStructuredMaps
	bpfEnterStructuredVariables
}

func (o *bpfEnterStructuredObjects) Close() error {
	return _BpfEnterStructuredClose(
		&o.bpfEnterStructuredPrograms,
		&o.bpfEnterStructuredMaps,
	)
}

// bpfEnterStructuredMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterStructuredObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterStructuredMaps struct {
	ArmForkMap         *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap    *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap     *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap          *ebpf.Map `ebpf:"config_map"`
	EnterProgs         *ebpf.Map `ebpf:"enter_progs"`
	EnterRoutes        *ebpf.Map `ebpf:"enter_routes"`
	Events             *ebpf.Map `ebpf:"events"`
	ExitProgs          *ebpf.Map `ebpf:"exit_progs"`
	ExitRoutes         *ebpf.Map `ebpf:"exit_routes"`
	FdPathScratchMap   *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap          *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap      *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs     *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap     *ebpf.Map `ebpf:"pending_exec_map"`
	PendingStackMap    *ebpf.Map `ebpf:"pending_stack_map"`
	PendingTaskStorage *ebpf.Map `ebpf:"pending_task_storage"`
	PlainEnterElideMap *ebpf.Map `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs       *ebpf.Map `ebpf:"recvmsg_progs"`
	RuntimeMetaMap     *ebpf.Map `ebpf:"runtime_meta_map"`
	StackTraces        *ebpf.Map `ebpf:"stack_traces"`
	StatsMap           *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap   *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfEnterStructuredMaps) Close() error {
	return _BpfEnterStructuredClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.EnterRoutes,
		m.Events,
		m.ExitProgs,
		m.ExitRoutes,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingStackMap,
		m.PendingTaskStorage,
		m.PlainEnterElideMap,
		m.RecvmsgProgs,
		m.RuntimeMetaMap,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfEnterStructuredVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterStructuredObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterStructuredVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterStructuredPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterStructuredObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterStructuredPrograms struct {
	EnterBpf              *ebpf.Program `ebpf:"enter_bpf"`
	EnterBpfProgLoad      *ebpf.Program `ebpf:"enter_bpf_prog_load"`
	EnterBpfProgLoadDebug *ebpf.Program `ebpf:"enter_bpf_prog_load_debug"`
	EnterBpfUprobeMulti   *ebpf.Program `ebpf:"enter_bpf_uprobe_multi"`
	EnterCachestat        *ebpf.Program `ebpf:"enter_cachestat"`
	EnterCapability       *ebpf.Program `ebpf:"enter_capability"`
	EnterClone3           *ebpf.Program `ebpf:"enter_clone3"`
	EnterFileTime         *ebpf.Program `ebpf:"enter_file_time"`
	EnterFutex            *ebpf.Program `ebpf:"enter_futex"`
	EnterItimer           *ebpf.Program `ebpf:"enter_itimer"`
	EnterMemfd            *ebpf.Program `ebpf:"enter_memfd"`
	EnterMiscStruct       *ebpf.Program `ebpf:"enter_misc_struct"`
	EnterPrctl            *ebpf.Program `ebpf:"enter_prctl"`
	EnterQuota            *ebpf.Program `ebpf:"enter_quota"`
	EnterSignal           *ebpf.Program `ebpf:"enter_signal"`
	EnterSleep            *ebpf.Program `ebpf:"enter_sleep"`
	EnterSmallStruct      *ebpf.Program `ebpf:"enter_small_struct"`
	EnterTimeStruct       *ebpf.Program `ebpf:"enter_time_struct"`
}

func (p *bpfEnterStructuredPrograms) Close() error {
	return _BpfEnterStructuredClose(
		p.EnterBpf,
		p.EnterBpfProgLoad,
		p.EnterBpfProgLoadDebug,
		p.EnterBpfUprobeMulti,
		p.EnterCachestat,
		p.EnterCapability,
		p.EnterClone3,
		p.EnterFileTime,
		p.EnterFutex,
		p.EnterItimer,
		p.EnterMemfd,
		p.EnterMiscStruct,
		p.EnterPrctl,
		p.EnterQuota,
		p.EnterSignal,
		p.EnterSleep,
		p.EnterSmallStruct,
		p.EnterTimeStruct,
	)
}

func _BpfEnterStructuredClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfenterstructured_bpfel.o
var _BpfEnterStructuredBytes []byte
