// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEnterMemoryBpfStats struct {
	_                                 structs.HostLayout
	RingbufReserveFail                uint64
	RingbufCopyFail                   uint64
	PayloadTruncatedEvents            uint64
	PendingUpdateFail                 uint64
	OrphanExit                        uint64
	PendingMismatch                   uint64
	LifecycleMapUpdateFail            uint64
	LifecycleForkSeen                 uint64
	LifecycleForkParentTracked        uint64
	LifecycleForkParentUntracked      uint64
	LifecycleForkChildFilterInstalled uint64
	LifecycleForkChildFilterFailed    uint64
	LifecycleExecSeen                 uint64
	LifecycleExecUntracked            uint64
	LifecycleExitSeen                 uint64
	LifecycleExitUntracked            uint64
}

type bpfEnterMemoryFdPathScratch struct {
	_             structs.HostLayout
	Name          [256]int8
	Components    [8]uint64
	Args          [6]uint64
	NestedFdset   [128]uint8
	NestedFd0     int32
	NestedFd1     int32
	NestedFd2     int32
	NestedFd3     int32
	NestedFdCount uint32
	_             [4]byte
}

type bpfEnterMemoryPendingTaskState struct {
	_       structs.HostLayout
	Syscall struct {
		_         structs.HostLayout
		EnterTime uint64
		Args      [6]uint64
		Pid       uint32
		SysId     uint32
		Tid       uint32
		StackId   int32
	}
	NamespaceSnapshot struct {
		_      structs.HostLayout
		Flags  uint64
		Cgroup uint32
		Ipc    uint32
		Mnt    uint32
		Net    uint32
		Pid    uint32
		Time   uint32
		Uts    uint32
		User   uint32
	}
	Aux0  uint32
	Valid uint32
}

type bpfEnterMemoryPidNamespaceConfig struct {
	_     structs.HostLayout
	Nonce uint32
	Level uint32
	Inum  uint32
	Ready uint32
}

// loadBpfEnterMemory returns the embedded CollectionSpec for bpfEnterMemory.
func loadBpfEnterMemory() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfEnterMemoryBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfEnterMemory: %w", err)
	}

	return spec, err
}

// loadBpfEnterMemoryObjects loads bpfEnterMemory and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfEnterMemoryObjects
//	*bpfEnterMemoryPrograms
//	*bpfEnterMemoryMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfEnterMemoryObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfEnterMemory()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfEnterMemorySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterMemorySpecs struct {
	bpfEnterMemoryProgramSpecs
	bpfEnterMemoryMapSpecs
	bpfEnterMemoryVariableSpecs
}

// bpfEnterMemoryProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterMemoryProgramSpecs struct {
	EnterAio         *ebpf.ProgramSpec `ebpf:"enter_aio"`
	EnterAioBuf      *ebpf.ProgramSpec `ebpf:"enter_aio_buf"`
	EnterAioIovec    *ebpf.ProgramSpec `ebpf:"enter_aio_iovec"`
	EnterIovec       *ebpf.ProgramSpec `ebpf:"enter_iovec"`
	EnterIovecBase   *ebpf.ProgramSpec `ebpf:"enter_iovec_base"`
	EnterMmsg        *ebpf.ProgramSpec `ebpf:"enter_mmsg"`
	EnterMmsgBase01  *ebpf.ProgramSpec `ebpf:"enter_mmsg_base01"`
	EnterMmsgBase2   *ebpf.ProgramSpec `ebpf:"enter_mmsg_base2"`
	EnterMmsgBase3   *ebpf.ProgramSpec `ebpf:"enter_mmsg_base3"`
	EnterMmsgBytes0  *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes0"`
	EnterMmsgBytes1  *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes1"`
	EnterMmsgBytes2  *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes2"`
	EnterMmsgBytes3  *ebpf.ProgramSpec `ebpf:"enter_mmsg_bytes3"`
	EnterMsg         *ebpf.ProgramSpec `ebpf:"enter_msg"`
	EnterSendmsgBase *ebpf.ProgramSpec `ebpf:"enter_sendmsg_base"`
}

// bpfEnterMemoryMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterMemoryMapSpecs struct {
	ArmForkMap            *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap       *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap        *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap             *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs            *ebpf.MapSpec `ebpf:"enter_progs"`
	EnterRoutes           *ebpf.MapSpec `ebpf:"enter_routes"`
	Events                *ebpf.MapSpec `ebpf:"events"`
	ExitProgs             *ebpf.MapSpec `ebpf:"exit_progs"`
	ExitRoutes            *ebpf.MapSpec `ebpf:"exit_routes"`
	FdPathScratchMap      *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap             *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap         *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs        *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap        *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingStackMap       *ebpf.MapSpec `ebpf:"pending_stack_map"`
	PendingTaskStorage    *ebpf.MapSpec `ebpf:"pending_task_storage"`
	PidNamespaceConfigMap *ebpf.MapSpec `ebpf:"pid_namespace_config_map"`
	PlainEnterElideMap    *ebpf.MapSpec `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs          *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	RuntimeMetaMap        *ebpf.MapSpec `ebpf:"runtime_meta_map"`
	StackTraces           *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap              *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap      *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfEnterMemoryVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterMemoryVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterMemoryObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterMemoryObjects struct {
	bpfEnterMemoryPrograms
	bpfEnterMemoryMaps
	bpfEnterMemoryVariables
}

func (o *bpfEnterMemoryObjects) Close() error {
	return _BpfEnterMemoryClose(
		&o.bpfEnterMemoryPrograms,
		&o.bpfEnterMemoryMaps,
	)
}

// bpfEnterMemoryMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterMemoryMaps struct {
	ArmForkMap            *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap       *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap        *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap             *ebpf.Map `ebpf:"config_map"`
	EnterProgs            *ebpf.Map `ebpf:"enter_progs"`
	EnterRoutes           *ebpf.Map `ebpf:"enter_routes"`
	Events                *ebpf.Map `ebpf:"events"`
	ExitProgs             *ebpf.Map `ebpf:"exit_progs"`
	ExitRoutes            *ebpf.Map `ebpf:"exit_routes"`
	FdPathScratchMap      *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap             *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap         *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs        *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap        *ebpf.Map `ebpf:"pending_exec_map"`
	PendingStackMap       *ebpf.Map `ebpf:"pending_stack_map"`
	PendingTaskStorage    *ebpf.Map `ebpf:"pending_task_storage"`
	PidNamespaceConfigMap *ebpf.Map `ebpf:"pid_namespace_config_map"`
	PlainEnterElideMap    *ebpf.Map `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs          *ebpf.Map `ebpf:"recvmsg_progs"`
	RuntimeMetaMap        *ebpf.Map `ebpf:"runtime_meta_map"`
	StackTraces           *ebpf.Map `ebpf:"stack_traces"`
	StatsMap              *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap      *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfEnterMemoryMaps) Close() error {
	return _BpfEnterMemoryClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.EnterRoutes,
		m.Events,
		m.ExitProgs,
		m.ExitRoutes,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingStackMap,
		m.PendingTaskStorage,
		m.PidNamespaceConfigMap,
		m.PlainEnterElideMap,
		m.RecvmsgProgs,
		m.RuntimeMetaMap,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfEnterMemoryVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterMemoryVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterMemoryPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterMemoryObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterMemoryPrograms struct {
	EnterAio         *ebpf.Program `ebpf:"enter_aio"`
	EnterAioBuf      *ebpf.Program `ebpf:"enter_aio_buf"`
	EnterAioIovec    *ebpf.Program `ebpf:"enter_aio_iovec"`
	EnterIovec       *ebpf.Program `ebpf:"enter_iovec"`
	EnterIovecBase   *ebpf.Program `ebpf:"enter_iovec_base"`
	EnterMmsg        *ebpf.Program `ebpf:"enter_mmsg"`
	EnterMmsgBase01  *ebpf.Program `ebpf:"enter_mmsg_base01"`
	EnterMmsgBase2   *ebpf.Program `ebpf:"enter_mmsg_base2"`
	EnterMmsgBase3   *ebpf.Program `ebpf:"enter_mmsg_base3"`
	EnterMmsgBytes0  *ebpf.Program `ebpf:"enter_mmsg_bytes0"`
	EnterMmsgBytes1  *ebpf.Program `ebpf:"enter_mmsg_bytes1"`
	EnterMmsgBytes2  *ebpf.Program `ebpf:"enter_mmsg_bytes2"`
	EnterMmsgBytes3  *ebpf.Program `ebpf:"enter_mmsg_bytes3"`
	EnterMsg         *ebpf.Program `ebpf:"enter_msg"`
	EnterSendmsgBase *ebpf.Program `ebpf:"enter_sendmsg_base"`
}

func (p *bpfEnterMemoryPrograms) Close() error {
	return _BpfEnterMemoryClose(
		p.EnterAio,
		p.EnterAioBuf,
		p.EnterAioIovec,
		p.EnterIovec,
		p.EnterIovecBase,
		p.EnterMmsg,
		p.EnterMmsgBase01,
		p.EnterMmsgBase2,
		p.EnterMmsgBase3,
		p.EnterMmsgBytes0,
		p.EnterMmsgBytes1,
		p.EnterMmsgBytes2,
		p.EnterMmsgBytes3,
		p.EnterMsg,
		p.EnterSendmsgBase,
	)
}

func _BpfEnterMemoryClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfentermemory_bpfel.o
var _BpfEnterMemoryBytes []byte
