// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEnterPayloadBpfStats struct {
	_                      structs.HostLayout
	RingbufReserveFail     uint64
	RingbufCopyFail        uint64
	PayloadTruncatedEvents uint64
	PendingUpdateFail      uint64
	OrphanExit             uint64
	PendingMismatch        uint64
	LifecycleMapUpdateFail uint64
}

type bpfEnterPayloadFdPathScratch struct {
	_             structs.HostLayout
	Name          [256]int8
	Components    [8]uint64
	Args          [6]uint64
	NestedFdset   [128]uint8
	NestedFd0     int32
	NestedFd1     int32
	NestedFd2     int32
	NestedFd3     int32
	NestedFdCount uint32
	_             [4]byte
}

type bpfEnterPayloadPendingSyscall struct {
	_         structs.HostLayout
	EnterTime uint64
	Args      [6]uint64
	Pid       uint32
	SysId     uint32
	Tid       uint32
	StackId   int32
	Aux0      uint32
	Aux1      uint32
}

// loadBpfEnterPayload returns the embedded CollectionSpec for bpfEnterPayload.
func loadBpfEnterPayload() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfEnterPayloadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfEnterPayload: %w", err)
	}

	return spec, err
}

// loadBpfEnterPayloadObjects loads bpfEnterPayload and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfEnterPayloadObjects
//	*bpfEnterPayloadPrograms
//	*bpfEnterPayloadMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfEnterPayloadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfEnterPayload()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfEnterPayloadSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPayloadSpecs struct {
	bpfEnterPayloadProgramSpecs
	bpfEnterPayloadMapSpecs
	bpfEnterPayloadVariableSpecs
}

// bpfEnterPayloadProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPayloadProgramSpecs struct {
	EnterExec          *ebpf.ProgramSpec `ebpf:"enter_exec"`
	EnterPayloadDirect *ebpf.ProgramSpec `ebpf:"enter_payload_direct"`
}

// bpfEnterPayloadMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPayloadMapSpecs struct {
	ArmForkMap       *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap  *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap   *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs       *ebpf.MapSpec `ebpf:"enter_progs"`
	EnterRoutes      *ebpf.MapSpec `ebpf:"enter_routes"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	ExitProgs        *ebpf.MapSpec `ebpf:"exit_progs"`
	ExitRoutes       *ebpf.MapSpec `ebpf:"exit_routes"`
	FdPathScratchMap *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap        *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap    *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs   *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap   *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.MapSpec `ebpf:"pending_syscalls"`
	PreExecMap       *ebpf.MapSpec `ebpf:"pre_exec_map"`
	RecvmsgProgs     *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	StackTraces      *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap         *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.MapSpec `ebpf:"syscall_filter_map"`
}

// bpfEnterPayloadVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfEnterPayloadVariableSpecs struct {
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterPayloadObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPayloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPayloadObjects struct {
	bpfEnterPayloadPrograms
	bpfEnterPayloadMaps
	bpfEnterPayloadVariables
}

func (o *bpfEnterPayloadObjects) Close() error {
	return _BpfEnterPayloadClose(
		&o.bpfEnterPayloadPrograms,
		&o.bpfEnterPayloadMaps,
	)
}

// bpfEnterPayloadMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPayloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPayloadMaps struct {
	ArmForkMap       *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap  *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap   *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	EnterProgs       *ebpf.Map `ebpf:"enter_progs"`
	EnterRoutes      *ebpf.Map `ebpf:"enter_routes"`
	Events           *ebpf.Map `ebpf:"events"`
	ExitProgs        *ebpf.Map `ebpf:"exit_progs"`
	ExitRoutes       *ebpf.Map `ebpf:"exit_routes"`
	FdPathScratchMap *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap        *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap    *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs   *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap   *ebpf.Map `ebpf:"pending_exec_map"`
	PendingSyscalls  *ebpf.Map `ebpf:"pending_syscalls"`
	PreExecMap       *ebpf.Map `ebpf:"pre_exec_map"`
	RecvmsgProgs     *ebpf.Map `ebpf:"recvmsg_progs"`
	StackTraces      *ebpf.Map `ebpf:"stack_traces"`
	StatsMap         *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap *ebpf.Map `ebpf:"syscall_filter_map"`
}

func (m *bpfEnterPayloadMaps) Close() error {
	return _BpfEnterPayloadClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.EnterRoutes,
		m.Events,
		m.ExitProgs,
		m.ExitRoutes,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingSyscalls,
		m.PreExecMap,
		m.RecvmsgProgs,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
	)
}

// bpfEnterPayloadVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPayloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPayloadVariables struct {
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfEnterPayloadPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfEnterPayloadObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfEnterPayloadPrograms struct {
	EnterExec          *ebpf.Program `ebpf:"enter_exec"`
	EnterPayloadDirect *ebpf.Program `ebpf:"enter_payload_direct"`
}

func (p *bpfEnterPayloadPrograms) Close() error {
	return _BpfEnterPayloadClose(
		p.EnterExec,
		p.EnterPayloadDirect,
	)
}

func _BpfEnterPayloadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfenterpayload_bpfel.o
var _BpfEnterPayloadBytes []byte
