// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfRecvmsgBpfStats struct {
	_                                 structs.HostLayout
	RingbufReserveFail                uint64
	RingbufCopyFail                   uint64
	PayloadTruncatedEvents            uint64
	PendingUpdateFail                 uint64
	OrphanExit                        uint64
	OrphanFirstPid                    uint64
	OrphanFirstTid                    uint64
	OrphanFirstSysId                  uint64
	OrphanFirstRet                    int64
	OrphanFirstReason                 uint64
	OrphanFirstTimeNs                 uint64
	OrphanLastPid                     uint64
	OrphanLastTid                     uint64
	OrphanLastSysId                   uint64
	OrphanLastRet                     int64
	OrphanLastReason                  uint64
	OrphanLastTimeNs                  uint64
	PendingMismatch                   uint64
	LifecycleMapUpdateFail            uint64
	LifecycleForkSeen                 uint64
	LifecycleForkParentTracked        uint64
	LifecycleForkParentUntracked      uint64
	LifecycleForkChildFilterInstalled uint64
	LifecycleForkChildFilterFailed    uint64
	LifecycleExecSeen                 uint64
	LifecycleExecUntracked            uint64
	LifecycleExitSeen                 uint64
	LifecycleExitUntracked            uint64
	EventSeq                          uint64
	IntegrityFirstTimeNs              uint64
}

type bpfRecvmsgEventLossState struct {
	_           structs.HostLayout
	Epoch       uint64
	FirstTimeNs uint64
}

type bpfRecvmsgFdPathScratch struct {
	_             structs.HostLayout
	Name          [256]int8
	Components    [8]uint64
	Args          [6]uint64
	NestedFdset   [128]uint8
	NestedFd0     int32
	NestedFd1     int32
	NestedFd2     int32
	NestedFd3     int32
	NestedFdCount uint32
	_             [4]byte
}

type bpfRecvmsgPendingTaskState struct {
	_       structs.HostLayout
	Syscall struct {
		_            structs.HostLayout
		EnterTime    uint64
		CpuEnterTime uint64
		Args         [6]uint64
		Pid          uint32
		SysId        uint32
		Tid          uint32
		StackId      int32
	}
	NamespaceSnapshot struct {
		_      structs.HostLayout
		Flags  uint64
		Cgroup uint32
		Ipc    uint32
		Mnt    uint32
		Net    uint32
		Pid    uint32
		Time   uint32
		Uts    uint32
		User   uint32
	}
	Aux0  uint32
	Valid uint32
}

type bpfRecvmsgPidNamespaceConfig struct {
	_     structs.HostLayout
	Nonce uint32
	Level uint32
	Inum  uint32
	Ready uint32
}

// loadBpfRecvmsg returns the embedded CollectionSpec for bpfRecvmsg.
func loadBpfRecvmsg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfRecvmsgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfRecvmsg: %w", err)
	}

	return spec, err
}

// loadBpfRecvmsgObjects loads bpfRecvmsg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfRecvmsgObjects
//	*bpfRecvmsgPrograms
//	*bpfRecvmsgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfRecvmsgObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfRecvmsg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfRecvmsgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfRecvmsgSpecs struct {
	bpfRecvmsgProgramSpecs
	bpfRecvmsgMapSpecs
	bpfRecvmsgVariableSpecs
}

// bpfRecvmsgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfRecvmsgProgramSpecs struct {
	TraceKretprobeRecvmsgControl  *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgDispatch *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_dispatch"`
	TraceKretprobeRecvmsgFinal    *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_final"`
	TraceKretprobeRecvmsgName     *ebpf.ProgramSpec `ebpf:"trace_kretprobe_recvmsg_name"`
}

// bpfRecvmsgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfRecvmsgMapSpecs struct {
	ArmForkMap            *ebpf.MapSpec `ebpf:"arm_fork_map"`
	AttachExitedMap       *ebpf.MapSpec `ebpf:"attach_exited_map"`
	AttachRootsMap        *ebpf.MapSpec `ebpf:"attach_roots_map"`
	ConfigMap             *ebpf.MapSpec `ebpf:"config_map"`
	EnterProgs            *ebpf.MapSpec `ebpf:"enter_progs"`
	EnterRoutes           *ebpf.MapSpec `ebpf:"enter_routes"`
	EventLossMap          *ebpf.MapSpec `ebpf:"event_loss_map"`
	Events                *ebpf.MapSpec `ebpf:"events"`
	ExitProgs             *ebpf.MapSpec `ebpf:"exit_progs"`
	ExitRoutes            *ebpf.MapSpec `ebpf:"exit_routes"`
	FdPathScratchMap      *ebpf.MapSpec `ebpf:"fd_path_scratch_map"`
	FilterMap             *ebpf.MapSpec `ebpf:"filter_map"`
	MainExitedMap         *ebpf.MapSpec `ebpf:"main_exited_map"`
	MmsgBytesProgs        *ebpf.MapSpec `ebpf:"mmsg_bytes_progs"`
	PendingExecMap        *ebpf.MapSpec `ebpf:"pending_exec_map"`
	PendingForkFlagsMap   *ebpf.MapSpec `ebpf:"pending_fork_flags_map"`
	PendingStackMap       *ebpf.MapSpec `ebpf:"pending_stack_map"`
	PendingTaskStorage    *ebpf.MapSpec `ebpf:"pending_task_storage"`
	PidNamespaceConfigMap *ebpf.MapSpec `ebpf:"pid_namespace_config_map"`
	PlainEnterElideMap    *ebpf.MapSpec `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs          *ebpf.MapSpec `ebpf:"recvmsg_progs"`
	RuntimeMetaMap        *ebpf.MapSpec `ebpf:"runtime_meta_map"`
	StackTraces           *ebpf.MapSpec `ebpf:"stack_traces"`
	StatsMap              *ebpf.MapSpec `ebpf:"stats_map"`
	SyscallFilterMap      *ebpf.MapSpec `ebpf:"syscall_filter_map"`
	UnknownChildrenMap    *ebpf.MapSpec `ebpf:"unknown_children_map"`
}

// bpfRecvmsgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfRecvmsgVariableSpecs struct {
	STRACE_GO_SYSCALL_ABI   *ebpf.VariableSpec `ebpf:"STRACE_GO_SYSCALL_ABI"`
	SYS_CAPGET              *ebpf.VariableSpec `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.VariableSpec `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.VariableSpec `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.VariableSpec `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.VariableSpec `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.VariableSpec `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.VariableSpec `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.VariableSpec `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.VariableSpec `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfRecvmsgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfRecvmsgObjects struct {
	bpfRecvmsgPrograms
	bpfRecvmsgMaps
	bpfRecvmsgVariables
}

func (o *bpfRecvmsgObjects) Close() error {
	return _BpfRecvmsgClose(
		&o.bpfRecvmsgPrograms,
		&o.bpfRecvmsgMaps,
	)
}

// bpfRecvmsgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfRecvmsgMaps struct {
	ArmForkMap            *ebpf.Map `ebpf:"arm_fork_map"`
	AttachExitedMap       *ebpf.Map `ebpf:"attach_exited_map"`
	AttachRootsMap        *ebpf.Map `ebpf:"attach_roots_map"`
	ConfigMap             *ebpf.Map `ebpf:"config_map"`
	EnterProgs            *ebpf.Map `ebpf:"enter_progs"`
	EnterRoutes           *ebpf.Map `ebpf:"enter_routes"`
	EventLossMap          *ebpf.Map `ebpf:"event_loss_map"`
	Events                *ebpf.Map `ebpf:"events"`
	ExitProgs             *ebpf.Map `ebpf:"exit_progs"`
	ExitRoutes            *ebpf.Map `ebpf:"exit_routes"`
	FdPathScratchMap      *ebpf.Map `ebpf:"fd_path_scratch_map"`
	FilterMap             *ebpf.Map `ebpf:"filter_map"`
	MainExitedMap         *ebpf.Map `ebpf:"main_exited_map"`
	MmsgBytesProgs        *ebpf.Map `ebpf:"mmsg_bytes_progs"`
	PendingExecMap        *ebpf.Map `ebpf:"pending_exec_map"`
	PendingForkFlagsMap   *ebpf.Map `ebpf:"pending_fork_flags_map"`
	PendingStackMap       *ebpf.Map `ebpf:"pending_stack_map"`
	PendingTaskStorage    *ebpf.Map `ebpf:"pending_task_storage"`
	PidNamespaceConfigMap *ebpf.Map `ebpf:"pid_namespace_config_map"`
	PlainEnterElideMap    *ebpf.Map `ebpf:"plain_enter_elide_map"`
	RecvmsgProgs          *ebpf.Map `ebpf:"recvmsg_progs"`
	RuntimeMetaMap        *ebpf.Map `ebpf:"runtime_meta_map"`
	StackTraces           *ebpf.Map `ebpf:"stack_traces"`
	StatsMap              *ebpf.Map `ebpf:"stats_map"`
	SyscallFilterMap      *ebpf.Map `ebpf:"syscall_filter_map"`
	UnknownChildrenMap    *ebpf.Map `ebpf:"unknown_children_map"`
}

func (m *bpfRecvmsgMaps) Close() error {
	return _BpfRecvmsgClose(
		m.ArmForkMap,
		m.AttachExitedMap,
		m.AttachRootsMap,
		m.ConfigMap,
		m.EnterProgs,
		m.EnterRoutes,
		m.EventLossMap,
		m.Events,
		m.ExitProgs,
		m.ExitRoutes,
		m.FdPathScratchMap,
		m.FilterMap,
		m.MainExitedMap,
		m.MmsgBytesProgs,
		m.PendingExecMap,
		m.PendingForkFlagsMap,
		m.PendingStackMap,
		m.PendingTaskStorage,
		m.PidNamespaceConfigMap,
		m.PlainEnterElideMap,
		m.RecvmsgProgs,
		m.RuntimeMetaMap,
		m.StackTraces,
		m.StatsMap,
		m.SyscallFilterMap,
		m.UnknownChildrenMap,
	)
}

// bpfRecvmsgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfRecvmsgVariables struct {
	STRACE_GO_SYSCALL_ABI   *ebpf.Variable `ebpf:"STRACE_GO_SYSCALL_ABI"`
	SYS_CAPGET              *ebpf.Variable `ebpf:"SYS_CAPGET"`
	SYS_CAPSET              *ebpf.Variable `ebpf:"SYS_CAPSET"`
	SYS_EXECVE              *ebpf.Variable `ebpf:"SYS_EXECVE"`
	SYS_EXECVEAT            *ebpf.Variable `ebpf:"SYS_EXECVEAT"`
	SYS_EXIT                *ebpf.Variable `ebpf:"SYS_EXIT"`
	SYS_EXIT_GROUP          *ebpf.Variable `ebpf:"SYS_EXIT_GROUP"`
	SYS_NANOSLEEP           *ebpf.Variable `ebpf:"SYS_NANOSLEEP"`
	SYS_RT_SIGRETURN        *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN"`
	SYS_RT_SIGRETURN_COMPAT *ebpf.Variable `ebpf:"SYS_RT_SIGRETURN_COMPAT"`
	SYS_RT_SIGSUSPEND       *ebpf.Variable `ebpf:"SYS_RT_SIGSUSPEND"`
}

// bpfRecvmsgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfRecvmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfRecvmsgPrograms struct {
	TraceKretprobeRecvmsgControl  *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_control"`
	TraceKretprobeRecvmsgDispatch *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_dispatch"`
	TraceKretprobeRecvmsgFinal    *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_final"`
	TraceKretprobeRecvmsgName     *ebpf.Program `ebpf:"trace_kretprobe_recvmsg_name"`
}

func (p *bpfRecvmsgPrograms) Close() error {
	return _BpfRecvmsgClose(
		p.TraceKretprobeRecvmsgControl,
		p.TraceKretprobeRecvmsgDispatch,
		p.TraceKretprobeRecvmsgFinal,
		p.TraceKretprobeRecvmsgName,
	)
}

func _BpfRecvmsgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfrecvmsg_arm64_bpfel.o
var _BpfRecvmsgBytes []byte
