// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type straceBpfEvent struct {
	_             structs.HostLayout
	Pid           uint32
	SysId         uint32
	Tid           uint32
	ProbeRetEnter int32
	ProbeRetExit  int32
	_             [4]byte
	EnterTime     uint64
	Duration      uint64
	Args          [6]uint64
	Ret           uint64
	Ptr           uint64
	DataLen       uint32
	Pad           uint32
	StrArg        [10000]uint8
}

// loadStrace returns the embedded CollectionSpec for strace.
func loadStrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load strace: %w", err)
	}

	return spec, err
}

// loadStraceObjects loads strace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*straceObjects
//	*stracePrograms
//	*straceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// straceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type straceSpecs struct {
	straceProgramSpecs
	straceMapSpecs
	straceVariableSpecs
}

// straceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type straceProgramSpecs struct {
	TraceSysEnter *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceSysExit  *ebpf.ProgramSpec `ebpf:"trace_sys_exit"`
}

// straceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type straceMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	EventsMap      *ebpf.MapSpec `ebpf:"events_map"`
	FilterMap      *ebpf.MapSpec `ebpf:"filter_map"`
	Heap           *ebpf.MapSpec `ebpf:"heap"`
	MainExitedMap  *ebpf.MapSpec `ebpf:"main_exited_map"`
	PendingExecMap *ebpf.MapSpec `ebpf:"pending_exec_map"`
}

// straceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type straceVariableSpecs struct {
}

// straceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type straceObjects struct {
	stracePrograms
	straceMaps
	straceVariables
}

func (o *straceObjects) Close() error {
	return _StraceClose(
		&o.stracePrograms,
		&o.straceMaps,
	)
}

// straceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type straceMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	EventsMap      *ebpf.Map `ebpf:"events_map"`
	FilterMap      *ebpf.Map `ebpf:"filter_map"`
	Heap           *ebpf.Map `ebpf:"heap"`
	MainExitedMap  *ebpf.Map `ebpf:"main_exited_map"`
	PendingExecMap *ebpf.Map `ebpf:"pending_exec_map"`
}

func (m *straceMaps) Close() error {
	return _StraceClose(
		m.Events,
		m.EventsMap,
		m.FilterMap,
		m.Heap,
		m.MainExitedMap,
		m.PendingExecMap,
	)
}

// straceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type straceVariables struct {
}

// stracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type stracePrograms struct {
	TraceSysEnter *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit  *ebpf.Program `ebpf:"trace_sys_exit"`
}

func (p *stracePrograms) Close() error {
	return _StraceClose(
		p.TraceSysEnter,
		p.TraceSysExit,
	)
}

func _StraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed strace_bpfel.o
var _StraceBytes []byte
