/* Generated by generate-syscalls. DO NOT EDIT. */
#ifndef __SYSCALL_CAPTURE_H__
#define __SYSCALL_CAPTURE_H__

#define CAPTURE_ARGS_ENTER(sys_id, e) \
	switch (sys_id) { \
	}
#define CAPTURE_ARGS_EXIT(sys_id, e) \
	switch (sys_id) { \
	}
#endif
