#ifndef STRACE_GO_SYSCALL_MOUNT_QUERY_DIRECT_EVENT_V2_H
#define STRACE_GO_SYSCALL_MOUNT_QUERY_DIRECT_EVENT_V2_H

#define MNT_ID_REQ_SIZE_FIELD_SIZE 4
#define MNT_ID_REQ_SIZE_VER0 24
#define MNT_ID_REQ_SIZE_VER1 32
#define MNT_ID_REQ_EXTENSION_MAX 256
#define STATMOUNT_FIXED_SIZE 512
#define STATMOUNT_STRING_MAX 4096
#define LISTMOUNT_ID_MAX 32
#define LISTMOUNT_ID_SIZE 8

#define MOUNT_QUERY_ENTER_PAYLOAD_CAPACITY \
    (3 * PAYLOAD_TLV_HEADER_SIZE + MNT_ID_REQ_SIZE_FIELD_SIZE + \
     MNT_ID_REQ_SIZE_VER1 + MNT_ID_REQ_EXTENSION_MAX)
#define STATMOUNT_EXIT_PAYLOAD_CAPACITY \
    (3 * PAYLOAD_TLV_HEADER_SIZE + MNT_ID_REQ_SIZE_FIELD_SIZE + \
     STATMOUNT_FIXED_SIZE + STATMOUNT_STRING_MAX)
#define LISTMOUNT_EXIT_PAYLOAD_CAPACITY \
    (PAYLOAD_TLV_HEADER_SIZE + LISTMOUNT_ID_MAX * LISTMOUNT_ID_SIZE)

static __always_inline int is_mount_query_direct_syscall(u32 sys_id)
{
    return sys_id == SYS_STATMOUNT || sys_id == SYS_LISTMOUNT;
}

#include "syscall_mount_query_capture_direct_event_v2.h"
#include "syscall_mount_query_emit_direct_event_v2.h"

#endif
