#ifndef STRACE_GO_SYSCALL_MMSG_CAPTURE_DIRECT_EVENT_V2_H
#define STRACE_GO_SYSCALL_MMSG_CAPTURE_DIRECT_EVENT_V2_H

#include "syscall_mmsg_struct_capture_direct_event_v2.h"
#include "syscall_mmsg_bytes_capture_direct_event_v2.h"

#endif
