#ifndef STRACE_GO_SYSCALL_NETWORK_DIRECT_EXIT_EVENT_V2_H
#define STRACE_GO_SYSCALL_NETWORK_DIRECT_EXIT_EVENT_V2_H

#include "syscall_network_exit_capture_direct_event_v2.h"
#include "syscall_network_exit_emit_direct_event_v2.h"

#endif
