/* Generated by generate-syscalls. DO NOT EDIT. */
#if defined(__TARGET_ARCH_x86)
#include "syscall_numbers_amd64_generated.h"
#elif defined(__TARGET_ARCH_arm64)
#include "syscall_numbers_arm64_generated.h"
#else
#error "unsupported BPF architecture: use generate-bpf for amd64 or arm64"
#endif
