package main

type protocolConstant struct {
	cName  string
	goName string
	cValue string
	goType string
}

// protocolConstants is the wire contract shared by the BPF producer and Go decoder.
var protocolConstants = []protocolConstant{
	{cName: "EVENT_VERSION", goName: "traceEventV2Version", cValue: "2"},
	{cName: "EVENT_TYPE_ENTER", goName: "bpfEventTypeEnter", cValue: "1", goType: "uint16"},
	{cName: "EVENT_TYPE_EXIT", goName: "bpfEventTypeExit", cValue: "2", goType: "uint16"},
	{cName: "EVENT_TYPE_LIFECYCLE", goName: "bpfEventTypeLifecycle", cValue: "3", goType: "uint16"},
	{cName: "EVENT_TYPE_SIGNAL", goName: "bpfEventTypeSignal", cValue: "4", goType: "uint16"},
	{cName: "EVENT_FLAG_GENERIC_ENTER", goName: "bpfEventFlagGenericEnter", cValue: "1", goType: "uint32"},
	{cName: "EVENT_FLAG_PAYLOAD_TLV", goName: "bpfEventFlagPayloadTLV", cValue: "2", goType: "uint32"},
	{cName: "EVENT_FLAG_TRUNCATED", goName: "bpfEventFlagTruncated", cValue: "4", goType: "uint32"},
	{cName: "EVENT_FLAG_EXIT_FRAGMENT", goName: "bpfEventFlagExitFragment", cValue: "8", goType: "uint32"},
	{cName: "EVENT_FLAG_COMPACT_ENTER", goName: "bpfEventFlagCompactEnter", cValue: "16", goType: "uint32"},
	{cName: "EVENT_FLAG_ENTER_FRAGMENT", goName: "bpfEventFlagEnterFragment", cValue: "32", goType: "uint32"},
	{cName: "LIFECYCLE_FORK", goName: "lifecycleFork", cValue: "1", goType: "uint32"},
	{cName: "LIFECYCLE_EXEC", goName: "lifecycleExec", cValue: "2", goType: "uint32"},
	{cName: "LIFECYCLE_EXIT", goName: "lifecycleExit", cValue: "3", goType: "uint32"},
	{cName: "LIFECYCLE_FREE", goName: "lifecycleFree", cValue: "4", goType: "uint32"},
	{cName: "CONFIG_CAPTURE_STACK", goName: "bpfConfigCaptureStack", cValue: "1"},
	{cName: "CONFIG_FOLLOW_FORKS", goName: "bpfConfigFollowForks", cValue: "2"},
	{cName: "CONFIG_EMIT_ENTER", goName: "bpfConfigEmitEnter", cValue: "4"},
	{cName: "CONFIG_SYSCALL_FILTER", goName: "bpfConfigSyscallFilter", cValue: "8"},
	{cName: "CONFIG_SYSCALL_FILTER_NEGATED", goName: "bpfConfigSyscallFilterNegated", cValue: "16"},
	{cName: "CONFIG_EMIT_LIFECYCLE", goName: "bpfConfigEmitLifecycle", cValue: "32"},
	{cName: "CONFIG_FD_STATE", goName: "bpfConfigFdState", cValue: "64"},
	{cName: "CONFIG_ELIDE_PLAIN_ENTER", goName: "bpfConfigElidePlainEnter", cValue: "128"},
	{cName: "CONFIG_EMIT_SIGNAL", goName: "bpfConfigEmitSignal", cValue: "256"},
	{cName: "CONFIG_DECODE_PID_COMM", goName: "bpfConfigDecodePIDComm", cValue: "512"},
	{cName: "FILTER_TASK_TRACKED", goName: "bpfFilterTaskTracked", cValue: "1", goType: "uint32"},
	{cName: "FILTER_TASK_PRE_EXEC", goName: "bpfFilterTaskPreExec", cValue: "2", goType: "uint32"},
	{cName: "EVENT_V2_HEADER_LEN", goName: "traceEventV2HeaderLen", cValue: "56"},
	{cName: "EVENT_V2_COMM_SIZE", goName: "traceEventV2CommSize", cValue: "16"},
	{cName: "EVENT_V2_ENTER_BODY_LEN", goName: "traceEventV2EnterBodyLen", cValue: "72"},
	{cName: "EVENT_V2_COMPACT_ENTER_BODY_LEN", goName: "traceEventV2CompactEnterBodyLen", cValue: "48"},
	{cName: "EVENT_V2_EXIT_BODY_LEN", goName: "traceEventV2ExitBodyLen", cValue: "80"},
	{cName: "EVENT_V2_LIFECYCLE_BODY_LEN", goName: "traceEventV2LifecycleBodyLen", cValue: "56"},
	{cName: "EVENT_V2_SIGNAL_BODY_LEN", goName: "traceEventV2SignalBodyLen", cValue: "24"},
	{cName: "EVENT_V2_U16_SIZE", goName: "traceEventV2U16Size", cValue: "2"},
	{cName: "EVENT_V2_U32_SIZE", goName: "traceEventV2U32Size", cValue: "4"},
	{cName: "EVENT_V2_U64_SIZE", goName: "traceEventV2U64Size", cValue: "8"},
	{cName: "EVENT_V2_ARGS_SIZE", goName: "traceEventV2ArgsSize", cValue: "48"},
	{cName: "EVENT_V2_HEADER_VERSION_OFFSET", goName: "traceEventV2HeaderVersionOffset", cValue: "0"},
	{cName: "EVENT_V2_HEADER_EVENT_TYPE_OFFSET", goName: "traceEventV2HeaderEventTypeOffset", cValue: "2"},
	{cName: "EVENT_V2_HEADER_FLAGS_OFFSET", goName: "traceEventV2HeaderFlagsOffset", cValue: "4"},
	{cName: "EVENT_V2_HEADER_LEN_OFFSET", goName: "traceEventV2HeaderLenOffset", cValue: "6"},
	{cName: "EVENT_V2_HEADER_SIZE_OFFSET", goName: "traceEventV2HeaderSizeOffset", cValue: "8"},
	{cName: "EVENT_V2_HEADER_PID_OFFSET", goName: "traceEventV2HeaderPIDOffset", cValue: "12"},
	{cName: "EVENT_V2_HEADER_TID_OFFSET", goName: "traceEventV2HeaderTIDOffset", cValue: "16"},
	{cName: "EVENT_V2_HEADER_SYS_ID_OFFSET", goName: "traceEventV2HeaderSysIDOffset", cValue: "20"},
	{cName: "EVENT_V2_HEADER_SEQ_OFFSET", goName: "traceEventV2HeaderSeqOffset", cValue: "24"},
	{cName: "EVENT_V2_HEADER_TS_NS_OFFSET", goName: "traceEventV2HeaderTSNSOffset", cValue: "32"},
	{cName: "EVENT_V2_HEADER_COMM_OFFSET", goName: "traceEventV2HeaderCommOffset", cValue: "40"},
	{cName: "EVENT_V2_ENTER_RET_OFFSET", goName: "traceEventV2EnterRetOffset", cValue: "0"},
	{cName: "EVENT_V2_ENTER_PROBE_RET_ENTER_OFFSET", goName: "traceEventV2EnterProbeRetEnterOffset", cValue: "8"},
	{cName: "EVENT_V2_ENTER_PROBE_RET_EXIT_OFFSET", goName: "traceEventV2EnterProbeRetExitOffset", cValue: "12"},
	{cName: "EVENT_V2_ENTER_ARGS_OFFSET", goName: "traceEventV2EnterArgsOffset", cValue: "16"},
	{cName: "EVENT_V2_ENTER_CAPTURE_LEN_OFFSET", goName: "traceEventV2EnterCaptureLenOffset", cValue: "64"},
	{cName: "EVENT_V2_ENTER_CAPTURE_FLAGS_OFFSET", goName: "traceEventV2EnterCaptureFlagsOffset", cValue: "68"},
	{cName: "EVENT_V2_COMPACT_ENTER_ARGS_OFFSET", goName: "traceEventV2CompactEnterArgsOffset", cValue: "0"},
	{cName: "EVENT_V2_EXIT_RET_OFFSET", goName: "traceEventV2ExitRetOffset", cValue: "0"},
	{cName: "EVENT_V2_EXIT_DURATION_OFFSET", goName: "traceEventV2ExitDurationOffset", cValue: "8"},
	{cName: "EVENT_V2_EXIT_ARGS_OFFSET", goName: "traceEventV2ExitArgsOffset", cValue: "16"},
	{cName: "EVENT_V2_EXIT_CAPTURE_LEN_OFFSET", goName: "traceEventV2ExitCaptureLenOffset", cValue: "64"},
	{cName: "EVENT_V2_EXIT_CAPTURE_FLAGS_OFFSET", goName: "traceEventV2ExitCaptureFlagsOffset", cValue: "68"},
	{cName: "EVENT_V2_EXIT_STACK_ID_OFFSET", goName: "traceEventV2ExitStackIDOffset", cValue: "72"},
	{cName: "EVENT_V2_EXIT_RESERVED_OFFSET", goName: "traceEventV2ExitReservedOffset", cValue: "76"},
	{cName: "EVENT_V2_LIFECYCLE_ACTION_OFFSET", goName: "traceEventV2LifecycleActionOffset", cValue: "0"},
	{cName: "EVENT_V2_LIFECYCLE_SNAPSHOT_LEN_OFFSET", goName: "traceEventV2LifecycleSnapshotLenOffset", cValue: "4"},
	{cName: "EVENT_V2_LIFECYCLE_ARGS_OFFSET", goName: "traceEventV2LifecycleArgsOffset", cValue: "8"},
	{cName: "EVENT_V2_SIGNAL_NUMBER_OFFSET", goName: "traceEventV2SignalNumberOffset", cValue: "0"},
	{cName: "EVENT_V2_SIGNAL_ERRNO_OFFSET", goName: "traceEventV2SignalErrnoOffset", cValue: "4"},
	{cName: "EVENT_V2_SIGNAL_CODE_OFFSET", goName: "traceEventV2SignalCodeOffset", cValue: "8"},
	{cName: "EVENT_V2_SIGNAL_SENDER_PID_OFFSET", goName: "traceEventV2SignalSenderPIDOffset", cValue: "12"},
	{cName: "EVENT_V2_SIGNAL_SENDER_UID_OFFSET", goName: "traceEventV2SignalSenderUIDOffset", cValue: "16"},
	{cName: "EVENT_V2_SIGNAL_RESERVED_OFFSET", goName: "traceEventV2SignalReservedOffset", cValue: "20"},
	{cName: "PAYLOAD_TLV_HEADER_SIZE", goName: "payloadTLVHeaderSize", cValue: "32"},
	{cName: "PAYLOAD_TLV_OPENAT_MAX", cValue: "512"},
	{cName: "PAYLOAD_TLV_READ_MAX", cValue: "512"},
	{cName: "PAYLOAD_TLV_WRITE_MAX", cValue: "512"},
	{cName: "PAYLOAD_TLV_DATA_BUCKET_64", cValue: "64"},
	{cName: "PAYLOAD_TLV_DATA_BUCKET_128", cValue: "128"},
	{cName: "PAYLOAD_TLV_DATA_BUCKET_256", cValue: "256"},
	{cName: "PAYLOAD_TLV_DATA_BUCKET_512", cValue: "512"},
	{cName: "PAYLOAD_TLV_KIND_STRING", goName: "payloadTLVKindString", cValue: "1"},
	{cName: "PAYLOAD_TLV_KIND_BYTES", goName: "payloadTLVKindBytes", cValue: "2"},
	{cName: "PAYLOAD_TLV_KIND_STRUCT", goName: "payloadTLVKindStruct", cValue: "3"},
	{cName: "PAYLOAD_TLV_KIND_IOVEC", goName: "payloadTLVKindIovec", cValue: "4"},
	{cName: "PAYLOAD_TLV_KIND_SOCKADDR", goName: "payloadTLVKindSockaddr", cValue: "5"},
	{cName: "PAYLOAD_TLV_KIND_EXEC_ARGS", goName: "payloadTLVKindExecArgs", cValue: "6"},
	{cName: "PAYLOAD_TLV_KIND_CMSG", goName: "payloadTLVKindCmsg", cValue: "7"},
	{cName: "PAYLOAD_TLV_KIND_FD_STATE", goName: "payloadTLVKindFDState", cValue: "8"},
	{cName: "PAYLOAD_TLV_KIND_FD_PATH", goName: "payloadTLVKindFDPath", cValue: "9"},
	{cName: "PAYLOAD_TLV_KIND_EVENTFD_STATE", goName: "payloadTLVKindEventFDState", cValue: "10"},
	{cName: "PAYLOAD_TLV_FD_STATE_ARG_INDEX", goName: "payloadTLVFDStateArgIndex", cValue: "0xffff"},
	{cName: "PAYLOAD_TLV_FD_PATH_CWD_ARG_INDEX", goName: "payloadTLVFDPathCwdArgIndex", cValue: "0xfffe"},
	{cName: "PAYLOAD_TLV_FD_PATH_NESTED_ARG_INDEX", goName: "payloadTLVFDPathNestedArgIndex", cValue: "0xfffd"},
	{cName: "PAYLOAD_TLV_EVENTFD_STATE_ARG_INDEX", goName: "payloadTLVEventFDStateArgIndex", cValue: "0xfffc"},
	{cName: "PAYLOAD_TLV_FLAG_DIRECTION_OUT", goName: "payloadTLVFlagDirectionOut", cValue: "1"},
	{cName: "FD_STATE_SNAPSHOT_SIZE", cValue: "48"},
	{cName: "FD_STATE_FLAG_IDENTITY", cValue: "1"},
	{cName: "FD_STATE_FLAG_OFFSET", cValue: "2"},
	{cName: "EVENTFD_STATE_SNAPSHOT_SIZE", cValue: "16"},
}
