package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

func validateProtocolConstants(constants []protocolConstant) error {
	seenC := make(map[string]struct{}, len(constants))
	seenGo := make(map[string]struct{}, len(constants))
	for _, constant := range constants {
		if constant.cName == "" || constant.cValue == "" {
			return fmt.Errorf("protocol constant has empty name or value")
		}
		if _, exists := seenC[constant.cName]; exists {
			return fmt.Errorf("duplicate C protocol constant %s", constant.cName)
		}
		seenC[constant.cName] = struct{}{}
		if constant.goName == "" {
			continue
		}
		if _, exists := seenGo[constant.goName]; exists {
			return fmt.Errorf("duplicate Go protocol constant %s", constant.goName)
		}
		seenGo[constant.goName] = struct{}{}
	}
	return nil
}

func writeProtocolHeader(path string) error {
	data, err := renderProtocolHeader()
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(data), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func renderProtocolHeader() (string, error) {
	if err := validateProtocolConstants(protocolConstants); err != nil {
		return "", err
	}
	var out strings.Builder
	fmt.Fprintln(&out, "#ifndef STRACE_GO_EVENT_ABI_GENERATED_H")
	fmt.Fprintln(&out, "#define STRACE_GO_EVENT_ABI_GENERATED_H")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-event-abi. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	for _, constant := range protocolConstants {
		fmt.Fprintf(&out, "#define %s %s\n", constant.cName, constant.cValue)
	}
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#endif")
	return out.String(), nil
}

func writeProtocolGo(path string) error {
	data, err := renderProtocolGo()
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(data), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func renderProtocolGo() (string, error) {
	if err := validateProtocolConstants(protocolConstants); err != nil {
		return "", err
	}
	var out strings.Builder
	fmt.Fprintln(&out, "package main")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-event-abi. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	for _, constant := range protocolConstants {
		if constant.goName == "" {
			continue
		}
		fmt.Fprintf(&out, "\t%s", constant.goName)
		if constant.goType != "" {
			fmt.Fprintf(&out, " %s", constant.goType)
		}
		fmt.Fprintf(&out, " = %s\n", constant.cValue)
	}
	fmt.Fprintln(&out, ")")
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", fmt.Errorf("format generated Go protocol constants: %w", err)
	}
	return string(formatted), nil
}
