package main

// Generated input for capture orchestration. Keep all stable slot/program facts here.

func captureProgramSpecs() []captureProgramSpec {
	return []captureProgramSpec{
		{array: captureProgramArrayEnter, slot: 1, goName: "enterProgTerminating", cName: "ENTER_PROG_TERMINATING", programName: "enter_terminating", familyGoName: "bpfHandlerEnterGenericFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 2, goName: "enterProgExec", cName: "ENTER_PROG_EXEC", programName: "enter_exec", familyGoName: "bpfHandlerEnterPayloadFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 3, goName: "enterProgPathStat", cName: "ENTER_PROG_PATH_STAT", programName: "enter_path_stat", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 4, goName: "enterProgPathOnly", cName: "ENTER_PROG_PATH_ONLY", programName: "enter_path_only", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 5, goName: "enterProgDualPath", cName: "ENTER_PROG_DUAL_PATH", programName: "enter_dual_path", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 6, goName: "enterProgOpenat2", cName: "ENTER_PROG_OPENAT2", programName: "enter_openat2", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 7, goName: "enterProgReadlink", cName: "ENTER_PROG_READLINK", programName: "enter_readlink", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 8, goName: "enterProgMiscStruct", cName: "ENTER_PROG_MISC_STRUCT", programName: "enter_misc_struct", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 9, goName: "enterProgSmallStruct", cName: "ENTER_PROG_SMALL_STRUCT", programName: "enter_small_struct", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 10, goName: "enterProgItimer", cName: "ENTER_PROG_ITIMER", programName: "enter_itimer", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 11, goName: "enterProgTimeStruct", cName: "ENTER_PROG_TIME_STRUCT", programName: "enter_time_struct", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 12, goName: "enterProgSignal", cName: "ENTER_PROG_SIGNAL", programName: "enter_signal", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 13, goName: "enterProgFileTime", cName: "ENTER_PROG_FILE_TIME", programName: "enter_file_time", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 14, goName: "enterProgSleep", cName: "ENTER_PROG_SLEEP", programName: "enter_sleep", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 15, goName: "enterProgFutex", cName: "ENTER_PROG_FUTEX", programName: "enter_futex", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 16, goName: "enterProgCachestat", cName: "ENTER_PROG_CACHESTAT", programName: "enter_cachestat", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 17, goName: "enterProgCapability", cName: "ENTER_PROG_CAPABILITY", programName: "enter_capability", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 18, goName: "enterProgMemfd", cName: "ENTER_PROG_MEMFD", programName: "enter_memfd", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 19, goName: "enterProgPrctl", cName: "ENTER_PROG_PRCTL", programName: "enter_prctl", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 20, goName: "enterProgClone3", cName: "ENTER_PROG_CLONE3", programName: "enter_clone3", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 21, goName: "enterProgBpf", cName: "ENTER_PROG_BPF", programName: "enter_bpf", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_bpf_uprobe_multi"}, {array: captureProgramArrayEnter, program: "enter_bpf_prog_load"}, {array: captureProgramArrayEnter, program: "enter_bpf_prog_load_debug"}}},
		{array: captureProgramArrayEnter, slot: 51, goName: "enterProgBpfUprobeMulti", cName: "ENTER_PROG_BPF_UPROBE_MULTI", programName: "enter_bpf_uprobe_multi", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 52, goName: "enterProgBpfProgLoad", cName: "ENTER_PROG_BPF_PROG_LOAD", programName: "enter_bpf_prog_load", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 53, goName: "enterProgBpfProgLoadDebug", cName: "ENTER_PROG_BPF_PROG_LOAD_DEBUG", programName: "enter_bpf_prog_load_debug", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 22, goName: "enterProgIovec", cName: "ENTER_PROG_IOVEC", programName: "enter_iovec", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_iovec_base"}}},
		{array: captureProgramArrayEnter, slot: 23, goName: "enterProgMsg", cName: "ENTER_PROG_MSG", programName: "enter_msg", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_sendmsg_base"}}},
		{array: captureProgramArrayEnter, slot: 24, goName: "enterProgMmsg", cName: "ENTER_PROG_MMSG", programName: "enter_mmsg", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_mmsg_base01"}, {array: captureProgramArrayEnter, program: "enter_mmsg_base2"}, {array: captureProgramArrayEnter, program: "enter_mmsg_base3"}}},
		{array: captureProgramArrayEnter, slot: 25, goName: "enterProgFcntl", cName: "ENTER_PROG_FCNTL", programName: "enter_fcntl", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 26, goName: "enterProgIoctl", cName: "ENTER_PROG_IOCTL", programName: "enter_ioctl", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 27, goName: "enterProgNetwork", cName: "ENTER_PROG_NETWORK", programName: "enter_network", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 28, goName: "enterProgKey", cName: "ENTER_PROG_KEY", programName: "enter_key", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 29, goName: "enterProgXattr", cName: "ENTER_PROG_XATTR", programName: "enter_xattr", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 30, goName: "enterProgFs", cName: "ENTER_PROG_FS", programName: "enter_fs", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 31, goName: "enterProgAio", cName: "ENTER_PROG_AIO", programName: "enter_aio", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_aio_iovec"}}},
		{array: captureProgramArrayEnter, slot: 32, goName: "enterProgPoll", cName: "ENTER_PROG_POLL", programName: "enter_poll", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 33, goName: "enterProgSelect", cName: "ENTER_PROG_SELECT", programName: "enter_select", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 34, goName: "enterProgEpoll", cName: "ENTER_PROG_EPOLL", programName: "enter_epoll", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 35, goName: "enterProgNoPayload", cName: "ENTER_PROG_NO_PAYLOAD_DIRECT", programName: "enter_no_payload_direct", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 36, goName: "enterProgPayload", cName: "ENTER_PROG_PAYLOAD_DIRECT", programName: "enter_payload_direct", familyGoName: "bpfHandlerEnterPayloadFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 46, goName: "enterProgNoPayloadGeneric", cName: "ENTER_PROG_NO_PAYLOAD_GENERIC", programName: "enter_no_payload_generic", familyGoName: "bpfHandlerEnterGenericFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 37, goName: "enterProgIovecBase", cName: "ENTER_PROG_IOVEC_BASE", programName: "enter_iovec_base", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 38, goName: "enterProgSendmsgBase", cName: "ENTER_PROG_SENDMSG_BASE", programName: "enter_sendmsg_base", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 39, goName: "enterProgMmsgB01", cName: "ENTER_PROG_MMSG_BASE01", programName: "enter_mmsg_base01", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_mmsg_base2"}}},
		{array: captureProgramArrayEnter, slot: 40, goName: "enterProgMmsgB2", cName: "ENTER_PROG_MMSG_BASE2", programName: "enter_mmsg_base2", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_mmsg_base3"}}},
		{array: captureProgramArrayEnter, slot: 41, goName: "enterProgMmsgB3", cName: "ENTER_PROG_MMSG_BASE3", programName: "enter_mmsg_base3", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 42, goName: "enterProgAioIovec", cName: "ENTER_PROG_AIO_IOVEC", programName: "enter_aio_iovec", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false,
			dependencies: []captureProgramRef{{array: captureProgramArrayEnter, program: "enter_aio_buf"}}},
		{array: captureProgramArrayEnter, slot: 43, goName: "enterProgAioBuf", cName: "ENTER_PROG_AIO_BUF", programName: "enter_aio_buf", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 44, goName: "enterProgQuota", cName: "ENTER_PROG_QUOTA", programName: "enter_quota", familyGoName: "bpfHandlerEnterStructuredFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 45, goName: "enterProgMountPath", cName: "ENTER_PROG_MOUNT_PATH", programName: "enter_mount_path", familyGoName: "bpfHandlerEnterPathFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayEnter, slot: 47, goName: "enterProgNestedFDPath0", cName: "ENTER_PROG_NESTED_FD_PATH0", programName: "enter_nested_fd_path0", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 48, goName: "enterProgNestedFDPath1", cName: "ENTER_PROG_NESTED_FD_PATH1", programName: "enter_nested_fd_path1", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 49, goName: "enterProgNestedFDPath2", cName: "ENTER_PROG_NESTED_FD_PATH2", programName: "enter_nested_fd_path2", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayEnter, slot: 50, goName: "enterProgNestedFDPath3", cName: "ENTER_PROG_NESTED_FD_PATH3", programName: "enter_nested_fd_path3", familyGoName: "bpfHandlerEnterControlFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayExit, slot: 0, goName: "exitProgGeneric", cName: "EXIT_PROG_GENERIC", programName: "exit_generic", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 1, goName: "exitProgIovecBase", cName: "EXIT_PROG_IOVEC_BASE", programName: "exit_iovec_base", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 2, goName: "exitProgMsg", cName: "EXIT_PROG_MSG", programName: "exit_msg", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 3, goName: "exitProgMmsgFinal", cName: "EXIT_PROG_MMSG_FINAL", programName: "exit_mmsg_final", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 4, goName: "exitProgRecvmmsgBase01", cName: "EXIT_PROG_RECVMMSG_BASE01", programName: "exit_recvmmsg_base01", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true,
			dependencies: []captureProgramRef{{array: captureProgramArrayExit, program: "exit_recvmmsg_base23"}}},
		{array: captureProgramArrayExit, slot: 5, goName: "exitProgRecvmmsgBase23", cName: "EXIT_PROG_RECVMMSG_BASE23", programName: "exit_recvmmsg_base23", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: false,
			dependencies: []captureProgramRef{{array: captureProgramArrayExit, program: "exit_mmsg_final"}}},
		{array: captureProgramArrayExit, slot: 6, goName: "exitProgQuota", cName: "EXIT_PROG_QUOTA", programName: "exit_quota", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 7, goName: "exitProgMountQuery", cName: "EXIT_PROG_MOUNT_QUERY", programName: "exit_mount_query", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 8, goName: "exitProgPath", cName: "EXIT_PROG_PATH", programName: "exit_path", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 9, goName: "exitProgFDTime", cName: "EXIT_PROG_FD_TIME", programName: "exit_fd_time", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 10, goName: "exitProgStruct", cName: "EXIT_PROG_STRUCT", programName: "exit_struct", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 11, goName: "exitProgAsync", cName: "EXIT_PROG_ASYNC", programName: "exit_async", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 12, goName: "exitProgIO", cName: "EXIT_PROG_IO", programName: "exit_io", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 13, goName: "exitProgControl", cName: "EXIT_PROG_CONTROL", programName: "exit_control", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayExit, slot: 14, goName: "exitProgNestedFDPath0", cName: "EXIT_PROG_NESTED_FD_PATH0", programName: "exit_nested_fd_path0", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayExit, slot: 15, goName: "exitProgNestedFDPath1", cName: "EXIT_PROG_NESTED_FD_PATH1", programName: "exit_nested_fd_path1", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayExit, slot: 16, goName: "exitProgNestedFDPath2", cName: "EXIT_PROG_NESTED_FD_PATH2", programName: "exit_nested_fd_path2", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayExit, slot: 17, goName: "exitProgNestedFDPath3", cName: "EXIT_PROG_NESTED_FD_PATH3", programName: "exit_nested_fd_path3", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayExit, slot: 18, goName: "exitProgNamespace", cName: "EXIT_PROG_NAMESPACE", programName: "exit_namespace", familyGoName: "bpfHandlerExitFamily", kind: captureProgramTailCall, direct: true},
		{array: captureProgramArrayRecvmsg, slot: 0, goName: "recvmsgProgName", cName: "RECVMSG_PROG_NAME", programName: "trace_kretprobe_recvmsg_name", familyGoName: "bpfHandlerRecvmsgFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayRecvmsg, slot: 1, goName: "recvmsgProgControl", cName: "RECVMSG_PROG_CONTROL", programName: "trace_kretprobe_recvmsg_control", familyGoName: "bpfHandlerRecvmsgFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayRecvmsg, slot: 2, goName: "recvmsgProgFinal", cName: "RECVMSG_PROG_FINAL", programName: "trace_kretprobe_recvmsg_final", familyGoName: "bpfHandlerRecvmsgFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayMmsg, slot: 0, goName: "mmsgBytesProgBase0", cName: "MMSG_BYTES_PROG_BASE0", programName: "enter_mmsg_bytes0", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayMmsg, slot: 1, goName: "mmsgBytesProgBase1", cName: "MMSG_BYTES_PROG_BASE1", programName: "enter_mmsg_bytes1", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayMmsg, slot: 2, goName: "mmsgBytesProgBase2", cName: "MMSG_BYTES_PROG_BASE2", programName: "enter_mmsg_bytes2", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{array: captureProgramArrayMmsg, slot: 3, goName: "mmsgBytesProgBase3", cName: "MMSG_BYTES_PROG_BASE3", programName: "enter_mmsg_bytes3", familyGoName: "bpfHandlerEnterMemoryFamily", kind: captureProgramTailCall, direct: false},
		{programName: "trace_kretprobe_recvmsg_dispatch", familyGoName: "bpfHandlerRecvmsgFamily", kind: captureProgramStandalone, direct: true},
	}
}
