package main

import (
	"fmt"
	"go/format"
	"strings"
)

func renderCaptureGo(manifest captureManifest) (string, error) {
	if err := validateCaptureManifest(manifest); err != nil {
		return "", err
	}
	programs := sortedProgramSpecs(manifest.programs)
	byName := make(map[string]captureProgramSpec, len(programs))
	for _, program := range programs {
		byName[program.programName] = program
	}

	var out strings.Builder
	fmt.Fprintln(&out, "package main")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "// Generated by generate-capture-manifest. DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	fmt.Fprintf(&out, "\tbpfRouteMapMaxEntries = %d\n", manifest.routeMapMaxEntries)
	for _, array := range captureProgramArrays() {
		fmt.Fprintf(&out, "\tbpf%sProgArrayMaxEntries = %d\n", array.goName, programArrayCapacity(programs, array.kind))
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)

	for _, array := range captureProgramArrays() {
		fmt.Fprintln(&out, "const (")
		for _, program := range programs {
			if program.array != array.kind {
				continue
			}
			fmt.Fprintf(&out, "\t%s = %d\n", program.goName, program.slot)
		}
		fmt.Fprintln(&out, ")")
		fmt.Fprintln(&out)
	}

	for _, array := range captureProgramArrays() {
		fmt.Fprintf(&out, "var bpf%sProgramCatalog = []bpfTailCallProgramSpec{\n", array.catalogName)
		for _, program := range programs {
			if program.array != array.kind {
				continue
			}
			fmt.Fprintf(&out, "\t{slot: %s, name: %q, family: %s", program.goName, program.programName, program.familyGoName)
			if len(program.dependencies) > 0 {
				fmt.Fprint(&out, ", dependencies: []bpfProgramRef{")
				for _, dependency := range program.dependencies {
					dependencySpec := byName[dependency.program]
					fmt.Fprintf(&out, "{array: %s, slot: %s},", goProgramArray(dependency.array), dependencySpec.goName)
				}
				fmt.Fprint(&out, "}")
			}
			fmt.Fprintln(&out, "},")
		}
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}

	for _, program := range programs {
		if program.kind == captureProgramStandalone {
			fmt.Fprintf(&out, "const bpfRecvmsgDispatchProgramName = %q\n", program.programName)
			fmt.Fprintln(&out, "var bpfStandaloneProgramCatalog = []bpfStandaloneProgramSpec{")
			fmt.Fprintf(&out, "\t{name: bpfRecvmsgDispatchProgramName, family: %s},\n", program.familyGoName)
			fmt.Fprintln(&out, "}")
			fmt.Fprintln(&out)
			break
		}
	}

	fmt.Fprintln(&out, "var bpfRouteCapabilities = map[string]bpfRouteCapability{")
	for _, route := range sortedRouteSpecs(manifest.routes) {
		fmt.Fprintf(&out, "\t%q: {enterSlot: %s, exitSlot: %s, standaloneExitElision: %t},\n",
			route.syscallName,
			routeSlot(route.enterProgram, byName),
			routeSlot(route.exitProgram, byName),
			route.standaloneExitElision,
		)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)

	fmt.Fprintln(&out, "var bpfSyscallProgramRoots = map[string]bpfProgramRootSpec{")
	for _, root := range sortedAuxRootSpecs(manifest.auxRoots) {
		fmt.Fprintf(&out, "\t%q: {", root.syscallName)
		if len(root.programs) > 0 {
			fmt.Fprint(&out, "programs: []string{")
			for _, program := range root.programs {
				fmt.Fprintf(&out, "%q,", program)
			}
			fmt.Fprint(&out, "},")
		}
		if len(root.programRefs) > 0 {
			fmt.Fprint(&out, "refs: []bpfProgramRef{")
			for _, ref := range root.programRefs {
				program := byName[ref.program]
				fmt.Fprintf(&out, "{array: %s, slot: %s},", goProgramArray(ref.array), program.goName)
			}
			fmt.Fprint(&out, "},")
		}
		if root.recvmsgProbe {
			fmt.Fprint(&out, "recvmsgKretprobe: true,")
		}
		fmt.Fprintln(&out, "},")
	}
	fmt.Fprintln(&out, "}")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return "", fmt.Errorf("format generated capture Go: %w", err)
	}
	return string(formatted), nil
}

func renderCaptureHeader(manifest captureManifest) (string, error) {
	if err := validateCaptureManifest(manifest); err != nil {
		return "", err
	}
	programs := sortedProgramSpecs(manifest.programs)
	var out strings.Builder
	fmt.Fprintln(&out, "#ifndef STRACE_GO_CAPTURE_MANIFEST_GENERATED_H")
	fmt.Fprintln(&out, "#define STRACE_GO_CAPTURE_MANIFEST_GENERATED_H")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-capture-manifest. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "#define STRACE_GO_CAPTURE_ROUTE_MAP_MAX_ENTRIES %d\n", manifest.routeMapMaxEntries)
	for _, array := range captureProgramArrays() {
		fmt.Fprintf(&out, "#define STRACE_GO_%s_PROG_ARRAY_MAX_ENTRIES %d\n", array.cName, programArrayCapacity(programs, array.kind))
	}
	fmt.Fprintln(&out)
	for _, array := range captureProgramArrays() {
		fmt.Fprintf(&out, "enum %s_prog_index {\n", array.enumName)
		for _, program := range programs {
			if program.array == array.kind {
				fmt.Fprintf(&out, "    %s = %d,\n", program.cName, program.slot)
			}
		}
		fmt.Fprintln(&out, "};")
		fmt.Fprintln(&out)
	}
	fmt.Fprintln(&out, "#endif")
	return out.String(), nil
}

type captureProgramArrayInfo struct {
	kind        captureProgramArray
	goName      string
	cName       string
	enumName    string
	catalogName string
}

func captureProgramArrays() []captureProgramArrayInfo {
	return []captureProgramArrayInfo{
		{captureProgramArrayEnter, "Enter", "ENTER", "enter", "Enter"},
		{captureProgramArrayExit, "Exit", "EXIT", "exit", "Exit"},
		{captureProgramArrayRecvmsg, "Recvmsg", "RECVMSG", "recvmsg", "Recvmsg"},
		{captureProgramArrayMmsg, "MmsgBytes", "MMSG_BYTES", "mmsg_bytes", "MmsgByte"},
	}
}

func goProgramArray(array captureProgramArray) string {
	for _, info := range captureProgramArrays() {
		if info.kind == array {
			return "bpfProgramArray" + info.goName
		}
	}
	return "bpfProgramArrayUnknown"
}

func routeSlot(name string, programs map[string]captureProgramSpec) string {
	if name == "" {
		return "0"
	}
	return programs[name].goName
}

func programArrayCapacity(programs []captureProgramSpec, array captureProgramArray) uint32 {
	var max uint32
	for _, program := range programs {
		if program.array == array && program.slot > max {
			max = program.slot
		}
	}
	if array == captureProgramArrayEnter {
		return max + 1
	}
	return max + 1
}
