package meta

type SyscallMeta struct { Name string; Args []string; ArgTypes []string }

var SyscallTable = map[uint32]SyscallMeta{
	43: {Name: "accept", Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen", }, ArgTypes: []string{"int", "struct sockaddr *", "int *", }},
	288: {Name: "accept4", Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen", "flags", }, ArgTypes: []string{"int", "struct sockaddr *", "int *", "int", }},
	21: {Name: "access", Args: []string{"filename", "mode", }, ArgTypes: []string{"const char *", "int", }},
	163: {Name: "acct", Args: []string{"name", }, ArgTypes: []string{"const char *", }},
	248: {Name: "add_key", Args: []string{"_type", "_description", "_payload", "plen", "ringid", }, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "key_serial_t", }},
	159: {Name: "adjtimex", Args: []string{"txc_p", }, ArgTypes: []string{"struct __kernel_timex *", }},
	37: {Name: "alarm", Args: []string{"seconds", }, ArgTypes: []string{"unsigned int", }},
	158: {Name: "arch_prctl", Args: []string{"option", "arg2", }, ArgTypes: []string{"int", "unsigned long", }},
	49: {Name: "bind", Args: []string{"fd", "umyaddr", "addrlen", }, ArgTypes: []string{"int", "struct sockaddr *", "int", }},
	321: {Name: "bpf", Args: []string{"cmd", "uattr", "size", }, ArgTypes: []string{"int", "union bpf_attr *", "unsigned int", }},
	12: {Name: "brk", Args: []string{"brk", }, ArgTypes: []string{"unsigned long", }},
	451: {Name: "cachestat", Args: []string{"fd", "cstat_range", "cstat", "flags", }, ArgTypes: []string{"unsigned int", "struct cachestat_range *", "struct cachestat *", "unsigned int", }},
	125: {Name: "capget", Args: []string{"header", "dataptr", }, ArgTypes: []string{"cap_user_header_t", "cap_user_data_t", }},
	126: {Name: "capset", Args: []string{"header", "data", }, ArgTypes: []string{"cap_user_header_t", "const cap_user_data_t", }},
	80: {Name: "chdir", Args: []string{"filename", }, ArgTypes: []string{"const char *", }},
	90: {Name: "chmod", Args: []string{"filename", "mode", }, ArgTypes: []string{"const char *", "umode_t", }},
	92: {Name: "chown", Args: []string{"filename", "user", "group", }, ArgTypes: []string{"const char *", "uid_t", "gid_t", }},
	161: {Name: "chroot", Args: []string{"filename", }, ArgTypes: []string{"const char *", }},
	305: {Name: "clock_adjtime", Args: []string{"which_clock", "utx", }, ArgTypes: []string{"const clockid_t", "struct __kernel_timex *", }},
	229: {Name: "clock_getres", Args: []string{"which_clock", "tp", }, ArgTypes: []string{"const clockid_t", "struct __kernel_timespec *", }},
	228: {Name: "clock_gettime", Args: []string{"which_clock", "tp", }, ArgTypes: []string{"const clockid_t", "struct __kernel_timespec *", }},
	230: {Name: "clock_nanosleep", Args: []string{"which_clock", "flags", "rqtp", "rmtp", }, ArgTypes: []string{"const clockid_t", "int", "const struct __kernel_timespec *", "struct __kernel_timespec *", }},
	227: {Name: "clock_settime", Args: []string{"which_clock", "tp", }, ArgTypes: []string{"const clockid_t", "const struct __kernel_timespec *", }},
	56: {Name: "clone", Args: []string{"clone_flags", "newsp", "parent_tidptr", "child_tidptr", "tls", }, ArgTypes: []string{"unsigned long", "unsigned long", "int *", "int *", "unsigned long", }},
	435: {Name: "clone3", Args: []string{"uargs", "size", }, ArgTypes: []string{"struct clone_args *", "size_t", }},
	3: {Name: "close", Args: []string{"fd", }, ArgTypes: []string{"unsigned int", }},
	436: {Name: "close_range", Args: []string{"fd", "max_fd", "flags", }, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned int", }},
	42: {Name: "connect", Args: []string{"fd", "uservaddr", "addrlen", }, ArgTypes: []string{"int", "struct sockaddr *", "int", }},
	326: {Name: "copy_file_range", Args: []string{"fd_in", "off_in", "fd_out", "off_out", "len", "flags", }, ArgTypes: []string{"int", "loff_t *", "int", "loff_t *", "size_t", "unsigned int", }},
	85: {Name: "creat", Args: []string{"pathname", "mode", }, ArgTypes: []string{"const char *", "umode_t", }},
	176: {Name: "delete_module", Args: []string{"name_user", "flags", }, ArgTypes: []string{"const char *", "unsigned int", }},
	32: {Name: "dup", Args: []string{"fildes", }, ArgTypes: []string{"unsigned int", }},
	33: {Name: "dup2", Args: []string{"oldfd", "newfd", }, ArgTypes: []string{"unsigned int", "unsigned int", }},
	292: {Name: "dup3", Args: []string{"oldfd", "newfd", "flags", }, ArgTypes: []string{"unsigned int", "unsigned int", "int", }},
	213: {Name: "epoll_create", Args: []string{"size", }, ArgTypes: []string{"int", }},
	291: {Name: "epoll_create1", Args: []string{"flags", }, ArgTypes: []string{"int", }},
	233: {Name: "epoll_ctl", Args: []string{"epfd", "op", "fd", "event", }, ArgTypes: []string{"int", "int", "int", "struct epoll_event *", }},
	281: {Name: "epoll_pwait", Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize", }, ArgTypes: []string{"int", "struct epoll_event *", "int", "int", "const sigset_t *", "size_t", }},
	441: {Name: "epoll_pwait2", Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize", }, ArgTypes: []string{"int", "struct epoll_event *", "int", "const struct __kernel_timespec *", "const sigset_t *", "size_t", }},
	232: {Name: "epoll_wait", Args: []string{"epfd", "events", "maxevents", "timeout", }, ArgTypes: []string{"int", "struct epoll_event *", "int", "int", }},
	284: {Name: "eventfd", Args: []string{"count", }, ArgTypes: []string{"unsigned int", }},
	290: {Name: "eventfd2", Args: []string{"count", "flags", }, ArgTypes: []string{"unsigned int", "int", }},
	59: {Name: "execve", Args: []string{"filename", "argv", "envp", }, ArgTypes: []string{"const char *", "const char *const *", "const char *const *", }},
	322: {Name: "execveat", Args: []string{"fd", "filename", "argv", "envp", "flags", }, ArgTypes: []string{"int", "const char *", "const char *const *", "const char *const *", "int", }},
	60: {Name: "exit", Args: []string{"error_code", }, ArgTypes: []string{"int", }},
	231: {Name: "exit_group", Args: []string{"error_code", }, ArgTypes: []string{"int", }},
	269: {Name: "faccessat", Args: []string{"dfd", "filename", "mode", }, ArgTypes: []string{"int", "const char *", "int", }},
	439: {Name: "faccessat2", Args: []string{"dfd", "filename", "mode", "flags", }, ArgTypes: []string{"int", "const char *", "int", "int", }},
	221: {Name: "fadvise64", Args: []string{"fd", "offset", "len", "advice", }, ArgTypes: []string{"int", "loff_t", "size_t", "int", }},
	285: {Name: "fallocate", Args: []string{"fd", "mode", "offset", "len", }, ArgTypes: []string{"int", "int", "loff_t", "loff_t", }},
	300: {Name: "fanotify_init", Args: []string{"flags", "event_f_flags", }, ArgTypes: []string{"unsigned int", "unsigned int", }},
	301: {Name: "fanotify_mark", Args: []string{"fanotify_fd", "flags", "mask", "dfd", "pathname", }, ArgTypes: []string{"int", "unsigned int", "__u64", "int", "const char *", }},
	81: {Name: "fchdir", Args: []string{"fd", }, ArgTypes: []string{"unsigned int", }},
	91: {Name: "fchmod", Args: []string{"fd", "mode", }, ArgTypes: []string{"unsigned int", "umode_t", }},
	268: {Name: "fchmodat", Args: []string{"dfd", "filename", "mode", }, ArgTypes: []string{"int", "const char *", "umode_t", }},
	452: {Name: "fchmodat2", Args: []string{"dfd", "filename", "mode", "flags", }, ArgTypes: []string{"int", "const char *", "umode_t", "unsigned int", }},
	93: {Name: "fchown", Args: []string{"fd", "user", "group", }, ArgTypes: []string{"unsigned int", "uid_t", "gid_t", }},
	260: {Name: "fchownat", Args: []string{"dfd", "filename", "user", "group", "flag", }, ArgTypes: []string{"int", "const char *", "uid_t", "gid_t", "int", }},
	72: {Name: "fcntl", Args: []string{"fd", "cmd", "arg", }, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned long", }},
	75: {Name: "fdatasync", Args: []string{"fd", }, ArgTypes: []string{"unsigned int", }},
	193: {Name: "fgetxattr", Args: []string{"fd", "name", "value", "size", }, ArgTypes: []string{"int", "const char *", "void *", "size_t", }},
	468: {Name: "file_getattr", Args: []string{"dfd", "filename", "ufattr", "usize", "at_flags", }, ArgTypes: []string{"int", "const char *", "struct file_attr *", "size_t", "unsigned int", }},
	469: {Name: "file_setattr", Args: []string{"dfd", "filename", "ufattr", "usize", "at_flags", }, ArgTypes: []string{"int", "const char *", "struct file_attr *", "size_t", "unsigned int", }},
	313: {Name: "finit_module", Args: []string{"fd", "uargs", "flags", }, ArgTypes: []string{"int", "const char *", "int", }},
	196: {Name: "flistxattr", Args: []string{"fd", "list", "size", }, ArgTypes: []string{"int", "char *", "size_t", }},
	73: {Name: "flock", Args: []string{"fd", "cmd", }, ArgTypes: []string{"unsigned int", "unsigned int", }},
	57: {Name: "fork", Args: []string{}, ArgTypes: []string{}},
	199: {Name: "fremovexattr", Args: []string{"fd", "name", }, ArgTypes: []string{"int", "const char *", }},
	431: {Name: "fsconfig", Args: []string{"fd", "cmd", "_key", "_value", "aux", }, ArgTypes: []string{"int", "unsigned int", "const char *", "const void *", "int", }},
	190: {Name: "fsetxattr", Args: []string{"fd", "name", "value", "size", "flags", }, ArgTypes: []string{"int", "const char *", "const void *", "size_t", "int", }},
	432: {Name: "fsmount", Args: []string{"fs_fd", "flags", "attr_flags", }, ArgTypes: []string{"int", "unsigned int", "unsigned int", }},
	430: {Name: "fsopen", Args: []string{"_fs_name", "flags", }, ArgTypes: []string{"const char *", "unsigned int", }},
	433: {Name: "fspick", Args: []string{"dfd", "path", "flags", }, ArgTypes: []string{"int", "const char *", "unsigned int", }},
	138: {Name: "fstatfs", Args: []string{"fd", "buf", }, ArgTypes: []string{"unsigned int", "struct statfs *", }},
	74: {Name: "fsync", Args: []string{"fd", }, ArgTypes: []string{"unsigned int", }},
	77: {Name: "ftruncate", Args: []string{"fd", "length", }, ArgTypes: []string{"unsigned int", "off_t", }},
	202: {Name: "futex", Args: []string{"uaddr", "op", "val", "utime", "uaddr2", "val3", }, ArgTypes: []string{"u32 *", "int", "u32", "const struct __kernel_timespec *", "u32 *", "u32", }},
	456: {Name: "futex_requeue", Args: []string{"waiters", "flags", "nr_wake", "nr_requeue", }, ArgTypes: []string{"struct futex_waitv *", "unsigned int", "int", "int", }},
	455: {Name: "futex_wait", Args: []string{"uaddr", "val", "mask", "flags", "timeout", "clockid", }, ArgTypes: []string{"void *", "unsigned long", "unsigned long", "unsigned int", "struct __kernel_timespec *", "clockid_t", }},
	449: {Name: "futex_waitv", Args: []string{"waiters", "nr_futexes", "flags", "timeout", "clockid", }, ArgTypes: []string{"struct futex_waitv *", "unsigned int", "unsigned int", "struct __kernel_timespec *", "clockid_t", }},
	454: {Name: "futex_wake", Args: []string{"uaddr", "mask", "nr", "flags", }, ArgTypes: []string{"void *", "unsigned long", "int", "unsigned int", }},
	261: {Name: "futimesat", Args: []string{"dfd", "filename", "utimes", }, ArgTypes: []string{"int", "const char *", "struct __kernel_old_timeval *", }},
	239: {Name: "get_mempolicy", Args: []string{"policy", "nmask", "maxnode", "addr", "flags", }, ArgTypes: []string{"int *", "unsigned long *", "unsigned long", "unsigned long", "unsigned long", }},
	274: {Name: "get_robust_list", Args: []string{"pid", "head_ptr", "len_ptr", }, ArgTypes: []string{"int", "struct robust_list_head * *", "size_t *", }},
	309: {Name: "getcpu", Args: []string{"cpup", "nodep", "unused", }, ArgTypes: []string{"unsigned *", "unsigned *", "struct getcpu_cache *", }},
	79: {Name: "getcwd", Args: []string{"buf", "size", }, ArgTypes: []string{"char *", "unsigned long", }},
	78: {Name: "getdents", Args: []string{"fd", "dirent", "count", }, ArgTypes: []string{"unsigned int", "struct linux_dirent *", "unsigned int", }},
	217: {Name: "getdents64", Args: []string{"fd", "dirent", "count", }, ArgTypes: []string{"unsigned int", "struct linux_dirent64 *", "unsigned int", }},
	108: {Name: "getegid", Args: []string{}, ArgTypes: []string{}},
	107: {Name: "geteuid", Args: []string{}, ArgTypes: []string{}},
	104: {Name: "getgid", Args: []string{}, ArgTypes: []string{}},
	115: {Name: "getgroups", Args: []string{"gidsetsize", "grouplist", }, ArgTypes: []string{"int", "gid_t *", }},
	36: {Name: "getitimer", Args: []string{"which", "value", }, ArgTypes: []string{"int", "struct __kernel_old_itimerval *", }},
	52: {Name: "getpeername", Args: []string{"fd", "usockaddr", "usockaddr_len", }, ArgTypes: []string{"int", "struct sockaddr *", "int *", }},
	121: {Name: "getpgid", Args: []string{"pid", }, ArgTypes: []string{"pid_t", }},
	111: {Name: "getpgrp", Args: []string{}, ArgTypes: []string{}},
	39: {Name: "getpid", Args: []string{}, ArgTypes: []string{}},
	110: {Name: "getppid", Args: []string{}, ArgTypes: []string{}},
	140: {Name: "getpriority", Args: []string{"which", "who", }, ArgTypes: []string{"int", "int", }},
	318: {Name: "getrandom", Args: []string{"ubuf", "len", "flags", }, ArgTypes: []string{"char *", "size_t", "unsigned int", }},
	120: {Name: "getresgid", Args: []string{"rgidp", "egidp", "sgidp", }, ArgTypes: []string{"gid_t *", "gid_t *", "gid_t *", }},
	118: {Name: "getresuid", Args: []string{"ruidp", "euidp", "suidp", }, ArgTypes: []string{"uid_t *", "uid_t *", "uid_t *", }},
	97: {Name: "getrlimit", Args: []string{"resource", "rlim", }, ArgTypes: []string{"unsigned int", "struct rlimit *", }},
	98: {Name: "getrusage", Args: []string{"who", "ru", }, ArgTypes: []string{"int", "struct rusage *", }},
	124: {Name: "getsid", Args: []string{"pid", }, ArgTypes: []string{"pid_t", }},
	51: {Name: "getsockname", Args: []string{"fd", "usockaddr", "usockaddr_len", }, ArgTypes: []string{"int", "struct sockaddr *", "int *", }},
	55: {Name: "getsockopt", Args: []string{"fd", "level", "optname", "optval", "optlen", }, ArgTypes: []string{"int", "int", "int", "char *", "int *", }},
	186: {Name: "gettid", Args: []string{}, ArgTypes: []string{}},
	96: {Name: "gettimeofday", Args: []string{"tv", "tz", }, ArgTypes: []string{"struct __kernel_old_timeval *", "struct timezone *", }},
	102: {Name: "getuid", Args: []string{}, ArgTypes: []string{}},
	191: {Name: "getxattr", Args: []string{"pathname", "name", "value", "size", }, ArgTypes: []string{"const char *", "const char *", "void *", "size_t", }},
	464: {Name: "getxattrat", Args: []string{"dfd", "pathname", "at_flags", "name", "uargs", "usize", }, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *", "struct xattr_args *", "size_t", }},
	175: {Name: "init_module", Args: []string{"umod", "len", "uargs", }, ArgTypes: []string{"void *", "unsigned long", "const char *", }},
	254: {Name: "inotify_add_watch", Args: []string{"fd", "pathname", "mask", }, ArgTypes: []string{"int", "const char *", "u32", }},
	253: {Name: "inotify_init", Args: []string{}, ArgTypes: []string{}},
	294: {Name: "inotify_init1", Args: []string{"flags", }, ArgTypes: []string{"int", }},
	255: {Name: "inotify_rm_watch", Args: []string{"fd", "wd", }, ArgTypes: []string{"int", "__s32", }},
	210: {Name: "io_cancel", Args: []string{"ctx_id", "iocb", "result", }, ArgTypes: []string{"aio_context_t", "struct iocb *", "struct io_event *", }},
	207: {Name: "io_destroy", Args: []string{"ctx", }, ArgTypes: []string{"aio_context_t", }},
	208: {Name: "io_getevents", Args: []string{"ctx_id", "min_nr", "nr", "events", "timeout", }, ArgTypes: []string{"aio_context_t", "long", "long", "struct io_event *", "struct __kernel_timespec *", }},
	333: {Name: "io_pgetevents", Args: []string{"ctx_id", "min_nr", "nr", "events", "timeout", "usig", }, ArgTypes: []string{"aio_context_t", "long", "long", "struct io_event *", "struct __kernel_timespec *", "const struct __aio_sigset *", }},
	206: {Name: "io_setup", Args: []string{"nr_events", "ctxp", }, ArgTypes: []string{"unsigned", "aio_context_t *", }},
	209: {Name: "io_submit", Args: []string{"ctx_id", "nr", "iocbpp", }, ArgTypes: []string{"aio_context_t", "long", "struct iocb * *", }},
	426: {Name: "io_uring_enter", Args: []string{"fd", "to_submit", "min_complete", "flags", "argp", "argsz", }, ArgTypes: []string{"unsigned int", "u32", "u32", "u32", "const void *", "size_t", }},
	427: {Name: "io_uring_register", Args: []string{"fd", "opcode", "arg", "nr_args", }, ArgTypes: []string{"unsigned int", "unsigned int", "void *", "unsigned int", }},
	425: {Name: "io_uring_setup", Args: []string{"entries", "params", }, ArgTypes: []string{"u32", "struct io_uring_params *", }},
	16: {Name: "ioctl", Args: []string{"fd", "cmd", "arg", }, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned long", }},
	173: {Name: "ioperm", Args: []string{"from", "num", "turn_on", }, ArgTypes: []string{"unsigned long", "unsigned long", "int", }},
	172: {Name: "iopl", Args: []string{"level", }, ArgTypes: []string{"unsigned int", }},
	252: {Name: "ioprio_get", Args: []string{"which", "who", }, ArgTypes: []string{"int", "int", }},
	251: {Name: "ioprio_set", Args: []string{"which", "who", "ioprio", }, ArgTypes: []string{"int", "int", "int", }},
	312: {Name: "kcmp", Args: []string{"pid1", "pid2", "type", "idx1", "idx2", }, ArgTypes: []string{"pid_t", "pid_t", "int", "unsigned long", "unsigned long", }},
	320: {Name: "kexec_file_load", Args: []string{"kernel_fd", "initrd_fd", "cmdline_len", "cmdline_ptr", "flags", }, ArgTypes: []string{"int", "int", "unsigned long", "const char *", "unsigned long", }},
	246: {Name: "kexec_load", Args: []string{"entry", "nr_segments", "segments", "flags", }, ArgTypes: []string{"unsigned long", "unsigned long", "struct kexec_segment *", "unsigned long", }},
	250: {Name: "keyctl", Args: []string{"option", "arg2", "arg3", "arg4", "arg5", }, ArgTypes: []string{"int", "unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	62: {Name: "kill", Args: []string{"pid", "sig", }, ArgTypes: []string{"pid_t", "int", }},
	445: {Name: "landlock_add_rule", Args: []string{"ruleset_fd", "rule_type", "rule_attr", "flags", }, ArgTypes: []string{"const int", "const enum landlock_rule_type", "const void *const", "const __u32", }},
	444: {Name: "landlock_create_ruleset", Args: []string{"attr", "size", "flags", }, ArgTypes: []string{"const struct landlock_ruleset_attr *const", "const size_t", "const __u32", }},
	446: {Name: "landlock_restrict_self", Args: []string{"ruleset_fd", "flags", }, ArgTypes: []string{"const int", "const __u32", }},
	94: {Name: "lchown", Args: []string{"filename", "user", "group", }, ArgTypes: []string{"const char *", "uid_t", "gid_t", }},
	192: {Name: "lgetxattr", Args: []string{"pathname", "name", "value", "size", }, ArgTypes: []string{"const char *", "const char *", "void *", "size_t", }},
	86: {Name: "link", Args: []string{"oldname", "newname", }, ArgTypes: []string{"const char *", "const char *", }},
	265: {Name: "linkat", Args: []string{"olddfd", "oldname", "newdfd", "newname", "flags", }, ArgTypes: []string{"int", "const char *", "int", "const char *", "int", }},
	50: {Name: "listen", Args: []string{"fd", "backlog", }, ArgTypes: []string{"int", "int", }},
	458: {Name: "listmount", Args: []string{"req", "mnt_ids", "nr_mnt_ids", "flags", }, ArgTypes: []string{"const struct mnt_id_req *", "u64 *", "size_t", "unsigned int", }},
	194: {Name: "listxattr", Args: []string{"pathname", "list", "size", }, ArgTypes: []string{"const char *", "char *", "size_t", }},
	465: {Name: "listxattrat", Args: []string{"dfd", "pathname", "at_flags", "list", "size", }, ArgTypes: []string{"int", "const char *", "unsigned int", "char *", "size_t", }},
	195: {Name: "llistxattr", Args: []string{"pathname", "list", "size", }, ArgTypes: []string{"const char *", "char *", "size_t", }},
	198: {Name: "lremovexattr", Args: []string{"pathname", "name", }, ArgTypes: []string{"const char *", "const char *", }},
	8: {Name: "lseek", Args: []string{"fd", "offset", "whence", }, ArgTypes: []string{"unsigned int", "off_t", "unsigned int", }},
	189: {Name: "lsetxattr", Args: []string{"pathname", "name", "value", "size", "flags", }, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "int", }},
	459: {Name: "lsm_get_self_attr", Args: []string{"attr", "ctx", "size", "flags", }, ArgTypes: []string{"unsigned int", "struct lsm_ctx *", "u32 *", "u32", }},
	461: {Name: "lsm_list_modules", Args: []string{"ids", "size", "flags", }, ArgTypes: []string{"u64 *", "u32 *", "u32", }},
	460: {Name: "lsm_set_self_attr", Args: []string{"attr", "ctx", "size", "flags", }, ArgTypes: []string{"unsigned int", "struct lsm_ctx *", "u32", "u32", }},
	28: {Name: "madvise", Args: []string{"start", "len_in", "behavior", }, ArgTypes: []string{"unsigned long", "size_t", "int", }},
	453: {Name: "map_shadow_stack", Args: []string{"addr", "size", "flags", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned int", }},
	237: {Name: "mbind", Args: []string{"start", "len", "mode", "nmask", "maxnode", "flags", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "const unsigned long *", "unsigned long", "unsigned int", }},
	324: {Name: "membarrier", Args: []string{"cmd", "flags", "cpu_id", }, ArgTypes: []string{"int", "unsigned int", "int", }},
	319: {Name: "memfd_create", Args: []string{"uname", "flags", }, ArgTypes: []string{"const char *", "unsigned int", }},
	447: {Name: "memfd_secret", Args: []string{"flags", }, ArgTypes: []string{"unsigned int", }},
	256: {Name: "migrate_pages", Args: []string{"pid", "maxnode", "old_nodes", "new_nodes", }, ArgTypes: []string{"pid_t", "unsigned long", "const unsigned long *", "const unsigned long *", }},
	27: {Name: "mincore", Args: []string{"start", "len", "vec", }, ArgTypes: []string{"unsigned long", "size_t", "unsigned char *", }},
	83: {Name: "mkdir", Args: []string{"pathname", "mode", }, ArgTypes: []string{"const char *", "umode_t", }},
	258: {Name: "mkdirat", Args: []string{"dfd", "pathname", "mode", }, ArgTypes: []string{"int", "const char *", "umode_t", }},
	133: {Name: "mknod", Args: []string{"filename", "mode", "dev", }, ArgTypes: []string{"const char *", "umode_t", "unsigned", }},
	259: {Name: "mknodat", Args: []string{"dfd", "filename", "mode", "dev", }, ArgTypes: []string{"int", "const char *", "umode_t", "unsigned int", }},
	149: {Name: "mlock", Args: []string{"start", "len", }, ArgTypes: []string{"unsigned long", "size_t", }},
	325: {Name: "mlock2", Args: []string{"start", "len", "flags", }, ArgTypes: []string{"unsigned long", "size_t", "int", }},
	151: {Name: "mlockall", Args: []string{"flags", }, ArgTypes: []string{"int", }},
	9: {Name: "mmap", Args: []string{"addr", "len", "prot", "flags", "fd", "off", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	154: {Name: "modify_ldt", Args: []string{"func", "ptr", "bytecount", }, ArgTypes: []string{"int", "void *", "unsigned long", }},
	165: {Name: "mount", Args: []string{"dev_name", "dir_name", "type", "flags", "data", }, ArgTypes: []string{"char *", "char *", "char *", "unsigned long", "void *", }},
	442: {Name: "mount_setattr", Args: []string{"dfd", "path", "flags", "uattr", "usize", }, ArgTypes: []string{"int", "const char *", "unsigned int", "struct mount_attr *", "size_t", }},
	429: {Name: "move_mount", Args: []string{"from_dfd", "from_pathname", "to_dfd", "to_pathname", "flags", }, ArgTypes: []string{"int", "const char *", "int", "const char *", "unsigned int", }},
	279: {Name: "move_pages", Args: []string{"pid", "nr_pages", "pages", "nodes", "status", "flags", }, ArgTypes: []string{"pid_t", "unsigned long", "const void * *", "const int *", "int *", "int", }},
	10: {Name: "mprotect", Args: []string{"start", "len", "prot", }, ArgTypes: []string{"unsigned long", "size_t", "unsigned long", }},
	245: {Name: "mq_getsetattr", Args: []string{"mqdes", "u_mqstat", "u_omqstat", }, ArgTypes: []string{"mqd_t", "const struct mq_attr *", "struct mq_attr *", }},
	244: {Name: "mq_notify", Args: []string{"mqdes", "u_notification", }, ArgTypes: []string{"mqd_t", "const struct sigevent *", }},
	240: {Name: "mq_open", Args: []string{"u_name", "oflag", "mode", "u_attr", }, ArgTypes: []string{"const char *", "int", "umode_t", "struct mq_attr *", }},
	243: {Name: "mq_timedreceive", Args: []string{"mqdes", "u_msg_ptr", "msg_len", "u_msg_prio", "u_abs_timeout", }, ArgTypes: []string{"mqd_t", "char *", "size_t", "unsigned int *", "const struct __kernel_timespec *", }},
	242: {Name: "mq_timedsend", Args: []string{"mqdes", "u_msg_ptr", "msg_len", "msg_prio", "u_abs_timeout", }, ArgTypes: []string{"mqd_t", "const char *", "size_t", "unsigned int", "const struct __kernel_timespec *", }},
	241: {Name: "mq_unlink", Args: []string{"u_name", }, ArgTypes: []string{"const char *", }},
	25: {Name: "mremap", Args: []string{"addr", "old_len", "new_len", "flags", "new_addr", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	462: {Name: "mseal", Args: []string{"start", "len", "flags", }, ArgTypes: []string{"unsigned long", "size_t", "unsigned long", }},
	71: {Name: "msgctl", Args: []string{"msqid", "cmd", "buf", }, ArgTypes: []string{"int", "int", "struct msqid_ds *", }},
	68: {Name: "msgget", Args: []string{"key", "msgflg", }, ArgTypes: []string{"key_t", "int", }},
	70: {Name: "msgrcv", Args: []string{"msqid", "msgp", "msgsz", "msgtyp", "msgflg", }, ArgTypes: []string{"int", "struct msgbuf *", "size_t", "long", "int", }},
	69: {Name: "msgsnd", Args: []string{"msqid", "msgp", "msgsz", "msgflg", }, ArgTypes: []string{"int", "struct msgbuf *", "size_t", "int", }},
	26: {Name: "msync", Args: []string{"start", "len", "flags", }, ArgTypes: []string{"unsigned long", "size_t", "int", }},
	150: {Name: "munlock", Args: []string{"start", "len", }, ArgTypes: []string{"unsigned long", "size_t", }},
	152: {Name: "munlockall", Args: []string{}, ArgTypes: []string{}},
	11: {Name: "munmap", Args: []string{"addr", "len", }, ArgTypes: []string{"unsigned long", "size_t", }},
	303: {Name: "name_to_handle_at", Args: []string{"dfd", "name", "handle", "mnt_id", "flag", }, ArgTypes: []string{"int", "const char *", "struct file_handle *", "void *", "int", }},
	35: {Name: "nanosleep", Args: []string{"rqtp", "rmtp", }, ArgTypes: []string{"struct __kernel_timespec *", "struct __kernel_timespec *", }},
	5: {Name: "fstat", Args: []string{"fd", "statbuf", }, ArgTypes: []string{"unsigned int", "struct stat *", }},
	262: {Name: "newfstatat", Args: []string{"dfd", "filename", "statbuf", "flag", }, ArgTypes: []string{"int", "const char *", "struct stat *", "int", }},
	6: {Name: "lstat", Args: []string{"filename", "statbuf", }, ArgTypes: []string{"const char *", "struct stat *", }},
	4: {Name: "stat", Args: []string{"filename", "statbuf", }, ArgTypes: []string{"const char *", "struct stat *", }},
	63: {Name: "uname", Args: []string{"name", }, ArgTypes: []string{"struct new_utsname *", }},
	2: {Name: "open", Args: []string{"filename", "flags", "mode", }, ArgTypes: []string{"const char *", "int", "umode_t", }},
	304: {Name: "open_by_handle_at", Args: []string{"mountdirfd", "handle", "flags", }, ArgTypes: []string{"int", "struct file_handle *", "int", }},
	428: {Name: "open_tree", Args: []string{"dfd", "filename", "flags", }, ArgTypes: []string{"int", "const char *", "unsigned", }},
	467: {Name: "open_tree_attr", Args: []string{"dfd", "filename", "flags", "uattr", "usize", }, ArgTypes: []string{"int", "const char *", "unsigned", "struct mount_attr *", "size_t", }},
	257: {Name: "openat", Args: []string{"dfd", "filename", "flags", "mode", }, ArgTypes: []string{"int", "const char *", "int", "umode_t", }},
	437: {Name: "openat2", Args: []string{"dfd", "filename", "how", "usize", }, ArgTypes: []string{"int", "const char *", "struct open_how *", "size_t", }},
	34: {Name: "pause", Args: []string{}, ArgTypes: []string{}},
	298: {Name: "perf_event_open", Args: []string{"attr_uptr", "pid", "cpu", "group_fd", "flags", }, ArgTypes: []string{"struct perf_event_attr *", "pid_t", "int", "int", "unsigned long", }},
	135: {Name: "personality", Args: []string{"personality", }, ArgTypes: []string{"unsigned int", }},
	438: {Name: "pidfd_getfd", Args: []string{"pidfd", "fd", "flags", }, ArgTypes: []string{"int", "int", "unsigned int", }},
	434: {Name: "pidfd_open", Args: []string{"pid", "flags", }, ArgTypes: []string{"pid_t", "unsigned int", }},
	424: {Name: "pidfd_send_signal", Args: []string{"pidfd", "sig", "info", "flags", }, ArgTypes: []string{"int", "int", "siginfo_t *", "unsigned int", }},
	22: {Name: "pipe", Args: []string{"fildes", }, ArgTypes: []string{"int *", }},
	293: {Name: "pipe2", Args: []string{"fildes", "flags", }, ArgTypes: []string{"int *", "int", }},
	155: {Name: "pivot_root", Args: []string{"new_root", "put_old", }, ArgTypes: []string{"const char *", "const char *", }},
	330: {Name: "pkey_alloc", Args: []string{"flags", "init_val", }, ArgTypes: []string{"unsigned long", "unsigned long", }},
	331: {Name: "pkey_free", Args: []string{"pkey", }, ArgTypes: []string{"int", }},
	329: {Name: "pkey_mprotect", Args: []string{"start", "len", "prot", "pkey", }, ArgTypes: []string{"unsigned long", "size_t", "unsigned long", "int", }},
	7: {Name: "poll", Args: []string{"ufds", "nfds", "timeout_msecs", }, ArgTypes: []string{"struct pollfd *", "unsigned int", "int", }},
	271: {Name: "ppoll", Args: []string{"ufds", "nfds", "tsp", "sigmask", "sigsetsize", }, ArgTypes: []string{"struct pollfd *", "unsigned int", "struct __kernel_timespec *", "const sigset_t *", "size_t", }},
	157: {Name: "prctl", Args: []string{"option", "arg2", "arg3", "arg4", "arg5", }, ArgTypes: []string{"int", "unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	17: {Name: "pread64", Args: []string{"fd", "buf", "count", "pos", }, ArgTypes: []string{"unsigned int", "char *", "size_t", "loff_t", }},
	295: {Name: "preadv", Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", }},
	327: {Name: "preadv2", Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", "flags", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", "rwf_t", }},
	302: {Name: "prlimit64", Args: []string{"pid", "resource", "new_rlim", "old_rlim", }, ArgTypes: []string{"pid_t", "unsigned int", "const struct rlimit64 *", "struct rlimit64 *", }},
	440: {Name: "process_madvise", Args: []string{"pidfd", "vec", "vlen", "behavior", "flags", }, ArgTypes: []string{"int", "const struct iovec *", "size_t", "int", "unsigned int", }},
	448: {Name: "process_mrelease", Args: []string{"pidfd", "flags", }, ArgTypes: []string{"int", "unsigned int", }},
	310: {Name: "process_vm_readv", Args: []string{"pid", "lvec", "liovcnt", "rvec", "riovcnt", "flags", }, ArgTypes: []string{"pid_t", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long", }},
	311: {Name: "process_vm_writev", Args: []string{"pid", "lvec", "liovcnt", "rvec", "riovcnt", "flags", }, ArgTypes: []string{"pid_t", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long", }},
	270: {Name: "pselect6", Args: []string{"n", "inp", "outp", "exp", "tsp", "sig", }, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct __kernel_timespec *", "void *", }},
	101: {Name: "ptrace", Args: []string{"request", "pid", "addr", "data", }, ArgTypes: []string{"long", "long", "unsigned long", "unsigned long", }},
	18: {Name: "pwrite64", Args: []string{"fd", "buf", "count", "pos", }, ArgTypes: []string{"unsigned int", "const char *", "size_t", "loff_t", }},
	296: {Name: "pwritev", Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", }},
	328: {Name: "pwritev2", Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", "flags", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", "rwf_t", }},
	179: {Name: "quotactl", Args: []string{"cmd", "special", "id", "addr", }, ArgTypes: []string{"unsigned int", "const char *", "qid_t", "void *", }},
	443: {Name: "quotactl_fd", Args: []string{"fd", "cmd", "id", "addr", }, ArgTypes: []string{"unsigned int", "unsigned int", "qid_t", "void *", }},
	0: {Name: "read", Args: []string{"fd", "buf", "count", }, ArgTypes: []string{"unsigned int", "char *", "size_t", }},
	187: {Name: "readahead", Args: []string{"fd", "offset", "count", }, ArgTypes: []string{"int", "loff_t", "size_t", }},
	89: {Name: "readlink", Args: []string{"path", "buf", "bufsiz", }, ArgTypes: []string{"const char *", "char *", "int", }},
	267: {Name: "readlinkat", Args: []string{"dfd", "pathname", "buf", "bufsiz", }, ArgTypes: []string{"int", "const char *", "char *", "int", }},
	19: {Name: "readv", Args: []string{"fd", "vec", "vlen", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", }},
	169: {Name: "reboot", Args: []string{"magic1", "magic2", "cmd", "arg", }, ArgTypes: []string{"int", "int", "unsigned int", "void *", }},
	45: {Name: "recvfrom", Args: []string{"fd", "ubuf", "size", "flags", "addr", "addr_len", }, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int *", }},
	299: {Name: "recvmmsg", Args: []string{"fd", "mmsg", "vlen", "flags", "timeout", }, ArgTypes: []string{"int", "struct mmsghdr *", "unsigned int", "unsigned int", "struct __kernel_timespec *", }},
	47: {Name: "recvmsg", Args: []string{"fd", "msg", "flags", }, ArgTypes: []string{"int", "struct user_msghdr *", "unsigned int", }},
	216: {Name: "remap_file_pages", Args: []string{"start", "size", "prot", "pgoff", "flags", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	197: {Name: "removexattr", Args: []string{"pathname", "name", }, ArgTypes: []string{"const char *", "const char *", }},
	466: {Name: "removexattrat", Args: []string{"dfd", "pathname", "at_flags", "name", }, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *", }},
	82: {Name: "rename", Args: []string{"oldname", "newname", }, ArgTypes: []string{"const char *", "const char *", }},
	264: {Name: "renameat", Args: []string{"olddfd", "oldname", "newdfd", "newname", }, ArgTypes: []string{"int", "const char *", "int", "const char *", }},
	316: {Name: "renameat2", Args: []string{"olddfd", "oldname", "newdfd", "newname", "flags", }, ArgTypes: []string{"int", "const char *", "int", "const char *", "unsigned int", }},
	249: {Name: "request_key", Args: []string{"_type", "_description", "_callout_info", "destringid", }, ArgTypes: []string{"const char *", "const char *", "const char *", "key_serial_t", }},
	219: {Name: "restart_syscall", Args: []string{}, ArgTypes: []string{}},
	84: {Name: "rmdir", Args: []string{"pathname", }, ArgTypes: []string{"const char *", }},
	334: {Name: "rseq", Args: []string{"rseq", "rseq_len", "flags", "sig", }, ArgTypes: []string{"struct rseq *", "u32", "int", "u32", }},
	13: {Name: "rt_sigaction", Args: []string{"sig", "act", "oact", "sigsetsize", }, ArgTypes: []string{"int", "const struct sigaction *", "struct sigaction *", "size_t", }},
	127: {Name: "rt_sigpending", Args: []string{"uset", "sigsetsize", }, ArgTypes: []string{"sigset_t *", "size_t", }},
	14: {Name: "rt_sigprocmask", Args: []string{"how", "nset", "oset", "sigsetsize", }, ArgTypes: []string{"int", "sigset_t *", "sigset_t *", "size_t", }},
	129: {Name: "rt_sigqueueinfo", Args: []string{"pid", "sig", "uinfo", }, ArgTypes: []string{"pid_t", "int", "siginfo_t *", }},
	15: {Name: "rt_sigreturn", Args: []string{}, ArgTypes: []string{}},
	130: {Name: "rt_sigsuspend", Args: []string{"unewset", "sigsetsize", }, ArgTypes: []string{"sigset_t *", "size_t", }},
	128: {Name: "rt_sigtimedwait", Args: []string{"uthese", "uinfo", "uts", "sigsetsize", }, ArgTypes: []string{"const sigset_t *", "siginfo_t *", "const struct __kernel_timespec *", "size_t", }},
	297: {Name: "rt_tgsigqueueinfo", Args: []string{"tgid", "pid", "sig", "uinfo", }, ArgTypes: []string{"pid_t", "pid_t", "int", "siginfo_t *", }},
	146: {Name: "sched_get_priority_max", Args: []string{"policy", }, ArgTypes: []string{"int", }},
	147: {Name: "sched_get_priority_min", Args: []string{"policy", }, ArgTypes: []string{"int", }},
	204: {Name: "sched_getaffinity", Args: []string{"pid", "len", "user_mask_ptr", }, ArgTypes: []string{"pid_t", "unsigned int", "unsigned long *", }},
	315: {Name: "sched_getattr", Args: []string{"pid", "uattr", "usize", "flags", }, ArgTypes: []string{"pid_t", "struct sched_attr *", "unsigned int", "unsigned int", }},
	143: {Name: "sched_getparam", Args: []string{"pid", "param", }, ArgTypes: []string{"pid_t", "struct sched_param *", }},
	145: {Name: "sched_getscheduler", Args: []string{"pid", }, ArgTypes: []string{"pid_t", }},
	148: {Name: "sched_rr_get_interval", Args: []string{"pid", "interval", }, ArgTypes: []string{"pid_t", "struct __kernel_timespec *", }},
	203: {Name: "sched_setaffinity", Args: []string{"pid", "len", "user_mask_ptr", }, ArgTypes: []string{"pid_t", "unsigned int", "unsigned long *", }},
	314: {Name: "sched_setattr", Args: []string{"pid", "uattr", "flags", }, ArgTypes: []string{"pid_t", "struct sched_attr *", "unsigned int", }},
	142: {Name: "sched_setparam", Args: []string{"pid", "param", }, ArgTypes: []string{"pid_t", "struct sched_param *", }},
	144: {Name: "sched_setscheduler", Args: []string{"pid", "policy", "param", }, ArgTypes: []string{"pid_t", "int", "struct sched_param *", }},
	24: {Name: "sched_yield", Args: []string{}, ArgTypes: []string{}},
	317: {Name: "seccomp", Args: []string{"op", "flags", "uargs", }, ArgTypes: []string{"unsigned int", "unsigned int", "void *", }},
	23: {Name: "select", Args: []string{"n", "inp", "outp", "exp", "tvp", }, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct __kernel_old_timeval *", }},
	66: {Name: "semctl", Args: []string{"semid", "semnum", "cmd", "arg", }, ArgTypes: []string{"int", "int", "int", "unsigned long", }},
	64: {Name: "semget", Args: []string{"key", "nsems", "semflg", }, ArgTypes: []string{"key_t", "int", "int", }},
	65: {Name: "semop", Args: []string{"semid", "tsops", "nsops", }, ArgTypes: []string{"int", "struct sembuf *", "unsigned", }},
	220: {Name: "semtimedop", Args: []string{"semid", "tsops", "nsops", "timeout", }, ArgTypes: []string{"int", "struct sembuf *", "unsigned int", "const struct __kernel_timespec *", }},
	307: {Name: "sendmmsg", Args: []string{"fd", "mmsg", "vlen", "flags", }, ArgTypes: []string{"int", "struct mmsghdr *", "unsigned int", "unsigned int", }},
	46: {Name: "sendmsg", Args: []string{"fd", "msg", "flags", }, ArgTypes: []string{"int", "struct user_msghdr *", "unsigned int", }},
	44: {Name: "sendto", Args: []string{"fd", "buff", "len", "flags", "addr", "addr_len", }, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int", }},
	238: {Name: "set_mempolicy", Args: []string{"mode", "nmask", "maxnode", }, ArgTypes: []string{"int", "const unsigned long *", "unsigned long", }},
	450: {Name: "set_mempolicy_home_node", Args: []string{"start", "len", "home_node", "flags", }, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", }},
	273: {Name: "set_robust_list", Args: []string{"head", "len", }, ArgTypes: []string{"struct robust_list_head *", "size_t", }},
	218: {Name: "set_tid_address", Args: []string{"tidptr", }, ArgTypes: []string{"int *", }},
	171: {Name: "setdomainname", Args: []string{"name", "len", }, ArgTypes: []string{"char *", "int", }},
	123: {Name: "setfsgid", Args: []string{"gid", }, ArgTypes: []string{"gid_t", }},
	122: {Name: "setfsuid", Args: []string{"uid", }, ArgTypes: []string{"uid_t", }},
	106: {Name: "setgid", Args: []string{"gid", }, ArgTypes: []string{"gid_t", }},
	116: {Name: "setgroups", Args: []string{"gidsetsize", "grouplist", }, ArgTypes: []string{"int", "gid_t *", }},
	170: {Name: "sethostname", Args: []string{"name", "len", }, ArgTypes: []string{"char *", "int", }},
	38: {Name: "setitimer", Args: []string{"which", "value", "ovalue", }, ArgTypes: []string{"int", "struct __kernel_old_itimerval *", "struct __kernel_old_itimerval *", }},
	308: {Name: "setns", Args: []string{"fd", "flags", }, ArgTypes: []string{"int", "int", }},
	109: {Name: "setpgid", Args: []string{"pid", "pgid", }, ArgTypes: []string{"pid_t", "pid_t", }},
	141: {Name: "setpriority", Args: []string{"which", "who", "niceval", }, ArgTypes: []string{"int", "int", "int", }},
	114: {Name: "setregid", Args: []string{"rgid", "egid", }, ArgTypes: []string{"gid_t", "gid_t", }},
	119: {Name: "setresgid", Args: []string{"rgid", "egid", "sgid", }, ArgTypes: []string{"gid_t", "gid_t", "gid_t", }},
	117: {Name: "setresuid", Args: []string{"ruid", "euid", "suid", }, ArgTypes: []string{"uid_t", "uid_t", "uid_t", }},
	113: {Name: "setreuid", Args: []string{"ruid", "euid", }, ArgTypes: []string{"uid_t", "uid_t", }},
	160: {Name: "setrlimit", Args: []string{"resource", "rlim", }, ArgTypes: []string{"unsigned int", "struct rlimit *", }},
	112: {Name: "setsid", Args: []string{}, ArgTypes: []string{}},
	54: {Name: "setsockopt", Args: []string{"fd", "level", "optname", "optval", "optlen", }, ArgTypes: []string{"int", "int", "int", "char *", "int", }},
	164: {Name: "settimeofday", Args: []string{"tv", "tz", }, ArgTypes: []string{"struct __kernel_old_timeval *", "struct timezone *", }},
	105: {Name: "setuid", Args: []string{"uid", }, ArgTypes: []string{"uid_t", }},
	188: {Name: "setxattr", Args: []string{"pathname", "name", "value", "size", "flags", }, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "int", }},
	463: {Name: "setxattrat", Args: []string{"dfd", "pathname", "at_flags", "name", "uargs", "usize", }, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *", "const struct xattr_args *", "size_t", }},
	30: {Name: "shmat", Args: []string{"shmid", "shmaddr", "shmflg", }, ArgTypes: []string{"int", "char *", "int", }},
	31: {Name: "shmctl", Args: []string{"shmid", "cmd", "buf", }, ArgTypes: []string{"int", "int", "struct shmid_ds *", }},
	67: {Name: "shmdt", Args: []string{"shmaddr", }, ArgTypes: []string{"char *", }},
	29: {Name: "shmget", Args: []string{"key", "size", "shmflg", }, ArgTypes: []string{"key_t", "size_t", "int", }},
	48: {Name: "shutdown", Args: []string{"fd", "how", }, ArgTypes: []string{"int", "int", }},
	131: {Name: "sigaltstack", Args: []string{"uss", "uoss", }, ArgTypes: []string{"const stack_t *", "stack_t *", }},
	282: {Name: "signalfd", Args: []string{"ufd", "user_mask", "sizemask", }, ArgTypes: []string{"int", "sigset_t *", "size_t", }},
	289: {Name: "signalfd4", Args: []string{"ufd", "user_mask", "sizemask", "flags", }, ArgTypes: []string{"int", "sigset_t *", "size_t", "int", }},
	41: {Name: "socket", Args: []string{"family", "type", "protocol", }, ArgTypes: []string{"int", "int", "int", }},
	53: {Name: "socketpair", Args: []string{"family", "type", "protocol", "usockvec", }, ArgTypes: []string{"int", "int", "int", "int *", }},
	275: {Name: "splice", Args: []string{"fd_in", "off_in", "fd_out", "off_out", "len", "flags", }, ArgTypes: []string{"int", "loff_t *", "int", "loff_t *", "size_t", "unsigned int", }},
	137: {Name: "statfs", Args: []string{"pathname", "buf", }, ArgTypes: []string{"const char *", "struct statfs *", }},
	457: {Name: "statmount", Args: []string{"req", "buf", "bufsize", "flags", }, ArgTypes: []string{"const struct mnt_id_req *", "struct statmount *", "size_t", "unsigned int", }},
	332: {Name: "statx", Args: []string{"dfd", "filename", "flags", "mask", "buffer", }, ArgTypes: []string{"int", "const char *", "unsigned", "unsigned int", "struct statx *", }},
	168: {Name: "swapoff", Args: []string{"specialfile", }, ArgTypes: []string{"const char *", }},
	167: {Name: "swapon", Args: []string{"specialfile", "swap_flags", }, ArgTypes: []string{"const char *", "int", }},
	88: {Name: "symlink", Args: []string{"oldname", "newname", }, ArgTypes: []string{"const char *", "const char *", }},
	266: {Name: "symlinkat", Args: []string{"oldname", "newdfd", "newname", }, ArgTypes: []string{"const char *", "int", "const char *", }},
	162: {Name: "sync", Args: []string{}, ArgTypes: []string{}},
	277: {Name: "sync_file_range", Args: []string{"fd", "offset", "nbytes", "flags", }, ArgTypes: []string{"int", "loff_t", "loff_t", "unsigned int", }},
	306: {Name: "syncfs", Args: []string{"fd", }, ArgTypes: []string{"int", }},
	139: {Name: "sysfs", Args: []string{"option", "arg1", "arg2", }, ArgTypes: []string{"int", "unsigned long", "unsigned long", }},
	99: {Name: "sysinfo", Args: []string{"info", }, ArgTypes: []string{"struct sysinfo *", }},
	103: {Name: "syslog", Args: []string{"type", "buf", "len", }, ArgTypes: []string{"int", "char *", "int", }},
	276: {Name: "tee", Args: []string{"fdin", "fdout", "len", "flags", }, ArgTypes: []string{"int", "int", "size_t", "unsigned int", }},
	234: {Name: "tgkill", Args: []string{"tgid", "pid", "sig", }, ArgTypes: []string{"pid_t", "pid_t", "int", }},
	201: {Name: "time", Args: []string{"tloc", }, ArgTypes: []string{"__kernel_old_time_t *", }},
	222: {Name: "timer_create", Args: []string{"which_clock", "timer_event_spec", "created_timer_id", }, ArgTypes: []string{"const clockid_t", "struct sigevent *", "timer_t *", }},
	226: {Name: "timer_delete", Args: []string{"timer_id", }, ArgTypes: []string{"timer_t", }},
	225: {Name: "timer_getoverrun", Args: []string{"timer_id", }, ArgTypes: []string{"timer_t", }},
	224: {Name: "timer_gettime", Args: []string{"timer_id", "setting", }, ArgTypes: []string{"timer_t", "struct __kernel_itimerspec *", }},
	223: {Name: "timer_settime", Args: []string{"timer_id", "flags", "new_setting", "old_setting", }, ArgTypes: []string{"timer_t", "int", "const struct __kernel_itimerspec *", "struct __kernel_itimerspec *", }},
	283: {Name: "timerfd_create", Args: []string{"clockid", "flags", }, ArgTypes: []string{"int", "int", }},
	287: {Name: "timerfd_gettime", Args: []string{"ufd", "otmr", }, ArgTypes: []string{"int", "struct __kernel_itimerspec *", }},
	286: {Name: "timerfd_settime", Args: []string{"ufd", "flags", "utmr", "otmr", }, ArgTypes: []string{"int", "int", "const struct __kernel_itimerspec *", "struct __kernel_itimerspec *", }},
	100: {Name: "times", Args: []string{"tbuf", }, ArgTypes: []string{"struct tms *", }},
	200: {Name: "tkill", Args: []string{"pid", "sig", }, ArgTypes: []string{"pid_t", "int", }},
	76: {Name: "truncate", Args: []string{"path", "length", }, ArgTypes: []string{"const char *", "long", }},
	95: {Name: "umask", Args: []string{"mask", }, ArgTypes: []string{"int", }},
	87: {Name: "unlink", Args: []string{"pathname", }, ArgTypes: []string{"const char *", }},
	263: {Name: "unlinkat", Args: []string{"dfd", "pathname", "flag", }, ArgTypes: []string{"int", "const char *", "int", }},
	272: {Name: "unshare", Args: []string{"unshare_flags", }, ArgTypes: []string{"unsigned long", }},
	335: {Name: "uretprobe", Args: []string{}, ArgTypes: []string{}},
	323: {Name: "userfaultfd", Args: []string{"flags", }, ArgTypes: []string{"int", }},
	136: {Name: "ustat", Args: []string{"dev", "ubuf", }, ArgTypes: []string{"unsigned", "struct ustat *", }},
	132: {Name: "utime", Args: []string{"filename", "times", }, ArgTypes: []string{"char *", "struct utimbuf *", }},
	280: {Name: "utimensat", Args: []string{"dfd", "filename", "utimes", "flags", }, ArgTypes: []string{"int", "const char *", "struct __kernel_timespec *", "int", }},
	235: {Name: "utimes", Args: []string{"filename", "utimes", }, ArgTypes: []string{"char *", "struct __kernel_old_timeval *", }},
	58: {Name: "vfork", Args: []string{}, ArgTypes: []string{}},
	153: {Name: "vhangup", Args: []string{}, ArgTypes: []string{}},
	278: {Name: "vmsplice", Args: []string{"fd", "uiov", "nr_segs", "flags", }, ArgTypes: []string{"int", "const struct iovec *", "unsigned long", "unsigned int", }},
	61: {Name: "wait4", Args: []string{"upid", "stat_addr", "options", "ru", }, ArgTypes: []string{"pid_t", "int *", "int", "struct rusage *", }},
	247: {Name: "waitid", Args: []string{"which", "upid", "infop", "options", "ru", }, ArgTypes: []string{"int", "pid_t", "struct siginfo *", "int", "struct rusage *", }},
	1: {Name: "write", Args: []string{"fd", "buf", "count", }, ArgTypes: []string{"unsigned int", "const char *", "size_t", }},
	20: {Name: "writev", Args: []string{"fd", "vec", "vlen", }, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", }},
}
