package meta
type Syscall struct { Name string; Args []string; ArgTypes []string }
var SyscallTable = map[uint32]Syscall{
	0: {Name: "read", Args: []string{"fd", "buf", "count"}, ArgTypes: []string{"int", "char *", "size_t"}},
	1: {Name: "write", Args: []string{"fd", "buf", "count"}, ArgTypes: []string{"int", "const char *", "size_t"}},
	2: {Name: "open", Args: []string{"filename", "flags", "mode"}, ArgTypes: []string{"const char *", "int", "umode_t"}},
	3: {Name: "close", Args: []string{"fd"}, ArgTypes: []string{"int"}},
	4: {Name: "stat", Args: []string{"filename", "statbuf"}, ArgTypes: []string{"const char *", "struct stat *"}},
	5: {Name: "fstat", Args: []string{"fd", "statbuf"}, ArgTypes: []string{"int", "struct stat *"}},
	6: {Name: "lstat", Args: []string{"filename", "statbuf"}, ArgTypes: []string{"const char *", "struct stat *"}},
	7: {Name: "poll", Args: []string{"ufds", "nfds", "timeout"}, ArgTypes: []string{"struct pollfd *", "unsigned int", "int"}},
	9: {Name: "mmap", Args: []string{"addr", "len", "prot", "flags", "fd", "off"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	10: {Name: "mprotect", Args: []string{"start", "len", "prot"}, ArgTypes: []string{"unsigned long", "size_t", "unsigned long"}},
	11: {Name: "munmap", Args: []string{"addr", "len"}, ArgTypes: []string{"unsigned long", "size_t"}},
	12: {Name: "brk", Args: []string{"brk"}, ArgTypes: []string{"unsigned long"}},
	16: {Name: "ioctl", Args: []string{"fd", "cmd", "arg"}, ArgTypes: []string{"int", "unsigned long", "unsigned long"}},
	21: {Name: "access", Args: []string{"filename", "mode"}, ArgTypes: []string{"const char *", "int"}},
	23: {Name: "select", Args: []string{"n", "inp", "outp", "exp", "tvp"}, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct timeval *"}},
	39: {Name: "getpid", Args: []string{}, ArgTypes: []string{}},
	42: {Name: "connect", Args: []string{"fd", "uservaddr", "addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int"}},
	43: {Name: "accept", Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	44: {Name: "sendto", Args: []string{"fd", "buff", "len", "flags", "addr", "addr_len"}, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int"}},
	45: {Name: "recvfrom", Args: []string{"fd", "ubuf", "size", "flags", "addr", "addr_len"}, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int *"}},
	49: {Name: "bind", Args: []string{"fd", "umyaddr", "addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int"}},
	51: {Name: "getsockname", Args: []string{"fd", "usockaddr", "usockaddr_len"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	52: {Name: "getpeername", Args: []string{"fd", "usockaddr", "usockaddr_len"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	79: {Name: "rmdir", Args: []string{"pathname"}, ArgTypes: []string{"const char *"}},
	80: {Name: "chdir", Args: []string{"filename"}, ArgTypes: []string{"const char *"}},
	81: {Name: "fchdir", Args: []string{"fd"}, ArgTypes: []string{"int"}},
	82: {Name: "rename", Args: []string{"oldname", "newname"}, ArgTypes: []string{"const char *", "const char *"}},
	83: {Name: "mkdir", Args: []string{"pathname", "mode"}, ArgTypes: []string{"const char *", "umode_t"}},
	87: {Name: "unlink", Args: []string{"pathname"}, ArgTypes: []string{"const char *"}},
	89: {Name: "readlink", Args: []string{"path", "buf", "bufsiz"}, ArgTypes: []string{"const char *", "char *", "int"}},
	90: {Name: "chmod", Args: []string{"filename", "mode"}, ArgTypes: []string{"const char *", "umode_t"}},
	92: {Name: "chown", Args: []string{"filename", "user", "group"}, ArgTypes: []string{"const char *", "uid_t", "gid_t"}},
	93: {Name: "fchown", Args: []string{"fd", "user", "group"}, ArgTypes: []string{"int", "uid_t", "gid_t"}},
	94: {Name: "lchown", Args: []string{"filename", "user", "group"}, ArgTypes: []string{"const char *", "uid_t", "gid_t"}},
	158: {Name: "arch_prctl", Args: []string{"option", "arg2"}, ArgTypes: []string{"int", "unsigned long"}},
	159: {Name: "adjtimex", Args: []string{"txc_p"}, ArgTypes: []string{"struct timex *"}},
	161: {Name: "chroot", Args: []string{"filename"}, ArgTypes: []string{"const char *"}},
	232: {Name: "epoll_wait", Args: []string{"epfd", "events", "maxevents", "timeout"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "int"}},
	233: {Name: "epoll_ctl", Args: []string{"epfd", "op", "fd", "event"}, ArgTypes: []string{"int", "int", "int", "struct epoll_event *"}},
	257: {Name: "openat", Args: []string{"dfd", "filename", "flags", "mode"}, ArgTypes: []string{"int", "const char *", "int", "umode_t"}},
	258: {Name: "mkdirat", Args: []string{"dfd", "pathname", "mode"}, ArgTypes: []string{"int", "const char *", "umode_t"}},
	260: {Name: "fchownat", Args: []string{"dfd", "filename", "user", "group", "flag"}, ArgTypes: []string{"int", "const char *", "uid_t", "gid_t", "int"}},
	262: {Name: "newfstatat", Args: []string{"dfd", "filename", "statbuf", "flag"}, ArgTypes: []string{"int", "const char *", "struct stat *", "int"}},
	263: {Name: "unlinkat", Args: []string{"dfd", "pathname", "flag"}, ArgTypes: []string{"int", "const char *", "int"}},
	264: {Name: "renameat", Args: []string{"olddfd", "oldname", "newdfd", "newname"}, ArgTypes: []string{"int", "const char *", "int", "const char *"}},
	266: {Name: "readlinkat", Args: []string{"dfd", "pathname", "buf", "bufsiz"}, ArgTypes: []string{"int", "const char *", "char *", "int"}},
	267: {Name: "chmodat", Args: []string{"dfd", "filename", "mode"}, ArgTypes: []string{"int", "const char *", "umode_t"}},
	269: {Name: "faccessat", Args: []string{"dfd", "filename", "mode"}, ArgTypes: []string{"int", "const char *", "int"}},
	270: {Name: "pselect6", Args: []string{"n", "inp", "outp", "exp", "tsp", "sig"}, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct timespec *", "void *"}},
	271: {Name: "ppoll", Args: []string{"ufds", "nfds", "tsp", "sigmask", "sigsetsize"}, ArgTypes: []string{"struct pollfd *", "unsigned int", "struct timespec *", "const sigset_t *", "size_t"}},
	281: {Name: "epoll_pwait", Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "int", "const sigset_t *", "size_t"}},
	288: {Name: "accept4", Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen", "flags"}, ArgTypes: []string{"int", "struct sockaddr *", "int *", "int"}},
	291: {Name: "epoll_create1", Args: []string{"flags"}, ArgTypes: []string{"int"}},
	316: {Name: "renameat2", Args: []string{"olddfd", "oldname", "newdfd", "newname", "flags"}, ArgTypes: []string{"int", "const char *", "int", "const char *", "unsigned int"}},
	439: {Name: "faccessat2", Args: []string{"dfd", "filename", "mode", "flags"}, ArgTypes: []string{"int", "const char *", "int", "int"}},
	441: {Name: "epoll_pwait2", Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "struct timespec *", "const sigset_t *", "size_t"}},
}
