package meta
type XlatVal struct { Val uint64; Str string }
type XlatTable struct { Entries []XlatVal; Prefix string }
var XlatTables = map[string]XlatTable{
	"access_modes": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 0, Str: "F_OK"},
			{Val: 4, Str: "R_OK"},
			{Val: 2, Str: "W_OK"},
			{Val: 1, Str: "X_OK"},
		},
	},
	"addrfams": {
		Prefix: "AF_",
		Entries: []XlatVal{
			{Val: 0, Str: "AF_UNSPEC"},
			{Val: 1, Str: "AF_UNIX"},
			{Val: 2, Str: "AF_INET"},
			{Val: 3, Str: "AF_AX25"},
			{Val: 4, Str: "AF_IPX"},
			{Val: 5, Str: "AF_APPLETALK"},
			{Val: 6, Str: "AF_NETROM"},
			{Val: 7, Str: "AF_BRIDGE"},
			{Val: 8, Str: "AF_ATMPVC"},
			{Val: 9, Str: "AF_X25"},
			{Val: 10, Str: "AF_INET6"},
			{Val: 11, Str: "AF_ROSE"},
			{Val: 12, Str: "AF_DECnet"},
			{Val: 13, Str: "AF_NETBEUI"},
			{Val: 14, Str: "AF_SECURITY"},
			{Val: 15, Str: "AF_KEY"},
			{Val: 16, Str: "AF_NETLINK"},
			{Val: 17, Str: "AF_PACKET"},
			{Val: 18, Str: "AF_ASH"},
			{Val: 19, Str: "AF_ECONET"},
			{Val: 20, Str: "AF_ATMSVC"},
			{Val: 21, Str: "AF_RDS"},
			{Val: 22, Str: "AF_SNA"},
			{Val: 23, Str: "AF_IRDA"},
			{Val: 24, Str: "AF_PPPOX"},
			{Val: 25, Str: "AF_WANPIPE"},
			{Val: 26, Str: "AF_LLC"},
			{Val: 27, Str: "AF_IB"},
			{Val: 28, Str: "AF_MPLS"},
			{Val: 29, Str: "AF_CAN"},
			{Val: 30, Str: "AF_TIPC"},
			{Val: 31, Str: "AF_BLUETOOTH"},
			{Val: 32, Str: "AF_IUCV"},
			{Val: 33, Str: "AF_RXRPC"},
			{Val: 34, Str: "AF_ISDN"},
			{Val: 35, Str: "AF_PHONET"},
			{Val: 36, Str: "AF_IEEE802154"},
			{Val: 37, Str: "AF_CAIF"},
			{Val: 38, Str: "AF_ALG"},
			{Val: 39, Str: "AF_NFC"},
			{Val: 40, Str: "AF_VSOCK"},
			{Val: 41, Str: "AF_KCM"},
			{Val: 42, Str: "AF_QIPCRTR"},
			{Val: 43, Str: "AF_SMC"},
			{Val: 44, Str: "AF_XDP"},
			{Val: 45, Str: "AF_MCTP"},
		},
	},
	"adjtimex_status": {
		Prefix: "STA_",
		Entries: []XlatVal{
			{Val: 1, Str: "STA_PLL"},
			{Val: 2, Str: "STA_PPSFREQ"},
			{Val: 4, Str: "STA_PPSTIME"},
			{Val: 8, Str: "STA_FLL"},
			{Val: 16, Str: "STA_INS"},
			{Val: 32, Str: "STA_DEL"},
			{Val: 64, Str: "STA_UNSYNC"},
			{Val: 128, Str: "STA_FREQHOLD"},
			{Val: 256, Str: "STA_PPSSIGNAL"},
			{Val: 512, Str: "STA_PPSJITTER"},
			{Val: 1024, Str: "STA_PPSWANDER"},
			{Val: 2048, Str: "STA_PPSERROR"},
			{Val: 4096, Str: "STA_CLOCKERR"},
			{Val: 8192, Str: "STA_NANO"},
			{Val: 16384, Str: "STA_MODE"},
			{Val: 32768, Str: "STA_CLK"},
		},
	},
	"archvals": {
		Prefix: "ARCH_",
		Entries: []XlatVal{
			{Val: 4097, Str: "ARCH_SET_GS"},
			{Val: 4098, Str: "ARCH_SET_FS"},
			{Val: 4099, Str: "ARCH_GET_FS"},
			{Val: 4100, Str: "ARCH_GET_GS"},
			{Val: 4113, Str: "ARCH_GET_CPUID"},
			{Val: 4114, Str: "ARCH_SET_CPUID"},
			{Val: 4129, Str: "ARCH_GET_XCOMP_SUPP"},
			{Val: 4130, Str: "ARCH_GET_XCOMP_PERM"},
			{Val: 4131, Str: "ARCH_REQ_XCOMP_PERM"},
			{Val: 4132, Str: "ARCH_GET_XCOMP_GUEST_PERM"},
			{Val: 4133, Str: "ARCH_REQ_XCOMP_GUEST_PERM"},
			{Val: 8193, Str: "ARCH_MAP_VDSO_X32"},
			{Val: 8194, Str: "ARCH_MAP_VDSO_32"},
			{Val: 8195, Str: "ARCH_MAP_VDSO_64"},
			{Val: 16385, Str: "ARCH_GET_UNTAG_MASK"},
			{Val: 16386, Str: "ARCH_ENABLE_TAGGED_ADDR"},
			{Val: 16387, Str: "ARCH_GET_MAX_TAG_BITS"},
			{Val: 16388, Str: "ARCH_FORCE_TAGGED_SVA"},
			{Val: 20481, Str: "ARCH_SHSTK_ENABLE"},
			{Val: 20482, Str: "ARCH_SHSTK_DISABLE"},
			{Val: 20483, Str: "ARCH_SHSTK_LOCK"},
			{Val: 20484, Str: "ARCH_SHSTK_UNLOCK"},
			{Val: 20485, Str: "ARCH_SHSTK_STATUS"},
		},
	},
	"bpf_commands": {
		Prefix: "BPF_",
		Entries: []XlatVal{
		},
	},
	"clocknames": {
		Prefix: "CLOCK_",
		Entries: []XlatVal{
			{Val: 0, Str: "CLOCK_REALTIME"},
			{Val: 1, Str: "CLOCK_MONOTONIC"},
			{Val: 2, Str: "CLOCK_PROCESS_CPUTIME_ID"},
			{Val: 3, Str: "CLOCK_THREAD_CPUTIME_ID"},
			{Val: 4, Str: "CLOCK_MONOTONIC_RAW"},
			{Val: 5, Str: "CLOCK_REALTIME_COARSE"},
			{Val: 6, Str: "CLOCK_MONOTONIC_COARSE"},
			{Val: 7, Str: "CLOCK_BOOTTIME"},
			{Val: 8, Str: "CLOCK_REALTIME_ALARM"},
			{Val: 9, Str: "CLOCK_BOOTTIME_ALARM"},
			{Val: 10, Str: "CLOCK_SGI_CYCLE"},
			{Val: 11, Str: "CLOCK_TAI"},
		},
	},
	"epollctls": {
		Prefix: "EPOLL_CTL_",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLL_CTL_ADD"},
			{Val: 2, Str: "EPOLL_CTL_DEL"},
			{Val: 3, Str: "EPOLL_CTL_MOD"},
		},
	},
	"epollevents": {
		Prefix: "EPOLL",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLLIN"},
			{Val: 2, Str: "EPOLLPRI"},
			{Val: 4, Str: "EPOLLOUT"},
			{Val: 8, Str: "EPOLLERR"},
			{Val: 16, Str: "EPOLLHUP"},
			{Val: 64, Str: "EPOLLRDNORM"},
			{Val: 128, Str: "EPOLLRDBAND"},
			{Val: 256, Str: "EPOLLWRNORM"},
			{Val: 512, Str: "EPOLLWRBAND"},
			{Val: 1024, Str: "EPOLLMSG"},
			{Val: 8192, Str: "EPOLLRDHUP"},
			{Val: 268435456, Str: "EPOLLEXCLUSIVE"},
			{Val: 536870912, Str: "EPOLLWAKEUP"},
			{Val: 1073741824, Str: "EPOLLONESHOT"},
			{Val: 2147483648, Str: "EPOLLET"},
		},
	},
	"epollflags": {
		Prefix: "EPOLL_",
		Entries: []XlatVal{
			{Val: 524288, Str: "EPOLL_CLOEXEC"},
		},
	},
	"open_access_modes": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 0, Str: "O_RDONLY"},
			{Val: 1, Str: "O_WRONLY"},
			{Val: 2, Str: "O_RDWR"},
			{Val: 3, Str: "O_ACCMODE"},
		},
	},
	"open_mode_flags": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 64, Str: "O_CREAT"},
			{Val: 128, Str: "O_EXCL"},
			{Val: 256, Str: "O_NOCTTY"},
			{Val: 512, Str: "O_TRUNC"},
			{Val: 1024, Str: "O_APPEND"},
			{Val: 2048, Str: "O_NONBLOCK"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4096, Str: "O_DSYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 131072, Str: "O_NOFOLLOW"},
			{Val: 262144, Str: "O_NOATIME"},
			{Val: 524288, Str: "O_CLOEXEC"},
			{Val: 2097152, Str: "O_PATH"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 4259840, Str: "__O_TMPFILE"},
			{Val: 65536, Str: "O_DIRECTORY"},
			{Val: 8192, Str: "FASYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4194304, Str: "__O_TMPFILE"},
			{Val: 1048576, Str: "__O_SYNC"},
			{Val: 32768, Str: "O_LARGEFILE"},
		},
	},
	"pollflags": {
		Prefix: "POLL",
		Entries: []XlatVal{
			{Val: 1, Str: "POLLIN"},
			{Val: 2, Str: "POLLPRI"},
			{Val: 4, Str: "POLLOUT"},
			{Val: 8, Str: "POLLERR"},
			{Val: 16, Str: "POLLHUP"},
			{Val: 32, Str: "POLLNVAL"},
			{Val: 64, Str: "POLLRDNORM"},
			{Val: 128, Str: "POLLRDBAND"},
			{Val: 256, Str: "POLLWRNORM"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 8192, Str: "POLLRDHUP"},
			{Val: 8192, Str: "POLLRDHUP"},
		},
	},
	"sock_type_flags": {
		Prefix: "SOCK_",
		Entries: []XlatVal{
			{Val: 524288, Str: "SOCK_CLOEXEC"},
			{Val: 2048, Str: "SOCK_NONBLOCK"},
		},
	},
	"x86_xfeatures": {
		Prefix: "XFEATURE_MASK_",
		Entries: []XlatVal{
		},
	},
}
var SyscallArgXlatMap = map[string]map[string]string{
	"access": {
		"mode": "access_modes",
	},
	"faccessat": {
		"mode": "access_modes",
	},
	"openat": {
		"flags": "open_mode_flags",
	},
	"epoll_ctl": {
		"op": "epollctls",
	},
	"accept4": {
		"flags": "sock_type_flags",
	},
	"bpf": {
		"cmd": "bpf_commands",
	},
	"clock_nanosleep": {
		"which_clock": "clocknames",
	},
	"open": {
		"flags": "open_mode_flags",
	},
	"arch_prctl": {
		"option": "archvals",
	},
	"epoll_create1": {
		"flags": "epollflags",
	},
	"faccessat2": {
		"mode": "access_modes",
	},
	"clock_adjtime": {
		"which_clock": "clocknames",
	},
	"clock_settime": {
		"which_clock": "clocknames",
	},
}
