package meta
type XlatVal struct { Val uint64; Str string }
type XlatTable struct { Prefix string; Entries []XlatVal }
var XlatTables = map[string]XlatTable{
	"access_modes": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 0, Str: "F_OK"},
			{Val: 4, Str: "R_OK"},
			{Val: 2, Str: "W_OK"},
			{Val: 1, Str: "X_OK"},
		},
	},
	"addrfams": {
		Prefix: "AF_",
		Entries: []XlatVal{
			{Val: 0, Str: "AF_UNSPEC"},
			{Val: 1, Str: "AF_UNIX"},
			{Val: 2, Str: "AF_INET"},
			{Val: 3, Str: "AF_AX25"},
			{Val: 4, Str: "AF_IPX"},
			{Val: 5, Str: "AF_APPLETALK"},
			{Val: 6, Str: "AF_NETROM"},
			{Val: 7, Str: "AF_BRIDGE"},
			{Val: 8, Str: "AF_ATMPVC"},
			{Val: 9, Str: "AF_X25"},
			{Val: 10, Str: "AF_INET6"},
			{Val: 11, Str: "AF_ROSE"},
			{Val: 12, Str: "AF_DECnet"},
			{Val: 13, Str: "AF_NETBEUI"},
			{Val: 14, Str: "AF_SECURITY"},
			{Val: 15, Str: "AF_KEY"},
			{Val: 16, Str: "AF_NETLINK"},
			{Val: 17, Str: "AF_PACKET"},
			{Val: 18, Str: "AF_ASH"},
			{Val: 19, Str: "AF_ECONET"},
			{Val: 20, Str: "AF_ATMSVC"},
			{Val: 21, Str: "AF_RDS"},
			{Val: 22, Str: "AF_SNA"},
			{Val: 23, Str: "AF_IRDA"},
			{Val: 24, Str: "AF_PPPOX"},
			{Val: 25, Str: "AF_WANPIPE"},
			{Val: 26, Str: "AF_LLC"},
			{Val: 27, Str: "AF_IB"},
			{Val: 28, Str: "AF_MPLS"},
			{Val: 29, Str: "AF_CAN"},
			{Val: 30, Str: "AF_TIPC"},
			{Val: 31, Str: "AF_BLUETOOTH"},
			{Val: 32, Str: "AF_IUCV"},
			{Val: 33, Str: "AF_RXRPC"},
			{Val: 34, Str: "AF_ISDN"},
			{Val: 35, Str: "AF_PHONET"},
			{Val: 36, Str: "AF_IEEE802154"},
			{Val: 37, Str: "AF_CAIF"},
			{Val: 38, Str: "AF_ALG"},
			{Val: 39, Str: "AF_NFC"},
			{Val: 40, Str: "AF_VSOCK"},
			{Val: 41, Str: "AF_KCM"},
			{Val: 42, Str: "AF_QIPCRTR"},
			{Val: 43, Str: "AF_SMC"},
			{Val: 44, Str: "AF_XDP"},
			{Val: 45, Str: "AF_MCTP"},
		},
	},
	"adjtimex_status": {
		Prefix: "STA_",
		Entries: []XlatVal{
			{Val: 1, Str: "STA_PLL"},
			{Val: 2, Str: "STA_PPSFREQ"},
			{Val: 4, Str: "STA_PPSTIME"},
			{Val: 8, Str: "STA_FLL"},
			{Val: 16, Str: "STA_INS"},
			{Val: 32, Str: "STA_DEL"},
			{Val: 64, Str: "STA_UNSYNC"},
			{Val: 128, Str: "STA_FREQHOLD"},
			{Val: 256, Str: "STA_PPSSIGNAL"},
			{Val: 512, Str: "STA_PPSJITTER"},
			{Val: 1024, Str: "STA_PPSWANDER"},
			{Val: 2048, Str: "STA_PPSERROR"},
			{Val: 4096, Str: "STA_CLOCKERR"},
			{Val: 8192, Str: "STA_NANO"},
			{Val: 16384, Str: "STA_MODE"},
			{Val: 32768, Str: "STA_CLK"},
		},
	},
	"archvals": {
		Prefix: "ARCH_",
		Entries: []XlatVal{
			{Val: 4097, Str: "ARCH_SET_GS"},
			{Val: 4098, Str: "ARCH_SET_FS"},
			{Val: 4099, Str: "ARCH_GET_FS"},
			{Val: 4100, Str: "ARCH_GET_GS"},
			{Val: 4113, Str: "ARCH_GET_CPUID"},
			{Val: 4114, Str: "ARCH_SET_CPUID"},
			{Val: 4129, Str: "ARCH_GET_XCOMP_SUPP"},
			{Val: 4130, Str: "ARCH_GET_XCOMP_PERM"},
			{Val: 4131, Str: "ARCH_REQ_XCOMP_PERM"},
			{Val: 4132, Str: "ARCH_GET_XCOMP_GUEST_PERM"},
			{Val: 4133, Str: "ARCH_REQ_XCOMP_GUEST_PERM"},
			{Val: 8193, Str: "ARCH_MAP_VDSO_X32"},
			{Val: 8194, Str: "ARCH_MAP_VDSO_32"},
			{Val: 8195, Str: "ARCH_MAP_VDSO_64"},
			{Val: 16385, Str: "ARCH_GET_UNTAG_MASK"},
			{Val: 16386, Str: "ARCH_ENABLE_TAGGED_ADDR"},
			{Val: 16387, Str: "ARCH_GET_MAX_TAG_BITS"},
			{Val: 16388, Str: "ARCH_FORCE_TAGGED_SVA"},
			{Val: 20481, Str: "ARCH_SHSTK_ENABLE"},
			{Val: 20482, Str: "ARCH_SHSTK_DISABLE"},
			{Val: 20483, Str: "ARCH_SHSTK_LOCK"},
			{Val: 20484, Str: "ARCH_SHSTK_UNLOCK"},
			{Val: 20485, Str: "ARCH_SHSTK_STATUS"},
		},
	},
	"bpf_commands": {
		Prefix: "BPF_",
		Entries: []XlatVal{
			{Val: 0, Str: "BPF_MAP_CREATE"},
			{Val: 1, Str: "BPF_MAP_LOOKUP_ELEM"},
			{Val: 2, Str: "BPF_MAP_UPDATE_ELEM"},
			{Val: 3, Str: "BPF_MAP_DELETE_ELEM"},
			{Val: 4, Str: "BPF_MAP_GET_NEXT_KEY"},
			{Val: 5, Str: "BPF_PROG_LOAD"},
			{Val: 6, Str: "BPF_OBJ_PIN"},
			{Val: 7, Str: "BPF_OBJ_GET"},
			{Val: 8, Str: "BPF_PROG_ATTACH"},
			{Val: 9, Str: "BPF_PROG_DETACH"},
			{Val: 10, Str: "BPF_PROG_TEST_RUN"},
			{Val: 11, Str: "BPF_PROG_GET_NEXT_ID"},
			{Val: 12, Str: "BPF_MAP_GET_NEXT_ID"},
			{Val: 13, Str: "BPF_PROG_GET_FD_BY_ID"},
			{Val: 14, Str: "BPF_MAP_GET_FD_BY_ID"},
			{Val: 15, Str: "BPF_OBJ_GET_INFO_BY_FD"},
			{Val: 16, Str: "BPF_PROG_QUERY"},
			{Val: 17, Str: "BPF_RAW_TRACEPOINT_OPEN"},
			{Val: 18, Str: "BPF_BTF_LOAD"},
			{Val: 19, Str: "BPF_BTF_GET_FD_BY_ID"},
			{Val: 20, Str: "BPF_TASK_FD_QUERY"},
			{Val: 21, Str: "BPF_MAP_LOOKUP_AND_DELETE_ELEM"},
			{Val: 22, Str: "BPF_MAP_FREEZE"},
			{Val: 23, Str: "BPF_BTF_GET_NEXT_ID"},
			{Val: 24, Str: "BPF_MAP_LOOKUP_BATCH"},
			{Val: 25, Str: "BPF_MAP_LOOKUP_AND_DELETE_BATCH"},
			{Val: 26, Str: "BPF_MAP_UPDATE_BATCH"},
			{Val: 27, Str: "BPF_MAP_DELETE_BATCH"},
			{Val: 28, Str: "BPF_LINK_CREATE"},
			{Val: 29, Str: "BPF_LINK_UPDATE"},
			{Val: 30, Str: "BPF_LINK_GET_FD_BY_ID"},
			{Val: 31, Str: "BPF_LINK_GET_NEXT_ID"},
			{Val: 32, Str: "BPF_ENABLE_STATS"},
			{Val: 33, Str: "BPF_ITER_CREATE"},
			{Val: 34, Str: "BPF_LINK_DETACH"},
			{Val: 35, Str: "BPF_PROG_BIND_MAP"},
			{Val: 36, Str: "BPF_TOKEN_CREATE"},
			{Val: 37, Str: "BPF_PROG_STREAM_READ_BY_FD"},
			{Val: 38, Str: "BPF_PROG_ASSOC_STRUCT_OPS"},
		},
	},
	"bpf_map_flags": {
		Prefix: "BPF_F_",
		Entries: []XlatVal{
			{Val: 1, Str: "BPF_F_NO_PREALLOC"},
			{Val: 8192, Str: "BPF_F_LINK"},
		},
	},
	"bpf_map_types": {
		Prefix: "BPF_MAP_TYPE_",
		Entries: []XlatVal{
			{Val: 0, Str: "BPF_MAP_TYPE_UNSPEC"},
			{Val: 1, Str: "BPF_MAP_TYPE_HASH"},
			{Val: 2, Str: "BPF_MAP_TYPE_ARRAY"},
			{Val: 3, Str: "BPF_MAP_TYPE_PROG_ARRAY"},
			{Val: 4, Str: "BPF_MAP_TYPE_PERF_EVENT_ARRAY"},
			{Val: 5, Str: "BPF_MAP_TYPE_PERCPU_HASH"},
			{Val: 6, Str: "BPF_MAP_TYPE_PERCPU_ARRAY"},
			{Val: 7, Str: "BPF_MAP_TYPE_STACK_TRACE"},
			{Val: 8, Str: "BPF_MAP_TYPE_CGROUP_ARRAY"},
			{Val: 9, Str: "BPF_MAP_TYPE_LRU_HASH"},
			{Val: 10, Str: "BPF_MAP_TYPE_LRU_PERCPU_HASH"},
			{Val: 11, Str: "BPF_MAP_TYPE_LPM_TRIE"},
			{Val: 12, Str: "BPF_MAP_TYPE_ARRAY_OF_MAPS"},
			{Val: 13, Str: "BPF_MAP_TYPE_HASH_OF_MAPS"},
			{Val: 14, Str: "BPF_MAP_TYPE_DEVMAP"},
			{Val: 15, Str: "BPF_MAP_TYPE_SOCKMAP"},
			{Val: 16, Str: "BPF_MAP_TYPE_CPUMAP"},
			{Val: 17, Str: "BPF_MAP_TYPE_XSKMAP"},
			{Val: 18, Str: "BPF_MAP_TYPE_SOCKHASH"},
			{Val: 19, Str: "BPF_MAP_TYPE_CGROUP_STORAGE"},
			{Val: 20, Str: "BPF_MAP_TYPE_REUSEPORT_SOCKARRAY"},
			{Val: 21, Str: "BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE"},
			{Val: 22, Str: "BPF_MAP_TYPE_QUEUE"},
			{Val: 23, Str: "BPF_MAP_TYPE_STACK"},
			{Val: 24, Str: "BPF_MAP_TYPE_SK_STORAGE"},
			{Val: 25, Str: "BPF_MAP_TYPE_DEVMAP_HASH"},
			{Val: 26, Str: "BPF_MAP_TYPE_STRUCT_OPS"},
			{Val: 27, Str: "BPF_MAP_TYPE_RINGBUF"},
			{Val: 28, Str: "BPF_MAP_TYPE_INODE_STORAGE"},
			{Val: 29, Str: "BPF_MAP_TYPE_TASK_STORAGE"},
			{Val: 30, Str: "BPF_MAP_TYPE_BLOOM_FILTER"},
			{Val: 31, Str: "BPF_MAP_TYPE_USER_RINGBUF"},
			{Val: 32, Str: "BPF_MAP_TYPE_CGRP_STORAGE"},
			{Val: 33, Str: "BPF_MAP_TYPE_ARENA"},
			{Val: 34, Str: "BPF_MAP_TYPE_INSN_ARRAY"},
		},
	},
	"clocknames": {
		Prefix: "CLOCK_",
		Entries: []XlatVal{
			{Val: 0, Str: "CLOCK_REALTIME"},
			{Val: 1, Str: "CLOCK_MONOTONIC"},
			{Val: 2, Str: "CLOCK_PROCESS_CPUTIME_ID"},
			{Val: 3, Str: "CLOCK_THREAD_CPUTIME_ID"},
			{Val: 4, Str: "CLOCK_MONOTONIC_RAW"},
			{Val: 5, Str: "CLOCK_REALTIME_COARSE"},
			{Val: 6, Str: "CLOCK_MONOTONIC_COARSE"},
			{Val: 7, Str: "CLOCK_BOOTTIME"},
			{Val: 8, Str: "CLOCK_REALTIME_ALARM"},
			{Val: 9, Str: "CLOCK_BOOTTIME_ALARM"},
			{Val: 10, Str: "CLOCK_SGI_CYCLE"},
			{Val: 11, Str: "CLOCK_TAI"},
		},
	},
	"clone3_flags": {
		Prefix: "CLONE_",
		Entries: []XlatVal{
			{Val: 128, Str: "CLONE_NEWTIME"},
		},
	},
	"clone_flags": {
		Prefix: "CLONE_",
		Entries: []XlatVal{
			{Val: 256, Str: "CLONE_VM"},
			{Val: 512, Str: "CLONE_FS"},
			{Val: 1024, Str: "CLONE_FILES"},
			{Val: 2048, Str: "CLONE_SIGHAND"},
			{Val: 4096, Str: "CLONE_PIDFD"},
			{Val: 8192, Str: "CLONE_PTRACE"},
			{Val: 16384, Str: "CLONE_VFORK"},
			{Val: 32768, Str: "CLONE_PARENT"},
			{Val: 65536, Str: "CLONE_THREAD"},
			{Val: 131072, Str: "CLONE_NEWNS"},
			{Val: 262144, Str: "CLONE_SYSVSEM"},
			{Val: 524288, Str: "CLONE_SETTLS"},
			{Val: 1048576, Str: "CLONE_PARENT_SETTID"},
			{Val: 2097152, Str: "CLONE_CHILD_CLEARTID"},
			{Val: 8388608, Str: "CLONE_UNTRACED"},
			{Val: 16777216, Str: "CLONE_CHILD_SETTID"},
			{Val: 33554432, Str: "CLONE_NEWCGROUP"},
			{Val: 67108864, Str: "CLONE_NEWUTS"},
			{Val: 134217728, Str: "CLONE_NEWIPC"},
			{Val: 268435456, Str: "CLONE_NEWUSER"},
			{Val: 536870912, Str: "CLONE_NEWPID"},
			{Val: 1073741824, Str: "CLONE_NEWNET"},
			{Val: 2147483648, Str: "CLONE_IO"},
		},
	},
	"epollctls": {
		Prefix: "EPOLL_CTL_",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLL_CTL_ADD"},
			{Val: 2, Str: "EPOLL_CTL_DEL"},
			{Val: 3, Str: "EPOLL_CTL_MOD"},
		},
	},
	"epollevents": {
		Prefix: "EPOLL",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLLIN"},
			{Val: 2, Str: "EPOLLPRI"},
			{Val: 4, Str: "EPOLLOUT"},
			{Val: 8, Str: "EPOLLERR"},
			{Val: 16, Str: "EPOLLHUP"},
			{Val: 0x00000020, Str: "EPOLLNVAL"},
			{Val: 64, Str: "EPOLLRDNORM"},
			{Val: 128, Str: "EPOLLRDBAND"},
			{Val: 256, Str: "EPOLLWRNORM"},
			{Val: 512, Str: "EPOLLWRBAND"},
			{Val: 1024, Str: "EPOLLMSG"},
			{Val: 8192, Str: "EPOLLRDHUP"},
			{Val: 268435456, Str: "EPOLLEXCLUSIVE"},
			{Val: 536870912, Str: "EPOLLWAKEUP"},
			{Val: 1073741824, Str: "EPOLLONESHOT"},
			{Val: 2147483648, Str: "EPOLLET"},
		},
	},
	"epollflags": {
		Prefix: "EPOLL_",
		Entries: []XlatVal{
			{Val: 524288, Str: "EPOLL_CLOEXEC"},
		},
	},
	"futexops": {
		Prefix: "FUTEX_",
		Entries: []XlatVal{
			{Val: 0, Str: "FUTEX_WAIT"},
			{Val: 1, Str: "FUTEX_WAKE"},
			{Val: 2, Str: "FUTEX_FD"},
			{Val: 3, Str: "FUTEX_REQUEUE"},
			{Val: 4, Str: "FUTEX_CMP_REQUEUE"},
			{Val: 5, Str: "FUTEX_WAKE_OP"},
			{Val: 6, Str: "FUTEX_LOCK_PI"},
			{Val: 7, Str: "FUTEX_UNLOCK_PI"},
			{Val: 8, Str: "FUTEX_TRYLOCK_PI"},
			{Val: 9, Str: "FUTEX_WAIT_BITSET"},
			{Val: 10, Str: "FUTEX_WAKE_BITSET"},
			{Val: 11, Str: "FUTEX_WAIT_REQUEUE_PI"},
			{Val: 12, Str: "FUTEX_CMP_REQUEUE_PI"},
			{Val: 13, Str: "FUTEX_LOCK_PI2"},
		},
	},
	"key_spec": {
		Prefix: "KEY_SPEC_",
		Entries: []XlatVal{
			{Val: 18446744073709551615, Str: "KEY_SPEC_THREAD_KEYRING"},
			{Val: 18446744073709551614, Str: "KEY_SPEC_PROCESS_KEYRING"},
			{Val: 18446744073709551613, Str: "KEY_SPEC_SESSION_KEYRING"},
			{Val: 18446744073709551612, Str: "KEY_SPEC_USER_KEYRING"},
			{Val: 18446744073709551611, Str: "KEY_SPEC_USER_SESSION_KEYRING"},
			{Val: 18446744073709551610, Str: "KEY_SPEC_GROUP_KEYRING"},
			{Val: 18446744073709551609, Str: "KEY_SPEC_REQKEY_AUTH_KEY"},
			{Val: 18446744073709551608, Str: "KEY_SPEC_REQUESTOR_KEYRING"},
		},
	},
	"madvise_cmds": {
		Prefix: "MADV_",
		Entries: []XlatVal{
			{Val: 0, Str: "MADV_NORMAL"},
			{Val: 1, Str: "MADV_RANDOM"},
			{Val: 2, Str: "MADV_SEQUENTIAL"},
			{Val: 3, Str: "MADV_WILLNEED"},
			{Val: 4, Str: "MADV_DONTNEED"},
			{Val: 4, Str: "MADV_DONTNEED"},
			{Val: 8, Str: "MADV_FREE"},
			{Val: 9, Str: "MADV_REMOVE"},
			{Val: 10, Str: "MADV_DONTFORK"},
			{Val: 11, Str: "MADV_DOFORK"},
			{Val: 20, Str: "MADV_COLD"},
			{Val: 21, Str: "MADV_PAGEOUT"},
			{Val: 22, Str: "MADV_POPULATE_READ"},
			{Val: 23, Str: "MADV_POPULATE_WRITE"},
			{Val: 24, Str: "MADV_DONTNEED_LOCKED"},
			{Val: 100, Str: "MADV_HWPOISON"},
			{Val: 101, Str: "MADV_SOFT_OFFLINE"},
			{Val: 102, Str: "MADV_GUARD_INSTALL"},
			{Val: 103, Str: "MADV_GUARD_REMOVE"},
		},
	},
	"mmap_flags": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 1, Str: "MAP_SHARED"},
			{Val: 2, Str: "MAP_PRIVATE"},
			{Val: 3, Str: "MAP_SHARED_VALIDATE"},
			{Val: 8, Str: "MAP_DROPPABLE"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 64, Str: "MAP_32BIT"},
			{Val: 64, Str: "MAP_32BIT"},
			{Val: 128, Str: "MAP_ABOVE4G"},
			{Val: 128, Str: "MAP_ABOVE4G"},
			{Val: 0x20, Str: "MAP_RENAME"},
			{Val: 0x20, Str: "MAP_RENAME"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 0x80000000, Str: "_MAP_NEW"},
			{Val: 0x80000000, Str: "_MAP_NEW"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 0x200, Str: "MAP_GROWSUP"},
			{Val: 0x200, Str: "MAP_GROWSUP"},
			{Val: 2048, Str: "MAP_DENYWRITE"},
			{Val: 2048, Str: "MAP_DENYWRITE"},
			{Val: 4096, Str: "MAP_EXECUTABLE"},
			{Val: 4096, Str: "MAP_EXECUTABLE"},
			{Val: 0x80, Str: "MAP_INHERIT"},
			{Val: 0x80, Str: "MAP_INHERIT"},
			{Val: 0x400, Str: "_MAP_INHERIT"},
			{Val: 0x400, Str: "_MAP_INHERIT"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 0x200, Str: "_MAP_HASSEMAPHORE"},
			{Val: 0x200, Str: "_MAP_HASSEMAPHORE"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 524288, Str: "MAP_SYNC"},
			{Val: 0x4000000, Str: "MAP_UNINITIALIZED"},
			{Val: 1048576, Str: "MAP_FIXED_NOREPLACE"},
			{Val: 1048576, Str: "MAP_FIXED_NOREPLACE"},
			{Val: 0x40, Str: "MAP_AUTOGROW"},
			{Val: 0x40, Str: "MAP_AUTOGROW"},
			{Val: 0x100, Str: "MAP_AUTORSRV"},
			{Val: 0x100, Str: "MAP_AUTORSRV"},
			{Val: 0x80, Str: "MAP_LOCAL"},
			{Val: 0x80, Str: "MAP_LOCAL"},
			{Val: 0x800, Str: "_MAP_UNALIGNED"},
			{Val: 0x800, Str: "_MAP_UNALIGNED"},
		},
	},
	"mmap_prot": {
		Prefix: "PROT_",
		Entries: []XlatVal{
			{Val: 0, Str: "PROT_NONE"},
			{Val: 1, Str: "PROT_READ"},
			{Val: 2, Str: "PROT_WRITE"},
			{Val: 4, Str: "PROT_EXEC"},
			{Val: 16777216, Str: "PROT_GROWSDOWN"},
			{Val: 33554432, Str: "PROT_GROWSUP"},
		},
	},
	"modetypes": {
		Prefix: "S_",
		Entries: []XlatVal{
			{Val: 32768, Str: "S_IFREG"},
			{Val: 49152, Str: "S_IFSOCK"},
			{Val: 4096, Str: "S_IFIFO"},
			{Val: 40960, Str: "S_IFLNK"},
			{Val: 16384, Str: "S_IFDIR"},
			{Val: 24576, Str: "S_IFBLK"},
			{Val: 8192, Str: "S_IFCHR"},
		},
	},
	"mount_flags": {
		Prefix: "MS_",
		Entries: []XlatVal{
			{Val: 1, Str: "MS_RDONLY"},
			{Val: 2, Str: "MS_NOSUID"},
			{Val: 4, Str: "MS_NODEV"},
			{Val: 8, Str: "MS_NOEXEC"},
			{Val: 16, Str: "MS_SYNCHRONOUS"},
			{Val: 32, Str: "MS_REMOUNT"},
			{Val: 64, Str: "MS_MANDLOCK"},
			{Val: 128, Str: "MS_DIRSYNC"},
			{Val: 256, Str: "MS_NOSYMFOLLOW"},
			{Val: 1024, Str: "MS_NOATIME"},
			{Val: 2048, Str: "MS_NODIRATIME"},
			{Val: 4096, Str: "MS_BIND"},
			{Val: 8192, Str: "MS_MOVE"},
			{Val: 16384, Str: "MS_REC"},
			{Val: 32768, Str: "MS_SILENT"},
			{Val: 65536, Str: "MS_POSIXACL"},
			{Val: 131072, Str: "MS_UNBINDABLE"},
			{Val: 262144, Str: "MS_PRIVATE"},
			{Val: 524288, Str: "MS_SLAVE"},
			{Val: 1048576, Str: "MS_SHARED"},
			{Val: 2097152, Str: "MS_RELATIME"},
			{Val: 4194304, Str: "MS_KERNMOUNT"},
			{Val: 8388608, Str: "MS_I_VERSION"},
			{Val: 16777216, Str: "MS_STRICTATIME"},
			{Val: 33554432, Str: "MS_LAZYTIME"},
			{Val: 67108864, Str: "MS_SUBMOUNT"},
			{Val: 134217728, Str: "MS_NOREMOTELOCK"},
			{Val: 268435456, Str: "MS_NOSEC"},
			{Val: 536870912, Str: "MS_BORN"},
			{Val: 1073741824, Str: "MS_ACTIVE"},
			{Val: 2147483648, Str: "MS_NOUSER"},
		},
	},
	"mremap_flags": {
		Prefix: "MREMAP_",
		Entries: []XlatVal{
			{Val: 1, Str: "MREMAP_MAYMOVE"},
			{Val: 2, Str: "MREMAP_FIXED"},
			{Val: 4, Str: "MREMAP_DONTUNMAP"},
		},
	},
	"open_access_modes": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 0, Str: "O_RDONLY"},
			{Val: 1, Str: "O_WRONLY"},
			{Val: 2, Str: "O_RDWR"},
			{Val: 3, Str: "O_ACCMODE"},
		},
	},
	"open_mode_flags": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 64, Str: "O_CREAT"},
			{Val: 128, Str: "O_EXCL"},
			{Val: 256, Str: "O_NOCTTY"},
			{Val: 512, Str: "O_TRUNC"},
			{Val: 1024, Str: "O_APPEND"},
			{Val: 2048, Str: "O_NONBLOCK"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4096, Str: "O_DSYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 131072, Str: "O_NOFOLLOW"},
			{Val: 262144, Str: "O_NOATIME"},
			{Val: 524288, Str: "O_CLOEXEC"},
			{Val: 2097152, Str: "O_PATH"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 4259840, Str: "__O_TMPFILE"},
			{Val: 65536, Str: "O_DIRECTORY"},
			{Val: 8192, Str: "FASYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4194304, Str: "__O_TMPFILE"},
			{Val: 1048576, Str: "__O_SYNC"},
			{Val: 32768, Str: "O_LARGEFILE"},
		},
	},
	"pollflags": {
		Prefix: "POLL",
		Entries: []XlatVal{
			{Val: 1, Str: "POLLIN"},
			{Val: 2, Str: "POLLPRI"},
			{Val: 4, Str: "POLLOUT"},
			{Val: 8, Str: "POLLERR"},
			{Val: 16, Str: "POLLHUP"},
			{Val: 32, Str: "POLLNVAL"},
			{Val: 64, Str: "POLLRDNORM"},
			{Val: 128, Str: "POLLRDBAND"},
			{Val: 256, Str: "POLLWRNORM"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 8192, Str: "POLLRDHUP"},
			{Val: 8192, Str: "POLLRDHUP"},
			{Val: 0x8000, Str: "POLL_BUSY_LOOP"},
		},
	},
	"sigprocmaskcmds": {
		Prefix: "SIG_",
		Entries: []XlatVal{
			{Val: 0, Str: "SIG_BLOCK"},
			{Val: 1, Str: "SIG_UNBLOCK"},
			{Val: 2, Str: "SIG_SETMASK"},
		},
	},
	"sock_type_flags": {
		Prefix: "SOCK_",
		Entries: []XlatVal{
			{Val: 524288, Str: "SOCK_CLOEXEC"},
			{Val: 2048, Str: "SOCK_NONBLOCK"},
		},
	},
	"umount_flags": {
		Prefix: "MNT_ UMOUNT_",
		Entries: []XlatVal{
			{Val: 1, Str: "MNT_FORCE"},
			{Val: 2, Str: "MNT_DETACH"},
			{Val: 4, Str: "MNT_EXPIRE"},
			{Val: 8, Str: "UMOUNT_NOFOLLOW"},
		},
	},
	"wait4_options": {
		Prefix: "W __W",
		Entries: []XlatVal{
			{Val: 1, Str: "WNOHANG"},
			{Val: 2, Str: "WUNTRACED"},
			{Val: 4, Str: "WEXITED"},
			{Val: 2, Str: "WSTOPPED"},
			{Val: 8, Str: "WCONTINUED"},
			{Val: 16777216, Str: "WNOWAIT"},
			{Val: 2147483648, Str: "__WCLONE"},
			{Val: 1073741824, Str: "__WALL"},
			{Val: 536870912, Str: "__WNOTHREAD"},
		},
	},
	"whence_codes": {
		Prefix: "SEEK_",
		Entries: []XlatVal{
			{Val: 0, Str: "SEEK_SET"},
			{Val: 1, Str: "SEEK_CUR"},
			{Val: 2, Str: "SEEK_END"},
			{Val: 3, Str: "SEEK_DATA"},
			{Val: 4, Str: "SEEK_HOLE"},
		},
	},
	"x86_xfeature_bits": {
		Prefix: "XFEATURE_",
		Entries: []XlatVal{
			{Val: 0, Str: "XFEATURE_FP"},
			{Val: 1, Str: "XFEATURE_SSE"},
			{Val: 2, Str: "XFEATURE_YMM"},
			{Val: 3, Str: "XFEATURE_BNDREGS"},
			{Val: 4, Str: "XFEATURE_BNDCSR"},
			{Val: 5, Str: "XFEATURE_OPMASK"},
			{Val: 6, Str: "XFEATURE_ZMM_Hi256"},
			{Val: 7, Str: "XFEATURE_Hi16_ZMM"},
			{Val: 8, Str: "XFEATURE_PT_UNIMPLEMENTED_SO_FAR"},
			{Val: 9, Str: "XFEATURE_PKRU"},
			{Val: 10, Str: "XFEATURE_PASID"},
			{Val: 15, Str: "XFEATURE_LBR"},
			{Val: 17, Str: "XFEATURE_XTILE_CFG"},
			{Val: 18, Str: "XFEATURE_XTILE_DATA"},
			{Val: 8, Str: "XFEATURE_PT_UNIMPLEMENTED_SO_FAR"},
			{Val: 15, Str: "XFEATURE_LBR"},
			{Val: 17, Str: "XFEATURE_XTILE_CFG"},
			{Val: 18, Str: "XFEATURE_XTILE_DATA"},
		},
	},
	"x86_xfeatures": {
		Prefix: "XFEATURE_MASK_",
		Entries: []XlatVal{
		},
	},
}
var SyscallArgXlatMap = map[string]map[string]string{
	"openat": {
		"flags": "open_mode_flags",
	},
	"arch_prctl": {
		"option": "archvals",
	},
	"mprotect": {
		"prot": "mmap_prot",
	},
	"madvise": {
		"behavior": "madvise_cmds",
	},
	"lseek": {
		"whence": "whence_codes",
	},
	"mount": {
		"mountflags": "mount_flags",
	},
	"access": {
		"mode": "access_modes",
	},
	"open": {
		"flags": "open_mode_flags",
	},
	"faccessat2": {
		"mode": "access_modes",
	},
	"bpf": {
		"arg0": "bpf_commands",
	},
	"clock_adjtime": {
		"which_clock": "clocknames",
	},
	"clock_settime": {
		"which_clock": "clocknames",
	},
	"epoll_ctl": {
		"op": "epollctls",
	},
	"rt_sigprocmask": {
		"how": "sigprocmaskcmds",
	},
	"clock_nanosleep": {
		"which_clock": "clocknames",
	},
	"request_key": {
		"destringid": "key_spec",
	},
	"epoll_create1": {
		"flags": "epollflags",
	},
	"futex": {
		"op": "futexops",
	},
	"umount2": {
		"flags": "umount_flags",
	},
	"faccessat": {
		"mode": "access_modes",
	},
	"mremap": {
		"flags": "mremap_flags",
	},
	"clone3": {
		"flags": "clone3_flags",
	},
	"mmap": {
		"prot": "mmap_prot",
		"flags": "mmap_flags",
	},
	"clone": {
		"clone_flags": "clone_flags",
	},
	"wait4": {
		"options": "wait4_options",
	},
	"add_key": {
		"ringid": "key_spec",
	},
	"accept4": {
		"flags": "sock_type_flags",
	},
}
