package meta
type XlatVal struct { Val uint64; Str string }
type XlatTable struct { Prefix string; Entries []XlatVal }
var XlatTables = map[string]XlatTable{
	"access_modes": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 0, Str: "F_OK"},
			{Val: 4, Str: "R_OK"},
			{Val: 2, Str: "W_OK"},
			{Val: 1, Str: "X_OK"},
		},
	},
	"addrfams": {
		Prefix: "AF_",
		Entries: []XlatVal{
			{Val: 0, Str: "AF_UNSPEC"},
			{Val: 1, Str: "AF_UNIX"},
			{Val: 2, Str: "AF_INET"},
			{Val: 3, Str: "AF_AX25"},
			{Val: 4, Str: "AF_IPX"},
			{Val: 5, Str: "AF_APPLETALK"},
			{Val: 6, Str: "AF_NETROM"},
			{Val: 7, Str: "AF_BRIDGE"},
			{Val: 8, Str: "AF_ATMPVC"},
			{Val: 9, Str: "AF_X25"},
			{Val: 10, Str: "AF_INET6"},
			{Val: 11, Str: "AF_ROSE"},
			{Val: 12, Str: "AF_DECnet"},
			{Val: 13, Str: "AF_NETBEUI"},
			{Val: 14, Str: "AF_SECURITY"},
			{Val: 15, Str: "AF_KEY"},
			{Val: 16, Str: "AF_NETLINK"},
			{Val: 17, Str: "AF_PACKET"},
			{Val: 18, Str: "AF_ASH"},
			{Val: 19, Str: "AF_ECONET"},
			{Val: 20, Str: "AF_ATMSVC"},
			{Val: 21, Str: "AF_RDS"},
			{Val: 22, Str: "AF_SNA"},
			{Val: 23, Str: "AF_IRDA"},
			{Val: 24, Str: "AF_PPPOX"},
			{Val: 25, Str: "AF_WANPIPE"},
			{Val: 26, Str: "AF_LLC"},
			{Val: 27, Str: "AF_IB"},
			{Val: 28, Str: "AF_MPLS"},
			{Val: 29, Str: "AF_CAN"},
			{Val: 30, Str: "AF_TIPC"},
			{Val: 31, Str: "AF_BLUETOOTH"},
			{Val: 32, Str: "AF_IUCV"},
			{Val: 33, Str: "AF_RXRPC"},
			{Val: 34, Str: "AF_ISDN"},
			{Val: 35, Str: "AF_PHONET"},
			{Val: 36, Str: "AF_IEEE802154"},
			{Val: 37, Str: "AF_CAIF"},
			{Val: 38, Str: "AF_ALG"},
			{Val: 39, Str: "AF_NFC"},
			{Val: 40, Str: "AF_VSOCK"},
			{Val: 41, Str: "AF_KCM"},
			{Val: 42, Str: "AF_QIPCRTR"},
			{Val: 43, Str: "AF_SMC"},
			{Val: 44, Str: "AF_XDP"},
			{Val: 45, Str: "AF_MCTP"},
		},
	},
	"adjtimex_status": {
		Prefix: "STA_",
		Entries: []XlatVal{
			{Val: 1, Str: "STA_PLL"},
			{Val: 2, Str: "STA_PPSFREQ"},
			{Val: 4, Str: "STA_PPSTIME"},
			{Val: 8, Str: "STA_FLL"},
			{Val: 16, Str: "STA_INS"},
			{Val: 32, Str: "STA_DEL"},
			{Val: 64, Str: "STA_UNSYNC"},
			{Val: 128, Str: "STA_FREQHOLD"},
			{Val: 256, Str: "STA_PPSSIGNAL"},
			{Val: 512, Str: "STA_PPSJITTER"},
			{Val: 1024, Str: "STA_PPSWANDER"},
			{Val: 2048, Str: "STA_PPSERROR"},
			{Val: 4096, Str: "STA_CLOCKERR"},
			{Val: 8192, Str: "STA_NANO"},
			{Val: 16384, Str: "STA_MODE"},
			{Val: 32768, Str: "STA_CLK"},
		},
	},
	"archvals": {
		Prefix: "ARCH_",
		Entries: []XlatVal{
			{Val: 4097, Str: "ARCH_SET_GS"},
			{Val: 4098, Str: "ARCH_SET_FS"},
			{Val: 4099, Str: "ARCH_GET_FS"},
			{Val: 4100, Str: "ARCH_GET_GS"},
			{Val: 4113, Str: "ARCH_GET_CPUID"},
			{Val: 4114, Str: "ARCH_SET_CPUID"},
			{Val: 4129, Str: "ARCH_GET_XCOMP_SUPP"},
			{Val: 4130, Str: "ARCH_GET_XCOMP_PERM"},
			{Val: 4131, Str: "ARCH_REQ_XCOMP_PERM"},
			{Val: 4132, Str: "ARCH_GET_XCOMP_GUEST_PERM"},
			{Val: 4133, Str: "ARCH_REQ_XCOMP_GUEST_PERM"},
			{Val: 8193, Str: "ARCH_MAP_VDSO_X32"},
			{Val: 8194, Str: "ARCH_MAP_VDSO_32"},
			{Val: 8195, Str: "ARCH_MAP_VDSO_64"},
			{Val: 16385, Str: "ARCH_GET_UNTAG_MASK"},
			{Val: 16386, Str: "ARCH_ENABLE_TAGGED_ADDR"},
			{Val: 16387, Str: "ARCH_GET_MAX_TAG_BITS"},
			{Val: 16388, Str: "ARCH_FORCE_TAGGED_SVA"},
			{Val: 20481, Str: "ARCH_SHSTK_ENABLE"},
			{Val: 20482, Str: "ARCH_SHSTK_DISABLE"},
			{Val: 20483, Str: "ARCH_SHSTK_LOCK"},
			{Val: 20484, Str: "ARCH_SHSTK_UNLOCK"},
			{Val: 20485, Str: "ARCH_SHSTK_STATUS"},
		},
	},
	"bpf_attach_type": {
		Prefix: "BPF_",
		Entries: []XlatVal{
			{Val: 1, Str: "BPF_CGROUP_INET_EGRESS"},
			{Val: 2, Str: "BPF_CGROUP_INET_SOCK_CREATE"},
			{Val: 3, Str: "BPF_CGROUP_SOCK_OPS"},
			{Val: 4, Str: "BPF_SK_SKB_STREAM_PARSER"},
			{Val: 5, Str: "BPF_SK_SKB_STREAM_VERDICT"},
			{Val: 6, Str: "BPF_CGROUP_DEVICE"},
			{Val: 7, Str: "BPF_SK_MSG_VERDICT"},
			{Val: 8, Str: "BPF_CGROUP_INET4_BIND"},
			{Val: 9, Str: "BPF_CGROUP_INET6_BIND"},
			{Val: 10, Str: "BPF_CGROUP_INET4_CONNECT"},
			{Val: 11, Str: "BPF_CGROUP_INET6_CONNECT"},
			{Val: 12, Str: "BPF_CGROUP_INET4_POST_BIND"},
			{Val: 13, Str: "BPF_CGROUP_INET6_POST_BIND"},
			{Val: 14, Str: "BPF_CGROUP_UDP4_SENDMSG"},
			{Val: 15, Str: "BPF_CGROUP_UDP6_SENDMSG"},
			{Val: 16, Str: "BPF_LIRC_MODE2"},
			{Val: 17, Str: "BPF_FLOW_DISSECTOR"},
			{Val: 18, Str: "BPF_CGROUP_SYSCTL"},
			{Val: 19, Str: "BPF_CGROUP_UDP4_RECVMSG"},
			{Val: 20, Str: "BPF_CGROUP_UDP6_RECVMSG"},
			{Val: 21, Str: "BPF_CGROUP_GETSOCKOPT"},
			{Val: 22, Str: "BPF_CGROUP_SETSOCKOPT"},
			{Val: 23, Str: "BPF_TRACE_RAW_TP"},
			{Val: 24, Str: "BPF_TRACE_FENTRY"},
			{Val: 25, Str: "BPF_TRACE_FEXIT"},
			{Val: 26, Str: "BPF_MODIFY_RETURN"},
			{Val: 27, Str: "BPF_LSM_MAC"},
			{Val: 28, Str: "BPF_TRACE_ITER"},
			{Val: 29, Str: "BPF_CGROUP_INET4_GETPEERNAME"},
			{Val: 30, Str: "BPF_CGROUP_INET6_GETPEERNAME"},
			{Val: 31, Str: "BPF_CGROUP_INET4_GETSOCKNAME"},
			{Val: 32, Str: "BPF_CGROUP_INET6_GETSOCKNAME"},
			{Val: 33, Str: "BPF_XDP_DEVMAP"},
			{Val: 34, Str: "BPF_CGROUP_INET_SOCK_RELEASE"},
			{Val: 35, Str: "BPF_XDP_CPUMAP"},
			{Val: 36, Str: "BPF_SK_LOOKUP"},
			{Val: 37, Str: "BPF_XDP"},
			{Val: 38, Str: "BPF_SK_SKB_VERDICT"},
			{Val: 39, Str: "BPF_SK_REUSEPORT_SELECT"},
			{Val: 40, Str: "BPF_SK_REUSEPORT_SELECT_OR_MIGRATE"},
			{Val: 41, Str: "BPF_PERF_EVENT"},
			{Val: 42, Str: "BPF_TRACE_KPROBE_MULTI"},
			{Val: 43, Str: "BPF_LSM_CGROUP"},
			{Val: 44, Str: "BPF_STRUCT_OPS"},
			{Val: 45, Str: "BPF_NETFILTER"},
			{Val: 46, Str: "BPF_TCX_INGRESS"},
			{Val: 47, Str: "BPF_TCX_EGRESS"},
			{Val: 48, Str: "BPF_TRACE_UPROBE_MULTI"},
			{Val: 49, Str: "BPF_CGROUP_UNIX_CONNECT"},
			{Val: 50, Str: "BPF_CGROUP_UNIX_SENDMSG"},
			{Val: 51, Str: "BPF_CGROUP_UNIX_RECVMSG"},
			{Val: 52, Str: "BPF_CGROUP_UNIX_GETPEERNAME"},
			{Val: 53, Str: "BPF_CGROUP_UNIX_GETSOCKNAME"},
			{Val: 54, Str: "BPF_NETKIT_PRIMARY"},
			{Val: 55, Str: "BPF_NETKIT_PEER"},
			{Val: 56, Str: "BPF_TRACE_KPROBE_SESSION"},
			{Val: 57, Str: "BPF_TRACE_UPROBE_SESSION"},
			{Val: 58, Str: "BPF_TRACE_FSESSION"},
		},
	},
	"bpf_commands": {
		Prefix: "BPF_",
		Entries: []XlatVal{
			{Val: 0, Str: "BPF_MAP_CREATE"},
			{Val: 1, Str: "BPF_MAP_LOOKUP_ELEM"},
			{Val: 2, Str: "BPF_MAP_UPDATE_ELEM"},
			{Val: 3, Str: "BPF_MAP_DELETE_ELEM"},
			{Val: 4, Str: "BPF_MAP_GET_NEXT_KEY"},
			{Val: 5, Str: "BPF_PROG_LOAD"},
			{Val: 6, Str: "BPF_OBJ_PIN"},
			{Val: 7, Str: "BPF_OBJ_GET"},
			{Val: 8, Str: "BPF_PROG_ATTACH"},
			{Val: 9, Str: "BPF_PROG_DETACH"},
			{Val: 10, Str: "BPF_PROG_TEST_RUN"},
			{Val: 11, Str: "BPF_PROG_GET_NEXT_ID"},
			{Val: 12, Str: "BPF_MAP_GET_NEXT_ID"},
			{Val: 13, Str: "BPF_PROG_GET_FD_BY_ID"},
			{Val: 14, Str: "BPF_MAP_GET_FD_BY_ID"},
			{Val: 15, Str: "BPF_OBJ_GET_INFO_BY_FD"},
			{Val: 16, Str: "BPF_PROG_QUERY"},
			{Val: 17, Str: "BPF_RAW_TRACEPOINT_OPEN"},
			{Val: 18, Str: "BPF_BTF_LOAD"},
			{Val: 19, Str: "BPF_BTF_GET_FD_BY_ID"},
			{Val: 20, Str: "BPF_TASK_FD_QUERY"},
			{Val: 21, Str: "BPF_MAP_LOOKUP_AND_DELETE_ELEM"},
			{Val: 22, Str: "BPF_MAP_FREEZE"},
			{Val: 23, Str: "BPF_BTF_GET_NEXT_ID"},
			{Val: 24, Str: "BPF_MAP_LOOKUP_BATCH"},
			{Val: 25, Str: "BPF_MAP_LOOKUP_AND_DELETE_BATCH"},
			{Val: 26, Str: "BPF_MAP_UPDATE_BATCH"},
			{Val: 27, Str: "BPF_MAP_DELETE_BATCH"},
			{Val: 28, Str: "BPF_LINK_CREATE"},
			{Val: 29, Str: "BPF_LINK_UPDATE"},
			{Val: 30, Str: "BPF_LINK_GET_FD_BY_ID"},
			{Val: 31, Str: "BPF_LINK_GET_NEXT_ID"},
			{Val: 32, Str: "BPF_ENABLE_STATS"},
			{Val: 33, Str: "BPF_ITER_CREATE"},
			{Val: 34, Str: "BPF_LINK_DETACH"},
			{Val: 35, Str: "BPF_PROG_BIND_MAP"},
			{Val: 36, Str: "BPF_TOKEN_CREATE"},
			{Val: 37, Str: "BPF_PROG_STREAM_READ_BY_FD"},
			{Val: 38, Str: "BPF_PROG_ASSOC_STRUCT_OPS"},
		},
	},
	"bpf_map_flags": {
		Prefix: "BPF_F_",
		Entries: []XlatVal{
			{Val: 1, Str: "BPF_F_NO_PREALLOC"},
			{Val: 2, Str: "BPF_F_NO_COMMON_LRU"},
			{Val: 4, Str: "BPF_F_NUMA_NODE"},
			{Val: 8, Str: "BPF_F_RDONLY"},
			{Val: 16, Str: "BPF_F_WRONLY"},
			{Val: 32, Str: "BPF_F_STACK_BUILD_ID"},
			{Val: 64, Str: "BPF_F_ZERO_SEED"},
			{Val: 128, Str: "BPF_F_RDONLY_PROG"},
			{Val: 256, Str: "BPF_F_WRONLY_PROG"},
			{Val: 512, Str: "BPF_F_CLONE"},
			{Val: 1024, Str: "BPF_F_MMAPABLE"},
			{Val: 2048, Str: "BPF_F_PRESERVE_ELEMS"},
			{Val: 4096, Str: "BPF_F_INNER_MAP"},
			{Val: 8192, Str: "BPF_F_LINK"},
		},
	},
	"bpf_map_types": {
		Prefix: "BPF_MAP_TYPE_",
		Entries: []XlatVal{
			{Val: 0, Str: "BPF_MAP_TYPE_UNSPEC"},
			{Val: 1, Str: "BPF_MAP_TYPE_HASH"},
			{Val: 2, Str: "BPF_MAP_TYPE_ARRAY"},
			{Val: 3, Str: "BPF_MAP_TYPE_PROG_ARRAY"},
			{Val: 4, Str: "BPF_MAP_TYPE_PERF_EVENT_ARRAY"},
			{Val: 5, Str: "BPF_MAP_TYPE_PERCPU_HASH"},
			{Val: 6, Str: "BPF_MAP_TYPE_PERCPU_ARRAY"},
			{Val: 7, Str: "BPF_MAP_TYPE_STACK_TRACE"},
			{Val: 8, Str: "BPF_MAP_TYPE_CGROUP_ARRAY"},
			{Val: 9, Str: "BPF_MAP_TYPE_LRU_HASH"},
			{Val: 10, Str: "BPF_MAP_TYPE_LRU_PERCPU_HASH"},
			{Val: 11, Str: "BPF_MAP_TYPE_LPM_TRIE"},
			{Val: 12, Str: "BPF_MAP_TYPE_ARRAY_OF_MAPS"},
			{Val: 13, Str: "BPF_MAP_TYPE_HASH_OF_MAPS"},
			{Val: 14, Str: "BPF_MAP_TYPE_DEVMAP"},
			{Val: 15, Str: "BPF_MAP_TYPE_SOCKMAP"},
			{Val: 16, Str: "BPF_MAP_TYPE_CPUMAP"},
			{Val: 17, Str: "BPF_MAP_TYPE_XSKMAP"},
			{Val: 18, Str: "BPF_MAP_TYPE_SOCKHASH"},
			{Val: 19, Str: "BPF_MAP_TYPE_CGROUP_STORAGE"},
			{Val: 20, Str: "BPF_MAP_TYPE_REUSEPORT_SOCKARRAY"},
			{Val: 21, Str: "BPF_MAP_TYPE_PERCPU_CGROUP_STORAGE"},
			{Val: 22, Str: "BPF_MAP_TYPE_QUEUE"},
			{Val: 23, Str: "BPF_MAP_TYPE_STACK"},
			{Val: 24, Str: "BPF_MAP_TYPE_SK_STORAGE"},
			{Val: 25, Str: "BPF_MAP_TYPE_DEVMAP_HASH"},
			{Val: 26, Str: "BPF_MAP_TYPE_STRUCT_OPS"},
			{Val: 27, Str: "BPF_MAP_TYPE_RINGBUF"},
			{Val: 28, Str: "BPF_MAP_TYPE_INODE_STORAGE"},
			{Val: 29, Str: "BPF_MAP_TYPE_TASK_STORAGE"},
			{Val: 30, Str: "BPF_MAP_TYPE_BLOOM_FILTER"},
			{Val: 31, Str: "BPF_MAP_TYPE_USER_RINGBUF"},
			{Val: 32, Str: "BPF_MAP_TYPE_CGRP_STORAGE"},
			{Val: 33, Str: "BPF_MAP_TYPE_ARENA"},
			{Val: 34, Str: "BPF_MAP_TYPE_INSN_ARRAY"},
		},
	},
	"bpf_prog_flags": {
		Prefix: "BPF_F_",
		Entries: []XlatVal{
			{Val: 1, Str: "BPF_F_STRICT_ALIGNMENT"},
			{Val: 2, Str: "BPF_F_ANY_ALIGNMENT"},
			{Val: 4, Str: "BPF_F_TEST_RND_HI32"},
			{Val: 8, Str: "BPF_F_TEST_STATE_FREQ"},
			{Val: 16, Str: "BPF_F_SLEEPABLE"},
			{Val: 32, Str: "BPF_F_XDP_HAS_FRAGS"},
			{Val: 64, Str: "BPF_F_XDP_DEV_BOUND_ONLY"},
			{Val: 128, Str: "BPF_F_TEST_REG_INVARIANTS"},
		},
	},
	"bpf_prog_types": {
		Prefix: "BPF_PROG_TYPE_",
		Entries: []XlatVal{
			{Val: 1, Str: "BPF_PROG_TYPE_SOCKET_FILTER"},
			{Val: 2, Str: "BPF_PROG_TYPE_KPROBE"},
			{Val: 3, Str: "BPF_PROG_TYPE_SCHED_CLS"},
			{Val: 4, Str: "BPF_PROG_TYPE_SCHED_ACT"},
			{Val: 5, Str: "BPF_PROG_TYPE_TRACEPOINT"},
			{Val: 6, Str: "BPF_PROG_TYPE_XDP"},
			{Val: 7, Str: "BPF_PROG_TYPE_PERF_EVENT"},
			{Val: 8, Str: "BPF_PROG_TYPE_CGROUP_SKB"},
			{Val: 9, Str: "BPF_PROG_TYPE_CGROUP_SOCK"},
			{Val: 10, Str: "BPF_PROG_TYPE_LWT_IN"},
			{Val: 11, Str: "BPF_PROG_TYPE_LWT_OUT"},
			{Val: 12, Str: "BPF_PROG_TYPE_LWT_XMIT"},
			{Val: 13, Str: "BPF_PROG_TYPE_SOCK_OPS"},
			{Val: 14, Str: "BPF_PROG_TYPE_SK_SKB"},
			{Val: 15, Str: "BPF_PROG_TYPE_CGROUP_DEVICE"},
			{Val: 16, Str: "BPF_PROG_TYPE_SK_MSG"},
			{Val: 17, Str: "BPF_PROG_TYPE_RAW_TRACEPOINT"},
			{Val: 18, Str: "BPF_PROG_TYPE_CGROUP_SOCK_ADDR"},
			{Val: 19, Str: "BPF_PROG_TYPE_LWT_SEG6LOCAL"},
			{Val: 20, Str: "BPF_PROG_TYPE_LIRC_MODE2"},
			{Val: 21, Str: "BPF_PROG_TYPE_SK_REUSEPORT"},
			{Val: 22, Str: "BPF_PROG_TYPE_FLOW_DISSECTOR"},
			{Val: 23, Str: "BPF_PROG_TYPE_CGROUP_SYSCTL"},
			{Val: 24, Str: "BPF_PROG_TYPE_RAW_TRACEPOINT_WRITABLE"},
			{Val: 25, Str: "BPF_PROG_TYPE_CGROUP_SOCKOPT"},
			{Val: 26, Str: "BPF_PROG_TYPE_TRACING"},
			{Val: 27, Str: "BPF_PROG_TYPE_STRUCT_OPS"},
			{Val: 28, Str: "BPF_PROG_TYPE_EXT"},
			{Val: 29, Str: "BPF_PROG_TYPE_LSM"},
			{Val: 30, Str: "BPF_PROG_TYPE_SK_LOOKUP"},
			{Val: 31, Str: "BPF_PROG_TYPE_SYSCALL"},
			{Val: 32, Str: "BPF_PROG_TYPE_NETFILTER"},
		},
	},
	"clone_flags": {
		Prefix: "CLONE_",
		Entries: []XlatVal{
			{Val: 256, Str: "CLONE_VM"},
			{Val: 512, Str: "CLONE_FS"},
			{Val: 1024, Str: "CLONE_FILES"},
			{Val: 2048, Str: "CLONE_SIGHAND"},
			{Val: 4096, Str: "CLONE_PIDFD"},
			{Val: 8192, Str: "CLONE_PTRACE"},
			{Val: 16384, Str: "CLONE_VFORK"},
			{Val: 32768, Str: "CLONE_PARENT"},
			{Val: 65536, Str: "CLONE_THREAD"},
			{Val: 131072, Str: "CLONE_NEWNS"},
			{Val: 262144, Str: "CLONE_SYSVSEM"},
			{Val: 524288, Str: "CLONE_SETTLS"},
			{Val: 1048576, Str: "CLONE_PARENT_SETTID"},
			{Val: 2097152, Str: "CLONE_CHILD_CLEARTID"},
			{Val: 8388608, Str: "CLONE_UNTRACED"},
			{Val: 16777216, Str: "CLONE_CHILD_SETTID"},
			{Val: 33554432, Str: "CLONE_NEWCGROUP"},
			{Val: 67108864, Str: "CLONE_NEWUTS"},
			{Val: 134217728, Str: "CLONE_NEWIPC"},
			{Val: 268435456, Str: "CLONE_NEWUSER"},
			{Val: 536870912, Str: "CLONE_NEWPID"},
			{Val: 1073741824, Str: "CLONE_NEWNET"},
			{Val: 2147483648, Str: "CLONE_IO"},
		},
	},
	"epollctls": {
		Prefix: "EPOLL_CTL_",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLL_CTL_ADD"},
			{Val: 2, Str: "EPOLL_CTL_DEL"},
			{Val: 3, Str: "EPOLL_CTL_MOD"},
		},
	},
	"epollevents": {
		Prefix: "EPOLL",
		Entries: []XlatVal{
			{Val: 1, Str: "EPOLLIN"},
			{Val: 2, Str: "EPOLLPRI"},
			{Val: 4, Str: "EPOLLOUT"},
			{Val: 8, Str: "EPOLLERR"},
			{Val: 16, Str: "EPOLLHUP"},
			{Val: 32, Str: "EPOLLNVAL"},
			{Val: 64, Str: "EPOLLRDNORM"},
			{Val: 128, Str: "EPOLLRDBAND"},
			{Val: 256, Str: "EPOLLWRNORM"},
			{Val: 512, Str: "EPOLLWRBAND"},
			{Val: 1024, Str: "EPOLLMSG"},
			{Val: 8192, Str: "EPOLLRDHUP"},
			{Val: 268435456, Str: "EPOLLEXCLUSIVE"},
			{Val: 536870912, Str: "EPOLLWAKEUP"},
			{Val: 1073741824, Str: "EPOLLONESHOT"},
			{Val: 2147483648, Str: "EPOLLET"},
		},
	},
	"epollflags": {
		Prefix: "EPOLL_",
		Entries: []XlatVal{
			{Val: 524288, Str: "EPOLL_CLOEXEC"},
		},
	},
	"futexops": {
		Prefix: "FUTEX_",
		Entries: []XlatVal{
			{Val: 0, Str: "FUTEX_WAIT"},
			{Val: 1, Str: "FUTEX_WAKE"},
			{Val: 2, Str: "FUTEX_FD"},
			{Val: 3, Str: "FUTEX_REQUEUE"},
			{Val: 4, Str: "FUTEX_CMP_REQUEUE"},
			{Val: 5, Str: "FUTEX_WAKE_OP"},
			{Val: 6, Str: "FUTEX_LOCK_PI"},
			{Val: 7, Str: "FUTEX_UNLOCK_PI"},
			{Val: 8, Str: "FUTEX_TRYLOCK_PI"},
			{Val: 9, Str: "FUTEX_WAIT_BITSET"},
			{Val: 10, Str: "FUTEX_WAKE_BITSET"},
			{Val: 11, Str: "FUTEX_WAIT_REQUEUE_PI"},
			{Val: 12, Str: "FUTEX_CMP_REQUEUE_PI"},
			{Val: 13, Str: "FUTEX_LOCK_PI2"},
		},
	},
	"key_spec": {
		Prefix: "KEY_SPEC_",
		Entries: []XlatVal{
			{Val: 18446744073709551615, Str: "KEY_SPEC_THREAD_KEYRING"},
			{Val: 18446744073709551614, Str: "KEY_SPEC_PROCESS_KEYRING"},
			{Val: 18446744073709551613, Str: "KEY_SPEC_SESSION_KEYRING"},
			{Val: 18446744073709551612, Str: "KEY_SPEC_USER_KEYRING"},
			{Val: 18446744073709551611, Str: "KEY_SPEC_USER_SESSION_KEYRING"},
			{Val: 18446744073709551610, Str: "KEY_SPEC_GROUP_KEYRING"},
			{Val: 18446744073709551609, Str: "KEY_SPEC_REQKEY_AUTH_KEY"},
			{Val: 18446744073709551608, Str: "KEY_SPEC_REQUESTOR_KEYRING"},
		},
	},
	"madvise_cmds": {
		Prefix: "MADV_",
		Entries: []XlatVal{
			{Val: 0, Str: "MADV_NORMAL"},
			{Val: 1, Str: "MADV_RANDOM"},
			{Val: 2, Str: "MADV_SEQUENTIAL"},
			{Val: 3, Str: "MADV_WILLNEED"},
			{Val: 4, Str: "MADV_DONTNEED"},
			{Val: 4, Str: "MADV_DONTNEED"},
			{Val: 8, Str: "MADV_FREE"},
			{Val: 9, Str: "MADV_REMOVE"},
			{Val: 10, Str: "MADV_DONTFORK"},
			{Val: 11, Str: "MADV_DOFORK"},
			{Val: 20, Str: "MADV_COLD"},
			{Val: 21, Str: "MADV_PAGEOUT"},
			{Val: 22, Str: "MADV_POPULATE_READ"},
			{Val: 23, Str: "MADV_POPULATE_WRITE"},
			{Val: 24, Str: "MADV_DONTNEED_LOCKED"},
			{Val: 100, Str: "MADV_HWPOISON"},
			{Val: 101, Str: "MADV_SOFT_OFFLINE"},
			{Val: 102, Str: "MADV_GUARD_INSTALL"},
			{Val: 103, Str: "MADV_GUARD_REMOVE"},
		},
	},
	"mmap_flags": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 1, Str: "MAP_SHARED"},
			{Val: 2, Str: "MAP_PRIVATE"},
			{Val: 3, Str: "MAP_SHARED_VALIDATE"},
			{Val: 8, Str: "MAP_DROPPABLE"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 16, Str: "MAP_FIXED"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 32, Str: "MAP_ANONYMOUS"},
			{Val: 64, Str: "MAP_32BIT"},
			{Val: 64, Str: "MAP_32BIT"},
			{Val: 128, Str: "MAP_ABOVE4G"},
			{Val: 128, Str: "MAP_ABOVE4G"},
			{Val: 0x20, Str: "MAP_RENAME"},
			{Val: 0x20, Str: "MAP_RENAME"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 16384, Str: "MAP_NORESERVE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 32768, Str: "MAP_POPULATE"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 65536, Str: "MAP_NONBLOCK"},
			{Val: 0x80000000, Str: "_MAP_NEW"},
			{Val: 0x80000000, Str: "_MAP_NEW"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 256, Str: "MAP_GROWSDOWN"},
			{Val: 0x200, Str: "MAP_GROWSUP"},
			{Val: 0x200, Str: "MAP_GROWSUP"},
			{Val: 2048, Str: "MAP_DENYWRITE"},
			{Val: 2048, Str: "MAP_DENYWRITE"},
			{Val: 4096, Str: "MAP_EXECUTABLE"},
			{Val: 4096, Str: "MAP_EXECUTABLE"},
			{Val: 0x80, Str: "MAP_INHERIT"},
			{Val: 0x80, Str: "MAP_INHERIT"},
			{Val: 0x400, Str: "_MAP_INHERIT"},
			{Val: 0x400, Str: "_MAP_INHERIT"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 8192, Str: "MAP_LOCKED"},
			{Val: 0x200, Str: "_MAP_HASSEMAPHORE"},
			{Val: 0x200, Str: "_MAP_HASSEMAPHORE"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 131072, Str: "MAP_STACK"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 262144, Str: "MAP_HUGETLB"},
			{Val: 524288, Str: "MAP_SYNC"},
			{Val: 67108864, Str: "MAP_UNINITIALIZED"},
			{Val: 1048576, Str: "MAP_FIXED_NOREPLACE"},
			{Val: 1048576, Str: "MAP_FIXED_NOREPLACE"},
			{Val: 0x40, Str: "MAP_AUTOGROW"},
			{Val: 0x40, Str: "MAP_AUTOGROW"},
			{Val: 0x100, Str: "MAP_AUTORSRV"},
			{Val: 0x100, Str: "MAP_AUTORSRV"},
			{Val: 0x80, Str: "MAP_LOCAL"},
			{Val: 0x80, Str: "MAP_LOCAL"},
			{Val: 0x800, Str: "_MAP_UNALIGNED"},
			{Val: 0x800, Str: "_MAP_UNALIGNED"},
		},
	},
	"mmap_prot": {
		Prefix: "PROT_",
		Entries: []XlatVal{
			{Val: 0, Str: "PROT_NONE"},
			{Val: 1, Str: "PROT_READ"},
			{Val: 2, Str: "PROT_WRITE"},
			{Val: 4, Str: "PROT_EXEC"},
			{Val: 16777216, Str: "PROT_GROWSDOWN"},
			{Val: 33554432, Str: "PROT_GROWSUP"},
		},
	},
	"modetypes": {
		Prefix: "S_",
		Entries: []XlatVal{
			{Val: 32768, Str: "S_IFREG"},
			{Val: 49152, Str: "S_IFSOCK"},
			{Val: 4096, Str: "S_IFIFO"},
			{Val: 40960, Str: "S_IFLNK"},
			{Val: 16384, Str: "S_IFDIR"},
			{Val: 24576, Str: "S_IFBLK"},
			{Val: 8192, Str: "S_IFCHR"},
		},
	},
	"mremap_flags": {
		Prefix: "MREMAP_",
		Entries: []XlatVal{
			{Val: 1, Str: "MREMAP_MAYMOVE"},
			{Val: 2, Str: "MREMAP_FIXED"},
			{Val: 4, Str: "MREMAP_DONTUNMAP"},
		},
	},
	"open_access_modes": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 0, Str: "O_RDONLY"},
			{Val: 1, Str: "O_WRONLY"},
			{Val: 2, Str: "O_RDWR"},
			{Val: 3, Str: "O_ACCMODE"},
		},
	},
	"open_mode_flags": {
		Prefix: "O_",
		Entries: []XlatVal{
			{Val: 64, Str: "O_CREAT"},
			{Val: 128, Str: "O_EXCL"},
			{Val: 256, Str: "O_NOCTTY"},
			{Val: 512, Str: "O_TRUNC"},
			{Val: 1024, Str: "O_APPEND"},
			{Val: 2048, Str: "O_NONBLOCK"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4096, Str: "O_DSYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 131072, Str: "O_NOFOLLOW"},
			{Val: 262144, Str: "O_NOATIME"},
			{Val: 524288, Str: "O_CLOEXEC"},
			{Val: 2097152, Str: "O_PATH"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 4259840, Str: "__O_TMPFILE"},
			{Val: 65536, Str: "O_DIRECTORY"},
			{Val: 8192, Str: "FASYNC"},
			{Val: 16384, Str: "O_DIRECT"},
			{Val: 4259840, Str: "O_TMPFILE"},
			{Val: 1052672, Str: "O_SYNC"},
			{Val: 4194304, Str: "__O_TMPFILE"},
			{Val: 1048576, Str: "__O_SYNC"},
			{Val: 32768, Str: "O_LARGEFILE"},
		},
	},
	"pollflags": {
		Prefix: "POLL",
		Entries: []XlatVal{
			{Val: 1, Str: "POLLIN"},
			{Val: 2, Str: "POLLPRI"},
			{Val: 4, Str: "POLLOUT"},
			{Val: 8, Str: "POLLERR"},
			{Val: 16, Str: "POLLHUP"},
			{Val: 32, Str: "POLLNVAL"},
			{Val: 64, Str: "POLLRDNORM"},
			{Val: 128, Str: "POLLRDBAND"},
			{Val: 256, Str: "POLLWRNORM"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 512, Str: "POLLWRBAND"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 1024, Str: "POLLMSG"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 4096, Str: "POLLREMOVE"},
			{Val: 8192, Str: "POLLRDHUP"},
			{Val: 8192, Str: "POLLRDHUP"},
			{Val: 32768, Str: "POLL_BUSY_LOOP"},
		},
	},
	"prctl_options": {
		Prefix: "PR_",
		Entries: []XlatVal{
			{Val: 1, Str: "PR_SET_PDEATHSIG"},
			{Val: 2, Str: "PR_GET_PDEATHSIG"},
			{Val: 3, Str: "PR_GET_DUMPABLE"},
			{Val: 4, Str: "PR_SET_DUMPABLE"},
			{Val: 5, Str: "PR_GET_UNALIGN"},
			{Val: 6, Str: "PR_SET_UNALIGN"},
			{Val: 7, Str: "PR_GET_KEEPCAPS"},
			{Val: 8, Str: "PR_SET_KEEPCAPS"},
			{Val: 9, Str: "PR_GET_FPEMU"},
			{Val: 10, Str: "PR_SET_FPEMU"},
			{Val: 11, Str: "PR_GET_FPEXC"},
			{Val: 12, Str: "PR_SET_FPEXC"},
			{Val: 13, Str: "PR_GET_TIMING"},
			{Val: 14, Str: "PR_SET_TIMING"},
			{Val: 15, Str: "PR_SET_NAME"},
			{Val: 16, Str: "PR_GET_NAME"},
			{Val: 19, Str: "PR_GET_ENDIAN"},
			{Val: 20, Str: "PR_SET_ENDIAN"},
			{Val: 21, Str: "PR_GET_SECCOMP"},
			{Val: 22, Str: "PR_SET_SECCOMP"},
			{Val: 23, Str: "PR_CAPBSET_READ"},
			{Val: 24, Str: "PR_CAPBSET_DROP"},
			{Val: 25, Str: "PR_GET_TSC"},
			{Val: 26, Str: "PR_SET_TSC"},
			{Val: 27, Str: "PR_GET_SECUREBITS"},
			{Val: 28, Str: "PR_SET_SECUREBITS"},
			{Val: 29, Str: "PR_SET_TIMERSLACK"},
			{Val: 30, Str: "PR_GET_TIMERSLACK"},
			{Val: 31, Str: "PR_TASK_PERF_EVENTS_DISABLE"},
			{Val: 32, Str: "PR_TASK_PERF_EVENTS_ENABLE"},
			{Val: 33, Str: "PR_MCE_KILL"},
			{Val: 34, Str: "PR_MCE_KILL_GET"},
			{Val: 35, Str: "PR_SET_MM"},
			{Val: 36, Str: "PR_SET_CHILD_SUBREAPER"},
			{Val: 37, Str: "PR_GET_CHILD_SUBREAPER"},
			{Val: 38, Str: "PR_SET_NO_NEW_PRIVS"},
			{Val: 39, Str: "PR_GET_NO_NEW_PRIVS"},
			{Val: 40, Str: "PR_GET_TID_ADDRESS"},
			{Val: 41, Str: "PR_SET_THP_DISABLE"},
			{Val: 42, Str: "PR_GET_THP_DISABLE"},
			{Val: 43, Str: "PR_MPX_ENABLE_MANAGEMENT"},
			{Val: 44, Str: "PR_MPX_DISABLE_MANAGEMENT"},
			{Val: 45, Str: "PR_SET_FP_MODE"},
			{Val: 46, Str: "PR_GET_FP_MODE"},
			{Val: 47, Str: "PR_CAP_AMBIENT"},
			{Val: 50, Str: "PR_SVE_SET_VL"},
			{Val: 51, Str: "PR_SVE_GET_VL"},
			{Val: 52, Str: "PR_GET_SPECULATION_CTRL"},
			{Val: 53, Str: "PR_SET_SPECULATION_CTRL"},
			{Val: 54, Str: "PR_PAC_RESET_KEYS"},
			{Val: 55, Str: "PR_SET_TAGGED_ADDR_CTRL"},
			{Val: 56, Str: "PR_GET_TAGGED_ADDR_CTRL"},
			{Val: 57, Str: "PR_SET_IO_FLUSHER"},
			{Val: 58, Str: "PR_GET_IO_FLUSHER"},
			{Val: 59, Str: "PR_SET_SYSCALL_USER_DISPATCH"},
			{Val: 60, Str: "PR_PAC_SET_ENABLED_KEYS"},
			{Val: 61, Str: "PR_PAC_GET_ENABLED_KEYS"},
			{Val: 62, Str: "PR_SCHED_CORE"},
			{Val: 63, Str: "PR_SME_SET_VL"},
			{Val: 64, Str: "PR_SME_GET_VL"},
			{Val: 65, Str: "PR_SET_MDWE"},
			{Val: 66, Str: "PR_GET_MDWE"},
			{Val: 67, Str: "PR_SET_MEMORY_MERGE"},
			{Val: 68, Str: "PR_GET_MEMORY_MERGE"},
			{Val: 69, Str: "PR_RISCV_V_SET_CONTROL"},
			{Val: 70, Str: "PR_RISCV_V_GET_CONTROL"},
			{Val: 71, Str: "PR_RISCV_SET_ICACHE_FLUSH_CTX"},
			{Val: 72, Str: "PR_PPC_GET_DEXCR"},
			{Val: 73, Str: "PR_PPC_SET_DEXCR"},
			{Val: 74, Str: "PR_GET_SHADOW_STACK_STATUS"},
			{Val: 75, Str: "PR_SET_SHADOW_STACK_STATUS"},
			{Val: 76, Str: "PR_LOCK_SHADOW_STACK_STATUS"},
			{Val: 77, Str: "PR_TIMER_CREATE_RESTORE_IDS"},
			{Val: 78, Str: "PR_FUTEX_HASH"},
			{Val: 79, Str: "PR_RSEQ_SLICE_EXTENSION"},
			{Val: 80, Str: "PR_GET_CFI"},
			{Val: 81, Str: "PR_SET_CFI"},
			{Val: 1096112214, Str: "PR_GET_AUXV"},
			{Val: 1398164801, Str: "PR_SET_VMA"},
			{Val: 1499557217, Str: "PR_SET_PTRACER"},
		},
	},
	"sigprocmaskcmds": {
		Prefix: "SIG_",
		Entries: []XlatVal{
			{Val: 0, Str: "SIG_BLOCK"},
			{Val: 1, Str: "SIG_UNBLOCK"},
			{Val: 2, Str: "SIG_SETMASK"},
		},
	},
	"sock_options": {
		Prefix: "",
		Entries: []XlatVal{
			{Val: 1, Str: "SO_DEBUG"},
			{Val: 2, Str: "SO_REUSEADDR"},
			{Val: 2, Str: "SO_REUSEADDR"},
			{Val: 3, Str: "SO_TYPE"},
			{Val: 3, Str: "SO_TYPE"},
			{Val: 4, Str: "SO_ERROR"},
			{Val: 4, Str: "SO_ERROR"},
			{Val: 5, Str: "SO_DONTROUTE"},
			{Val: 5, Str: "SO_DONTROUTE"},
			{Val: 6, Str: "SO_BROADCAST"},
			{Val: 6, Str: "SO_BROADCAST"},
			{Val: 7, Str: "SO_SNDBUF"},
			{Val: 7, Str: "SO_SNDBUF"},
			{Val: 8, Str: "SO_RCVBUF"},
			{Val: 8, Str: "SO_RCVBUF"},
			{Val: 9, Str: "SO_KEEPALIVE"},
			{Val: 9, Str: "SO_KEEPALIVE"},
			{Val: 10, Str: "SO_OOBINLINE"},
			{Val: 10, Str: "SO_OOBINLINE"},
			{Val: 11, Str: "SO_NO_CHECK"},
			{Val: 11, Str: "SO_NO_CHECK"},
			{Val: 12, Str: "SO_PRIORITY"},
			{Val: 12, Str: "SO_PRIORITY"},
			{Val: 13, Str: "SO_LINGER"},
			{Val: 13, Str: "SO_LINGER"},
			{Val: 14, Str: "SO_BSDCOMPAT"},
			{Val: 14, Str: "SO_BSDCOMPAT"},
			{Val: 14, Str: "SO_BSDCOMPAT"},
			{Val: 15, Str: "SO_REUSEPORT"},
			{Val: 15, Str: "SO_REUSEPORT"},
			{Val: 16, Str: "SO_PASSCRED"},
			{Val: 16, Str: "SO_PASSCRED"},
			{Val: 16, Str: "SO_PASSCRED"},
			{Val: 16, Str: "SO_PASSCRED"},
			{Val: 16, Str: "SO_PASSCRED"},
			{Val: 17, Str: "SO_PEERCRED"},
			{Val: 17, Str: "SO_PEERCRED"},
			{Val: 17, Str: "SO_PEERCRED"},
			{Val: 17, Str: "SO_PEERCRED"},
			{Val: 17, Str: "SO_PEERCRED"},
			{Val: 18, Str: "SO_RCVLOWAT"},
			{Val: 18, Str: "SO_RCVLOWAT"},
			{Val: 18, Str: "SO_RCVLOWAT"},
			{Val: 18, Str: "SO_RCVLOWAT"},
			{Val: 18, Str: "SO_RCVLOWAT"},
			{Val: 19, Str: "SO_SNDLOWAT"},
			{Val: 19, Str: "SO_SNDLOWAT"},
			{Val: 19, Str: "SO_SNDLOWAT"},
			{Val: 19, Str: "SO_SNDLOWAT"},
			{Val: 19, Str: "SO_SNDLOWAT"},
			{Val: 20, Str: "SO_RCVTIMEO_OLD"},
			{Val: 20, Str: "SO_RCVTIMEO_OLD"},
			{Val: 20, Str: "SO_RCVTIMEO_OLD"},
			{Val: 20, Str: "SO_RCVTIMEO_OLD"},
			{Val: 20, Str: "SO_RCVTIMEO_OLD"},
			{Val: 21, Str: "SO_SNDTIMEO_OLD"},
			{Val: 21, Str: "SO_SNDTIMEO_OLD"},
			{Val: 21, Str: "SO_SNDTIMEO_OLD"},
			{Val: 21, Str: "SO_SNDTIMEO_OLD"},
			{Val: 21, Str: "SO_SNDTIMEO_OLD"},
			{Val: 22, Str: "SO_SECURITY_AUTHENTICATION"},
			{Val: 22, Str: "SO_SECURITY_AUTHENTICATION"},
			{Val: 22, Str: "SO_SECURITY_AUTHENTICATION"},
			{Val: 22, Str: "SO_SECURITY_AUTHENTICATION"},
			{Val: 23, Str: "SO_SECURITY_ENCRYPTION_TRANSPORT"},
			{Val: 23, Str: "SO_SECURITY_ENCRYPTION_TRANSPORT"},
			{Val: 23, Str: "SO_SECURITY_ENCRYPTION_TRANSPORT"},
			{Val: 23, Str: "SO_SECURITY_ENCRYPTION_TRANSPORT"},
			{Val: 24, Str: "SO_SECURITY_ENCRYPTION_NETWORK"},
			{Val: 24, Str: "SO_SECURITY_ENCRYPTION_NETWORK"},
			{Val: 24, Str: "SO_SECURITY_ENCRYPTION_NETWORK"},
			{Val: 24, Str: "SO_SECURITY_ENCRYPTION_NETWORK"},
			{Val: 25, Str: "SO_BINDTODEVICE"},
			{Val: 25, Str: "SO_BINDTODEVICE"},
			{Val: 25, Str: "SO_BINDTODEVICE"},
			{Val: 27, Str: "SO_DETACH_FILTER"},
			{Val: 27, Str: "SO_DETACH_FILTER"},
			{Val: 28, Str: "SO_PEERNAME"},
			{Val: 28, Str: "SO_PEERNAME"},
			{Val: 29, Str: "SO_TIMESTAMP_OLD"},
			{Val: 29, Str: "SO_TIMESTAMP_OLD"},
			{Val: 30, Str: "SO_ACCEPTCONN"},
			{Val: 30, Str: "SO_ACCEPTCONN"},
			{Val: 30, Str: "SO_ACCEPTCONN"},
			{Val: 30, Str: "SO_ACCEPTCONN"},
			{Val: 30, Str: "SO_ACCEPTCONN"},
			{Val: 31, Str: "SO_PEERSEC"},
			{Val: 31, Str: "SO_PEERSEC"},
			{Val: 31, Str: "SO_PEERSEC"},
			{Val: 32, Str: "SO_SNDBUFFORCE"},
			{Val: 32, Str: "SO_SNDBUFFORCE"},
			{Val: 32, Str: "SO_SNDBUFFORCE"},
			{Val: 33, Str: "SO_RCVBUFFORCE"},
			{Val: 33, Str: "SO_RCVBUFFORCE"},
			{Val: 34, Str: "SO_PASSSEC"},
			{Val: 34, Str: "SO_PASSSEC"},
			{Val: 34, Str: "SO_PASSSEC"},
			{Val: 35, Str: "SO_TIMESTAMPNS_OLD"},
			{Val: 35, Str: "SO_TIMESTAMPNS_OLD"},
			{Val: 35, Str: "SO_TIMESTAMPNS_OLD"},
			{Val: 36, Str: "SO_MARK"},
			{Val: 36, Str: "SO_MARK"},
			{Val: 36, Str: "SO_MARK"},
			{Val: 37, Str: "SO_TIMESTAMPING_OLD"},
			{Val: 37, Str: "SO_TIMESTAMPING_OLD"},
			{Val: 37, Str: "SO_TIMESTAMPING_OLD"},
			{Val: 38, Str: "SO_PROTOCOL"},
			{Val: 38, Str: "SO_PROTOCOL"},
			{Val: 39, Str: "SO_DOMAIN"},
			{Val: 39, Str: "SO_DOMAIN"},
			{Val: 40, Str: "SO_RXQ_OVFL"},
			{Val: 40, Str: "SO_RXQ_OVFL"},
			{Val: 40, Str: "SO_RXQ_OVFL"},
			{Val: 41, Str: "SO_WIFI_STATUS"},
			{Val: 41, Str: "SO_WIFI_STATUS"},
			{Val: 41, Str: "SO_WIFI_STATUS"},
			{Val: 42, Str: "SO_PEEK_OFF"},
			{Val: 42, Str: "SO_PEEK_OFF"},
			{Val: 42, Str: "SO_PEEK_OFF"},
			{Val: 43, Str: "SO_NOFCS"},
			{Val: 43, Str: "SO_NOFCS"},
			{Val: 43, Str: "SO_NOFCS"},
			{Val: 44, Str: "SO_LOCK_FILTER"},
			{Val: 44, Str: "SO_LOCK_FILTER"},
			{Val: 44, Str: "SO_LOCK_FILTER"},
			{Val: 45, Str: "SO_SELECT_ERR_QUEUE"},
			{Val: 45, Str: "SO_SELECT_ERR_QUEUE"},
			{Val: 45, Str: "SO_SELECT_ERR_QUEUE"},
			{Val: 46, Str: "SO_BUSY_POLL"},
			{Val: 46, Str: "SO_BUSY_POLL"},
			{Val: 46, Str: "SO_BUSY_POLL"},
			{Val: 47, Str: "SO_MAX_PACING_RATE"},
			{Val: 47, Str: "SO_MAX_PACING_RATE"},
			{Val: 47, Str: "SO_MAX_PACING_RATE"},
			{Val: 48, Str: "SO_BPF_EXTENSIONS"},
			{Val: 48, Str: "SO_BPF_EXTENSIONS"},
			{Val: 48, Str: "SO_BPF_EXTENSIONS"},
			{Val: 49, Str: "SO_INCOMING_CPU"},
			{Val: 49, Str: "SO_INCOMING_CPU"},
			{Val: 49, Str: "SO_INCOMING_CPU"},
			{Val: 50, Str: "SO_ATTACH_BPF"},
			{Val: 50, Str: "SO_ATTACH_BPF"},
			{Val: 50, Str: "SO_ATTACH_BPF"},
			{Val: 51, Str: "SO_ATTACH_REUSEPORT_CBPF"},
			{Val: 51, Str: "SO_ATTACH_REUSEPORT_CBPF"},
			{Val: 51, Str: "SO_ATTACH_REUSEPORT_CBPF"},
			{Val: 52, Str: "SO_ATTACH_REUSEPORT_EBPF"},
			{Val: 52, Str: "SO_ATTACH_REUSEPORT_EBPF"},
			{Val: 52, Str: "SO_ATTACH_REUSEPORT_EBPF"},
			{Val: 53, Str: "SO_CNX_ADVICE"},
			{Val: 53, Str: "SO_CNX_ADVICE"},
			{Val: 53, Str: "SO_CNX_ADVICE"},
			{Val: 55, Str: "SO_MEMINFO"},
			{Val: 55, Str: "SO_MEMINFO"},
			{Val: 55, Str: "SO_MEMINFO"},
			{Val: 56, Str: "SO_INCOMING_NAPI_ID"},
			{Val: 56, Str: "SO_INCOMING_NAPI_ID"},
			{Val: 56, Str: "SO_INCOMING_NAPI_ID"},
			{Val: 57, Str: "SO_COOKIE"},
			{Val: 57, Str: "SO_COOKIE"},
			{Val: 57, Str: "SO_COOKIE"},
			{Val: 59, Str: "SO_PEERGROUPS"},
			{Val: 59, Str: "SO_PEERGROUPS"},
			{Val: 59, Str: "SO_PEERGROUPS"},
			{Val: 60, Str: "SO_ZEROCOPY"},
			{Val: 60, Str: "SO_ZEROCOPY"},
			{Val: 60, Str: "SO_ZEROCOPY"},
			{Val: 61, Str: "SO_TXTIME"},
			{Val: 61, Str: "SO_TXTIME"},
			{Val: 61, Str: "SO_TXTIME"},
			{Val: 62, Str: "SO_BINDTOIFINDEX"},
			{Val: 62, Str: "SO_BINDTOIFINDEX"},
			{Val: 62, Str: "SO_BINDTOIFINDEX"},
			{Val: 63, Str: "SO_TIMESTAMP_NEW"},
			{Val: 63, Str: "SO_TIMESTAMP_NEW"},
			{Val: 63, Str: "SO_TIMESTAMP_NEW"},
			{Val: 64, Str: "SO_TIMESTAMPNS_NEW"},
			{Val: 64, Str: "SO_TIMESTAMPNS_NEW"},
			{Val: 64, Str: "SO_TIMESTAMPNS_NEW"},
			{Val: 65, Str: "SO_TIMESTAMPING_NEW"},
			{Val: 65, Str: "SO_TIMESTAMPING_NEW"},
			{Val: 65, Str: "SO_TIMESTAMPING_NEW"},
			{Val: 66, Str: "SO_RCVTIMEO_NEW"},
			{Val: 66, Str: "SO_RCVTIMEO_NEW"},
			{Val: 66, Str: "SO_RCVTIMEO_NEW"},
			{Val: 67, Str: "SO_SNDTIMEO_NEW"},
			{Val: 67, Str: "SO_SNDTIMEO_NEW"},
			{Val: 67, Str: "SO_SNDTIMEO_NEW"},
			{Val: 68, Str: "SO_DETACH_REUSEPORT_BPF"},
			{Val: 68, Str: "SO_DETACH_REUSEPORT_BPF"},
			{Val: 68, Str: "SO_DETACH_REUSEPORT_BPF"},
			{Val: 69, Str: "SO_PREFER_BUSY_POLL"},
			{Val: 69, Str: "SO_PREFER_BUSY_POLL"},
			{Val: 69, Str: "SO_PREFER_BUSY_POLL"},
			{Val: 70, Str: "SO_BUSY_POLL_BUDGET"},
			{Val: 70, Str: "SO_BUSY_POLL_BUDGET"},
			{Val: 70, Str: "SO_BUSY_POLL_BUDGET"},
			{Val: 71, Str: "SO_NETNS_COOKIE"},
			{Val: 71, Str: "SO_NETNS_COOKIE"},
			{Val: 71, Str: "SO_NETNS_COOKIE"},
			{Val: 72, Str: "SO_BUF_LOCK"},
			{Val: 72, Str: "SO_BUF_LOCK"},
			{Val: 72, Str: "SO_BUF_LOCK"},
			{Val: 73, Str: "SO_RESERVE_MEM"},
			{Val: 73, Str: "SO_RESERVE_MEM"},
			{Val: 73, Str: "SO_RESERVE_MEM"},
			{Val: 74, Str: "SO_TXREHASH"},
			{Val: 74, Str: "SO_TXREHASH"},
			{Val: 74, Str: "SO_TXREHASH"},
			{Val: 75, Str: "SO_RCVMARK"},
			{Val: 75, Str: "SO_RCVMARK"},
			{Val: 75, Str: "SO_RCVMARK"},
			{Val: 76, Str: "SO_PASSPIDFD"},
			{Val: 76, Str: "SO_PASSPIDFD"},
			{Val: 76, Str: "SO_PASSPIDFD"},
			{Val: 77, Str: "SO_PEERPIDFD"},
			{Val: 77, Str: "SO_PEERPIDFD"},
			{Val: 77, Str: "SO_PEERPIDFD"},
			{Val: 82, Str: "SO_RCVPRIORITY"},
			{Val: 82, Str: "SO_RCVPRIORITY"},
			{Val: 82, Str: "SO_RCVPRIORITY"},
			{Val: 83, Str: "SO_PASSRIGHTS"},
			{Val: 83, Str: "SO_PASSRIGHTS"},
			{Val: 83, Str: "SO_PASSRIGHTS"},
			{Val: 84, Str: "SO_INQ"},
			{Val: 84, Str: "SO_INQ"},
			{Val: 84, Str: "SO_INQ"},
		},
	},
	"sock_type_flags": {
		Prefix: "SOCK_",
		Entries: []XlatVal{
			{Val: 524288, Str: "SOCK_CLOEXEC"},
			{Val: 2048, Str: "SOCK_NONBLOCK"},
		},
	},
	"socketlayers": {
		Prefix: "AF_ SOL_",
		Entries: []XlatVal{
			{Val: 1, Str: "SOL_SOCKET"},
			{Val: 6, Str: "SOL_TCP"},
			{Val: 17, Str: "SOL_UDP"},
			{Val: 40, Str: "AF_VSOCK"},
			{Val: 41, Str: "SOL_IPV6"},
			{Val: 58, Str: "SOL_ICMPV6"},
			{Val: 100, Str: "SOL_CAN_BASE"},
			{Val: 101, Str: "SOL_CAN_RAW"},
			{Val: 132, Str: "SOL_SCTP"},
			{Val: 136, Str: "SOL_UDPLITE"},
			{Val: 255, Str: "SOL_RAW"},
			{Val: 256, Str: "SOL_IPX"},
			{Val: 257, Str: "SOL_AX25"},
			{Val: 258, Str: "SOL_ATALK"},
			{Val: 259, Str: "SOL_NETROM"},
			{Val: 260, Str: "SOL_ROSE"},
			{Val: 261, Str: "SOL_DECNET"},
			{Val: 262, Str: "SOL_X25"},
			{Val: 263, Str: "SOL_PACKET"},
			{Val: 264, Str: "SOL_ATM"},
			{Val: 265, Str: "SOL_AAL"},
			{Val: 266, Str: "SOL_IRDA"},
			{Val: 267, Str: "SOL_NETBEUI"},
			{Val: 268, Str: "SOL_LLC"},
			{Val: 269, Str: "SOL_DCCP"},
			{Val: 270, Str: "SOL_NETLINK"},
			{Val: 271, Str: "SOL_TIPC"},
			{Val: 272, Str: "SOL_RXRPC"},
			{Val: 273, Str: "SOL_PPPOL2TP"},
			{Val: 274, Str: "SOL_BLUETOOTH"},
			{Val: 275, Str: "SOL_PNPIPE"},
			{Val: 276, Str: "SOL_RDS"},
			{Val: 277, Str: "SOL_IUCV"},
			{Val: 278, Str: "SOL_CAIF"},
			{Val: 279, Str: "SOL_ALG"},
			{Val: 280, Str: "SOL_NFC"},
			{Val: 281, Str: "SOL_KCM"},
			{Val: 282, Str: "SOL_TLS"},
			{Val: 283, Str: "SOL_XDP"},
			{Val: 284, Str: "SOL_MPTCP"},
			{Val: 285, Str: "SOL_MCTP"},
			{Val: 286, Str: "SOL_SMC"},
			{Val: 287, Str: "SOL_VSOCK"},
			{Val: 1, Str: "SOL_SOCKET"},
		},
	},
	"umount_flags": {
		Prefix: "MNT_ UMOUNT_",
		Entries: []XlatVal{
			{Val: 1, Str: "MNT_FORCE"},
			{Val: 2, Str: "MNT_DETACH"},
			{Val: 4, Str: "MNT_EXPIRE"},
			{Val: 8, Str: "UMOUNT_NOFOLLOW"},
		},
	},
	"wait4_options": {
		Prefix: "W __W",
		Entries: []XlatVal{
			{Val: 1, Str: "WNOHANG"},
			{Val: 2, Str: "WUNTRACED"},
			{Val: 4, Str: "WEXITED"},
			{Val: 2, Str: "WSTOPPED"},
			{Val: 8, Str: "WCONTINUED"},
			{Val: 16777216, Str: "WNOWAIT"},
			{Val: 2147483648, Str: "__WCLONE"},
			{Val: 1073741824, Str: "__WALL"},
			{Val: 536870912, Str: "__WNOTHREAD"},
		},
	},
	"whence_codes": {
		Prefix: "SEEK_",
		Entries: []XlatVal{
			{Val: 0, Str: "SEEK_SET"},
			{Val: 1, Str: "SEEK_CUR"},
			{Val: 2, Str: "SEEK_END"},
			{Val: 3, Str: "SEEK_DATA"},
			{Val: 4, Str: "SEEK_HOLE"},
		},
	},
	"x86_xfeature_bits": {
		Prefix: "XFEATURE_",
		Entries: []XlatVal{
			{Val: 0, Str: "XFEATURE_FP"},
			{Val: 1, Str: "XFEATURE_SSE"},
			{Val: 2, Str: "XFEATURE_YMM"},
			{Val: 3, Str: "XFEATURE_BNDREGS"},
			{Val: 4, Str: "XFEATURE_BNDCSR"},
			{Val: 5, Str: "XFEATURE_OPMASK"},
			{Val: 6, Str: "XFEATURE_ZMM_Hi256"},
			{Val: 7, Str: "XFEATURE_Hi16_ZMM"},
			{Val: 8, Str: "XFEATURE_PT_UNIMPLEMENTED_SO_FAR"},
			{Val: 9, Str: "XFEATURE_PKRU"},
			{Val: 10, Str: "XFEATURE_PASID"},
			{Val: 15, Str: "XFEATURE_LBR"},
			{Val: 17, Str: "XFEATURE_XTILE_CFG"},
			{Val: 18, Str: "XFEATURE_XTILE_DATA"},
			{Val: 8, Str: "XFEATURE_PT_UNIMPLEMENTED_SO_FAR"},
			{Val: 15, Str: "XFEATURE_LBR"},
			{Val: 17, Str: "XFEATURE_XTILE_CFG"},
			{Val: 18, Str: "XFEATURE_XTILE_DATA"},
		},
	},
	"clocknames": {
		Prefix: "CLOCK_",
		Entries: []XlatVal{
			{Val: 3, Str: "CLOCK_THREAD_CPUTIME_ID"},
			{Val: 0, Str: "CLOCK_REALTIME"},
			{Val: 1, Str: "CLOCK_MONOTONIC"},
			{Val: 2, Str: "CLOCK_PROCESS_CPUTIME_ID"},
			{Val: 4, Str: "CLOCK_MONOTONIC_RAW"},
			{Val: 5, Str: "CLOCK_REALTIME_COARSE"},
			{Val: 6, Str: "CLOCK_MONOTONIC_COARSE"},
			{Val: 7, Str: "CLOCK_BOOTTIME"},
			{Val: 8, Str: "CLOCK_REALTIME_ALARM"},
			{Val: 9, Str: "CLOCK_BOOTTIME_ALARM"},
			{Val: 11, Str: "CLOCK_TAI"},
		},
	},
	"sigact_flags": {
		Prefix: "SA_",
		Entries: []XlatVal{
			{Val: 0x04000000, Str: "SA_RESTORER"},
			{Val: 1, Str: "SA_NOCLDSTOP"},
			{Val: 2, Str: "SA_NOCLDWAIT"},
			{Val: 4, Str: "SA_SIGINFO"},
			{Val: 0x08000000, Str: "SA_ONSTACK"},
			{Val: 0x10000000, Str: "SA_RESTART"},
			{Val: 0x20000000, Str: "SA_NODEFER"},
			{Val: 0x40000000, Str: "SA_RESETHAND"},
		},
	},
	"mount_flags": {
		Prefix: "MS_",
		Entries: []XlatVal{
			{Val: 0xc0ed0000, Str: "MS_MGC_VAL"},
			{Val: 1, Str: "MS_RDONLY"},
			{Val: 2, Str: "MS_NOSUID"},
			{Val: 4, Str: "MS_NODEV"},
			{Val: 8, Str: "MS_NOEXEC"},
			{Val: 16, Str: "MS_SYNCHRONOUS"},
			{Val: 32, Str: "MS_REMOUNT"},
			{Val: 64, Str: "MS_MANDLOCK"},
			{Val: 128, Str: "MS_DIRSYNC"},
			{Val: 256, Str: "MS_NOSYMFOLLOW"},
			{Val: 1024, Str: "MS_NOATIME"},
			{Val: 2048, Str: "MS_NODIRATIME"},
			{Val: 4096, Str: "MS_BIND"},
			{Val: 8192, Str: "MS_MOVE"},
			{Val: 16384, Str: "MS_REC"},
			{Val: 32768, Str: "MS_SILENT"},
			{Val: 65536, Str: "MS_POSIXACL"},
			{Val: 131072, Str: "MS_UNBINDABLE"},
			{Val: 262144, Str: "MS_PRIVATE"},
			{Val: 524288, Str: "MS_SLAVE"},
			{Val: 1048576, Str: "MS_SHARED"},
			{Val: 2097152, Str: "MS_RELATIME"},
			{Val: 4194304, Str: "MS_KERNMOUNT"},
			{Val: 8388608, Str: "MS_I_VERSION"},
			{Val: 16777216, Str: "MS_STRICTATIME"},
			{Val: 33554432, Str: "MS_LAZYTIME"},
			{Val: 0x10000000, Str: "MS_NOREMOTELOCK"},
			{Val: 0x20000000, Str: "MS_NOSEC"},
			{Val: 0x40000000, Str: "MS_BORN"},
			{Val: 0x80000000, Str: "MS_ACTIVE"},
			{Val: 0x4000000, Str: "MS_SUBMOUNT"},
			{Val: 0x2000000, Str: "MS_NOUSER"},
		},
	},
	"protocols": {
		Prefix: "IPPROTO_",
		Entries: []XlatVal{
			{Val: 0, Str: "IPPROTO_IP"},
			{Val: 1, Str: "IPPROTO_ICMP"},
			{Val: 2, Str: "IPPROTO_IGMP"},
			{Val: 6, Str: "IPPROTO_TCP"},
			{Val: 17, Str: "IPPROTO_UDP"},
			{Val: 41, Str: "IPPROTO_IPV6"},
			{Val: 58, Str: "IPPROTO_ICMPV6"},
			{Val: 255, Str: "IPPROTO_RAW"},
		},
	},
	"signalnames": {
		Prefix: "SIG",
		Entries: []XlatVal{
			{Val: 1, Str: "SIGHUP"},
			{Val: 2, Str: "SIGINT"},
			{Val: 3, Str: "SIGQUIT"},
			{Val: 4, Str: "SIGILL"},
			{Val: 5, Str: "SIGTRAP"},
			{Val: 6, Str: "SIGABRT"},
			{Val: 7, Str: "SIGBUS"},
			{Val: 8, Str: "SIGFPE"},
			{Val: 9, Str: "SIGKILL"},
			{Val: 10, Str: "SIGUSR1"},
			{Val: 11, Str: "SIGSEGV"},
			{Val: 12, Str: "SIGUSR2"},
			{Val: 13, Str: "SIGPIPE"},
			{Val: 14, Str: "SIGALRM"},
			{Val: 15, Str: "SIGTERM"},
			{Val: 16, Str: "SIGSTKFLT"},
			{Val: 17, Str: "SIGCHLD"},
			{Val: 18, Str: "SIGCONT"},
			{Val: 19, Str: "SIGSTOP"},
			{Val: 20, Str: "SIGTSTP"},
			{Val: 21, Str: "SIGTTIN"},
			{Val: 22, Str: "SIGTTOU"},
			{Val: 23, Str: "SIGURG"},
			{Val: 24, Str: "SIGXCPU"},
			{Val: 25, Str: "SIGXFSZ"},
			{Val: 26, Str: "SIGVTALRM"},
			{Val: 27, Str: "SIGPROF"},
			{Val: 28, Str: "SIGWINCH"},
			{Val: 29, Str: "SIGIO"},
			{Val: 30, Str: "SIGPWR"},
			{Val: 31, Str: "SIGSYS"},
		},
	},
	"clone3_flags": {
		Prefix: "CLONE_",
		Entries: []XlatVal{
			{Val: 0x00000100, Str: "CLONE_VM"},
			{Val: 0x00000200, Str: "CLONE_FS"},
			{Val: 0x00000400, Str: "CLONE_FILES"},
			{Val: 0x00000800, Str: "CLONE_SIGHAND"},
			{Val: 0x00001000, Str: "CLONE_PIDFD"},
			{Val: 0x00002000, Str: "CLONE_PTRACE"},
			{Val: 0x00004000, Str: "CLONE_VFORK"},
			{Val: 0x00008000, Str: "CLONE_PARENT"},
			{Val: 0x00010000, Str: "CLONE_THREAD"},
			{Val: 0x00020000, Str: "CLONE_NEWNS"},
			{Val: 0x00040000, Str: "CLONE_SYSVSEM"},
			{Val: 0x00080000, Str: "CLONE_SETTLS"},
			{Val: 0x00100000, Str: "CLONE_PARENT_SETTID"},
			{Val: 0x00200000, Str: "CLONE_CHILD_CLEARTID"},
			{Val: 0x00800000, Str: "CLONE_UNTRACED"},
			{Val: 0x01000000, Str: "CLONE_CHILD_SETTID"},
			{Val: 0x02000000, Str: "CLONE_NEWCGROUP"},
			{Val: 0x04000000, Str: "CLONE_NEWUTS"},
			{Val: 0x08000000, Str: "CLONE_NEWIPC"},
			{Val: 0x10000000, Str: "CLONE_NEWUSER"},
			{Val: 0x20000000, Str: "CLONE_NEWPID"},
			{Val: 0x40000000, Str: "CLONE_NEWNET"},
			{Val: 0x80000000, Str: "CLONE_IO"},
			{Val: 128, Str: "CLONE_NEWTIME"},
			{Val: 4294967296, Str: "CLONE_CLEAR_SIGHAND"},
			{Val: 8589934592, Str: "CLONE_INTO_CGROUP"},
			{Val: 17179869184, Str: "CLONE_AUTOREAP"},
			{Val: 34359738368, Str: "CLONE_NNP"},
			{Val: 68719476736, Str: "CLONE_PIDFD_AUTOKILL"},
			{Val: 137438953472, Str: "CLONE_EMPTY_MNTNS"},
		},
	},
	"x86_xfeatures": {
		Prefix: "XFEATURE_MASK_",
		Entries: []XlatVal{
			{Val: 0x3, Str: "XFEATURE_MASK_FPSSE"},
			{Val: 0xe0, Str: "XFEATURE_MASK_AVX512"},
			{Val: 0x60000, Str: "XFEATURE_MASK_XTILE"},
			{Val: 0x1, Str: "XFEATURE_MASK_FP"},
			{Val: 0x2, Str: "XFEATURE_MASK_SSE"},
			{Val: 0x4, Str: "XFEATURE_MASK_YMM"},
			{Val: 0x8, Str: "XFEATURE_MASK_BNDREGS"},
			{Val: 0x10, Str: "XFEATURE_MASK_BNDCSR"},
			{Val: 0x20, Str: "XFEATURE_MASK_OPMASK"},
			{Val: 0x40, Str: "XFEATURE_MASK_ZMM_Hi256"},
			{Val: 0x80, Str: "XFEATURE_MASK_Hi16_ZMM"},
			{Val: 0x100, Str: "XFEATURE_MASK_PT"},
			{Val: 0x200, Str: "XFEATURE_MASK_PKRU"},
			{Val: 0x400, Str: "XFEATURE_MASK_PASID"},
			{Val: 0x8000, Str: "XFEATURE_MASK_LBR"},
			{Val: 0x20000, Str: "XFEATURE_MASK_XTILE_CFG"},
			{Val: 0x40000, Str: "XFEATURE_MASK_XTILE_DATA"},
		},
	},
}
var SyscallArgXlatMap = map[string]map[string]string{
	"mprotect": {
		"prot": "mmap_prot",
	},
	"mremap": {
		"flags": "mremap_flags",
	},
	"getpeername": {
		"addr": "sockaddr",
	},
	"clock_adjtime": {
		"which_clock": "clocknames",
	},
	"epoll_create1": {
		"flags": "epollflags",
	},
	"clone": {
		"clone_flags": "clone_flags",
	},
	"madvise": {
		"behavior": "madvise_cmds",
	},
	"arch_prctl": {
		"option": "archvals",
	},
	"setsockopt": {
		"level": "socketlayers",
	},
	"lseek": {
		"whence": "whence_codes",
	},
	"umount2": {
		"flags": "umount_flags",
	},
	"faccessat": {
		"mode": "access_modes",
	},
	"accept4": {
		"flags": "sock_type_flags",
	},
	"bind": {
		"addr": "sockaddr",
	},
	"futex": {
		"op": "futexops",
	},
	"wait4": {
		"options": "wait4_options",
	},
	"rt_sigprocmask": {
		"how": "sigprocmaskcmds",
	},
	"access": {
		"mode": "access_modes",
	},
	"openat": {
		"flags": "open_mode_flags",
	},
	"connect": {
		"addr": "sockaddr",
	},
	"epoll_ctl": {
		"op": "epollctls",
	},
	"open": {
		"flags": "open_mode_flags",
	},
	"faccessat2": {
		"mode": "access_modes",
	},
	"add_key": {
		"ringid": "key_spec",
	},
	"sendto": {
		"addr": "sockaddr",
	},
	"ppoll": {
		"revents": "pollflags",
		"events": "pollflags",
	},
	"clock_settime": {
		"which_clock": "clocknames",
	},
	"mmap": {
		"prot": "mmap_prot",
		"flags": "mmap_flags",
	},
	"clone3": {
		"flags": "clone3_flags",
	},
	"request_key": {
		"destringid": "key_spec",
	},
	"socket": {
		"domain": "addrfams",
		"type": "sock_type_flags",
	},
	"getsockopt": {
		"level": "socketlayers",
	},
	"bpf": {
		"arg0": "bpf_commands",
	},
	"clock_nanosleep": {
		"which_clock": "clocknames",
	},
	"prctl": {
		"option": "prctl_options",
	},
	"mount": {
		"flags": "mount_flags",
	},
	"poll": {
		"events": "pollflags",
		"revents": "pollflags",
	},
	"recvfrom": {
		"addr": "sockaddr",
	},
	"getsockname": {
		"addr": "sockaddr",
	},
}
