package main

import (
	"fmt"
	"os"
	"strings"
)

func writeBPFCaptureHeader(path string, syscalls map[int]SyscallMeta) error {
	var out strings.Builder

	fmt.Fprintln(&out, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(&out, "#ifndef __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(&out, "#define __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(&out)

	fmt.Fprintln(&out, "#define CAPTURE_ARGS_ENTER(sys_id, e) \\")
	fmt.Fprintln(&out, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfEnterCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(&out, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(&out, "\t}")

	fmt.Fprintln(&out, "#define CAPTURE_ARGS_EXIT(sys_id, e) \\")
	fmt.Fprintln(&out, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfExitCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(&out, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(&out, "\t}")
	fmt.Fprintln(&out, "#endif")
	if err := os.WriteFile(path, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func bpfEnterCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Enter, "enter", name)
			}
		}
	}
	return ""
}

func bpfExitCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Exit, "exit", name)
			}
		}
	}
	return ""
}

// generateBPFCode generates eBPF C code to capture syscall arguments.
func generateBPFCode(p CapturePoint, suffix string, scName string) string {
	res := ""
	for _, r := range p.Reads {
		res += generateCaptureReadCode(r, suffix, scName)
	}
	return res
}

func generateCaptureReadCode(r CaptureRead, suffix string, scName string) string {
	fn := probeReadFunc(r)
	buf := captureBufferExpr(r)
	sizeStr := captureSizeExpr(scName, suffix, r)

	res := "\t\t\t{ \\\n"
	res += dynamicPreludeCode(scName, r)
	res += readProbeCode(r, fn, buf, sizeStr)
	res += probeAccountingCode(r, suffix)
	res += "\t\t\t} \\\n"
	return res
}

func probeReadFunc(r CaptureRead) string {
	if r.Type == "string" {
		return "bpf_probe_read_user_str"
	}
	return "bpf_probe_read_user"
}

func captureBufferExpr(r CaptureRead) string {
	buf := "(e)->str_arg"
	if r.Offset != 0 {
		buf += fmt.Sprintf(" + %d", r.Offset)
	}
	return buf
}

func captureSizeExpr(scName string, suffix string, r CaptureRead) string {
	if r.Size == 0 {
		if size, ok := policyDynamicSizeExpr(r); ok {
			return size
		}
		return "0"
	}
	return fmt.Sprintf("%d", r.Size)
}

func policyDynamicSizeExpr(r CaptureRead) (string, bool) {
	if r.Max <= 0 {
		return "", false
	}
	if r.LenFromArg != nil {
		arg := *r.LenFromArg
		if r.Min > 0 {
			return fmt.Sprintf("((e)->args[%d] >= %d ? ((e)->args[%d] > %d ? %d : (e)->args[%d]) : 0)", arg, r.Min, arg, r.Max, r.Max, arg), true
		}
		return fmt.Sprintf("((e)->args[%d] > 0 ? ((e)->args[%d] > %d ? %d : (e)->args[%d]) : 0)", arg, arg, r.Max, r.Max, arg), true
	}
	if r.LenFromRet {
		return fmt.Sprintf("((e)->ret > 0 ? ((e)->ret > %d ? %d : (e)->ret) : 0)", r.Max, r.Max), true
	}
	if r.LenFromUserArg != nil {
		return "addrlen", true
	}
	if r.LenFromArgBits != nil {
		return "iosz", true
	}
	if r.LenFromArgCases != nil {
		return "fsz", true
	}
	if r.StringBytesSwitch != nil {
		return "switchsz", true
	}
	if r.CountFromArg != nil {
		arg := *r.CountFromArg
		if r.SplitFirst > 0 {
			return "countsz", true
		}
		return fmt.Sprintf("((e)->args[%d] > 0 ? ((e)->args[%d] * %d > %d ? %d : (e)->args[%d] * %d) : 0)", arg, arg, r.ElemSize, r.Max, r.Max, arg, r.ElemSize), true
	}
	if r.CountFromRet {
		return fmt.Sprintf("((e)->ret > 0 ? ((e)->ret * %d > %d ? %d : (e)->ret * %d) : 0)", r.ElemSize, r.Max, r.Max, r.ElemSize), true
	}
	return "", false
}

func dynamicPreludeCode(scName string, r CaptureRead) string {
	res := ""
	if r.Size == 0 && r.LenFromUserArg != nil {
		lenArg := *r.LenFromUserArg
		res += fmt.Sprintf("\t\t\t\tu32 addrlen = 0; \\\n")
		res += fmt.Sprintf("\t\t\t\tbpf_probe_read_user(&addrlen, 4, (void *)(e)->args[%d]); \\\n", lenArg)
		if r.ClampU32FromOffset != nil {
			res += fmt.Sprintf("\t\t\t\tu32 inlen = *(u32 *)((e)->str_arg + %d); \\\n", *r.ClampU32FromOffset)
			res += fmt.Sprintf("\t\t\t\tif (inlen > 0 && inlen < addrlen) addrlen = inlen; \\\n")
		}
		res += fmt.Sprintf("\t\t\t\taddrlen = (addrlen > %d) ? %d : addrlen; \\\n", r.Max, r.Max)
	} else if r.Size == 0 && r.LenFromArgBits != nil {
		bits := r.LenFromArgBits
		res += fmt.Sprintf("\t\t\t\tu32 iosz = (((e)->args[%d] >> %d) & %#x); \\\n", bits.Arg, bits.Shift, bits.Mask)
		res += fmt.Sprintf("\t\t\t\tiosz = (iosz == 0) ? %d : (iosz > %d ? %d : iosz); \\\n", bits.ZeroLen, r.Max, r.Max)
	} else if r.Size == 0 && r.LenFromArgCases != nil {
		res += argCasesPreludeCode(r.LenFromArgCases)
	} else if r.Size == 0 && r.CountFromArg != nil && r.SplitFirst > 0 {
		res += countSplitPreludeCode(r)
	} else if r.Size == 0 && r.StringBytesSwitch != nil {
		res += stringBytesSwitchPreludeCode(r)
	}
	return res
}

func stringBytesSwitchPreludeCode(r CaptureRead) string {
	sw := r.StringBytesSwitch
	res := "\t\t\t\tu32 switchsz = 0; \\\n"
	res += fmt.Sprintf("\t\t\t\tif ((e)->args[%d] == %d) { \\\n", sw.SelectorArg, sw.BytesValue)
	res += fmt.Sprintf("\t\t\t\t\tswitchsz = (e)->args[%d]; \\\n", sw.LenFromArg)
	if sw.LenMask > 0 {
		res += fmt.Sprintf("\t\t\t\t\tswitchsz &= %#x; \\\n", sw.LenMask)
	}
	res += fmt.Sprintf("\t\t\t\t\tswitchsz = (switchsz > %d) ? %d : switchsz; \\\n", r.Max, r.Max)
	res += "\t\t\t\t} \\\n"
	return res
}

func countSplitPreludeCode(r CaptureRead) string {
	arg := *r.CountFromArg
	maxCount := r.Max / r.ElemSize
	res := fmt.Sprintf("\t\t\t\tu32 count = (u32)(e)->args[%d]; \\\n", arg)
	res += fmt.Sprintf("\t\t\t\tif (count > %d) count = %d; \\\n", maxCount, maxCount)
	res += fmt.Sprintf("\t\t\t\tu32 countsz = count * %d; \\\n", r.ElemSize)
	return res
}

func argCasesPreludeCode(cases *ArgCasesLength) string {
	res := fmt.Sprintf("\t\t\t\tu32 fcmd = (u32)(e)->args[%d]; \\\n", cases.Arg)
	res += fmt.Sprintf("\t\t\t\tu32 fsz = 0; \\\n")
	for i, c := range cases.Cases {
		prefix := "if"
		if i > 0 {
			prefix = "else if"
		}
		res += fmt.Sprintf("\t\t\t\t%s (%s) fsz = %d; \\\n", prefix, argCaseCondition("fcmd", c.Values), c.Size)
	}
	return res
}

func argCaseCondition(name string, values []int) string {
	res := ""
	for i, value := range values {
		if i > 0 {
			res += " || "
		}
		res += fmt.Sprintf("%s == %d", name, value)
	}
	return res
}

func readProbeCode(r CaptureRead, fn string, buf string, sizeStr string) string {
	switch {
	case sizeStr == "fsz":
		return fmt.Sprintf("\t\t\t\tlong __err = (fsz > 0 && (e)->args[%d]) ? %s(%s, fsz, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, r.Arg) +
			fmt.Sprintf("\t\t\t\tlong pr = (__err == 0 && fsz > 0 && (e)->args[%d]) ? fsz : __err; \\\n", r.Arg)
	case r.SplitFirst > 0 && sizeStr == "countsz":
		return splitCountReadProbeCode(r, buf, sizeStr)
	case r.StringBytesSwitch != nil && sizeStr == "switchsz":
		return stringBytesSwitchReadProbeCode(r, buf, sizeStr)
	case r.Type == "string" && r.Size > 2048:
		return splitStringReadProbeCode(r, buf)
	case r.Type == "string":
		return fmt.Sprintf("\t\t\t\tlong pr = (e)->args[%d] ? %s(%s, %s, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, sizeStr, r.Arg)
	case r.Type == "double_ptr":
		return fmt.Sprintf("\t\t\t\tvoid *__ptr = NULL; \\\n") +
			fmt.Sprintf("\t\t\t\tlong __err1 = (e)->args[%d] ? bpf_probe_read_user(&__ptr, sizeof(void*), (void *)(e)->args[%d]) : 0; \\\n", r.Arg, r.Arg) +
			fmt.Sprintf("\t\t\t\tlong __err = (__err1 == 0 && __ptr) ? %s(%s, %s, __ptr) : __err1; \\\n", fn, buf, sizeStr) +
			fmt.Sprintf("\t\t\t\tlong pr = (__err == 0 && __ptr) ? %s : __err; \\\n", sizeStr)
	default:
		return fmt.Sprintf("\t\t\t\tlong __err = (e)->args[%d] ? %s(%s, %s, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, sizeStr, r.Arg) +
			fmt.Sprintf("\t\t\t\tlong pr = (__err == 0 && (e)->args[%d]) ? %s : __err; \\\n", r.Arg, sizeStr)
	}
}

func stringBytesSwitchReadProbeCode(r CaptureRead, buf string, sizeStr string) string {
	sw := r.StringBytesSwitch
	return fmt.Sprintf("\t\t\t\tlong pr = 0; \\\n") +
		fmt.Sprintf("\t\t\t\tif ((e)->args[%d] == %d) { \\\n", sw.SelectorArg, sw.BytesValue) +
		fmt.Sprintf("\t\t\t\t\tif (%s > 0 && (e)->args[%d]) { \\\n", sizeStr, r.Arg) +
		fmt.Sprintf("\t\t\t\t\t\tint __err = bpf_probe_read_user(%s, %s, (void *)(e)->args[%d]); \\\n", buf, sizeStr, r.Arg) +
		fmt.Sprintf("\t\t\t\t\t\tpr = (__err == 0) ? %s : __err; \\\n", sizeStr) +
		fmt.Sprintf("\t\t\t\t\t} \\\n") +
		fmt.Sprintf("\t\t\t\t} else if ((e)->args[%d]) { \\\n", r.Arg) +
		fmt.Sprintf("\t\t\t\t\tpr = bpf_probe_read_user_str(%s, %d, (void *)(e)->args[%d]); \\\n", buf, r.Max, r.Arg) +
		fmt.Sprintf("\t\t\t\t} \\\n")
}

func splitCountReadProbeCode(r CaptureRead, buf string, sizeStr string) string {
	restVar := sizeStr + "_rest"
	return fmt.Sprintf("\t\t\t\tlong pr = 0; \\\n") +
		fmt.Sprintf("\t\t\t\tif (%s > 0 && (e)->args[%d]) { \\\n", sizeStr, r.Arg) +
		fmt.Sprintf("\t\t\t\t\tlong __err = bpf_probe_read_user(%s, %d, (void *)(e)->args[%d]); \\\n", buf, r.SplitFirst, r.Arg) +
		fmt.Sprintf("\t\t\t\t\tif (__err < 0) { \\\n") +
		fmt.Sprintf("\t\t\t\t\t\tpr = __err; \\\n") +
		fmt.Sprintf("\t\t\t\t\t} else { \\\n") +
		fmt.Sprintf("\t\t\t\t\t\tpr = %d; \\\n", r.SplitFirst) +
		fmt.Sprintf("\t\t\t\t\t\tu32 %s = 0; \\\n", restVar) +
		fmt.Sprintf("\t\t\t\t\t\tif (%s > %d) %s = %s - %d; \\\n", sizeStr, r.SplitFirst, restVar, sizeStr, r.SplitFirst) +
		fmt.Sprintf("\t\t\t\t\t\tif (%s > 0) { \\\n", restVar) +
		fmt.Sprintf("\t\t\t\t\t\t\tlong __err2 = bpf_probe_read_user(%s + %d, %s, (void *)((e)->args[%d] + %d)); \\\n", buf, r.SplitFirst, restVar, r.Arg, r.SplitFirst) +
		fmt.Sprintf("\t\t\t\t\t\t\tif (__err2 == 0) pr = %s; \\\n", sizeStr) +
		fmt.Sprintf("\t\t\t\t\t\t} \\\n") +
		fmt.Sprintf("\t\t\t\t\t} \\\n") +
		fmt.Sprintf("\t\t\t\t} \\\n")
}

func splitStringReadProbeCode(r CaptureRead, buf string) string {
	remain := r.Size - 2047
	return fmt.Sprintf("\t\t\t\tlong pr = 0; \\\n") +
		fmt.Sprintf("\t\t\t\tif ((e)->args[%d]) { \\\n", r.Arg) +
		fmt.Sprintf("\t\t\t\t\t(%s)[0] = 0; \\\n", buf) +
		fmt.Sprintf("\t\t\t\t\tpr = bpf_probe_read_user_str(%s, 2048, (void *)(e)->args[%d]); \\\n", buf, r.Arg) +
		fmt.Sprintf("\t\t\t\t\tif (pr < 0) { (%s)[0] = 0; } \\\n", buf) +
		fmt.Sprintf("\t\t\t\t\telse if (pr >= 2048) { \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t(%s + 2047)[0] = 0; \\\n", buf) +
		fmt.Sprintf("\t\t\t\t\t\tlong pr2 = bpf_probe_read_user_str(%s + 2047, %d, (void *)((e)->args[%d] + 2047)); \\\n", buf, remain, r.Arg) +
		fmt.Sprintf("\t\t\t\t\t\tif (pr2 >= 0) { \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t\tpr = 2047 + pr2; \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t\tif (pr == 4096) { \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t\t\tchar last_byte = 0; \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t\t\tbpf_probe_read_user(&last_byte, 1, (void *)((e)->args[%d] + 4095)); \\\n", r.Arg) +
		fmt.Sprintf("\t\t\t\t\t\t\t\t(%s + 4095)[0] = last_byte; \\\n", buf) +
		fmt.Sprintf("\t\t\t\t\t\t\t} \\\n") +
		fmt.Sprintf("\t\t\t\t\t\t} else { pr = pr2; (%s + 2047)[0] = 0; } \\\n", buf) +
		fmt.Sprintf("\t\t\t\t\t} \\\n") +
		fmt.Sprintf("\t\t\t\t} \\\n")
}

func probeAccountingCode(r CaptureRead, suffix string) string {
	bitOffset := r.Arg
	if r.Type == "double_ptr" {
		bitOffset += 8
	}
	return fmt.Sprintf("\t\t\t\tif (pr < 0) { \\\n") +
		fmt.Sprintf("\t\t\t\t\ts32 curr = (e)->probe_ret_%s; \\\n", suffix) +
		fmt.Sprintf("\t\t\t\t\tu32 mask = (curr < -1) ? (u32)(-curr - 1) : 0; \\\n") +
		fmt.Sprintf("\t\t\t\t\t(e)->probe_ret_%s = -(s32)((mask | (1 << %d)) + 1); \\\n", suffix, bitOffset) +
		fmt.Sprintf("\t\t\t\t} else { \\\n") +
		fmt.Sprintf("\t\t\t\t\tif ((e)->probe_ret_%s == -1) (e)->probe_ret_%s = 0; \\\n", suffix, suffix) +
		fmt.Sprintf("\t\t\t\t\tu32 req_len = %d + pr; \\\n", r.Offset) +
		fmt.Sprintf("\t\t\t\t\tif ((e)->data_len < req_len) (e)->data_len = req_len; \\\n") +
		fmt.Sprintf("\t\t\t\t} \\\n")
}
