package main

import (
	"fmt"
	"os"
)

func writeBPFCaptureHeader(path string, syscalls map[int]SyscallMeta) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()

	fmt.Fprintln(f, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(f, "#ifndef __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f, "#define __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f)

	fmt.Fprintln(f, "#define CAPTURE_ARGS_ENTER(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfEnterCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")

	fmt.Fprintln(f, "#define CAPTURE_ARGS_EXIT(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfExitCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "#endif")
	return nil
}
