package main

import (
	"fmt"
	"os"
	"strings"
)

func writeGoSyscallTable(path string, syscalls map[int]SyscallMeta) error {
	gf, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer gf.Close()

	fmt.Fprintln(gf, "package meta")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "var SyscallTable = map[uint32]Syscall{")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		fmt.Fprintf(gf, "\t%d: {Name: %q, Args: []string{%s}, ArgTypes: []string{%s}, Flags: %q},\n",
			id, meta.Name, formatStringSlice(meta.Args), formatStringSlice(meta.ArgTypes), meta.Flags)
	}
	fmt.Fprintln(gf, "}")
	return nil
}

func formatStringSlice(s []string) string {
	var quoted []string
	for _, v := range s {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return strings.Join(quoted, ", ")
}
