package main

import (
	"fmt"
	"sort"
	"strings"
)

type goSyscallTableWriter struct{}

func (goSyscallTableWriter) Write(path string, syscalls map[int]SyscallMeta) error {
	return writeGoSyscallTable(path, syscalls)
}

func writeGoSyscallTable(path string, syscalls map[int]SyscallMeta) error {
	return writeGeneratedOutput(path, renderGoSyscallTable(syscalls), false)
}

func renderGoSyscallTable(syscalls map[int]SyscallMeta) []byte {
	var out strings.Builder

	fmt.Fprintln(&out, "package meta")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var SyscallTable = map[uint32]Syscall{")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		fmt.Fprintf(&out, "\t%d: {Name: %q, Args: []string{%s}, ArgTypes: []string{%s}, Flags: %q},\n",
			id, meta.Name, formatStringSlice(meta.Args), formatStringSlice(meta.ArgTypes), meta.Flags)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var RuntimeSyscallVariables = map[string]string{")
	for _, variable := range sortedRuntimeABIVariables() {
		fmt.Fprintf(&out, "\t%q: %q,\n", variable.variableName, variable.syscallName)
	}
	fmt.Fprintln(&out, "}")
	return []byte(out.String())
}

func sortedRuntimeABIVariables() []runtimeABIVariable {
	variables := append([]runtimeABIVariable(nil), runtimeABIVariables...)
	sort.Slice(variables, func(i, j int) bool {
		return variables[i].variableName < variables[j].variableName
	})
	return variables
}

func sortedKeys(m map[int]SyscallMeta) []int {
	ids := make([]int, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	return ids
}

func formatStringSlice(s []string) string {
	var quoted []string
	for _, v := range s {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return strings.Join(quoted, ", ")
}
