package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

type goSyscallTableWriter struct{}

func (goSyscallTableWriter) Write(path string, syscalls map[int]SyscallMeta) error {
	return writeGoSyscallTable(path, syscalls)
}

func writeGoSyscallTable(path string, syscalls map[int]SyscallMeta) error {
	var out strings.Builder

	fmt.Fprintln(&out, "package meta")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var SyscallTable = map[uint32]Syscall{")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		fmt.Fprintf(&out, "\t%d: {Name: %q, Args: []string{%s}, ArgTypes: []string{%s}, Flags: %q},\n",
			id, meta.Name, formatStringSlice(meta.Args), formatStringSlice(meta.ArgTypes), meta.Flags)
	}
	fmt.Fprintln(&out, "}")
	if err := os.WriteFile(path, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func sortedKeys(m map[int]SyscallMeta) []int {
	ids := make([]int, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	return ids
}

func formatStringSlice(s []string) string {
	var quoted []string
	for _, v := range s {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return strings.Join(quoted, ", ")
}
