package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v2"
)

type SyscallMeta struct {
	Name     string
	Args     []string
	ArgTypes []string
}

type CaptureRule struct {
	Syscalls []string     `yaml:"syscalls"`
	Enter    CapturePoint `yaml:"enter"`
	Exit     CapturePoint `yaml:"exit"`
}

type CapturePoint struct {
	PtrArg *int          `yaml:"ptr_arg"`
	Reads  []CaptureRead `yaml:"reads"`
}

type CaptureRead struct {
	Arg    int    `yaml:"arg"`
	Size   int    `yaml:"size"`
	Offset int    `yaml:"offset"`
	Type   string `yaml:"type"`
}

type Config struct {
	Rules []CaptureRule `yaml:"rules"`
}

var globalConfig Config

func main() {
	configData, err := ioutil.ReadFile("capture_rules.yaml")
	if err != nil {
		log.Fatalf("failed to read capture_rules.yaml: %v", err)
	}
	if err := yaml.Unmarshal(configData, &globalConfig); err != nil {
		log.Fatalf("failed to unmarshal capture_rules.yaml: %v", err)
	}

	syscalls, err := LoadSyscalls()
	if err != nil {
		log.Fatalf("failed to load syscalls: %v", err)
	}

	// Generate BPF capture header
	f, err := os.Create("../../bpf/syscall_capture.h")
	if err != nil {
		log.Fatalf("failed to create syscall_capture.h: %v", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(f, "#ifndef __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f, "#define __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f)

	fmt.Fprintln(f, "#define CAPTURE_ARGS_ENTER(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfEnterCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")

	fmt.Fprintln(f, "#define CAPTURE_ARGS_EXIT(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfExitCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "#endif")

	// Generate Go syscall table
	gf, err := os.Create("../../pkg/meta/syscall_table.go")
	if err != nil {
		log.Fatalf("failed to create syscall_table.go: %v", err)
	}
	defer gf.Close()

	fmt.Fprintln(gf, "package meta")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "var SyscallTable = map[uint32]Syscall{")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		fmt.Fprintf(gf, "\t%d: {Name: %q, Args: []string{%s}, ArgTypes: []string{%s}},\n",
			id, meta.Name, formatStringSlice(meta.Args), formatStringSlice(meta.ArgTypes))
	}
	fmt.Fprintln(gf, "}")
}

func formatStringSlice(s []string) string {
	var quoted []string
	for _, v := range s {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return strings.Join(quoted, ", ")
}

func bpfEnterCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Enter, "enter", name)
			}
		}
	}
	return ""
}

func bpfExitCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Exit, "exit", name)
			}
		}
	}
	return ""
}

func dynamicSizeStr(scName string, suffix string, r CaptureRead) string {
	switch scName {
	case "accept", "accept4", "getsockname", "getpeername", "recvfrom":
		if r.Arg == 1 || r.Arg == 4 {
			return "addrlen"
		}
	case "fcntl", "fcntl64":
		if r.Arg == 2 {
			return "fsz"
		}
	case "add_key":
		if r.Arg == 2 {
			return "((e)->args[3] > 0 ? ((e)->args[3] > 256 ? 256 : (e)->args[3]) : 0)"
		}
	case "setxattr", "lsetxattr", "fsetxattr", "getxattr", "lgetxattr", "fgetxattr":
		if r.Arg == 2 {
			return "((e)->args[3] > 0 ? ((e)->args[3] > 256 ? 256 : (e)->args[3]) : 0)"
		}
	case "listxattr", "llistxattr", "flistxattr":
		if r.Arg == 1 {
			return "((e)->args[2] > 0 ? ((e)->args[2] > 256 ? 256 : (e)->args[2]) : 0)"
		}
	case "epoll_ctl":
		if r.Arg == 1 {
			return "((e)->args[2] > 0 ? ((e)->args[2] > 512 ? 512 : (e)->args[2]) : 0)"
		}
	case "bpf":
		if r.Arg == 1 {
			return "((e)->args[2] > 0 ? ((e)->args[2] > 512 ? 512 : (e)->args[2]) : 0)"
		}
	case "clone3":
		if r.Arg == 0 {
			return "((e)->args[1] > 0 ? ((e)->args[1] > 256 ? 256 : (e)->args[1]) : 0)"
		}
	case "ioctl":
		if r.Arg == 2 {
			return "iosz"
		}
	case "fsconfig":
		if r.Arg == 3 {
			return "fssz"
		}
	case "readlink", "readlinkat":
		return "((e)->ret > 0 ? ((e)->ret > 512 ? 512 : (e)->ret) : 0)"
	}

	if suffix == "exit" {
		return "((e)->ret > 0 ? ((e)->ret * 32 > 512 ? 512 : (e)->ret * 32) : 0)"
	}
	return "((e)->args[1] > 0 ? ((e)->args[1] * 8 > 512 ? 512 : (e)->args[1] * 8) : 0)"
}

// generateBPFCode generates eBPF C code to capture syscall arguments.
// Impact: Called by bpfEnterCapture and bpfExitCapture to construct BPF switches.
// Any changes here affect the compiled probe's argument capturing logic.
func generateBPFCode(p CapturePoint, suffix string, scName string) string {
	res := ""
	if p.PtrArg != nil {
		res += fmt.Sprintf("\t\t\t(e)->ptr = (e)->args[%d]; \\\n", *p.PtrArg)
	}
	for _, r := range p.Reads {
		fn := "bpf_probe_read_user"
		if r.Type == "string" {
			fn = "bpf_probe_read_user_str"
		}
		buf := "(e)->str_arg"
		if r.Offset != 0 {
			buf += fmt.Sprintf(" + %d", r.Offset)
		}
		sizeStr := fmt.Sprintf("%d", r.Size)
		if r.Size == 0 {
			sizeStr = dynamicSizeStr(scName, suffix, r)
		}
		res += fmt.Sprintf("\t\t\t{ \\\n")
		if r.Size == 0 && (scName == "accept" || scName == "accept4" || scName == "getsockname" || scName == "getpeername" || scName == "recvfrom") {
			if r.Arg == 1 || r.Arg == 4 {
				lenArg := 2
				if scName == "recvfrom" { lenArg = 5 }
				res += fmt.Sprintf("\t\t\t\tu32 addrlen = 0; \\\n")
				res += fmt.Sprintf("\t\t\t\tbpf_probe_read_user(&addrlen, 4, (void *)(e)->args[%d]); \\\n", lenArg)
				res += fmt.Sprintf("\t\t\t\tu32 inlen = *(u32 *)((e)->str_arg + 768); \\\n")
				res += fmt.Sprintf("\t\t\t\tif (inlen > 0 && inlen < addrlen) addrlen = inlen; \\\n")
				res += fmt.Sprintf("\t\t\t\taddrlen = (addrlen > 128) ? 128 : addrlen; \\\n")
			}
		} else if r.Size == 0 && (scName == "fcntl" || scName == "fcntl64") && r.Arg == 2 {
			res += fmt.Sprintf("\t\t\t\tu32 fcmd = (u32)(e)->args[1]; \\\n")
			res += fmt.Sprintf("\t\t\t\tu32 fsz = 0; \\\n")
			// IMPACT: Added glibc and native command codes for delegation, owner_ex, and RW hints to capture 8 bytes of memory.
			res += fmt.Sprintf("\t\t\t\tif (fcmd == 15 || fcmd == 16 || fcmd == 1035 || fcmd == 1036 || fcmd == 1037 || fcmd == 1038 || fcmd == 1039 || fcmd == 1040 || fcmd == 1043 || fcmd == 1044 || fcmd == 19 || fcmd == 20 || fcmd == 21 || fcmd == 22 || fcmd == 23 || fcmd == 24) fsz = 8; \\\n")
			res += fmt.Sprintf("\t\t\t\telse if (fcmd == 5 || fcmd == 6 || fcmd == 7 || fcmd == 12 || fcmd == 13 || fcmd == 14 || fcmd == 36 || fcmd == 37 || fcmd == 38) fsz = 32; \\\n")
		} else if r.Size == 0 && scName == "ioctl" && r.Arg == 2 {
			res += fmt.Sprintf("\t\t\t\tu32 iosz = (((e)->args[1] >> 16) & 0x3fff); \\\n")
			res += fmt.Sprintf("\t\t\t\tiosz = (iosz == 0) ? 128 : (iosz > 512 ? 512 : iosz); \\\n")
		} else if r.Size == 0 && scName == "fsconfig" && r.Arg == 3 {
			res += fmt.Sprintf("\t\t\t\tu32 fssz = 0; \\\n")
			res += fmt.Sprintf("\t\t\t\tif ((e)->args[1] == 2) { \\\n") // FSCONFIG_SET_BINARY
			res += fmt.Sprintf("\t\t\t\t\tfssz = (e)->args[4]; \\\n")
			res += fmt.Sprintf("\t\t\t\t\tfssz &= 0x1fff; \\\n")
			res += fmt.Sprintf("\t\t\t\t\tfssz = (fssz > 4096) ? 4096 : fssz; \\\n")
			res += fmt.Sprintf("\t\t\t\t} \\\n")
		}
		
		// IMPACT: Safe-guard fsz conditional read to prevent BPF errors when size is 0.
		if sizeStr == "fsz" {
			res += fmt.Sprintf("\t\t\t\tlong __err = (fsz > 0 && (e)->args[%d]) ? %s(%s, fsz, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, r.Arg)
			res += fmt.Sprintf("\t\t\t\tlong pr = (__err == 0 && fsz > 0 && (e)->args[%d]) ? fsz : __err; \\\n", r.Arg)
		} else if sizeStr == "fssz" {
			res += fmt.Sprintf("\t\t\t\tlong pr = 0; \\\n")
			res += fmt.Sprintf("\t\t\t\tif ((e)->args[1] == 2) { \\\n")
			res += fmt.Sprintf("\t\t\t\t\tif (fssz > 0 && (e)->args[%d]) { \\\n", r.Arg)
			res += fmt.Sprintf("\t\t\t\t\t\tint __err = bpf_probe_read_user(%s, fssz, (void *)(e)->args[%d]); \\\n", buf, r.Arg)
			res += fmt.Sprintf("\t\t\t\t\t\tpr = (__err == 0) ? fssz : __err; \\\n")
			res += fmt.Sprintf("\t\t\t\t\t} \\\n")
			res += fmt.Sprintf("\t\t\t\t} else if ((e)->args[%d]) { \\\n", r.Arg)
			res += fmt.Sprintf("\t\t\t\t\tpr = bpf_probe_read_user_str(%s, 4096, (void *)(e)->args[%d]); \\\n", buf, r.Arg)
			res += fmt.Sprintf("\t\t\t\t} \\\n")
		} else if r.Type == "string" && r.Size > 2048 {
			// IMPACT: Modified BPF multi-segment string read to overwrite the first phase's forced null terminator
			// at index 2047. The second phase starts writing from offset 2047 and reads from user pointer + 2047,
			// restoring the original character and ensuring continuous string parsing in Go's bytes.IndexByte.
			res += fmt.Sprintf("\t\t\t\tlong pr = 0; \\\n")
			res += fmt.Sprintf("\t\t\t\tif ((e)->args[%d]) { \\\n", r.Arg)
			res += fmt.Sprintf("\t\t\t\t\t(%s)[0] = 0; \\\n", buf)
			res += fmt.Sprintf("\t\t\t\t\tpr = bpf_probe_read_user_str(%s, 2048, (void *)(e)->args[%d]); \\\n", buf, r.Arg)
			res += fmt.Sprintf("\t\t\t\t\tif (pr < 0) { (%s)[0] = 0; } \\\n", buf)
			res += fmt.Sprintf("\t\t\t\t\telse if (pr >= 2048) { \\\n")
			res += fmt.Sprintf("\t\t\t\t\t\t(%s + 2047)[0] = 0; \\\n", buf)
			remain := r.Size - 2047
			res += fmt.Sprintf("\t\t\t\t\t\tlong pr2 = bpf_probe_read_user_str(%s + 2047, %d, (void *)((e)->args[%d] + 2047)); \\\n", buf, remain, r.Arg)
			res += fmt.Sprintf("\t\t\t\t\t\tif (pr2 >= 0) { pr = 2047 + pr2; } else { pr = pr2; (%s + 2047)[0] = 0; } \\\n", buf)
			res += fmt.Sprintf("\t\t\t\t\t} \\\n")
			res += fmt.Sprintf("\t\t\t\t} \\\n")
		} else {
			if r.Type == "string" {
				res += fmt.Sprintf("\t\t\t\tlong pr = (e)->args[%d] ? %s(%s, %s, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, sizeStr, r.Arg)
			} else {
				res += fmt.Sprintf("\t\t\t\tlong __err = (e)->args[%d] ? %s(%s, %s, (void *)(e)->args[%d]) : 0; \\\n", r.Arg, fn, buf, sizeStr, r.Arg)
				res += fmt.Sprintf("\t\t\t\tlong pr = (__err == 0 && (e)->args[%d]) ? %s : __err; \\\n", r.Arg, sizeStr)
			}
		}
		res += fmt.Sprintf("\t\t\t\tif (pr < 0) { \\\n")
		res += fmt.Sprintf("\t\t\t\t\ts32 curr = (e)->probe_ret_%s; \\\n", suffix)
		res += fmt.Sprintf("\t\t\t\t\tu32 mask = (curr < -1) ? (u32)(-curr - 1) : 0; \\\n")
		res += fmt.Sprintf("\t\t\t\t\t(e)->probe_ret_%s = -(s32)((mask | (1 << %d)) + 1); \\\n", suffix, r.Arg)
		res += fmt.Sprintf("\t\t\t\t} else { \\\n")
		res += fmt.Sprintf("\t\t\t\t\tif ((e)->probe_ret_%s == -1) (e)->probe_ret_%s = 0; \\\n", suffix, suffix)
		res += fmt.Sprintf("\t\t\t\t\tu32 req_len = %d + pr; \\\n", r.Offset)
		res += fmt.Sprintf("\t\t\t\t\tif ((e)->data_len < req_len) (e)->data_len = req_len; \\\n")
		res += fmt.Sprintf("\t\t\t\t} \\\n")
		res += fmt.Sprintf("\t\t\t} \\\n")
		
		if scName == "io_submit" && suffix == "enter" && r.Arg == 2 {
			res += "\t\t\tfor (int i = 0; i < 2; i++) { \\\n"
			res += "\t\t\t\tu64 p; \\\n"
			res += "\t\t\t\tif (bpf_probe_read_user(&p, 8, (void *)(e->args[2] + i*8)) == 0 && p != 0) { \\\n"
			res += "\t\t\t\t\tbpf_probe_read_user((e)->str_arg + 512 + i*64, 64, (void *)p); \\\n"
			res += "\t\t\t\t\tif ((e)->data_len < 512 + i*64 + 64) (e)->data_len = 512 + i*64 + 64; \\\n"
			res += "\t\t\t\t} \\\n"
			res += "\t\t\t} \\\n"
		}
	}
	return res
}

func sortedKeys(m map[int]SyscallMeta) []int {
	ids := make([]int, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	return ids
}

func LoadSyscalls() (map[int]SyscallMeta, error) {
	btf, err := loadBTFSyscalls()
	if err != nil { return nil, err }
	
	entries, err := parseSyscallent("../../strace-upstream/src/linux/x86_64/syscallent.h")
	if err != nil { return nil, err }
	
	res := make(map[int]SyscallMeta)
	for _, ent := range entries {
		// Priority 1: manual overrides
		if m, ok := manualOverrides[ent.Name]; ok {
			res[ent.ID] = m
			continue
		}
		// Priority 2: BTF
		if meta, ok := btf[ent.Name]; ok {
			res[ent.ID] = meta
			continue
		}
		// Priority 3: btfNameToSyscallent mapping
		found := false
		for btfName, sentName := range btfNameToSyscallent {
			if sentName == ent.Name {
				if meta, ok := btf[btfName]; ok {
					meta.Name = sentName
					res[ent.ID] = meta
					found = true
					break
				}
			}
		}
		if found { continue }

		// Fallback: dummy
		dummyArgs := make([]string, ent.Argc)
		dummyTypes := make([]string, ent.Argc)
		for i := 0; i < ent.Argc; i++ {
			dummyArgs[i] = fmt.Sprintf("arg%d", i)
			dummyTypes[i] = "unsigned long"
		}
		res[ent.ID] = SyscallMeta{Name: ent.Name, Args: dummyArgs, ArgTypes: dummyTypes}
	}
	return res, nil
}
