package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v2"
)

type SyscallMeta struct {
	Name     string
	Args     []string
	ArgTypes []string
}

type CaptureRule struct {
	Syscalls []string     `yaml:"syscalls"`
	Enter    CapturePoint `yaml:"enter"`
	Exit     CapturePoint `yaml:"exit"`
}

type CapturePoint struct {
	PtrArg *int          `yaml:"ptr_arg"`
	Reads  []CaptureRead `yaml:"reads"`
}

type CaptureRead struct {
	Arg    int    `yaml:"arg"`
	Size   int    `yaml:"size"`
	Offset int    `yaml:"offset"`
	Type   string `yaml:"type"`
}

type Config struct {
	Rules []CaptureRule `yaml:"rules"`
}

var globalConfig Config

func main() {
	configData, err := ioutil.ReadFile("capture_rules.yaml")
	if err != nil {
		log.Fatalf("failed to read capture_rules.yaml: %v", err)
	}
	if err := yaml.Unmarshal(configData, &globalConfig); err != nil {
		log.Fatalf("failed to unmarshal capture_rules.yaml: %v", err)
	}

	syscalls, err := LoadSyscalls()
	if err != nil {
		log.Fatalf("failed to load syscalls: %v", err)
	}

	// Generate BPF capture header
	f, err := os.Create("../../bpf/syscall_capture.h")
	if err != nil {
		log.Fatalf("failed to create syscall_capture.h: %v", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(f, "#ifndef __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f, "#define __SYSCALL_CAPTURE_H__")
	fmt.Fprintln(f)

	fmt.Fprintln(f, "#define CAPTURE_ARGS_ENTER(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfEnterCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")

	fmt.Fprintln(f, "#define CAPTURE_ARGS_EXIT(sys_id, e) \\")
	fmt.Fprintln(f, "\tswitch (sys_id) { \\")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		code := bpfExitCapture(meta.Name)
		if code != "" {
			fmt.Fprintf(f, "\t\tcase %d: /* %s */ \\\n%s\t\t\tbreak; \\\n", id, meta.Name, code)
		}
	}
	fmt.Fprintln(f, "\t}")
	fmt.Fprintln(f, "#endif")

	// Generate Go syscall table
	gf, err := os.Create("../../pkg/meta/syscall_table.go")
	if err != nil {
		log.Fatalf("failed to create syscall_table.go: %v", err)
	}
	defer gf.Close()

	fmt.Fprintln(gf, "package meta")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(gf)
	fmt.Fprintln(gf, "var SyscallTable = map[uint32]Syscall{")
	for _, id := range sortedKeys(syscalls) {
		meta := syscalls[id]
		fmt.Fprintf(gf, "\t%d: {Name: %q, Args: []string{%s}, ArgTypes: []string{%s}},\n",
			id, meta.Name, formatStringSlice(meta.Args), formatStringSlice(meta.ArgTypes))
	}
	fmt.Fprintln(gf, "}")
}

func formatStringSlice(s []string) string {
	var quoted []string
	for _, v := range s {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return strings.Join(quoted, ", ")
}

func bpfEnterCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Enter, "enter", name)
			}
		}
	}
	return ""
}

func bpfExitCapture(name string) string {
	for _, rule := range globalConfig.Rules {
		for _, sc := range rule.Syscalls {
			if sc == name {
				return generateBPFCode(rule.Exit, "exit", name)
			}
		}
	}
	return ""
}

func generateBPFCode(p CapturePoint, suffix string, scName string) string {
	res := ""
	if p.PtrArg != nil {
		res += fmt.Sprintf("\t\t\t(e)->ptr = (e)->args[%d]; \\\n", *p.PtrArg)
	}
	for _, r := range p.Reads {
		fn := "bpf_probe_read_user"
		if r.Type == "string" {
			fn = "bpf_probe_read_user_str"
		}
		buf := "(e)->str_arg"
		if r.Offset != 0 {
			buf += fmt.Sprintf(" + %d", r.Offset)
		}
		sizeStr := fmt.Sprintf("%d", r.Size)
		if r.Size == 0 {
			if suffix == "exit" {
				sizeStr = "((e)->ret > 0 ? ((e)->ret * 32 > 512 ? 512 : (e)->ret * 32) : 0)"
			} else {
				sizeStr = "((e)->args[1] > 0 ? ((e)->args[1] * 8 > 512 ? 512 : (e)->args[1] * 8) : 0)"
			}
		}
		res += fmt.Sprintf("\t\t\te->probe_ret_%s = %s(%s, %s, (void *)(e)->args[%d]); \\\n", suffix, fn, buf, sizeStr, r.Arg)
		
		if scName == "io_submit" && suffix == "enter" && r.Arg == 2 {
			res += "\t\t\tfor (int i = 0; i < 2; i++) { \\\n"
			res += "\t\t\t\tu64 p; \\\n"
			res += "\t\t\t\tif (bpf_probe_read_user(&p, 8, (void *)(e->args[2] + i*8)) == 0 && p != 0) { \\\n"
			res += "\t\t\t\t\tbpf_probe_read_user((e)->str_arg + 512 + i*64, 64, (void *)p); \\\n"
			res += "\t\t\t\t} \\\n"
			res += "\t\t\t} \\\n"
		}
	}
	return res
}

func sortedKeys(m map[int]SyscallMeta) []int {
	ids := make([]int, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Ints(ids)
	return ids
}

func LoadSyscalls() (map[int]SyscallMeta, error) {
	btf, err := loadBTFSyscalls()
	if err != nil { return nil, err }
	
	entries, err := parseSyscallent("../../strace-upstream/src/linux/x86_64/syscallent.h")
	if err != nil { return nil, err }
	
	res := make(map[int]SyscallMeta)
	for _, ent := range entries {
		// Priority 1: manual overrides
		if m, ok := manualOverrides[ent.Name]; ok {
			res[ent.ID] = m
			continue
		}
		// Priority 2: BTF
		if meta, ok := btf[ent.Name]; ok {
			res[ent.ID] = meta
			continue
		}
		// Priority 3: btfNameToSyscallent mapping
		found := false
		for btfName, sentName := range btfNameToSyscallent {
			if sentName == ent.Name {
				if meta, ok := btf[btfName]; ok {
					meta.Name = sentName
					res[ent.ID] = meta
					found = true
					break
				}
			}
		}
		if found { continue }

		// Fallback: dummy
		dummyArgs := make([]string, ent.Argc)
		dummyTypes := make([]string, ent.Argc)
		for i := 0; i < ent.Argc; i++ {
			dummyArgs[i] = fmt.Sprintf("arg%d", i)
			dummyTypes[i] = "unsigned long"
		}
		res[ent.ID] = SyscallMeta{Name: ent.Name, Args: dummyArgs, ArgTypes: dummyTypes}
	}
	return res, nil
}
