package main

// Native LP64 signatures migrated from the audited amd64 metadata baseline.
// Architecture differences are applied in target_schema.go; syscall IDs come from x/sys.
var nativeSyscallSignatures = map[string]syscallSignature{
	"_sysctl":                 {Args: []string{"arg0"}, ArgTypes: []string{"unsigned long"}},
	"accept":                  {Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	"accept4":                 {Args: []string{"fd", "upeer_sockaddr", "upeer_addrlen", "flags"}, ArgTypes: []string{"int", "struct sockaddr *", "int *", "int"}},
	"access":                  {Args: []string{"filename", "mode"}, ArgTypes: []string{"const char *", "int"}},
	"acct":                    {Args: []string{"name"}, ArgTypes: []string{"const char *"}},
	"add_key":                 {Args: []string{"_type", "_description", "_payload", "plen", "ringid"}, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "key_serial_t"}},
	"adjtimex":                {Args: []string{"txc_p"}, ArgTypes: []string{"struct timex *"}},
	"afs_syscall":             {Args: []string{"arg0", "arg1", "arg2", "arg3", "arg4"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"alarm":                   {Args: []string{"seconds"}, ArgTypes: []string{"unsigned int"}},
	"arch_prctl":              {Args: []string{"option", "arg2"}, ArgTypes: []string{"int", "unsigned long"}},
	"bind":                    {Args: []string{"fd", "umyaddr", "addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int"}},
	"bpf":                     {Args: []string{"cmd", "attr", "size"}, ArgTypes: []string{"int", "void *", "unsigned int"}},
	"brk":                     {Args: []string{"brk"}, ArgTypes: []string{"long unsigned int"}},
	"cachestat":               {Args: []string{"fd", "cstat_range", "cstat", "flags"}, ArgTypes: []string{"unsigned int", "struct cachestat_range *", "struct cachestat *", "unsigned int"}},
	"capget":                  {Args: []string{"header", "dataptr"}, ArgTypes: []string{"cap_user_header_t", "cap_user_data_t"}},
	"capset":                  {Args: []string{"header", "data"}, ArgTypes: []string{"cap_user_header_t", "const cap_user_data_t"}},
	"chdir":                   {Args: []string{"filename"}, ArgTypes: []string{"const char *"}},
	"chmod":                   {Args: []string{"filename", "mode"}, ArgTypes: []string{"const char *", "umode_t"}},
	"chown":                   {Args: []string{"filename", "user", "group"}, ArgTypes: []string{"const char *", "uid_t", "gid_t"}},
	"chroot":                  {Args: []string{"filename"}, ArgTypes: []string{"const char *"}},
	"clock_adjtime":           {Args: []string{"which_clock", "utx"}, ArgTypes: []string{"const clockid_t", "struct __kernel_timex *"}},
	"clock_getres":            {Args: []string{"which_clock", "tp"}, ArgTypes: []string{"const clockid_t", "struct __kernel_timespec *"}},
	"clock_gettime":           {Args: []string{"which_clock", "tp"}, ArgTypes: []string{"const clockid_t", "struct __kernel_timespec *"}},
	"clock_nanosleep":         {Args: []string{"which_clock", "flags", "rqtp", "rmtp"}, ArgTypes: []string{"const clockid_t", "int", "const struct __kernel_timespec *", "struct __kernel_timespec *"}},
	"clock_settime":           {Args: []string{"which_clock", "tp"}, ArgTypes: []string{"const clockid_t", "const struct __kernel_timespec *"}},
	"clone":                   {Args: []string{"clone_flags", "newsp", "parent_tidptr", "child_tidptr", "tls"}, ArgTypes: []string{"long unsigned int", "long unsigned int", "int *", "int *", "long unsigned int"}},
	"clone3":                  {Args: []string{"uargs", "size"}, ArgTypes: []string{"struct clone_args *", "size_t"}},
	"close":                   {Args: []string{"fd"}, ArgTypes: []string{"unsigned int"}},
	"close_range":             {Args: []string{"fd", "max_fd", "flags"}, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned int"}},
	"connect":                 {Args: []string{"fd", "uservaddr", "addrlen"}, ArgTypes: []string{"int", "struct sockaddr *", "int"}},
	"copy_file_range":         {Args: []string{"fd_in", "off_in", "fd_out", "off_out", "len", "flags"}, ArgTypes: []string{"int", "loff_t *", "int", "loff_t *", "size_t", "unsigned int"}},
	"creat":                   {Args: []string{"pathname", "mode"}, ArgTypes: []string{"const char *", "umode_t"}},
	"create_module":           {Args: []string{"arg0", "arg1"}, ArgTypes: []string{"unsigned long", "unsigned long"}},
	"delete_module":           {Args: []string{"name_user", "flags"}, ArgTypes: []string{"const char *", "unsigned int"}},
	"dup":                     {Args: []string{"fildes"}, ArgTypes: []string{"unsigned int"}},
	"dup2":                    {Args: []string{"oldfd", "newfd"}, ArgTypes: []string{"unsigned int", "unsigned int"}},
	"dup3":                    {Args: []string{"oldfd", "newfd", "flags"}, ArgTypes: []string{"unsigned int", "unsigned int", "int"}},
	"epoll_create":            {Args: []string{"size"}, ArgTypes: []string{"int"}},
	"epoll_create1":           {Args: []string{"flags"}, ArgTypes: []string{"int"}},
	"epoll_ctl":               {Args: []string{"epfd", "op", "fd", "event"}, ArgTypes: []string{"int", "int", "int", "struct epoll_event *"}},
	"epoll_ctl_old":           {Args: []string{"arg0", "arg1", "arg2", "arg3"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"epoll_pwait":             {Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "int", "const sigset_t *", "size_t"}},
	"epoll_pwait2":            {Args: []string{"epfd", "events", "maxevents", "timeout", "sigmask", "sigsetsize"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "const struct __kernel_timespec *", "const sigset_t *", "size_t"}},
	"epoll_wait":              {Args: []string{"epfd", "events", "maxevents", "timeout"}, ArgTypes: []string{"int", "struct epoll_event *", "int", "int"}},
	"epoll_wait_old":          {Args: []string{"arg0", "arg1", "arg2", "arg3"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"eventfd":                 {Args: []string{"count"}, ArgTypes: []string{"unsigned int"}},
	"eventfd2":                {Args: []string{"count", "flags"}, ArgTypes: []string{"unsigned int", "int"}},
	"execve":                  {Args: []string{"filename", "argv", "envp"}, ArgTypes: []string{"const char *", "const char *const *", "const char *const *"}},
	"execveat":                {Args: []string{"dfd", "filename", "argv", "envp", "flags"}, ArgTypes: []string{"int", "const char *", "const char *const *", "const char *const *", "int"}},
	"exit":                    {Args: []string{"error_code"}, ArgTypes: []string{"int"}},
	"exit_group":              {Args: []string{"error_code"}, ArgTypes: []string{"int"}},
	"faccessat":               {Args: []string{"dfd", "filename", "mode"}, ArgTypes: []string{"int", "const char *", "int"}},
	"faccessat2":              {Args: []string{"dfd", "filename", "mode", "flags"}, ArgTypes: []string{"int", "const char *", "int", "int"}},
	"fadvise64":               {Args: []string{"fd", "offset", "len", "advice"}, ArgTypes: []string{"int", "loff_t", "size_t", "int"}},
	"fallocate":               {Args: []string{"fd", "mode", "offset", "len"}, ArgTypes: []string{"int", "int", "loff_t", "loff_t"}},
	"fanotify_init":           {Args: []string{"flags", "event_f_flags"}, ArgTypes: []string{"unsigned int", "unsigned int"}},
	"fanotify_mark":           {Args: []string{"fanotify_fd", "flags", "mask", "dfd", "pathname"}, ArgTypes: []string{"int", "unsigned int", "__u64", "int", "const char *"}},
	"fchdir":                  {Args: []string{"fd"}, ArgTypes: []string{"unsigned int"}},
	"fchmod":                  {Args: []string{"fd", "mode"}, ArgTypes: []string{"unsigned int", "umode_t"}},
	"fchmodat":                {Args: []string{"dfd", "filename", "mode"}, ArgTypes: []string{"int", "const char *", "umode_t"}},
	"fchmodat2":               {Args: []string{"dfd", "filename", "mode", "flags"}, ArgTypes: []string{"int", "const char *", "umode_t", "unsigned int"}},
	"fchown":                  {Args: []string{"fd", "user", "group"}, ArgTypes: []string{"unsigned int", "uid_t", "gid_t"}},
	"fchownat":                {Args: []string{"dfd", "filename", "user", "group", "flag"}, ArgTypes: []string{"int", "const char *", "uid_t", "gid_t", "int"}},
	"fcntl":                   {Args: []string{"fd", "cmd", "arg"}, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned long"}},
	"fdatasync":               {Args: []string{"fd"}, ArgTypes: []string{"unsigned int"}},
	"fgetxattr":               {Args: []string{"fd", "name", "value", "size"}, ArgTypes: []string{"int", "const char *", "void *", "size_t"}},
	"file_getattr":            {Args: []string{"dfd", "filename", "ufattr", "usize", "at_flags"}, ArgTypes: []string{"int", "const char *", "struct file_attr *", "size_t", "unsigned int"}},
	"file_setattr":            {Args: []string{"dfd", "filename", "ufattr", "usize", "at_flags"}, ArgTypes: []string{"int", "const char *", "struct file_attr *", "size_t", "unsigned int"}},
	"finit_module":            {Args: []string{"fd", "uargs", "flags"}, ArgTypes: []string{"int", "const char *", "int"}},
	"flistxattr":              {Args: []string{"fd", "list", "size"}, ArgTypes: []string{"int", "char *", "size_t"}},
	"flock":                   {Args: []string{"fd", "op"}, ArgTypes: []string{"int", "int"}},
	"fork":                    {Args: []string{}, ArgTypes: []string{}},
	"fremovexattr":            {Args: []string{"fd", "name"}, ArgTypes: []string{"int", "const char *"}},
	"fsconfig":                {Args: []string{"fd", "cmd", "_key", "_value", "aux"}, ArgTypes: []string{"int", "unsigned int", "const char *", "const void *", "int"}},
	"fsetxattr":               {Args: []string{"fd", "name", "value", "size", "flags"}, ArgTypes: []string{"int", "const char *", "const void *", "size_t", "int"}},
	"fsmount":                 {Args: []string{"fs_fd", "flags", "attr_flags"}, ArgTypes: []string{"int", "unsigned int", "unsigned int"}},
	"fsopen":                  {Args: []string{"_fs_name", "flags"}, ArgTypes: []string{"const char *", "unsigned int"}},
	"fspick":                  {Args: []string{"dfd", "path", "flags"}, ArgTypes: []string{"int", "const char *", "unsigned int"}},
	"fstat":                   {Args: []string{"fd", "statbuf"}, ArgTypes: []string{"int", "struct stat *"}},
	"fstatfs":                 {Args: []string{"fd", "buf"}, ArgTypes: []string{"unsigned int", "struct statfs *"}},
	"fsync":                   {Args: []string{"fd"}, ArgTypes: []string{"unsigned int"}},
	"ftruncate":               {Args: []string{"fd", "length"}, ArgTypes: []string{"unsigned int", "off_t"}},
	"futex":                   {Args: []string{"uaddr", "op", "val", "utime", "uaddr2", "val3"}, ArgTypes: []string{"u32 *", "int", "u32", "const struct __kernel_timespec *", "u32 *", "u32"}},
	"futex_requeue":           {Args: []string{"waiters", "flags", "nr_wake", "nr_requeue"}, ArgTypes: []string{"struct futex_waitv *", "unsigned int", "int", "int"}},
	"futex_wait":              {Args: []string{"uaddr", "val", "mask", "flags", "timeout", "clockid"}, ArgTypes: []string{"void *", "unsigned long", "unsigned long", "unsigned int", "struct __kernel_timespec *", "clockid_t"}},
	"futex_waitv":             {Args: []string{"waiters", "nr_futexes", "flags", "timeout", "clockid"}, ArgTypes: []string{"struct futex_waitv *", "unsigned int", "unsigned int", "struct __kernel_timespec *", "clockid_t"}},
	"futex_wake":              {Args: []string{"uaddr", "mask", "nr", "flags"}, ArgTypes: []string{"void *", "unsigned long", "int", "unsigned int"}},
	"futimesat":               {Args: []string{"dfd", "filename", "utimes"}, ArgTypes: []string{"int", "const char *", "struct __kernel_old_timeval *"}},
	"get_kernel_syms":         {Args: []string{"arg0"}, ArgTypes: []string{"unsigned long"}},
	"get_mempolicy":           {Args: []string{"policy", "nmask", "maxnode", "addr", "flags"}, ArgTypes: []string{"int *", "unsigned long *", "unsigned long", "unsigned long", "unsigned long"}},
	"get_robust_list":         {Args: []string{"pid", "head_ptr", "len_ptr"}, ArgTypes: []string{"int", "struct robust_list_head * *", "size_t *"}},
	"get_thread_area":         {Args: []string{"arg0"}, ArgTypes: []string{"unsigned long"}},
	"getcpu":                  {Args: []string{"cpup", "nodep", "unused"}, ArgTypes: []string{"unsigned *", "unsigned *", "void *"}},
	"getcwd":                  {Args: []string{"buf", "size"}, ArgTypes: []string{"char *", "long unsigned int"}},
	"getdents":                {Args: []string{"fd", "dirent", "count"}, ArgTypes: []string{"unsigned int", "struct linux_dirent *", "unsigned int"}},
	"getdents64":              {Args: []string{"fd", "dirent", "count"}, ArgTypes: []string{"unsigned int", "struct linux_dirent64 *", "unsigned int"}},
	"getegid":                 {Args: []string{}, ArgTypes: []string{}},
	"geteuid":                 {Args: []string{}, ArgTypes: []string{}},
	"getgid":                  {Args: []string{}, ArgTypes: []string{}},
	"getgroups":               {Args: []string{"gidsetsize", "grouplist"}, ArgTypes: []string{"int", "gid_t *"}},
	"getitimer":               {Args: []string{"which", "value"}, ArgTypes: []string{"int", "struct __kernel_old_itimerval *"}},
	"getpeername":             {Args: []string{"fd", "usockaddr", "usockaddr_len"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	"getpgid":                 {Args: []string{"pid"}, ArgTypes: []string{"pid_t"}},
	"getpgrp":                 {Args: []string{}, ArgTypes: []string{}},
	"getpid":                  {Args: []string{}, ArgTypes: []string{}},
	"getpmsg":                 {Args: []string{"arg0", "arg1", "arg2", "arg3", "arg4"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"getppid":                 {Args: []string{}, ArgTypes: []string{}},
	"getpriority":             {Args: []string{"which", "who"}, ArgTypes: []string{"int", "int"}},
	"getrandom":               {Args: []string{"ubuf", "len", "flags"}, ArgTypes: []string{"char *", "size_t", "unsigned int"}},
	"getresgid":               {Args: []string{"rgidp", "egidp", "sgidp"}, ArgTypes: []string{"gid_t *", "gid_t *", "gid_t *"}},
	"getresuid":               {Args: []string{"ruidp", "euidp", "suidp"}, ArgTypes: []string{"uid_t *", "uid_t *", "uid_t *"}},
	"getrlimit":               {Args: []string{"resource", "rlim"}, ArgTypes: []string{"unsigned int", "struct rlimit *"}},
	"getrusage":               {Args: []string{"who", "ru"}, ArgTypes: []string{"int", "struct rusage *"}},
	"getsid":                  {Args: []string{"pid"}, ArgTypes: []string{"pid_t"}},
	"getsockname":             {Args: []string{"fd", "usockaddr", "usockaddr_len"}, ArgTypes: []string{"int", "struct sockaddr *", "int *"}},
	"getsockopt":              {Args: []string{"fd", "level", "optname", "optval", "optlen"}, ArgTypes: []string{"int", "int", "int", "char *", "int *"}},
	"gettid":                  {Args: []string{}, ArgTypes: []string{}},
	"gettimeofday":            {Args: []string{"tv", "tz"}, ArgTypes: []string{"struct __kernel_old_timeval *", "struct timezone *"}},
	"getuid":                  {Args: []string{}, ArgTypes: []string{}},
	"getxattr":                {Args: []string{"pathname", "name", "value", "size"}, ArgTypes: []string{"const char *", "const char *", "void *", "size_t"}},
	"getxattrat":              {Args: []string{"dfd", "pathname", "at_flags", "name", "uargs", "usize"}, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *", "struct xattr_args *", "size_t"}},
	"init_module":             {Args: []string{"umod", "len", "uargs"}, ArgTypes: []string{"void *", "long unsigned int", "const char *"}},
	"inotify_add_watch":       {Args: []string{"fd", "pathname", "mask"}, ArgTypes: []string{"int", "const char *", "u32"}},
	"inotify_init":            {Args: []string{}, ArgTypes: []string{}},
	"inotify_init1":           {Args: []string{"flags"}, ArgTypes: []string{"int"}},
	"inotify_rm_watch":        {Args: []string{"fd", "wd"}, ArgTypes: []string{"int", "__s32"}},
	"io_cancel":               {Args: []string{"ctx_id", "iocb", "result"}, ArgTypes: []string{"aio_context_t", "struct iocb *", "struct io_event *"}},
	"io_destroy":              {Args: []string{"ctx"}, ArgTypes: []string{"aio_context_t"}},
	"io_getevents":            {Args: []string{"ctx_id", "min_nr", "nr", "events", "timeout"}, ArgTypes: []string{"aio_context_t", "long", "long", "struct io_event *", "struct __kernel_timespec *"}},
	"io_pgetevents":           {Args: []string{"ctx_id", "min_nr", "nr", "events", "timeout", "usig"}, ArgTypes: []string{"aio_context_t", "long", "long", "struct io_event *", "struct __kernel_timespec *", "const struct __aio_sigset *"}},
	"io_setup":                {Args: []string{"nr_events", "ctxp"}, ArgTypes: []string{"unsigned", "aio_context_t *"}},
	"io_submit":               {Args: []string{"ctx_id", "nr", "iocbpp"}, ArgTypes: []string{"aio_context_t", "long", "struct iocb * *"}},
	"io_uring_enter":          {Args: []string{"fd", "to_submit", "min_complete", "flags", "argp", "argsz"}, ArgTypes: []string{"unsigned int", "u32", "u32", "u32", "const void *", "size_t"}},
	"io_uring_register":       {Args: []string{"fd", "opcode", "arg", "nr_args"}, ArgTypes: []string{"unsigned int", "unsigned int", "void *", "unsigned int"}},
	"io_uring_setup":          {Args: []string{"entries", "params"}, ArgTypes: []string{"u32", "struct io_uring_params *"}},
	"ioctl":                   {Args: []string{"fd", "cmd", "arg"}, ArgTypes: []string{"unsigned int", "unsigned int", "unsigned long"}},
	"ioperm":                  {Args: []string{"from", "num", "turn_on"}, ArgTypes: []string{"long unsigned int", "long unsigned int", "int"}},
	"iopl":                    {Args: []string{"level"}, ArgTypes: []string{"unsigned int"}},
	"ioprio_get":              {Args: []string{"which", "who"}, ArgTypes: []string{"int", "int"}},
	"ioprio_set":              {Args: []string{"which", "who", "ioprio"}, ArgTypes: []string{"int", "int", "int"}},
	"kcmp":                    {Args: []string{"pid1", "pid2", "type", "idx1", "idx2"}, ArgTypes: []string{"pid_t", "pid_t", "int", "long unsigned int", "long unsigned int"}},
	"kexec_file_load":         {Args: []string{"kernel_fd", "initrd_fd", "cmdline_len", "cmdline_ptr", "flags"}, ArgTypes: []string{"int", "int", "long unsigned int", "const char *", "long unsigned int"}},
	"kexec_load":              {Args: []string{"entry", "nr_segments", "segments", "flags"}, ArgTypes: []string{"unsigned long", "unsigned long", "struct kexec_segment *", "unsigned long"}},
	"keyctl":                  {Args: []string{"option", "arg2", "arg3", "arg4", "arg5"}, ArgTypes: []string{"int", "long unsigned int", "long unsigned int", "long unsigned int", "long unsigned int"}},
	"kill":                    {Args: []string{"pid", "sig"}, ArgTypes: []string{"pid_t", "int"}},
	"landlock_add_rule":       {Args: []string{"ruleset_fd", "rule_type", "rule_attr", "flags"}, ArgTypes: []string{"const int", "const enum landlock_rule_type", "const void *const", "const __u32"}},
	"landlock_create_ruleset": {Args: []string{"attr", "size", "flags"}, ArgTypes: []string{"const const struct landlock_ruleset_attr *", "const size_t", "const __u32"}},
	"landlock_restrict_self":  {Args: []string{"ruleset_fd", "flags"}, ArgTypes: []string{"const int", "const __u32"}},
	"lchown":                  {Args: []string{"filename", "user", "group"}, ArgTypes: []string{"const char *", "uid_t", "gid_t"}},
	"lgetxattr":               {Args: []string{"pathname", "name", "value", "size"}, ArgTypes: []string{"const char *", "const char *", "void *", "size_t"}},
	"link":                    {Args: []string{"oldname", "newname"}, ArgTypes: []string{"const char *", "const char *"}},
	"linkat":                  {Args: []string{"olddfd", "oldname", "newdfd", "newname", "flags"}, ArgTypes: []string{"int", "const char *", "int", "const char *", "int"}},
	"listen":                  {Args: []string{"fd", "backlog"}, ArgTypes: []string{"int", "int"}},
	"listmount":               {Args: []string{"req", "mnt_ids", "nr_mnt_ids", "flags"}, ArgTypes: []string{"const struct mnt_id_req *", "u64 *", "size_t", "unsigned int"}},
	"listns":                  {Args: []string{"req", "ns_ids", "nr_ns_ids", "flags"}, ArgTypes: []string{"const struct ns_id_req *", "u64 *", "size_t", "unsigned int"}},
	"listxattr":               {Args: []string{"pathname", "list", "size"}, ArgTypes: []string{"const char *", "char *", "size_t"}},
	"listxattrat":             {Args: []string{"dfd", "pathname", "at_flags", "list", "size"}, ArgTypes: []string{"int", "const char *", "unsigned int", "char *", "size_t"}},
	"llistxattr":              {Args: []string{"pathname", "list", "size"}, ArgTypes: []string{"const char *", "char *", "size_t"}},
	"lookup_dcookie":          {Args: []string{"arg0", "arg1", "arg2"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long"}},
	"lremovexattr":            {Args: []string{"pathname", "name"}, ArgTypes: []string{"const char *", "const char *"}},
	"lseek":                   {Args: []string{"fd", "offset", "whence"}, ArgTypes: []string{"unsigned int", "off_t", "unsigned int"}},
	"lsetxattr":               {Args: []string{"pathname", "name", "value", "size", "flags"}, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "int"}},
	"lsm_get_self_attr":       {Args: []string{"attr", "ctx", "size", "flags"}, ArgTypes: []string{"unsigned int", "struct lsm_ctx *", "u32 *", "u32"}},
	"lsm_list_modules":        {Args: []string{"ids", "size", "flags"}, ArgTypes: []string{"u64 *", "u32 *", "u32"}},
	"lsm_set_self_attr":       {Args: []string{"attr", "ctx", "size", "flags"}, ArgTypes: []string{"unsigned int", "struct lsm_ctx *", "u32", "u32"}},
	"lstat":                   {Args: []string{"filename", "statbuf"}, ArgTypes: []string{"const char *", "struct stat *"}},
	"madvise":                 {Args: []string{"start", "len_in", "behavior"}, ArgTypes: []string{"unsigned long", "size_t", "int"}},
	"map_shadow_stack":        {Args: []string{"addr", "size", "flags"}, ArgTypes: []string{"void *", "size_t", "unsigned int"}},
	"mbind":                   {Args: []string{"start", "len", "mode", "nmask", "maxnode", "flags"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "const unsigned long *", "unsigned long", "unsigned int"}},
	"membarrier":              {Args: []string{"cmd", "flags", "cpu_id"}, ArgTypes: []string{"int", "unsigned int", "int"}},
	"memfd_create":            {Args: []string{"uname", "flags"}, ArgTypes: []string{"const char *", "unsigned int"}},
	"memfd_secret":            {Args: []string{"flags"}, ArgTypes: []string{"unsigned int"}},
	"migrate_pages":           {Args: []string{"pid", "maxnode", "old_nodes", "new_nodes"}, ArgTypes: []string{"pid_t", "unsigned long", "const unsigned long *", "const unsigned long *"}},
	"mincore":                 {Args: []string{"start", "len", "vec"}, ArgTypes: []string{"unsigned long", "size_t", "unsigned char *"}},
	"mkdir":                   {Args: []string{"pathname", "mode"}, ArgTypes: []string{"const char *", "umode_t"}},
	"mkdirat":                 {Args: []string{"dfd", "pathname", "mode"}, ArgTypes: []string{"int", "const char *", "umode_t"}},
	"mknod":                   {Args: []string{"filename", "mode", "dev"}, ArgTypes: []string{"const char *", "umode_t", "unsigned"}},
	"mknodat":                 {Args: []string{"dfd", "filename", "mode", "dev"}, ArgTypes: []string{"int", "const char *", "umode_t", "unsigned int"}},
	"mlock":                   {Args: []string{"start", "len"}, ArgTypes: []string{"unsigned long", "size_t"}},
	"mlock2":                  {Args: []string{"start", "len", "flags"}, ArgTypes: []string{"unsigned long", "size_t", "int"}},
	"mlockall":                {Args: []string{"flags"}, ArgTypes: []string{"int"}},
	"mmap":                    {Args: []string{"addr", "len", "prot", "flags", "fd", "off"}, ArgTypes: []string{"const void *", "size_t", "unsigned long", "unsigned long", "int", "kernel_off_t"}},
	"modify_ldt":              {Args: []string{"func", "ptr", "bytecount"}, ArgTypes: []string{"int", "void *", "unsigned long"}},
	"mount":                   {Args: []string{"dev_name", "dir_name", "type", "flags", "data"}, ArgTypes: []string{"char *", "char *", "char *", "unsigned long", "void *"}},
	"mount_setattr":           {Args: []string{"dfd", "path", "flags", "uattr", "usize"}, ArgTypes: []string{"int", "const char *", "unsigned int", "struct mount_attr *", "size_t"}},
	"move_mount":              {Args: []string{"from_dfd", "from_pathname", "to_dfd", "to_pathname", "flags"}, ArgTypes: []string{"int", "const char *", "int", "const char *", "unsigned int"}},
	"move_pages":              {Args: []string{"pid", "nr_pages", "pages", "nodes", "status", "flags"}, ArgTypes: []string{"pid_t", "unsigned long", "const void * *", "const int *", "int *", "int"}},
	"mprotect":                {Args: []string{"start", "len", "prot"}, ArgTypes: []string{"const void *", "size_t", "unsigned long"}},
	"mq_getsetattr":           {Args: []string{"mqdes", "u_mqstat", "u_omqstat"}, ArgTypes: []string{"mqd_t", "const struct mq_attr *", "struct mq_attr *"}},
	"mq_notify":               {Args: []string{"mqdes", "u_notification"}, ArgTypes: []string{"mqd_t", "const struct sigevent *"}},
	"mq_open":                 {Args: []string{"u_name", "oflag", "mode", "u_attr"}, ArgTypes: []string{"const char *", "int", "umode_t", "struct mq_attr *"}},
	"mq_timedreceive":         {Args: []string{"mqdes", "u_msg_ptr", "msg_len", "u_msg_prio", "u_abs_timeout"}, ArgTypes: []string{"mqd_t", "char *", "size_t", "unsigned int *", "const struct __kernel_timespec *"}},
	"mq_timedsend":            {Args: []string{"mqdes", "u_msg_ptr", "msg_len", "msg_prio", "u_abs_timeout"}, ArgTypes: []string{"mqd_t", "const char *", "size_t", "unsigned int", "const struct __kernel_timespec *"}},
	"mq_unlink":               {Args: []string{"u_name"}, ArgTypes: []string{"const char *"}},
	"mremap":                  {Args: []string{"addr", "old_len", "new_len", "flags", "new_addr"}, ArgTypes: []string{"const void *", "unsigned long", "unsigned long", "unsigned long", "const void *"}},
	"mseal":                   {Args: []string{"start", "len", "flags"}, ArgTypes: []string{"unsigned long", "size_t", "unsigned long"}},
	"msgctl":                  {Args: []string{"msqid", "cmd", "buf"}, ArgTypes: []string{"int", "int", "struct msqid_ds *"}},
	"msgget":                  {Args: []string{"key", "msgflg"}, ArgTypes: []string{"key_t", "int"}},
	"msgrcv":                  {Args: []string{"msqid", "msgp", "msgsz", "msgtyp", "msgflg"}, ArgTypes: []string{"int", "struct msgbuf *", "size_t", "long int", "int"}},
	"msgsnd":                  {Args: []string{"msqid", "msgp", "msgsz", "msgflg"}, ArgTypes: []string{"int", "struct msgbuf *", "size_t", "int"}},
	"msync":                   {Args: []string{"addr", "len", "flags"}, ArgTypes: []string{"const void *", "size_t", "int"}},
	"munlock":                 {Args: []string{"start", "len"}, ArgTypes: []string{"unsigned long", "size_t"}},
	"munlockall":              {Args: []string{}, ArgTypes: []string{}},
	"munmap":                  {Args: []string{"addr", "len"}, ArgTypes: []string{"const void *", "size_t"}},
	"name_to_handle_at":       {Args: []string{"dfd", "name", "handle", "mnt_id", "flag"}, ArgTypes: []string{"int", "const char *", "struct file_handle *", "void *", "int"}},
	"nanosleep":               {Args: []string{"rqtp", "rmtp"}, ArgTypes: []string{"struct __kernel_timespec *", "struct __kernel_timespec *"}},
	"newfstatat":              {Args: []string{"dfd", "filename", "statbuf", "flag"}, ArgTypes: []string{"int", "const char *", "struct stat *", "int"}},
	"nfsservctl":              {Args: []string{"arg0", "arg1", "arg2"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long"}},
	"open":                    {Args: []string{"filename", "flags", "mode"}, ArgTypes: []string{"const char *", "int", "umode_t"}},
	"open_by_handle_at":       {Args: []string{"mountdirfd", "handle", "flags"}, ArgTypes: []string{"int", "struct file_handle *", "int"}},
	"open_tree":               {Args: []string{"dfd", "filename", "flags"}, ArgTypes: []string{"int", "const char *", "unsigned"}},
	"open_tree_attr":          {Args: []string{"dfd", "filename", "flags", "uattr", "usize"}, ArgTypes: []string{"int", "const char *", "unsigned int", "struct mount_attr *", "size_t"}},
	"openat":                  {Args: []string{"dfd", "filename", "flags", "mode"}, ArgTypes: []string{"int", "const char *", "int", "umode_t"}},
	"openat2":                 {Args: []string{"dfd", "filename", "how", "usize"}, ArgTypes: []string{"int", "const char *", "struct open_how *", "size_t"}},
	"pause":                   {Args: []string{}, ArgTypes: []string{}},
	"perf_event_open":         {Args: []string{"attr_uptr", "pid", "cpu", "group_fd", "flags"}, ArgTypes: []string{"struct perf_event_attr *", "pid_t", "int", "int", "long unsigned int"}},
	"personality":             {Args: []string{"personality"}, ArgTypes: []string{"unsigned int"}},
	"pidfd_getfd":             {Args: []string{"pidfd", "fd", "flags"}, ArgTypes: []string{"int", "int", "unsigned int"}},
	"pidfd_open":              {Args: []string{"pid", "flags"}, ArgTypes: []string{"pid_t", "unsigned int"}},
	"pidfd_send_signal":       {Args: []string{"pidfd", "sig", "info", "flags"}, ArgTypes: []string{"int", "int", "siginfo_t *", "unsigned int"}},
	"pipe":                    {Args: []string{"fildes"}, ArgTypes: []string{"int *"}},
	"pipe2":                   {Args: []string{"fildes", "flags"}, ArgTypes: []string{"int *", "int"}},
	"pivot_root":              {Args: []string{"new_root", "put_old"}, ArgTypes: []string{"const char *", "const char *"}},
	"pkey_alloc":              {Args: []string{"flags", "init_val"}, ArgTypes: []string{"long unsigned int", "long unsigned int"}},
	"pkey_free":               {Args: []string{"pkey"}, ArgTypes: []string{"int"}},
	"pkey_mprotect":           {Args: []string{"start", "len", "prot", "pkey"}, ArgTypes: []string{"unsigned long", "size_t", "unsigned long", "int"}},
	"poll":                    {Args: []string{"ufds", "nfds", "timeout_msecs"}, ArgTypes: []string{"struct pollfd *", "unsigned int", "int"}},
	"ppoll":                   {Args: []string{"ufds", "nfds", "tsp", "sigmask", "sigsetsize"}, ArgTypes: []string{"struct pollfd *", "unsigned int", "struct __kernel_timespec *", "const sigset_t *", "size_t"}},
	"prctl":                   {Args: []string{"option", "arg2", "arg3", "arg4", "arg5"}, ArgTypes: []string{"int", "long unsigned int", "long unsigned int", "long unsigned int", "long unsigned int"}},
	"pread64":                 {Args: []string{"fd", "buf", "count", "pos"}, ArgTypes: []string{"unsigned int", "char *", "size_t", "loff_t"}},
	"preadv":                  {Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h"}, ArgTypes: []string{"int", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long"}},
	"preadv2":                 {Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", "flags"}, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", "rwf_t"}},
	"prlimit64":               {Args: []string{"pid", "resource", "new_rlim", "old_rlim"}, ArgTypes: []string{"pid_t", "unsigned int", "const struct rlimit64 *", "struct rlimit64 *"}},
	"process_madvise":         {Args: []string{"pidfd", "vec", "vlen", "behavior", "flags"}, ArgTypes: []string{"int", "const struct iovec *", "size_t", "int", "unsigned int"}},
	"process_mrelease":        {Args: []string{"pidfd", "flags"}, ArgTypes: []string{"int", "unsigned int"}},
	"process_vm_readv":        {Args: []string{"pid", "lvec", "liovcnt", "rvec", "riovcnt", "flags"}, ArgTypes: []string{"pid_t", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long"}},
	"process_vm_writev":       {Args: []string{"pid", "lvec", "liovcnt", "rvec", "riovcnt", "flags"}, ArgTypes: []string{"pid_t", "const struct iovec *", "unsigned long", "const struct iovec *", "unsigned long", "unsigned long"}},
	"pselect6":                {Args: []string{"n", "inp", "outp", "exp", "tsp", "sig"}, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct __kernel_timespec *", "void *"}},
	"ptrace":                  {Args: []string{"request", "pid", "addr", "data"}, ArgTypes: []string{"long", "long", "unsigned long", "unsigned long"}},
	"putpmsg":                 {Args: []string{"arg0", "arg1", "arg2", "arg3", "arg4"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"pwrite64":                {Args: []string{"fd", "buf", "count", "pos"}, ArgTypes: []string{"unsigned int", "const char *", "size_t", "loff_t"}},
	"pwritev":                 {Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h"}, ArgTypes: []string{"int", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long"}},
	"pwritev2":                {Args: []string{"fd", "vec", "vlen", "pos_l", "pos_h", "flags"}, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long", "unsigned long", "unsigned long", "rwf_t"}},
	"query_module":            {Args: []string{"arg0", "arg1", "arg2", "arg3", "arg4"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"quotactl":                {Args: []string{"cmd", "special", "id", "addr"}, ArgTypes: []string{"unsigned int", "const char *", "qid_t", "void *"}},
	"quotactl_fd":             {Args: []string{"fd", "cmd", "id", "addr"}, ArgTypes: []string{"unsigned int", "unsigned int", "qid_t", "void *"}},
	"read":                    {Args: []string{"fd", "buf", "count"}, ArgTypes: []string{"unsigned int", "char *", "size_t"}},
	"readahead":               {Args: []string{"fd", "offset", "count"}, ArgTypes: []string{"int", "loff_t", "size_t"}},
	"readlink":                {Args: []string{"path", "buf", "bufsiz"}, ArgTypes: []string{"const char *", "char *", "int"}},
	"readlinkat":              {Args: []string{"dfd", "pathname", "buf", "bufsiz"}, ArgTypes: []string{"int", "const char *", "char *", "int"}},
	"readv":                   {Args: []string{"fd", "vec", "vlen"}, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long"}},
	"reboot":                  {Args: []string{"magic1", "magic2", "cmd", "arg"}, ArgTypes: []string{"int", "int", "unsigned int", "void *"}},
	"recvfrom":                {Args: []string{"fd", "ubuf", "size", "flags", "addr", "addr_len"}, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int *"}},
	"recvmmsg":                {Args: []string{"fd", "mmsg", "vlen", "flags", "timeout"}, ArgTypes: []string{"int", "struct mmsghdr *", "unsigned int", "unsigned int", "struct __kernel_timespec *"}},
	"recvmsg":                 {Args: []string{"fd", "msg", "flags"}, ArgTypes: []string{"int", "struct msghdr *", "unsigned int"}},
	"remap_file_pages":        {Args: []string{"start", "size", "prot", "pgoff", "flags"}, ArgTypes: []string{"long unsigned int", "long unsigned int", "long unsigned int", "long unsigned int", "long unsigned int"}},
	"removexattr":             {Args: []string{"pathname", "name"}, ArgTypes: []string{"const char *", "const char *"}},
	"removexattrat":           {Args: []string{"dfd", "pathname", "at_flags", "name"}, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *"}},
	"rename":                  {Args: []string{"oldname", "newname"}, ArgTypes: []string{"const char *", "const char *"}},
	"renameat":                {Args: []string{"olddfd", "oldname", "newdfd", "newname"}, ArgTypes: []string{"int", "const char *", "int", "const char *"}},
	"renameat2":               {Args: []string{"olddfd", "oldname", "newdfd", "newname", "flags"}, ArgTypes: []string{"int", "const char *", "int", "const char *", "unsigned int"}},
	"request_key":             {Args: []string{"_type", "_description", "_callout_info", "destringid"}, ArgTypes: []string{"const char *", "const char *", "const char *", "key_serial_t"}},
	"restart_syscall":         {Args: []string{}, ArgTypes: []string{}},
	"rmdir":                   {Args: []string{"pathname"}, ArgTypes: []string{"const char *"}},
	"rseq":                    {Args: []string{"rseq", "rseq_len", "flags", "sig"}, ArgTypes: []string{"struct rseq *", "u32", "int", "u32"}},
	"rseq_slice_yield":        {Args: []string{}, ArgTypes: []string{}},
	"rt_sigaction":            {Args: []string{"sig", "act", "oact", "sigsetsize"}, ArgTypes: []string{"int", "const struct sigaction *", "struct sigaction *", "size_t"}},
	"rt_sigpending":           {Args: []string{"uset", "sigsetsize"}, ArgTypes: []string{"sigset_t *", "size_t"}},
	"rt_sigprocmask":          {Args: []string{"how", "nset", "oset", "sigsetsize"}, ArgTypes: []string{"int", "sigset_t *", "sigset_t *", "size_t"}},
	"rt_sigqueueinfo":         {Args: []string{"pid", "sig", "uinfo"}, ArgTypes: []string{"pid_t", "int", "siginfo_t *"}},
	"rt_sigreturn":            {Args: []string{}, ArgTypes: []string{}},
	"rt_sigsuspend":           {Args: []string{"unewset", "sigsetsize"}, ArgTypes: []string{"sigset_t *", "size_t"}},
	"rt_sigtimedwait":         {Args: []string{"uthese", "uinfo", "uts", "sigsetsize"}, ArgTypes: []string{"const sigset_t *", "siginfo_t *", "const struct __kernel_timespec *", "size_t"}},
	"rt_tgsigqueueinfo":       {Args: []string{"tgid", "pid", "sig", "uinfo"}, ArgTypes: []string{"pid_t", "pid_t", "int", "siginfo_t *"}},
	"sched_get_priority_max":  {Args: []string{"policy"}, ArgTypes: []string{"int"}},
	"sched_get_priority_min":  {Args: []string{"policy"}, ArgTypes: []string{"int"}},
	"sched_getaffinity":       {Args: []string{"pid", "len", "user_mask_ptr"}, ArgTypes: []string{"pid_t", "unsigned int", "unsigned long *"}},
	"sched_getattr":           {Args: []string{"pid", "uattr", "usize", "flags"}, ArgTypes: []string{"pid_t", "struct sched_attr *", "unsigned int", "unsigned int"}},
	"sched_getparam":          {Args: []string{"pid", "param"}, ArgTypes: []string{"pid_t", "struct sched_param *"}},
	"sched_getscheduler":      {Args: []string{"pid"}, ArgTypes: []string{"pid_t"}},
	"sched_rr_get_interval":   {Args: []string{"pid", "interval"}, ArgTypes: []string{"pid_t", "struct __kernel_timespec *"}},
	"sched_setaffinity":       {Args: []string{"pid", "len", "user_mask_ptr"}, ArgTypes: []string{"pid_t", "unsigned int", "unsigned long *"}},
	"sched_setattr":           {Args: []string{"pid", "uattr", "flags"}, ArgTypes: []string{"pid_t", "struct sched_attr *", "unsigned int"}},
	"sched_setparam":          {Args: []string{"pid", "param"}, ArgTypes: []string{"pid_t", "struct sched_param *"}},
	"sched_setscheduler":      {Args: []string{"pid", "policy", "param"}, ArgTypes: []string{"pid_t", "int", "struct sched_param *"}},
	"sched_yield":             {Args: []string{}, ArgTypes: []string{}},
	"seccomp":                 {Args: []string{"op", "flags", "uargs"}, ArgTypes: []string{"unsigned int", "unsigned int", "void *"}},
	"security":                {Args: []string{"arg0", "arg1", "arg2"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long"}},
	"select":                  {Args: []string{"n", "inp", "outp", "exp", "tvp"}, ArgTypes: []string{"int", "fd_set *", "fd_set *", "fd_set *", "struct __kernel_old_timeval *"}},
	"semctl":                  {Args: []string{"semid", "semnum", "cmd", "arg"}, ArgTypes: []string{"int", "int", "int", "unsigned long"}},
	"semget":                  {Args: []string{"key", "nsems", "semflg"}, ArgTypes: []string{"key_t", "int", "int"}},
	"semop":                   {Args: []string{"semid", "tsops", "nsops"}, ArgTypes: []string{"int", "struct sembuf *", "unsigned"}},
	"semtimedop":              {Args: []string{"semid", "tsops", "nsops", "timeout"}, ArgTypes: []string{"int", "struct sembuf *", "unsigned int", "const struct __kernel_timespec *"}},
	"sendfile":                {Args: []string{"out_fd", "in_fd", "offset", "count"}, ArgTypes: []string{"int", "int", "loff_t *", "size_t"}},
	"sendmmsg":                {Args: []string{"fd", "mmsg", "vlen", "flags"}, ArgTypes: []string{"int", "struct mmsghdr *", "unsigned int", "unsigned int"}},
	"sendmsg":                 {Args: []string{"fd", "msg", "flags"}, ArgTypes: []string{"int", "struct msghdr *", "unsigned int"}},
	"sendto":                  {Args: []string{"fd", "buff", "len", "flags", "addr", "addr_len"}, ArgTypes: []string{"int", "void *", "size_t", "unsigned int", "struct sockaddr *", "int"}},
	"set_mempolicy":           {Args: []string{"mode", "nmask", "maxnode"}, ArgTypes: []string{"int", "const unsigned long *", "unsigned long"}},
	"set_mempolicy_home_node": {Args: []string{"start", "len", "home_node", "flags"}, ArgTypes: []string{"long unsigned int", "long unsigned int", "long unsigned int", "long unsigned int"}},
	"set_robust_list":         {Args: []string{"head", "len"}, ArgTypes: []string{"struct robust_list_head *", "size_t"}},
	"set_thread_area":         {Args: []string{"arg0"}, ArgTypes: []string{"unsigned long"}},
	"set_tid_address":         {Args: []string{"tidptr"}, ArgTypes: []string{"int *"}},
	"setdomainname":           {Args: []string{"name", "len"}, ArgTypes: []string{"char *", "int"}},
	"setfsgid":                {Args: []string{"gid"}, ArgTypes: []string{"gid_t"}},
	"setfsuid":                {Args: []string{"uid"}, ArgTypes: []string{"uid_t"}},
	"setgid":                  {Args: []string{"gid"}, ArgTypes: []string{"gid_t"}},
	"setgroups":               {Args: []string{"gidsetsize", "grouplist"}, ArgTypes: []string{"int", "gid_t *"}},
	"sethostname":             {Args: []string{"name", "len"}, ArgTypes: []string{"char *", "int"}},
	"setitimer":               {Args: []string{"which", "value", "ovalue"}, ArgTypes: []string{"int", "struct __kernel_old_itimerval *", "struct __kernel_old_itimerval *"}},
	"setns":                   {Args: []string{"fd", "flags"}, ArgTypes: []string{"int", "int"}},
	"setpgid":                 {Args: []string{"pid", "pgid"}, ArgTypes: []string{"pid_t", "pid_t"}},
	"setpriority":             {Args: []string{"which", "who", "niceval"}, ArgTypes: []string{"int", "int", "int"}},
	"setregid":                {Args: []string{"rgid", "egid"}, ArgTypes: []string{"gid_t", "gid_t"}},
	"setresgid":               {Args: []string{"rgid", "egid", "sgid"}, ArgTypes: []string{"gid_t", "gid_t", "gid_t"}},
	"setresuid":               {Args: []string{"ruid", "euid", "suid"}, ArgTypes: []string{"uid_t", "uid_t", "uid_t"}},
	"setreuid":                {Args: []string{"ruid", "euid"}, ArgTypes: []string{"uid_t", "uid_t"}},
	"setrlimit":               {Args: []string{"resource", "rlim"}, ArgTypes: []string{"unsigned int", "struct rlimit *"}},
	"setsid":                  {Args: []string{}, ArgTypes: []string{}},
	"setsockopt":              {Args: []string{"fd", "level", "optname", "optval", "optlen"}, ArgTypes: []string{"int", "int", "int", "char *", "int"}},
	"settimeofday":            {Args: []string{"tv", "tz"}, ArgTypes: []string{"struct __kernel_old_timeval *", "struct timezone *"}},
	"setuid":                  {Args: []string{"uid"}, ArgTypes: []string{"uid_t"}},
	"setxattr":                {Args: []string{"pathname", "name", "value", "size", "flags"}, ArgTypes: []string{"const char *", "const char *", "const void *", "size_t", "int"}},
	"setxattrat":              {Args: []string{"dfd", "pathname", "at_flags", "name", "uargs", "usize"}, ArgTypes: []string{"int", "const char *", "unsigned int", "const char *", "const struct xattr_args *", "size_t"}},
	"shmat":                   {Args: []string{"shmid", "shmaddr", "shmflg"}, ArgTypes: []string{"int", "char *", "int"}},
	"shmctl":                  {Args: []string{"shmid", "cmd", "buf"}, ArgTypes: []string{"int", "int", "struct shmid_ds *"}},
	"shmdt":                   {Args: []string{"shmaddr"}, ArgTypes: []string{"char *"}},
	"shmget":                  {Args: []string{"key", "size", "shmflg"}, ArgTypes: []string{"key_t", "size_t", "int"}},
	"shutdown":                {Args: []string{"fd", "how"}, ArgTypes: []string{"int", "int"}},
	"sigaltstack":             {Args: []string{"uss", "uoss"}, ArgTypes: []string{"const stack_t *", "stack_t *"}},
	"signalfd":                {Args: []string{"ufd", "user_mask", "sizemask"}, ArgTypes: []string{"int", "sigset_t *", "size_t"}},
	"signalfd4":               {Args: []string{"ufd", "user_mask", "sizemask", "flags"}, ArgTypes: []string{"int", "sigset_t *", "size_t", "int"}},
	"socket":                  {Args: []string{"family", "type", "protocol"}, ArgTypes: []string{"int", "int", "int"}},
	"socketpair":              {Args: []string{"family", "type", "protocol", "usockvec"}, ArgTypes: []string{"int", "int", "int", "int *"}},
	"splice":                  {Args: []string{"fd_in", "off_in", "fd_out", "off_out", "len", "flags"}, ArgTypes: []string{"int", "loff_t *", "int", "loff_t *", "size_t", "unsigned int"}},
	"stat":                    {Args: []string{"filename", "statbuf"}, ArgTypes: []string{"const char *", "struct stat *"}},
	"statfs":                  {Args: []string{"pathname", "buf"}, ArgTypes: []string{"const char *", "struct statfs *"}},
	"statmount":               {Args: []string{"req", "buf", "bufsize", "flags"}, ArgTypes: []string{"const struct mnt_id_req *", "struct statmount *", "size_t", "unsigned int"}},
	"statx":                   {Args: []string{"dfd", "filename", "flags", "mask", "buffer"}, ArgTypes: []string{"int", "const char *", "unsigned", "unsigned int", "struct statx *"}},
	"swapoff":                 {Args: []string{"specialfile"}, ArgTypes: []string{"const char *"}},
	"swapon":                  {Args: []string{"specialfile", "swap_flags"}, ArgTypes: []string{"const char *", "int"}},
	"symlink":                 {Args: []string{"oldname", "newname"}, ArgTypes: []string{"const char *", "const char *"}},
	"symlinkat":               {Args: []string{"oldname", "newdfd", "newname"}, ArgTypes: []string{"const char *", "int", "const char *"}},
	"sync":                    {Args: []string{}, ArgTypes: []string{}},
	"sync_file_range":         {Args: []string{"fd", "offset", "nbytes", "flags"}, ArgTypes: []string{"int", "loff_t", "loff_t", "unsigned int"}},
	"syncfs":                  {Args: []string{"fd"}, ArgTypes: []string{"int"}},
	"sysfs":                   {Args: []string{"option", "arg1", "arg2"}, ArgTypes: []string{"int", "unsigned long", "unsigned long"}},
	"sysinfo":                 {Args: []string{"info"}, ArgTypes: []string{"struct sysinfo *"}},
	"syslog":                  {Args: []string{"type", "buf", "len"}, ArgTypes: []string{"int", "char *", "int"}},
	"tee":                     {Args: []string{"fdin", "fdout", "len", "flags"}, ArgTypes: []string{"int", "int", "size_t", "unsigned int"}},
	"tgkill":                  {Args: []string{"tgid", "pid", "sig"}, ArgTypes: []string{"pid_t", "pid_t", "int"}},
	"time":                    {Args: []string{"tloc"}, ArgTypes: []string{"__kernel_old_time_t *"}},
	"timer_create":            {Args: []string{"which_clock", "timer_event_spec", "created_timer_id"}, ArgTypes: []string{"const clockid_t", "struct sigevent *", "timer_t *"}},
	"timer_delete":            {Args: []string{"timer_id"}, ArgTypes: []string{"timer_t"}},
	"timer_getoverrun":        {Args: []string{"timer_id"}, ArgTypes: []string{"timer_t"}},
	"timer_gettime":           {Args: []string{"timer_id", "setting"}, ArgTypes: []string{"timer_t", "struct __kernel_itimerspec *"}},
	"timer_settime":           {Args: []string{"timer_id", "flags", "new_setting", "old_setting"}, ArgTypes: []string{"timer_t", "int", "const struct __kernel_itimerspec *", "struct __kernel_itimerspec *"}},
	"timerfd_create":          {Args: []string{"clockid", "flags"}, ArgTypes: []string{"int", "int"}},
	"timerfd_gettime":         {Args: []string{"ufd", "otmr"}, ArgTypes: []string{"int", "struct __kernel_itimerspec *"}},
	"timerfd_settime":         {Args: []string{"ufd", "flags", "utmr", "otmr"}, ArgTypes: []string{"int", "int", "const struct __kernel_itimerspec *", "struct __kernel_itimerspec *"}},
	"times":                   {Args: []string{"tbuf"}, ArgTypes: []string{"struct tms *"}},
	"tkill":                   {Args: []string{"pid", "sig"}, ArgTypes: []string{"pid_t", "int"}},
	"truncate":                {Args: []string{"path", "length"}, ArgTypes: []string{"const char *", "long"}},
	"tuxcall":                 {Args: []string{"arg0", "arg1", "arg2"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long"}},
	"umask":                   {Args: []string{"mask"}, ArgTypes: []string{"int"}},
	"umount2":                 {Args: []string{"name", "flags"}, ArgTypes: []string{"char *", "int"}},
	"uname":                   {Args: []string{"name"}, ArgTypes: []string{"struct utsname *"}},
	"unlink":                  {Args: []string{"pathname"}, ArgTypes: []string{"const char *"}},
	"unlinkat":                {Args: []string{"dfd", "pathname", "flag"}, ArgTypes: []string{"int", "const char *", "int"}},
	"unshare":                 {Args: []string{"unshare_flags"}, ArgTypes: []string{"long unsigned int"}},
	"uprobe":                  {Args: []string{}, ArgTypes: []string{}},
	"uretprobe":               {Args: []string{}, ArgTypes: []string{}},
	"uselib":                  {Args: []string{"arg0"}, ArgTypes: []string{"unsigned long"}},
	"userfaultfd":             {Args: []string{"flags"}, ArgTypes: []string{"int"}},
	"ustat":                   {Args: []string{"dev", "ubuf"}, ArgTypes: []string{"dev_t", "struct ustat *"}},
	"utime":                   {Args: []string{"filename", "times"}, ArgTypes: []string{"char *", "struct utimbuf *"}},
	"utimensat":               {Args: []string{"dfd", "filename", "utimes", "flags"}, ArgTypes: []string{"int", "const char *", "struct __kernel_timespec *", "int"}},
	"utimes":                  {Args: []string{"filename", "utimes"}, ArgTypes: []string{"char *", "struct __kernel_old_timeval *"}},
	"vfork":                   {Args: []string{}, ArgTypes: []string{}},
	"vhangup":                 {Args: []string{}, ArgTypes: []string{}},
	"vmsplice":                {Args: []string{"fd", "uiov", "nr_segs", "flags"}, ArgTypes: []string{"int", "const struct iovec *", "long unsigned int", "unsigned int"}},
	"vserver":                 {Args: []string{"arg0", "arg1", "arg2", "arg3", "arg4"}, ArgTypes: []string{"unsigned long", "unsigned long", "unsigned long", "unsigned long", "unsigned long"}},
	"wait4":                   {Args: []string{"upid", "stat_addr", "options", "ru"}, ArgTypes: []string{"pid_t", "int *", "int", "struct rusage *"}},
	"waitid":                  {Args: []string{"which", "upid", "infop", "options", "ru"}, ArgTypes: []string{"int", "pid_t", "struct siginfo *", "int", "struct rusage *"}},
	"write":                   {Args: []string{"fd", "buf", "count"}, ArgTypes: []string{"unsigned int", "const char *", "size_t"}},
	"writev":                  {Args: []string{"fd", "vec", "vlen"}, ArgTypes: []string{"unsigned long", "const struct iovec *", "unsigned long"}},
}
