package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

type syscallNumberHeaderWriter interface {
	Write(path string, numbers []syscallNumberEntry) error
}

type generatedSyscallNumberHeaderWriter struct{}

type runtimeABIVariable struct {
	variableName string
	syscallName  string
	defaultID    uint32
}

var runtimeABIVariables = []runtimeABIVariable{
	{variableName: "SYS_CAPGET", syscallName: "capget"},
	{variableName: "SYS_CAPSET", syscallName: "capset"},
	{variableName: "SYS_EXECVE", syscallName: "execve"},
	{variableName: "SYS_EXECVEAT", syscallName: "execveat"},
	{variableName: "SYS_EXIT", syscallName: "exit"},
	{variableName: "SYS_EXIT_GROUP", syscallName: "exit_group"},
	{variableName: "SYS_NANOSLEEP", syscallName: "nanosleep"},
	{variableName: "SYS_RT_SIGRETURN", syscallName: "rt_sigreturn"},
	{variableName: "SYS_RT_SIGRETURN_COMPAT", defaultID: 173},
	{variableName: "SYS_RT_SIGSUSPEND", syscallName: "rt_sigsuspend"},
}

var runtimeABIVariableNames = buildRuntimeABIVariableNames()

func buildRuntimeABIVariableNames() map[string]struct{} {
	names := make(map[string]struct{}, len(runtimeABIVariables))
	for _, variable := range runtimeABIVariables {
		names[strings.TrimPrefix(variable.variableName, "SYS_")] = struct{}{}
	}
	return names
}

func runtimeABIVariableForSyscall(name string) (runtimeABIVariable, bool) {
	for _, variable := range runtimeABIVariables {
		if variable.syscallName == name {
			return variable, true
		}
	}
	return runtimeABIVariable{}, false
}

func (generatedSyscallNumberHeaderWriter) Write(path string, numbers []syscallNumberEntry) error {
	entries := append([]syscallNumberEntry(nil), numbers...)
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	var out strings.Builder
	fmt.Fprintln(&out, "#ifndef STRACE_GO_SYSCALL_NUMBERS_GENERATED_H")
	fmt.Fprintln(&out, "#define STRACE_GO_SYSCALL_NUMBERS_GENERATED_H")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	for _, entry := range entries {
		if _, managed := runtimeABIVariableForSyscall(entry.Name); managed {
			fmt.Fprintf(&out, "volatile const u32 SYS_%s = %d;\n", strings.ToUpper(entry.Name), entry.ID)
			continue
		}
		fmt.Fprintf(&out, "#define SYS_%s %d\n", strings.ToUpper(entry.Name), entry.ID)
	}
	for _, variable := range runtimeABIVariables {
		if variable.syscallName == "" {
			fmt.Fprintf(&out, "volatile const u32 %s = %d;\n", variable.variableName, variable.defaultID)
		}
	}
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#endif")

	if err := os.WriteFile(path, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
