package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

type syscallNumberHeaderWriter interface {
	Write(path string, numbers []syscallNumberEntry) error
}

type generatedSyscallNumberHeaderWriter struct{}

var runtimeABIVariableNames = map[string]struct{}{
	"capget":        {},
	"capset":        {},
	"execve":        {},
	"execveat":      {},
	"exit":          {},
	"exit_group":    {},
	"nanosleep":     {},
	"rt_sigreturn":  {},
	"rt_sigsuspend": {},
}

func (generatedSyscallNumberHeaderWriter) Write(path string, numbers []syscallNumberEntry) error {
	entries := append([]syscallNumberEntry(nil), numbers...)
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	var out strings.Builder
	fmt.Fprintln(&out, "#ifndef STRACE_GO_SYSCALL_NUMBERS_GENERATED_H")
	fmt.Fprintln(&out, "#define STRACE_GO_SYSCALL_NUMBERS_GENERATED_H")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/* Generated by generate-syscalls. DO NOT EDIT. */")
	fmt.Fprintln(&out)
	for _, entry := range entries {
		if _, managed := runtimeABIVariableNames[entry.Name]; managed {
			continue
		}
		fmt.Fprintf(&out, "#define SYS_%s %d\n", strings.ToUpper(entry.Name), entry.ID)
	}
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#endif")

	if err := os.WriteFile(path, []byte(out.String()), 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
