package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"strace-go/internal/architecture"
)

func generateTargetMetadata(requested, output string, check bool) error {
	targets := []architecture.Architecture{architecture.AMD64, architecture.ARM64}
	if requested != "all" {
		target, err := architecture.Select(requested, os.Getenv("GOARCH"), runtime.GOARCH)
		if err != nil {
			return err
		}
		targets = []architecture.Architecture{target}
	}
	if output != "" && len(targets) != 1 {
		return fmt.Errorf("--output requires one target architecture")
	}
	for _, target := range targets {
		if err := generateOneTarget(target, output, check); err != nil {
			return err
		}
	}

	wrapperPath, err := resolveRepoPath("bpf/syscall_numbers_generated.h")
	if err != nil {
		return err
	}
	return writeGeneratedOutput(wrapperPath, []byte(targetHeaderSelector), check)
}

const targetHeaderSelector = `/* Generated by generate-syscalls. DO NOT EDIT. */
#if defined(__TARGET_ARCH_x86)
#include "syscall_numbers_amd64_generated.h"
#elif defined(__TARGET_ARCH_arm64)
#include "syscall_numbers_arm64_generated.h"
#else
#error "unsupported BPF architecture: use generate-bpf for amd64 or arm64"
#endif
`

func generateOneTarget(target architecture.Architecture, output string, check bool) error {
	table, err := loadTargetSyscalls(target)
	if err != nil {
		return err
	}
	goData := renderGoSyscallTable(table)
	fingerprint := sha256.Sum256(append([]byte(target), goData...))
	abiHash := binary.LittleEndian.Uint64(fingerprint[:8])
	prefix := fmt.Sprintf("//go:build linux && %s\n\n", target)
	goData = append([]byte(prefix), goData...)
	goData = append(goData, []byte(fmt.Sprintf("\nconst SyscallArchitecture = %q\nconst SyscallABIHash uint64 = %#x\n", target, abiHash))...)
	if output == "" {
		output, err = resolveRepoPath(fmt.Sprintf("pkg/meta/syscall_table_%s.go", target))
		if err != nil {
			return err
		}
	}
	if err := writeGeneratedOutput(output, goData, check); err != nil {
		return err
	}
	header, err := targetNumberHeader(target, table, abiHash)
	if err != nil {
		return err
	}
	headerPath, err := resolveRepoPath(fmt.Sprintf("bpf/syscall_numbers_%s_generated.h", target))
	if err != nil {
		return err
	}
	return writeGeneratedOutput(headerPath, header, check)
}

func targetNumberHeader(target architecture.Architecture, table map[int]SyscallMeta, hash uint64) ([]byte, error) {
	numbers := make([]syscallNumberEntry, 0, len(table))
	present := make(map[string]bool, len(table))
	for id, sc := range table {
		numbers = append(numbers, syscallNumberEntry{ID: id, Name: sc.Name})
		present[sc.Name] = true
	}
	header := bytes.TrimSuffix(renderSyscallNumberHeader(numbers), []byte("#endif\n"))
	var tail strings.Builder
	fmt.Fprintf(&tail, "\nvolatile const u64 STRACE_GO_SYSCALL_ABI = %#xULL;\n", hash)
	// Unavailable names remain distinct compile-time sentinels outside every native route map.
	names := make([]string, 0)
	for name := range syscallSemanticCatalog {
		if !present[name] {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for i, name := range names {
		fmt.Fprintf(&tail, "#define SYS_%s %dU /* unavailable on %s */\n", strings.ToUpper(name), 0xffff0000+i, target)
	}
	tail.WriteString("\n#endif\n")
	return append(header, []byte(tail.String())...), nil
}

func writeGeneratedOutput(path string, data []byte, check bool) error {
	if check {
		existing, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated output %s: %w", path, err)
		}
		if !bytes.Equal(existing, data) {
			return fmt.Errorf("generated metadata is stale: %s", path)
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
